### ISSUE TITLE
Combine Dupes for Seamless Failover

### ISSUE THREAD

**Issue by xtinct101** [Threadfin/Threadfin#10]
**Is your feature request related to a problem? Please describe.**
With multiple tuners or m3us, you may end up with redundant channels with varying levels of quality and sources.. If one goes offline you have to manually find the next dupe if you didnt remove dupes to keep within channel limits.

**Describe the solution you'd like**
I would like a solution to assign multiple channels to the same number, with some indicator for priority.. ie, 10 = Primary, 10A = Secondary, 10B = Tertiary

When using the xTeVe buffer, the m3u would only contain channel 10, not the sub channels and if the primary stream fails to load, it should automatically try the secondary stream, and so on until its exhausted all options.

**Describe alternatives you've considered**
Duplicate Channels are confusing, and a hassle if you start getting multiple provider sources, also plex has a limit on channels so low bandwith streams and varying upstream sources are likely to be deactivated, and would require manual activation.. thats a clunky work around at best.

**Additional context**
Also should failover if the source runs out of streams but a backup has some available.. So instead of getting multiple streams from one provider you could instead get single streams from multiple providers.. or multiple accounts from one provider if they dont provide an adequate number of streams.

I understand that this functionality would require use of the buffer, and that is perfectly fine.

**Comment by Fyb3roptik** [comment]
Channel number have to be unique unfortunately. So you cannot assign multiple channels to the same channel number.

**Comment by Fyb3roptik** [comment]
Any changes to the EPG and channels would require you to delete/add in Plex anyways. I know its not great, I am in the same boat

**Comment by xtinct101** [comment]
That's not correct. 
You just need tvg-name to be identical which Xteve can already do. Identical tvg-names are then merged, this will require the Xteve buffer to be active to create a unique m3u's link.

HLS-Proxy already does this but adding it to the mix is cumbersome and adds more areas for failure. 
Basically how I have it working is like this:

1. Channels mapped in Xteve as follows: 
- Original channels are mapped and named: 100(ABC), 101(CBS), 102(FOX)
- Backup channels are mapped: 2100(ABC), 2101(CBS), 2102(FOX)
(xteve m3u examples)
#EXTINF:0 channelID="x-ID.9" tvg-chno="100" tvg-name="US ABC7" tvg-id="100"
http://x.x.x.x/stream/5d62f410182d018d76c5bbf154d772a3
#EXTINF:0 channelID="x-ID.31" tvg-chno="2100" tvg-name="US ABC7" tvg-id="2100"
http://x.x.x.x/stream/baeed0b72f84b4f6b1cf4e8eec8cf02d 

2. Add Xteve m3u playlist to HLS-Proxy, any duplicate tvg-name gets merged into a single channel in HLS-Proxy.
(hls-proxy m3u example)
#EXTINF:0 channelID="x-ID.9" tvg-chno="100" tvg-name="US ABC7" tvg-id="100" 
https://x.x.x.x:443/channel/nc9917a9/index.m3u8?q=1663717823767

3. Loading that playlist into plex shows a single channel 100 - US ABC7 which is able to cycle through the streams. 
Changes to the EPG cause no issues as I just remap it in Xteve, if I require to swap out channels(new back up or new main) I still don't have any issue as all I need to do is name it "US ABC7" and set the channel # 100 in Xteve. 
I don't have any issues in plex delete/adding the tuner on changes. 

Pretty flawless but overly complicated with too many in-between programs to achieve what ultimately Xteve could do on its own.

**Comment by Fyb3roptik** [comment]
So the current issue with this is if its active it will get mapped as a channel in plex. This could be worked around by marking the channel as a backup and could even mark which channel it is a backup for. How would you determine when it needs to switch?

**Comment by xtinct101** [comment]
Currently the way HLS-proxy treats streams with backups is to test the stream when launched. If a stream returns an error(404 or whatever) it tries the next stream and so on. 
This of course could be expanded but at the very least this will enable failover on channels.

**Comment by Fyb3roptik** [comment]
Ok so here are the changes I think will need to be made:

- Add the option to flag a channel as a backup for another channel
- Visibly mark those backup channels in the mapping editor
- If the original channel gets a 404, Threadfin will automatically use the URL from the backup without needing to assign it
- Backup channels will NOT show in the EPG

**Comment by xtinct101** [comment]
Fantastic. 
Thank you for picking up continued development on Threadfin(xteve).

**Comment by xtinct101** [comment]
Fyb3r, 
I gave this a little more thought on what implementation would be better and cause less failures and wanted to run it by you.
Would it be possible to create a "virtual" channel to store all the streams?

Let me elaborate:
- In Threadfin, you would create an empty "virtual" channel called "ABC7" with its own unique stream address. This would be the channel that Plex,Emby reads from the m3u.
- In Threadfin, you would assign(mark) streams that belong to the virtual channel. You could have as many or as little streams under a single virtual channel and the logic for cycling streams based on 404 or general failure would happen on the virtual channel.

This has a major upside: in the event that the main(or backup) channel changes or is replaced, plex/emby would not detect those changes as its the virtual channel with it's own unique name/id that that plex/emby are referencing.

- Threadfin: 
                   - "Virtual Channel" - Channel(100) "ABC7":
                                                                                         - Real ABC Stream #1
                                                                                         - Real ABC Stream #2
                                                                                         - Real ABC Stream #3
                   - "Virtual Channel" - Channel(101) "CBS":
                                                                                         - Real CBS Stream #1
                                                                                         - Real CBS Stream #2
                                                                                         - Real CBS Stream #3                                                                                         

Thoughts?

**Comment by Fyb3roptik** [comment]
So I have this all working, but the way I will have it setup is like this

1. Go into the main channel and assign a backup (active) channel - This has to be an active channel
2. Once a channel is marked as a backup, that backup channel will now have a checkbox option on whether or not to hide it from the EPG. This allows you to use other active channels as backups but still have them in the EPG.

I am working on the 2nd item now and should have an update for you soon!

**Comment by xtinct101** [comment]
That's fantastic news, can't wait to try it.

**Comment by xtinct101** [comment]
After posting my thoughts on how I would refine the system to reduce repetition and increase dependability, I decided to mock it up using a second instance of Threadfin(not really required but didn't want to mess up my original setup).

My new setup:

**- Threadfin(instance #1): Master M3U - Simulating Virtual(dummy) Channels**
Copied m3u from existing lineup and replaced all http:// links with "null" to force a 404 error
ABC7
CBS
FOX
Set real EPG to these channels.

**- Threadfin(instance #2):Real Streams**
Add as many actual streams, including backup etc. for the above channels and name them appropriately to the channels they represent, i.e ABC7. Channel numbers don't matter.
Bulk set all channels to "Threadfin Dummy" epg to force activate channels.

**- HLS-Proxy(only method I can test right now): Merge duplicate channels for Plex/Emby/Jelly**
Load **Threadfin** #1 m3u with dummy links in HLS-Proxy.
Load **Threadfin** #2 m3u with real links, set as backup in HLS-Proxy(HLS-Proxy merges all streams to **Threadfin** #1 channels).
Load HLS-Proxy M3U into Plex/Emby/Jelly. 

Since **Threadfin** #1 M3U cannot automatically change(due to provider or otherwise) unless I choose to change it, all I do now is replace/add channels as I wish to **Threadfin** #2 and Plex/Emby/Jelly automatically picks up the changes.

Definitely a far better workflow and could be accomplished all at once through a single instance on Threadfin using dummy(virtual) channels as the "main" channel. With the changes you're implementing to Threadfin allowing to mark/set backup channels this would be even simpler and more powerful as names shouldn't matter for backup channels.

**Comment by Fyb3roptik** [comment]
https://github.com/Threadfin/Threadfin/releases/tag/BETA-0.8.5

Please verify this works. Once you select a channel as a backup, go into that backup channel and you should see the option to hide it.

**Comment by xtinct101** [comment]
I run Threadfin via docker. 
I just built the container via the Dockerfile but I believe its pointing to the master branch. When I change the branch in the dockerfile to use the beta, the build process fails.

>  ---> Running in 031695b564d3
> src/config.go:10:2: cannot find package "." in:
>         /src/vendor/github.com/avfs/avfs
> src/buffer.go:26:2: cannot find package "." in:
>         /src/vendor/github.com/avfs/avfs/vfs/memfs
> src/buffer.go:27:2: cannot find package "." in:
>         /src/vendor/github.com/avfs/avfs/vfs/osfs
> 1 error occurred:
>         * Status: The command '/bin/sh -c go build threadfin.go' returned a non-zero code: 1, Code: 1

**Comment by Fyb3roptik** [comment]
oh snap let me check that

**Comment by Fyb3roptik** [comment]
just pushed an update to docker, try now

**Comment by xtinct101** [comment]
Thanks Fyb3r but unfortunately you only build for arm64 and I use amd64 so I have to build it manually, which for whatever reason wont let me build the beta branch.
Are you able to push a amd64 version to docker?

**Comment by Fyb3roptik** [comment]
Try now, added amd64

**Comment by Fyb3roptik** [comment]
https://discord.gg/bEPPNP2VG8

Join here to chat

**Comment by Fyb3roptik** [comment]
Released https://github.com/Threadfin/Threadfin/releases/tag/0.9.2
