### ISSUE TITLE
Threadfin not handling EPG titles/data correctly that are not in English

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#100]
Threadfin is not displaying non-English EPG Titles correctly (Plex and other IPTV apps are displaying only / // characters) instead of Armenian program titles when I use threadfin XML.  **See screenshots at the bottom of this post**.  I don't have this issue when using the original XML source with IPTV apps.

Could you please fix Threadfin so it maintains the integrity of the original XML data when the language is not in English?

**Source:**
```
[]</desc>
    <title lang="hy">Հոբելյանական հաճախորդ</title>
  </programme>
  <programme start="20230627105500 +0000" stop="20230627121500 +0000" channel="HayKino.am">
    <desc lang="hy">Գեղարվեստական ֆիլմ.

[]</desc>
    <title lang="hy">Ոսկին և հողը</title>
  </programme>
  <programme start="20230627121500 +0000" stop="20230627130000 +0000" channel="HayKino.am">
    <desc lang="hy">Աճպարար.
```

**Threadfin:**
```
      <programme channel="1224" start="20230627105500 +0000" stop="20230627121500 +0000">
          <title lang="hy"></title>
          <desc lang="hy">Գեղարվեստական ֆիլմ.&#xA;&#xA;[]</desc>
          <credits></credits>
          <video></video>
          <date></date>
      </programme>
      <programme channel="1224" start="20230627121500 +0000" stop="20230627130000 +0000">
          <title lang="hy"></title>
          <desc lang="hy">Աճպարար.&#xA;&#xA;[]</desc>
          <credits></credits>
          <video></video>
          <date></date>
      </programme>
```

**Threadfin XML:**
![iMPlayer](https://github.com/Threadfin/Threadfin/assets/811008/7205947b-9b34-4395-979b-033cb1d5b0d8)

**Original XML:**
If I don't use Threadfin.. and use the original XML data, it all displays correctly:
![image](https://github.com/Threadfin/Threadfin/assets/811008/8e406e77-e34d-4fe3-a090-975e294d424d)

**Comment by mkanet** [comment]
**Original XML (working correctly)**
[EPG.xml.gz](https://github.com/Threadfin/Threadfin/files/11861350/EPG.xml.gz)

**Threadfin XML (broken)**
[threadfin.xml.gz](https://github.com/Threadfin/Threadfin/files/11861351/threadfin.xml.gz)

**Comment by mkanet** [comment]
@Fyb3roptik it looks like the reason it couldn't display non-English characters in the title, etc is because the below setting is disabled by default.  Did you know about this setting?

![image](https://github.com/Threadfin/Threadfin/assets/811008/1d0ab322-4d85-46b9-baff-4a429d040047)

After I enabled the above setting and refreshed the Plex EPG, I noticed that the EPG was displaying the non-English characters in the program titles correctly:
![image](https://github.com/Threadfin/Threadfin/assets/811008/6b69c628-3f39-4d92-8ef8-cdd39cdf3bce)

**Comment by Fyb3roptik** [comment]
Ah yeah there were some weird characters coming into my xml so I made that. I need to allow for non English in that
