### ISSUE TITLE
Setting:  "Replace missing program images" Does NOT display correctly in Plex programmes (posters)

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#101]
I really like the setting below:
![Screenshot 06-29-2023 at 12 56 26 PM](https://github.com/Threadfin/Threadfin/assets/811008/5fb89660-3421-461b-8924-5fbef040d11f)

Unfortunately, the above setting is not compatible with Plex programmes (posters).. the logos are cut-off:

**Currently:**  _wrong!_
![Wrong](https://github.com/Threadfin/Threadfin/assets/811008/162144d5-3f38-4d6c-b704-332c3a970c80)

Please fix this setting so channel logos fit/display correctly in Plex poster area correctly (like below):
![Correct](https://github.com/Threadfin/Threadfin/assets/811008/f5fb2c16-7271-410d-a93e-56443b45595e)

**Comment by mkanet** [comment]
@Fyb3roptik I am very curious how you end up fixing this issue.  I only have experience in PowerShell code (and a little bit Python).  I know most basic programming concepts.  
I would love to see what code you change in this PR so I can learn "Go" from you.  I learn the fastest from actual existing code; and respective changes to the code.

Don't laugh... with my limited knowledge, I'm guessing the code below would need to be changed?

`struct-xml.go`
```
// Poster : Programmposter / Cover
type Poster struct {
	Height string `xml:"height,attr"`
	Src    string `xml:"src,attr"`
	Value  string `xml:",chardata"`
	Width  string `xml:"width,attr"`
}
```
`xepg.go`
```
if Settings.XepgReplaceMissingImages {

    if len(xmltvProgram.Poster) == 0 {
        var poster Poster
        poster.Src = imgc.Image.GetURL(xepgChannel.TvgLogo, Settings.HttpThreadfinDomain, Settings.ForceHttps, Settings.HttpsPort, Settings.HttpsThreadfinDomain)
        program.Poster = append(program.Poster, poster)
    }

}
```

Anyway, I am very curious how you would actually modify the Plex Poster image when `Settings.XepgReplaceMissingImages  == true`.

If there's any way I can help, please let me know.  Needless to say (but I'm going to say it anyway), thank you so much for all your hard work improving Threadfin!  It is extremely useful for Plex IPTV users.

**Comment by mkanet** [comment]
Hi @Fyb3roptik! I'm curious if you had a chance to look at this yet?

**Comment by jlippold** [comment]
Following this request. It would be even better to hit up public apis (theTvDB, movieDB) and replace the images with proper one
