### ISSUE TITLE
User management and priorities.

### ISSUE THREAD

**Issue by Themesaul** [Threadfin/Threadfin#102]
**Describe the solution you'd like**
I would like to be able to create different users from the UI for broadcasts. Also define who has priority over whom.In this way, if a user with a higher priority wants to start a streaming, he removes the slot in use from a lower priority user. 

**Describe alternatives you've considered**
A user management even if it does not have priorities would also be acceptable for me

**Additional context**
My provider only allows 1 simultaneous streaming and I want to share it with the different screens in my house without inadvertently giving the kitchen TV priority over the living room

Thank you very much for this project, it works amazing and I am very happy. It's brutal work.

**Comment by Fyb3roptik** [comment]
Use the buffer for this. You can use ffmpeg to share the same feed with multiple tv's
