### ISSUE TITLE
xml output categories issue

### ISSUE THREAD

**Issue by grooverider2016** [Threadfin/Threadfin#105]
### Discussed in https://github.com/Threadfin/Threadfin/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **grooverider2016** April 22, 2023</sup>
Threadfin generated xml seems to create categories for programmes in the following format...

\<category lang="">\</category> whereas the expected format would normally be \<category>\</category> with language being a seperate tag using \<language>\</language> 

I'm wondering if this can be changed so that the output for xml to be used for Plex server is \<category>\</category> and \<language>\</language> as it would seem that plex only handles xml categories using this format. 

When using the current xml files with the \<category lang="">\</category> style then Plex doesnt map any programmes to the Plex Guide categories. </div>

**Comment by Fyb3roptik** [comment]
Will not fix. Plex is not in our scope for changing this. Plex has not touched their live tv setup in some time, so if this is a huge issue try using an alternative
