### ISSUE TITLE
PPV Channels Get Unmapped When Name Changes

### ISSUE THREAD

**Issue by bweezy21** [Threadfin/Threadfin#108]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
PPV Channels from my provider include event specific information and therefore the channel names change as the events change. This causes Threadfin to unmap the channels and remove the dummy epg settings for the ones with the name changes.

**Server (please complete the following information):**
- OS: Windows
- Arch: Intel 64 bit
- Threadfin Version and Build: 1.0 (13)

**To Reproduce**
1. load an m3u and epg
2. map channels
3. rename a channel
4. channel will now be unmapped

**Expected behavior**
I would expect the channel to stay mapped. Maybe key on the actual link address, or in Xteve they had a regex setting that handled this situation.

**Screenshots**

![image](https://github.com/Threadfin/Threadfin/assets/8197439/ae79e2b3-a6f4-47bb-9898-1a17268263dd)

Edit:
Should mention that this happens regardless if threadfin dummy ppv is sellected or threadfin dummy and any time span is selected as dummy guide data.

**Comment by bweezy21** [comment]
> Did you check the box for this functionality inside of settings?

yes thats why i mentioned at the bottom it doesn't matter which dummy guide you choose.

**Comment by Fyb3roptik** [comment]
This means they are also changing the tvg-id as well. I am not seeing this issue with my provider as they keep the tvg-id the same. Can you confirm if tvg-id or tvg-channel change? Or is it just the name itself?

**Comment by bweezy21** [comment]
> This means they are also changing the tvg-id as well. I am not seeing this issue with my provider as they keep the tvg-id the same. Can you confirm if tvg-id or tvg-channel change? Or is it just the name itself?

This is a good observation. I will capture the current M3U and wait for it to update again (typically on weekends when a new event pops). So give me some time and I'll get back to you.

**Comment by Fyb3roptik** [comment]
That is def the issue haha. Have them set an ID that wont change and you shouldnt have this issue
