### ISSUE TITLE
Unable to Start Xteve

### ISSUE THREAD

**Issue by AjayKolaganti** [Threadfin/Threadfin#112]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
After folowing the docmentation for Xteve until Step-8. Step-9 doesn't work
![image](https://github.com/Threadfin/Threadfin/assets/136128017/7742edcc-592f-41fe-b44a-c0ff62b8682c)

Xteve says:
![image](https://github.com/Threadfin/Threadfin/assets/136128017/95450df5-2260-4661-90f3-ff2fa709d797)
Service is setup correctly
![image](https://github.com/Threadfin/Threadfin/assets/136128017/5ed6f80a-5a31-4226-be6e-6622299f4c01)

**Server (please complete the following information):**
- Windows 11 Pro 22H2
- Threadfin Version - 1.0.16

**To Reproduce**
Folow the until Step-8. Step-9 doesn't work
![image](https://github.com/Threadfin/Threadfin/assets/136128017/7742edcc-592f-41fe-b44a-c0ff62b8682c)

**Expected behavior**
Should start service?

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11 Pro 22H2
 - Brave 1.52.130

**Additional context**
NA

**Comment by Fyb3roptik** [comment]
This is NOT xteve. You should remove all references to it.
