### ISSUE TITLE
Channel Name missing from tvheadend m3u import

### ISSUE THREAD

**Issue by wingede** [Threadfin/Threadfin#117]
Similar to bug #65 ...

M3U from tvheadend....

#EXTM3U
#EXTINF:-1 logo="http://127.0.0.1:9981/imagecache/68" tvg-id="0cf15161232708eaefbf0f6ee1cf8741" tvg-chno="1",TV 1
http://127.0.0.1:9981/stream/channelid/1632760076?profile=pass

When importing to threadfin all channels have a dash, expecting with the above example the channel name to be "TV 1"

**Comment by Speedyhome72** [comment]
you can program options in the playlist import for those fields that are missing

**Comment by Fyb3roptik** [comment]
I can set a generic group as default if one doesn't exist. Should solve this issue.

**Comment by wingede** [comment]
I'm not sure how to better explain it, but after configuring the play list (which comes from TVHeadend) e.g, http://localhost:9981/playlist and also configuring XMLTV.  When I go into mappings I have no channel names as shown below,

![TVH-IMPORT](https://github.com/Threadfin/Threadfin/assets/55191079/3c9e7739-3539-4054-9e85-8fa5dc3fa395)

**Comment by Speedyhome72** [comment]
tvheadend cannot m3u playlist with group-title and threadfin can only m3u whis group-title in m3u
and breaks by import of m3u list

**Comment by wingede** [comment]
> tvheadend cannot m3u playlist with group-title and threadfin can only m3u whis group-title in m3u and breaks by import of m3u list when not in m3u list

ahh ok, so I guess Fyb3roptik's comment about setting a generic group would be a fix, or alternatively I need to manipulate the output from tvheadend to put in a group-title?

**Comment by Speedyhome72** [comment]
generic group does not have to be, you only have to intercept this during import if it is not in the m3u in other closed Post is a solution approach

**Comment by Speedyhome72** [comment]
> I can set a generic group as default if one doesn't exist. Should solve this issue.

can you this in parser this working from other user
https://github.com/Threadfin/Threadfin/issues/120#issuecomment-1664396916

**Comment by Speedyhome72** [comment]
> I can set a generic group as default if one doesn't exist. Should solve this issue.

this work for me

if stream["group-title"] == "" {
                   stream["group-title"] = "Default"
}

**Comment by wingede** [comment]
> > I can set a generic group as default if one doesn't exist. Should solve this issue.
> 
> this work for me
> 
> if stream["group-title"] == "" { stream["group-title"] = "Default" }

Where did you input this?

**Comment by Speedyhome72** [comment]
in sourcecode
/src/internal/m3u-parser/xteve_m3uParser.go
and compile git clone local

**Comment by wingede** [comment]
> if stream["group-title"] == "" {
> stream["group-title"] = "Default"
> }

Thank you!

**Comment by ricafett** [comment]
+1
Having the same problem, also with m3u from tvheadend

**Comment by wingede** [comment]
Can this be added to the next release?
