### ISSUE TITLE
No streams after parsing M3U playlist from Enigma

### ISSUE THREAD

**Issue by Dr4g0nM4st3r** [Threadfin/Threadfin#120]
After downloading playlist from specified URL, checking and saving logs and web interface shows 0 streams.

Same behavior ->https://github.com/Threadfin/Threadfin/issues/92

**Server:**
- OS Debian 11.7
- Arch 64bit
- Threadfin Version - Docker 1.0.16

**To Reproduce**
It will not be possible to download .m3u file as playlist or from a file within the docker directory. 

I am attaching playlist.m3u download from mentioned URL. Also I have tried downloading file manually and configure Threadfin to use local file - same result (0 streams).

**Expected behavior**
After parsing .m3u file there should be streams available.

**Desktop (please complete the following information):**
Desktop (please complete the following information):

OS: Linux Kubunbtu
Browser Chrome

**Additional context**
2023/08/03 15:11:11 [Threadfin] Open:                   /owi2plex/service0.m3u
2023/08/03 15:11:11 [Threadfin] Check File:             /owi2plex/service0.m3u
2023/08/03 15:11:11 [Threadfin] Save File:              /owi2plex/service0.m3u [ID: MA3Q595O8HC6HWJLSTMG]
2023/08/03 15:11:11 [Threadfin] Open:                   /owi2plex/enigmaFavoriten.xml
2023/08/03 15:11:11 [Threadfin] Check File:             /owi2plex/enigmaFavoriten.xml
2023/08/03 15:11:11 [Threadfin] Save File:              /owi2plex/enigmaFavoriten.xml [ID: XX12MMUP5MGTMBJQP5GS]
2023/08/03 15:11:11 [Threadfin] All streams:            0
2023/08/03 15:11:11 [Threadfin] Active streams:         0
2023/08/03 15:11:11 [Threadfin] Filter:                 0
2023/08/03 15:11:11 [Threadfin] XEPG:                   Parse XMLTV file: XMLTV
2023/08/03 15:11:11 [Threadfin] XEPG:                   Update database
2023/08/03 15:11:11 [Threadfin] XEPG:                   Save DB file
2023/08/03 15:11:11 [Threadfin] XEPG:                   Map channels
2023/08/03 15:11:11 [Threadfin] XEPG:                   Cleanup database
2023/08/03 15:11:11 [Threadfin] XEPG Channels:          0
[files.zip](https://github.com/Threadfin/Threadfin/files/12251244/files.zip)

**Comment by Dr4g0nM4st3r** [comment]
found the problem. 
File: xteve_m3uParser.go Line 99
Change: 
					if stream["group-title"] == "" {
To:
					if len(stream) != 0 && stream["group-title"] == "" {

Cause my stream is 0 and this terminates the complete run.

**Comment by Fyb3roptik** [comment]
Can you send me your m3u? Just need a sample

**Comment by Dr4g0nM4st3r** [comment]
the playlist/m3u is already attached. files.zip, than the file "service.m3u" is the original from my "vu ultimo4k" receiver

**Comment by aniel300** [comment]
@Fyb3roptik can i get a discord invite please

**Comment by Fyb3roptik** [comment]
Closing this as it's a duplicate. I'll be adding a generic group if one doesn't exist. This will bypass this issue
