### ISSUE TITLE
Group titles breaking with special characters

### ISSUE THREAD

**Issue by morpheus302** [Threadfin/Threadfin#124]
**Describe the bug**
When using some special characters like "&" in group titles, the filters doesn't work properly

**Server (please complete the following information):**
- OS : Docker (Unraid)
- Threadfin Version and Build 1.0 (16)

**To Reproduce**

* Go to Filter
If you have two group titles like

1. Kids & Family
2. Kids

Selecting Kids filters the kids & family category and thus breaks the utility of the filter.

**Expected behavior**
Select the appropriate filter

**Screenshots**
2 files

![1](https://github.com/Threadfin/Threadfin/assets/7501470/124773cd-4f45-4b39-9551-074a4bd2303f)
![2](https://github.com/Threadfin/Threadfin/assets/7501470/2ccc6407-d421-486b-9e2e-ba967fc88c11)

**Comment by morpheus302** [comment]
The filter used in the screenshots is "JEUNESSE" only and not "JEUNESSE & FAMILLE"

**Comment by Fyb3roptik** [comment]
Yup looks like it's the JavaScript. Should be an easy fix here

**Comment by morpheus302** [comment]
Any update for the fix? sorry for this silly question but it's really very annoying. Désolé.
