### ISSUE TITLE
The documentation is no longer accessible.

### ISSUE THREAD

**Issue by meyerjom** [Threadfin/Threadfin#125]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md 

This link no longer works.

**Comment by meyerjom** [comment]
![CleanShot 2023-08-18 at 16 53 59@2x](https://github.com/Threadfin/Threadfin/assets/5063343/afbe796b-59c3-4c40-ae5a-c264ebc91b85)

**Comment by meyerjom** [comment]
@d3m1s33 The Discord is channel is not linked anywhere in the project.

**Comment by JamsRepos** [comment]
> @meyerjom https://discord.gg/H5nEYbjq

This has expired, is there a new link @d3m1s33 ?
