### ISSUE TITLE
Two same M3U on the same Threadfin without duplicate channels

### ISSUE THREAD

**Issue by marciglesias17** [Threadfin/Threadfin#129]
Hello,

I have my Threadfin connected to a M3U list with limit of 2 devices, the provider gave me an additional list for 1 device for inviting a friend to the service, currently my Threadfin has limit of 2 devices and I would like to add 3 devices to it, I have talked to the provider and put the two lists together so I can have a M3U list with 3 simultaneous connections, is there any way to add the 2 lists, which have the same channels, have 3 connections but not have duplicate channels?

Thank you,

**Comment by marciglesias17** [comment]
They are 2 links from the same provider with different users/keys, offering the same channels, I don't understand what I should do.

**Comment by Killianbe** [comment]
+1 for that feature ! provider give me only 1 link 1 stream !

**Comment by Fyb3roptik** [comment]
This will not be added into Threadfin. Look for this being in Kernel once I can get to it
