### ISSUE TITLE
Image Cache rewrites Stream urls

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#132]
I tried using the image caching feature and after enabling it the resulting list of streams was rewritten with 443 / https links such that no stream was working anymore. I guess the rewriting script behind the https / https image cache rewriting does also rewrite the stream urls...

**Comment by meyerjom** [comment]
The images are always completely destroyed when they go through Threadfin. No matter if with or without cache.

**Comment by YodaDaCoda** [comment]
I think this line is to blame. If the "Force HTTPS" option is enabled, then the stream URL uses the HTTPS domain too.

https://github.com/Threadfin/Threadfin/blob/6d5ee16d31290cad530945275bb12c4c2aebfe2c/src/system.go#L349C3-L349C3

I have no use-case for forcing the stream URL to https, but I need the cached image URLs to use https so that they'll show up in Plex. I'd like to see this separated into multiple different settings.

**Comment by troykelly** [comment]
I can confirm that no streaming works when this option is enabled (because everything is rewritten to https and port 443)

```text
2024/01/17 11:52:54 [Threadfin] Buffer:                 true [ffmpeg]
2024/01/17 11:52:54 [Threadfin] Buffer Size:            1024 KB
2024/01/17 11:52:54 [Threadfin] Channel Name:           ABC NEWS
2024/01/17 11:52:54 [Threadfin] Client User-Agent:      VLC/3.0.20 LibVLC/3.0.20
2024/01/17 11:52:54 [DEBUG] Streaming Status:       Stream ID = 0
2024/01/17 11:52:54 [Threadfin] Streaming Status:       Playlist: hdhr001.sy3 - Tuner: 1 / 4
2024/01/17 11:52:54 [DEBUG] Create virtual filesystem Folder:/tmp/threadfin/2024-01-58NL-FBA0TJ/H3S279HT8BS5JQ6FSIRG/12669637b673488d397748d9a696239a/
2024/01/17 11:52:54 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
2024/01/17 11:52:54 [Threadfin] Streaming URL:          https://hdhr001.automation.example.invalid:443/auto/v24
2024/01/17 11:52:54 [DEBUG] FFMPEG:                 /usr/bin/ffmpeg [-user_agent Mozilla/5.0 (Linux; Android 11; Nokia Streaming Stick 800 Build/RTT0.210618.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36 -hide_banner -loglevel error -i https://hdhr001.automation.example.invalid:443/auto/v24 -c copy -f mpegts pipe:1]
2024/01/17 11:52:54 [Threadfin] FFMPEG:                 Processing data
2024/01/17 11:52:54 [Threadfin] Streaming Status:       Receive data from FFMPEG
2024/01/17 11:52:54 [Threadfin] FFMPEG log:             [tcp @ 0x55d05baa1b00] Connection to tcp://hdhr001.automation.example.invalid:443 failed: No route to host
2024/01/17 11:52:54 BACKUP NUMBER:  1
2024/01/17 11:52:54 STREAM ID: 0
2024/01/17 11:52:54 PLAYLIST ID:  H3S279HT8BS5JQ6FSIRG
2024/01/17 11:52:54 STREAM ID:  0
2024/01/17 11:52:54 STREAM:  map[0:{ABC NEWS  /tmp/threadfin/2024-01-58NL-FBA0TJ/H3S279HT8BS5JQ6FSIRG/12669637b673488d397748d9a696239a/ 12669637b673488d397748d9a696239a 0 H3S279HT8BS5JQ6FSIRG hdhr001.sy3 false https://hdhr001.automation.example.invalid:443/auto/v24    []         0 0 false 0 false 0  0 0 0 0 0001-01-01 00:00:00 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC 0 0 map[] []}]
2024/01/17 11:52:54 START OF BACKUP 1 STREAM
2024/01/17 11:52:54 [Threadfin] Backup Channel 1 URL:    
2024/01/17 11:52:54 [DEBUG] Create virtual filesystem Folder:/tmp/threadfin/2024-01-58NL-FBA0TJ/H3S279HT8BS5JQ6FSIRG/12669637b673488d397748d9a696239a/
2024/01/17 11:52:54 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
2024/01/17 11:52:54 [Threadfin] Streaming URL:          
2024/01/17 11:52:54 [DEBUG] FFMPEG:                 /usr/bin/ffmpeg [-user_agent Mozilla/5.0 (Linux; Android 11; Nokia Streaming Stick 800 Build/RTT0.210618.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36 -hide_banner -loglevel error -i  -c copy -f mpegts pipe:1]
2024/01/17 11:52:54 [Threadfin] FFMPEG:                 Processing data
2024/01/17 11:52:54 [Threadfin] Streaming Status:       Receive data from FFMPEG
2024/01/17 11:52:54 [Threadfin] FFMPEG log:             https://hdhr001.automation.example.invalid:443/auto/v24: No route to host
2024/01/17 11:52:54 [Threadfin] FFMPEG log:             : No such file or directory
```

**Comment by Fyb3roptik** [comment]
You cannot mix http and https. This is not a limitation of threadfin but rather the web in general. You either go ALL HTTPS or ALL HTTP. You CANNOT have mixed

**Comment by jbruns** [comment]
Maybe the issue was misunderstood: when the Force HTTPS setting is enabled, the upstream channel URLs from an HDHR or IPTV provider are also rewritten, which is undesired. I don't claim to have deep understanding of the code, but I believe the rewrite is happening here:

https://github.com/Threadfin/Threadfin/blob/77129c8db012cfd2dda21e200db5b461632239bf/src/m3u.go#L237

Threadfin then forces https connections _outbound to the stream provider_, rather than _inbound to itself_ (which I think is what we want, or, what I wanted, anyway.)

**Comment by troykelly** [comment]
@Fyb3roptik Can we please re-open this issue until it's resolved?

**Comment by Fyb3roptik** [comment]
No I will not be looking into this. Threadfin will not be receiving any updates as it's being pulled into a different project

**Comment by troykelly** [comment]
To clarify, you are canning Threadfin? @Fyb3roptik

**Comment by Fyb3roptik** [comment]
Eventually yes it will be archived
