### ISSUE TITLE
[HELP] M3U8 Provider and ffmpeg stream buffer.

### ISSUE THREAD

**Issue by konecnyna** [Threadfin/Threadfin#136]
My provider is `m3u8` streams only so I'm required to use a stream buffer for my end client (Plex.) Right now I have to use ffmpeg to get the stream to work with plex but have constant issues. 

I was able to use these arguments to give me the most reliable result:
```bash
-re -hide_banner -loglevel error -i [URL] -c:v copy -c:a copy -f mpegts pipe:1
```

I read Plex can struggle with some stream audios so I also tried:
```bash
-hide_banner -loglevel error -i [URL] -c:v copy -c:a -c:a libmp3lame -f mpegts pipe:1
``` 
But without `-re` it would crash on Plex after 2-3 minutes.

`-re` (Read input at native frame rate) seemed to be most helpful in making the stream reliable but it becomes extremely sluggish (upwards of 5 seconds to tune into a channel) and will buffer much more often than the upstream source. The sluggishness also happens with VLC so it's not a client issue. Without `-re` it's much faster and works great on VLC but the stream often crashes when using Plex.

I've been dealing with this for a while first with xTeve and has persisted over to Threadfin. Any ideas or suggestions?

**Comment by Deihmos** [comment]
Are you using Android? On my shield TV xteve, threadfin and telly are all unreliable. The streams always unexpectedly end with an error. Playback is perfectly fine on my Apple TV.

**Comment by konecnyna** [comment]
@Deihmos It happens on both the Shield TV and my Pixel 7 (android). Maybe it's an Android codec problem?

**Comment by Deihmos** [comment]
I have struggled with it for months and gave up. I guess it has something to do with the codecs. 

Emby is another option that works perfectly fine on Android. Maybe one day Plex will support m3u.

**Comment by konecnyna** [comment]
@d3m1s33 the stream last a bit longer than the default options but still crashes after 5-10 minutes in Plex.

I noticed that in VLC there will be a momentary hick-up where it buffers around the same time Plex would crash. Seems VLC is a bit more resilient handling the issue.


If I add the -re flag to the args it works fine but causes the same issue of having to wait almost 10 seconds for the stream to start.

**Comment by konecnyna** [comment]
I tried `VLC` as the buffer but got the same results. I think the issue lies in Plex and not being able to handle the hiccup / stream buffer issue. 

I also tried using these ffmpeg flags
`-hls_time 5 -hls_list_size 0 -hls_segment_filename "segment_%03d.ts"`

Which had similar results to `-re` but felt slower, I assume, from `hls_time` trying to buffer a 5second segment. 

Is it possible the upstream source is doing something odd? 
![image](https://github.com/Threadfin/Threadfin/assets/3903695/27f461eb-71da-42d3-82ba-8f2838dcb4da)
![image](https://github.com/Threadfin/Threadfin/assets/3903695/9bb8f4ff-78f0-4996-abb3-6d06c8b6d6e7)

**Comment by konecnyna** [comment]
Wow!

So I localized the issue to specifically **Android Plex client**.

Unfortunately still runs into stream fail. I did more testing around Plex and Plex web works fine with default settings. The Nvidia shield (android tv) and my Android Pixel 7 both get stream crashes after 3-5minutes.

Guessing Android are using some old codecs(?) on the client. 

Error logs from Plex when the android client crashes:
<img width="925" alt="image" src="https://github.com/Threadfin/Threadfin/assets/3903695/1d4fe4ea-d957-4a92-90dd-5e8b7888e2a2">

```
[Req#55ca4/Transcode] Streaming Resource: Cannot make a decision because either the file is unplayable or the client provided bad data
```

The extra fanciness stream is SUPER fast @d3m1s33! If I can ever figure out the Android Plex client issue ill def switch over to those args. When I use it with Plex web it's perfect.

**Comment by konecnyna** [comment]
It is Apollo yeah.

`-re` solves all the issues I have on Android clients. I can watch a live stream on the shield for 4+ hours with no issues. The side effect from that flag is it creates about a 3 to 5 second delay to tune to the channel which is a bad experience.

**Comment by konecnyna** [comment]
Sounds good, thank you for the help isolating the issue.

**Comment by Deihmos** [comment]
Consider using tvheadend as the buffer instead. That's what I do with a spawn profile and it works perfectly. This is the command I use on tvheadend. You will then disable the buffer on threadfin. Like I said, I can use the threadfin buffer fine with Apple TV so I think this is an issue with Plex for Android and not the provider. 

/usr/bin/ffmpeg -hide_banner -loglevel error -fflags +discardcorrupt -i pipe:0 -c:a libmp3lame -vcodec copy -c:s copy -f mpegts -tune zerolatency pipe:1

**Comment by gbenjamin24** [comment]
> Consider using tvheadend as the buffer instead. That's what I do with a spawn profile and it works perfectly. This is the command I use on tvheadend. You will then disable the buffer on threadfin. Like I said, I can use the threadfin buffer fine with Apple TV so I think this is an issue with Plex for Android and not the provider. 
> 
> 
> 
> https://forums.plex.tv/t/live-tv-iptv-support/780320/47
> 
> 
> 
> /usr/bin/ffmpeg -hide_banner -loglevel error -fflags +discardcorrupt -i pipe:0 -c:a libmp3lame -vcodec copy -f mpegts -tune zerolatency pipe:1

does using tvheadend with a threadfin disabled buffer limit you to only one stream at a time?
