### ISSUE TITLE
Cannot download icon from self-signed secure http websites

### ISSUE THREAD

**Issue by bennydiamond** [Threadfin/Threadfin#137]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
PNG icon is hosted on website with either self-signed or invalid ssl cert.
Threadfin seems unable to retreive image. Shows as broken link.

**Server (please complete the following information):**
- OS: Docker running on Alpine LXC
- Arch: AMD64
- Threadfin Version and Build: Latest docker image

**To Reproduce**
- Add xmltv epg from following link: https://xmltvfr.fr/xmltv/xmltv.xml.gz
- Find m3u playlist that includes channel supported in xmltv: https://iptv-org.github.io/iptv/countries/fr.m3u
- Map channel that includes an image hosted on unsecure web server (arte is one of them but not available in the m3u playlist linked above. I guess you could just map Arte XMLTV entry to whatever channel.
- Image should not download properly

**Expected behavior**
Icon should download from unsecure https website.

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/6563977/a0df7561-bd0a-4f61-bec4-fe2845406a57)

**Additional context**
Example image that causes issue: http://s3.i3ns.net/portal/picon/2021-06/37306f7774bbe96a948dc9d923c1db22.png

**Comment by Fyb3roptik** [comment]
That isnt something I can fix. It wont work unless the SSL cert is valid
