### ISSUE TITLE
Errorr s1001 streaming with plex

### ISSUE THREAD

**Issue by memnos** [Threadfin/Threadfin#138]
Hello,
i'm really new with iptv streaming in plex.
I've just set up my m3u file as a tuner via Threadfin and when i try to stream any channel with plex i have errorr s1001 (network)
I tried with all Stream Buffer options but nothing seems to change.

I don't know if i have to ask here or on plex forum.
Can anyone give me some help?

Tnx

**Comment by Fyb3roptik** [comment]
Have you tried playing one of the urls in VLC? You can open the m3u in a file editor

**Comment by memnos** [comment]
Yes, i can play in VLC. 

And i can edit m3u file with word.

I have this as first lines:
#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="INFO EVENTI" tvg-logo="http://XXXXXXX.XXXXXXX.XXXX:6923/images/XXXXXXXXXXXXX.jpg" group-title="ITALIA [XXXXXX]",INFO EVENTI
http://XXXXX.XXXXX.XXXX:XXXX/XXXXX/XXXXXXX/XXXXXX

**Comment by memnos** [comment]
Tnx fot your hints.
Following documentation i changed ffmpeg option in TF
from
-hide_banner -loglevel error -i [URL] -c copy -f mpegts pipe:1
to
-hide_banner -loglevel error -i [URL] -c:a libmp3lame -vcodec copy -f mpegts pipe:1

And now it seems to work.

I have to check if all the channels work.
