### ISSUE TITLE
Threadfin Dummy EPG and Plex

### ISSUE THREAD

**Issue by memnos** [Threadfin/Threadfin#139]
Hello, 
i read documentation, but cannot solve my problem.
For those channels not present in epg file, in Threadfin i put Threadfin dummy epg.

But when i'm in plex i'm asked to choose a channel EPG. Open manually available channels i cannot find anything about Threadfin Dummy.
How can i us it?
Here is what i have in Threadfin
![threadfin](https://github.com/Threadfin/Threadfin/assets/25641404/0b0ee8f9-f5d8-487b-b1d0-4ac4a4248140)

Here i what i see in plex
![Immagine 2023-09-25 163641](https://github.com/Threadfin/Threadfin/assets/25641404/d849234c-d58c-409e-843e-938eae941d92)

Tnx

**Comment by memnos** [comment]
> The dummy just adds a "dummy guide" using the option chosen for time. In your screenshot this would be 360 min.
> 
> So TF has created EPG guide entries for every 360 min (6 hours).
> 
> When adding this channel in Plex (mapping) you select the drop-down menu on the right and scroll and select the proper guide entry, named as your channel, and then save and it will update the guide.
> 
> Plex will ONLY auto match on the mapping page the 1st time you setup the tuner, all additional adjustments like adding channels you must manually map the epg from the drop-down in Plex.

The problem is that in the drop down menu i cannot find some of the channels. The channels that are not in the epg file for which i use FT dummy epg are not in the drop drop menu.

**Comment by Fyb3roptik** [comment]
<img width="287" alt="Screenshot 2023-09-26 at 10 15 15 AM" src="https://github.com/Threadfin/Threadfin/assets/339131/7c1558e6-f4d9-444a-b028-06630fab4578">

**Comment by memnos** [comment]
OK, i'll give it i try.
Tnx
