### ISSUE TITLE
Mapping and Bulk Edit

### ISSUE THREAD

**Issue by xtinct101** [Threadfin/Threadfin#14]
Currently when enabling Bulk Edit in Mapping, selecting multiple channels and editing a value, only the selected channel value gets changed and not all the selected channels.

To recreate, select Bulk Edit, check 2 or more channels, go into the settings of a single channel, change a value like "Active" or "XMLTV" and click "Done". Only that single channel should show the change.

Another issue, I can open a separate bug, present is that currently you can make changes on a channel settings and even if you don't click "Save" to save the changes, those changes are stored and saved.

**Comment by Fyb3roptik** [comment]
I am not able to reproduce this. Are you using docker?

**Comment by Fyb3roptik** [comment]
Right now only Active and starting channel number are bulk editable. I have to get XMLTV stuff working for bulk edit

**Comment by Fyb3roptik** [comment]
Unfortuantely being able to bulk map xmltv would require a significant rewrite =/
