### ISSUE TITLE
Characters are removed from XMLTV

### ISSUE THREAD

**Issue by bruor** [Threadfin/Threadfin#142]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Some characters are stripped out of EPG data when threadfin consumes and recomposes the feed. 

**Server (please complete the following information):**
- OS:  Linux - Ubuntu
- Arch x64
- Threadfin 1.0 (17)

**To Reproduce**
1. Feed threadfin EPG file from: https://epg.tvnow.best/utc.lite.xml
2. This file will contain entries similar to <title lang="en">José Díaz-Balart Reports</title>
3. Download the XMLTV generated by threadfin
4. You will see that it changes those entries to <title lang="en">Jos Daz-Balart Reports</title>

**Expected behavior**
Leave titles intact with special characters

**Comment by Fyb3roptik** [comment]
You need to enable this:
<img width="202" alt="Screenshot 2023-09-26 at 11 48 17 AM" src="https://github.com/Threadfin/Threadfin/assets/339131/9defe7bc-55cc-4125-b5e4-1c5ccf3e6ba0">
