### ISSUE TITLE
Wont compile Ubuntu 22.04

### ISSUE THREAD

**Issue by speedtoys** [Threadfin/Threadfin#143]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Fails with two errors in memfs and avfs

**Server (please complete the following information):**
- OS Ubuntu 22.04
- Arch Intel 64bit
- Threadfin  Main build

**To Reproduce**
go build threadfin.go

**Expected behavior**
It should compile...

**Screenshots**
<img width="591" alt="Screen Shot 2023-09-26 at 10 50 03 PM" src="https://github.com/Threadfin/Threadfin/assets/65208176/8e8d1e0f-5d06-465f-ab88-7df92046572f">

**Additional context**

**Comment by Fyb3roptik** [comment]
Use an already compiled binary please
