### ISSUE TITLE
VLC + Backup channels not working together

### ISSUE THREAD

**Issue by Ondrashek** [Threadfin/Threadfin#144]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
VLC buffer won't use backup channels. Only ffmpeg buffer working.

**Server (please complete the following information):**
Linux Docker 10 (18)

**To Reproduce**
Set VLC buffer in settings
Set backup channel
Look at logs

**Expected behavior**
Backup channel should trigger

**Desktop (please complete the following information):**
Linux

**Comment by Fyb3roptik** [comment]
Patched in 1.0.20
