### ISSUE TITLE
Threadfin doesn't parse provider playlist with no tags element

### ISSUE THREAD

**Issue by Ondrashek** [Threadfin/Threadfin#146]
**Is your feature request related to a problem? Please describe.**
When I import playlist from providers and M3U playlist doesn't contain tags element Threadfin have wierd results

**Describe the solution you'd like**
```
#EXTINF:-1 tvg-id="none" tvg-name="none" tvg-logo="" group-title="CZ/SK", 360TuneBox (CZE)
http://[url to stream].ts
```
Threadfin should parse channel name without space and use right stream url. For now imported channels have space in start and stream url is not assign right. Version 10 (3) parsed well (with space in start, but url assign good) but newer version not.

**Comment by Ondrashek** [comment]
I am sorry, but I am not able to change this when provider have m3u playlist on his server :-)

**Comment by Fyb3roptik** [comment]
Then find another provider. You wont get any software working that supports this

**Comment by glassbase** [comment]
Found this thread via Google. I know it is closed. I just decided to get into IPTV and my provider does not provide any identifiers so then it is not compatible, find a new one? That is why it says 0 streams?

Example m3u:
```
#EXTM3U
#EXT-X-SESSION-DATA:DATA-ID="com.xui.1_5_5r2"
#EXTINF:-1,USA A&E UHD
http://xxxx-iptv.com:80/xxxxx/xxxxx/175784.ts
#EXTINF:-1,USA AccuWeather
http://xxxx-iptv.com:80/xxxxx/xxxxx/175785.ts
#EXTINF:-1,USA AMC
http://xxxx-iptv.com:80/xxxxx/xxxxx/175787.ts
```
