### ISSUE TITLE
Always keep filtered channels active

### ISSUE THREAD

**Issue by ManvirDehal** [Threadfin/Threadfin#147]
**Is your feature request related to a problem? Please describe.**
When I make a filter, it works perfectly but whenever my source updates itself, the channels change and become inactive even thought they are being filtered. I would love for the filtered tab to always keep filtered channels enabled so that I won't have to go in and manually update it when the channels change on my iptv source.

**Describe the solution you'd like**
Maybe a toggle in the new filter window that will always keep filtered channels enabled.

**Describe alternatives you've considered**
I have not found any alternatives to fix this issue. I've thought about using a script through the api but the api isn't available at the moment

**Comment by ManvirDehal** [comment]
Ahhh I understand.  How would I be able to

**Comment by ManvirDehal** [comment]
Ahh I understand.  How would I be able to ensure that new channels get mapped?

**Comment by Fyb3roptik** [comment]
If you're talking about live event stuff then that is normal. If the provider changes the tvg-id it will cause it to deactivate
