### ISSUE TITLE
Best Path for xTeVe migration

### ISSUE THREAD

**Issue by rgabrielson11** [Threadfin/Threadfin#148]
What is the best (easiest) path to migrate from xTeVe to Threadfin?  Ive duped the config folder (docker) but seems the DB schema is not compatible.

Some other way?  Hundreds of channels I would have to remap to EPG data.

**Comment by Fyb3roptik** [comment]
The restore should work. Let me know if it doesn't

**Comment by flyize** [comment]
It does not seem to work for me. No errors in log or on screen, nothing changes.

**Comment by Fyb3roptik** [comment]
For now unzip the backup file and move the files into the threadfin config root (typically ~/.threadfin)
