### ISSUE TITLE
Setting to allow different filter channel number increments

### ISSUE THREAD

**Issue by flyize** [Threadfin/Threadfin#152]
**Is your feature request related to a problem? Please describe.**
My OCD really wants threadfin to use the actual channel numbers provided by my HDHR. If we can't do that, can we at least be able to set the channel increment to something other than 10? 

**Describe the solution you'd like**
I'd like to be able to set a channel increment of 1, so that when I start at 0 it goes 1,2,3,4,5

**Describe alternatives you've considered**
Getting a better OCD treatment plan

**Additional context**
Also, its very confusing to new people to set a starting channel at 1000 and then threadfin *actually* starts at 10,010.

**Comment by Fyb3roptik** [comment]
You can bulk edit the channel numbers and set a starting number and it will go up by 1 from there

**Comment by Fyb3roptik** [comment]
What I like to do is select the channels I want to edit, sort by name, bulk edit and set the channel number to my starting number

**Comment by flyize** [comment]
@Fyb3roptik I can't get bulk edit to work at all. It only edits a single channel.

**Comment by Fyb3roptik** [comment]
It will only popup 1 channel, but if you have several checked in bulk edit then it will change the channel numbers. This works for me on the current build

**Comment by Fyb3roptik** [comment]
You single click, not double click. This does not happen for me

**Comment by flyize** [comment]
What am I doing wrong?

https://www.loom.com/share/fc565ea98fc642ddacb188fd5e388f00?sid=131b1226-af76-456a-abcc-dc8b4fda50a4

**Comment by Fyb3roptik** [comment]
You are editing Inactive channels and furthermore you are not bulk editing. You have to check the boxes next to the GREEN ones that you want to edit. Then click on any of the channels and it will open a modal where you can edit the starting channel number at the top

**Comment by flyize** [comment]
So I have to activate each channel one by one?

**Comment by flyize** [comment]
@Fyb3roptik just following up on this, as I really love this fork of xsteve. Is there a way to bulk activate channels then?

**Comment by Fyb3roptik** [comment]
That is on my list to fix. But for now yes one by one. The hard part here is you would need to set each selected channel to the same EPG info since bulk edit will do the same changes to selected channels

**Comment by flyize** [comment]
If I don't touch the field, does it actually have to edit it? FWIW, I can bulk edit channel activation without touching EPG in xteve.

**Comment by Fyb3roptik** [comment]
Yes I am aware of that. One of the changes I made broke it :)

**Comment by flyize** [comment]
BTW, removing the Bulk Edit checklist from the inactive channels (until you have some time to locate the inactive channels bug) might help prevent confusion. Of course, I have no idea how hard that is to do...
