### ISSUE TITLE
load from baclkup on new install 

### ISSUE THREAD

**Issue by dingfelder** [Threadfin/Threadfin#153]
When you start up threadfin for the first time it requires you to enter a m3u url and then an xml url

You (I think) cannot get past that step if you do not input those 2 urls.

If you have an export/backup of a working version, a Is it possible to add an option on start up to load that backup (which contains those urls) rather than having to load them manually and then import the backup as a separate step?

**Comment by dingfelder** [comment]
Part of the problem is that i'm trying to run threadfin out of a docker container running under a kubernetes "chart" implementation, which is obviously out of scope for you guys... 

But in this instance i'm working on cleaning up environment variable passing, and there seems to be an error when I try and add the xml file as it just hangs and I don't see an error message - so there is no way to get passed that step.

In my opinion, the easiest thing would be that on the m3u input screen currently, there is only a save button (there is no "skip" or "cancel" option.)  If that were there you could just skip the step.  same for the xml page.

Or maybe even easier - if I passed in an option like SKIP_SETUP, when starting up the container - if that variable was set, it would skip the first 2 input screens so the user could get to the settings page directly.  
There must already be logic on startup to check if the urls are set, and if not then display those pages...  
Where that check occurs is where we could look for the environment variable (and skip that step)

**Comment by dingfelder** [comment]
> You can easily put the backup files in the root and start it up. Same thing

That will be interesting but doable I guess - as its a Kubernetes app (running who knows where) which uses a docker container, I suppose I can sh into the running container and create a file in the root and then restart it and hope the file persists to the next instance when I restart it - so it should be in /home/threadfin?  or in the /home/threadfin/config folder?

**Comment by Fyb3roptik** [comment]
Fixed in #155. Once 1.0.19 deploys it will be there
