### ISSUE TITLE
Would that repository be useful to me?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Threadfin/Threadfin#158]
## Just Ask
I saw this project and I think it's great, I can edit the channel lists and .etc
I hope you can help me find some software or if this project allows this.

I have a Ubuntu server on a local network that has an internet speed of **1.5mb/s.**
If we look at stream statistics, to watch a **1080p H264** video, you would need a bandwidth of **6 Mb/s** on average (a speed that the server does not have).

There is some life of storing an external m3u list, but in a file in /tmp/, said file will only be 1gb and where the transmission will be stored.
As the server does **not have** a speed of **6Mb/s** to watch a live video in 1080p, you will suffer **several playback interruptions** because you only have 1.5mb/s.

The idea is to download the video little by little at 1.5mb/s, store it in /tmp/ and when you have a percentage stored, then transmit the local video without playback interruptions, only having perhaps a few seconds of delay.

**Comment by Fyb3roptik** [comment]
What is your question? How do you only have 1.5mbps? What are you trying to do?

**Comment by AnonymousWebHacker** [comment]
> What is your question? How do you only have 1.5mbps? What are you trying to do?

Hi, greetings
**How do you only have 1.5mbps?**
It is not necessary to expose the country where I am now,  I am right now in Cuba. But it turns out that that country only has 1.5mb/s of internet, it is the maximum you can buy

**What are you trying to do?**
Example, there is an IPTV channel with this address http://vcpar.myplaytv.com/esportsmax/live/playlist.m3u8 . 
This transmission is in 720p, so a minimum of 3 MB/s is needed to watch without interruptions. From where I am, if I only have 1.5 mb/s, you know that I have 10 thousand interruptions of reproductions, due to the poor quality of the internet.

So my question.
Is there the possibility, for example, of downloading this transmission in real time, to an example file in /tmp/videolive.m3u8 at a speed of 1.5mb/s, to then be able to play the /tmp/videolive.m3u8 without transmission interruptions?

In the country where I am now, people do not know what IPtV is or what digital television is, in the middle of 2023

**Comment by 3v3rm4rt3lL** [comment]
Exactly, having a server let you download a full speed the stream, and when it need transcoding and sent a low bit rate the stream to you. For example you can achieve this by using emby, or plex and set bitrate to 1mb 480p  resolution. Or use only threadfin modify the ffmpeg option to transcode the output a lowbit rate. But using your pc it will takes longer. Even thinking about if the iptv is buffering by itself. Check ir out.

**Comment by AnonymousWebHacker** [comment]
Okay, I'll make it more complex. What do you say if I tell you that in Cuba there is no VPS hosting service, nor can you rent VPS in the clouds like Amazon Cloud or any other VPS manager? :)

**Comment by Fyb3roptik** [comment]
Your only option would be to have a server with a better connection be the proxy to then buffer it down to the right mbps for you. Sorry for your setup I hope Cuba gets better internet soon. I wonder if you could use Starlink?

**Comment by AnonymousWebHacker** [comment]
> I would say that a service like ultra.cc or other variations of that kind of service could still be purchased. Or try to use ffmpeg bufsize and make the Threadfin timeout huge.

Payment methods such as PayPal or debit cards are blocked for Cuba.

> Your only option would be to have a server with a better connection be the proxy to then buffer it down to the right mbps for you. Sorry for your setup I hope Cuba gets better internet soon. I wonder if you could use Starlink?

Impossible to acquire VPS income within the country or outside , Starlink or works in Cuba .

I'm working on the nginx option to cache locally in the form of an m3u8 list, and then move to a web player that allows m3u8 lists with 3 minutes of video delay, but without suffering cuts. I'm doing tests
