### ISSUE TITLE
Add VPN support

### ISSUE THREAD

**Issue by PilaScat** [Threadfin/Threadfin#159]
**Is your feature request related to a problem? Please describe.**
IPTVs can often only be reached via VPN

**Describe the solution you'd like**
Support for OpenVPN and/or WireGuard built-in

**Describe alternatives you've considered**
Now I'm using [xTeVe VPN](https://github.com/brycelarge/xteve-vpn) but I would try Threadfin instead

**Comment by Fyb3roptik** [comment]
This can be achieved using Gluetun and iptv-proxy. No plans to integrate any kind of VPN into this

**Comment by PilaScat** [comment]
Do I need to use both? I don't know what it's for iptv-proxy

**Comment by mf1x** [comment]
@Fyb3roptik
Would you be able to share a quick guide on how to build a setup like this?

**Comment by Fyb3roptik** [comment]
Use iptv_proxy and gluetun containers and you can funnel traffic through vpn

**Comment by mf1x** [comment]
Yes, thanks I am aware of that.

I think my Docker skills might not be good enough to set up an iptv-proxy container that works...

Wish me luck, lol.
