### ISSUE TITLE
No Channel names in Filter screen

### ISSUE THREAD

**Issue by philfycasual** [Threadfin/Threadfin#160]
**Describe the bug**
No channel names in filter screen (how am I supposed to filter if I cannot see channel names). Channels do have names as if I open the m3u playlist in another application these are loaded.

**Server (please complete the following information):**
- OS Windows 10
- Arch - Intel 64 Bit? The .exe is the amd64 exe 
- Threadfin Version and Build lastest - 1.0.19

**To Reproduce**
1. Have a playlist with streams added
2. Go to Filter
3. Observe -- a whole list of "Inactive" streams labelled "Channel: (-)"

**Expected behavior**
Channel names should load.

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/113337705/57cbbbc3-6874-419d-83c3-a8958939f8da)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser MS Edge
 - latest

**Comment by Fyb3roptik** [comment]
Can you give me a sample of your playlist? Scrub urls

**Comment by philfycasual** [comment]
No doubt a stupid question on my part, but when you say sample, what
exactly do you mean?

**Comment by meestark** [comment]
He needs a sample of the m3u playlist you are feeding into threadfin (with any credentials and actual direct URLs censored!)

if I had to guess, your provider is not giving you something like the group-title attribute that threadfin is looking for

**Comment by philfycasual** [comment]
Right so the 'base' url, but blotting out the credentials....
So, this?
`http://reddead.cf:8080/get.php?username=*****&password=*****&output=ts&type=m3u_plus`

**Comment by meestark** [comment]
Close! That link downloads a .m3u file (that's what Threadfin is actually importing).  This contains all your channel and personalized stream info. We'd need a sanitized snippet of this

**Comment by philfycasual** [comment]
Ohhhh, I got you (I hope)
So something from _within_ the m3u file:
```
http://reddead.cf:8080/series/<username>/<password>/597745.mkv
#EXTINF:-1 tvg-id="" tvg-name="The Simpsons S28 E12" tvg-logo="https://image.tmdb.org/t/p/w300/fizr0ciuwrOQVReD4DaVrAMfuAr.jpg" group-title="Family",The Simpsons S28 E12```

**Comment by GregTroar** [comment]
I got same issue it is a bit confusing but actually it is simple.
Click on New at the top left of the screen.
Click M3U Group Title
Select a group Title and click OK your channel will become active and you will see them

**Comment by MataRatos** [comment]
This also happens to me getting an m3u playlist from NextPVR. In VLC it plays ok, but Threafin doesn't retrieve the M3U playlist correctly.
Had to go back using xTeve, no issues.

**Comment by redahb** [comment]
Same happens to me. I'm grabbing .m3u from my local cable box (ZGemma). Playlist looks as follows:

```
#EXTM3U 
#EXTINF:-1 tvg-name="NPO 1"tvg-id="1:0:19:4BC9:832:600:FFFF0000:0:0:0:"tvg-logo="http://*/images/default_picon.png"tvg-chno="19401",NPO 1
```

**Comment by Fyb3roptik** [comment]
That is not a valid m3u. There should be spaces after each param

**Comment by redahb** [comment]
> That is not a valid m3u. There should be spaces after each param

I don't know why this happened whily copy/pasting. The original file has spaces. Yet Threadfin refuses to load it.

```
#EXTM3U 
#EXTINF:-1 tvg-name="NPO 1" tvg-id="1:0:19:4BC9:832:600:FFFF0000:0:0:0:" tvg-logo="http://*/images/default_picon.png" tvg-chno="19401",NPO 1
http://*:8001/1:0:19:4BC9:832:600:FFFF0000:0:0:0:
#EXTINF:-1 tvg-name="NPO 2" tvg-id="1:0:19:4BCA:832:600:FFFF0000:0:0:0:" tvg-logo="http://*/images/default_picon.png" tvg-chno="19402",NPO 2
http://*:8001/1:0:19:4BCA:832:600:FFFF0000:0:0:0:
```
