### ISSUE TITLE
Buffer Somewhere thats not RAM

### ISSUE THREAD

**Issue by ncsufan8628** [Threadfin/Threadfin#176]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I cant buffer somewhere other than RAM

**Server (please complete the following information):**
Linux Unraid

**To Reproduce**
uncheck buffer to RAM, try to play something

**Expected behavior**
channel plays

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ncsufan8628** [comment]
Yes, but even with FFMPEG, I'd love to set where I want the buffer to live.  I had the container run up like 7-8g of memory usage which seems strange.  Never had this with xteve with similar ffmpeg enabled.

**Comment by Fyb3roptik** [comment]
xteve was file based and it was much much slower. This is all done in RAM so you wont see any files

**Comment by ncsufan8628** [comment]
So what is the best way to keep the container's cache/ram usage under control?  6GB usage is not acceptable.  setting the `-m` flag in my container parameters?

As an aside, I see why RAM v. spinning disk makes sense, but RAM (20/gbs) v. m2 NVMe (4gb/s), not so much.  I'd rather save my RAM for other tasks and use my nvme drive for cache.  Is there ever a real world scenario (other than maybe handling tens or hundreds of concurrent users/buffering streams) where I'd need more than the 4gb/s bandwidth provided by NVMe?

Am I missing something in the equation as to the speed benefit from using RAM vs. nvme?

**Comment by vajonam** [comment]
should it be a total  of size/time for the buffer what does the buffer size setting do ?

**Comment by vajonam** [comment]
@Fyb3roptik 

https://github.com/Threadfin/Threadfin/blob/ec7628f5d6aa548be13a01d0083602547f23ac88/src/buffer.go#L871

That shows its multiplied by 1024, is it KB or MB?, the drop down shows MB, which means its 2G buffer in memory. Maybe just a typo somewhere. ?

**Comment by Fyb3roptik** [comment]
Those options are for the old buffer that isn't used anymore. The buffer is only ffmpeg or VLC now. So whatever options you pass there is what it will be

**Comment by vajonam** [comment]
so what is the default buffer size in memory? is there a limit?
