### ISSUE TITLE
Threadfin Removing <episode-num> From Source XML

### ISSUE THREAD

**Issue by n1xxk** [Threadfin/Threadfin#178]
**Describe the bug**
Hey,
Threadfin is removing all episode-num tags from the source XMLTV file for whatever reason so all tv show episodes are showing up as movies and duplicated in PLEX. 

**Server (please complete the following information):**
- OS Linux - Ubuntu
- Arch Intel 64 Bit
- Threadfin Version and Build 1.0 Build: 21

**Additional context**
Original XML:
```
<programme start="20231113000000 +0100" stop="20231113003000 +0100" channel="ComedyCentral.us">
    <title lang="en">South Park</title>
    <sub-title lang="en">Fishsticks</sub-title>
    <desc lang="en" desc="The kids come up with the funniest joke of all time while helping Jimmy with his comedy routine.">The kids come up with the funniest joke of all time while helping Jimmy with his comedy routine.</desc>
    <credits>
      <director>Trey Parker</director>
      <producer>Trey Parker</producer>
      <producer>Matt Stone</producer>
      <producer>Anne Garefino</producer>
    </credits>
    <category lang="en">Animated</category>
    <category lang="en">Sitcom</category>
    <icon src="https://zap2it.tmsimg.com/assets/p2026785_e_v10_aa.jpg"/>
    <episode-num system="xmltv_ns">12.4.</episode-num>
    <rating system="MPAA">
      <value>TV-14</value>
    </rating>
  </programme>
```
Threadfin Modified:
```
<programme channel="1050" start="20231113000000 +0100" stop="20231113003000 +0100">
          <title lang="en">South Park</title>
          <sub-title lang="en">Fishsticks</sub-title>
          <desc lang="en">The kids come up with the funniest joke of all time while helping Jimmy with his comedy routine.</desc>
          <category lang="en">Animated</category>
          <category lang="en">Sitcom</category>
          <icon height="" src="https://zap2it.tmsimg.com/assets/p2026785_e_v10_aa.jpg" width=""></icon>
          <credits>
              <director>Trey Parker</director>
              <producer>Trey Parker</producer>
              <producer>Matt Stone</producer>
              <producer>Anne Garefino</producer>
          </credits>
          <rating system="MPAA">
              <value>TV-14</value>
          </rating>
          <video></video>
          <date></date>
</programme>
```

**Comment by Throdne** [comment]
I have this exact issue as well.

**Comment by n1xxk** [comment]
downgrade ur version 1.0.20 as a temp fix

> I have this exact issue as well.

**Comment by Fyb3roptik** [comment]
This should have been patched in the latest release as I'm now watching for that field. Latest release is still broken?

**Comment by redtigre** [comment]
Seems doesn't seem to work for me

**Comment by andonevris** [comment]
> This should have been patched in the latest release as I'm now watching for that field. Latest release is still broken?

Can confirm broken on latest version 1.0.23

Rolling back to 1.0.20 fixes it

**Comment by andonevris** [comment]
1.0.21 removed the code regarding episode numbers, not sure why this was done but this seems to be the reason why this is now happening.

in [src/xepg.go](https://github.com/Threadfin/Threadfin/commit/987f63da2882dcd81652982e88f9609e8b42ea45#diff-0f90f28f754d54b43d69b9e6272a4809ca09d9c5ee3f772ed6917fb68842fb37)

line 906 & 1023

**Comment by bennydiamond** [comment]
Can confirm downgrading to 1.20 fixes the missing progid from xmltv issue.

For those having a hard time making version 1.20 stick in their container, make sure to disable 'auto-update' in Threadfin settings beforehand.

**Comment by iceman73** [comment]
Same issue rolling back to 1.0.20 fixed the issue

**Comment by grooverider2016** [comment]
Is this going to be fixed at all? It's a real pain as plex tries to put episodes in Movies library when you record something.

**Comment by grooverider2016** [comment]
> This should have been patched in the latest release as I'm now watching for that field. Latest release is still broken?

This is definitely still an issue. Can it be fixed as it is a major issue stopping recordings in Plex?

**Comment by grooverider2016** [comment]
Just found a fix but this is done through using EPG123 to generate my guide xml file to be read by threadfin. In EPG123 i have set it to append the season/episode info to the description and after doing this it seems that Plex is picking up episode numbers and so is now showing correctly in Plex so can now record episodes and series and it saves it to the correct library.

**Comment by chreds** [comment]
I just reverted to 1.0.20 and life is good. Not everyone uses epg123 so that's only a partial workaround.

**Comment by grooverider2016** [comment]
> I just reverted to 1.0.20 and life is good. Not everyone uses epg123 so that's only a partial workaround.

I tried that and it only partially worked. I would highly suggest using EPG123 in combination with Schedules Direct if you can. I have it all automated to download guide data daily and export the info to Threadfin. Also got a daily task to check and update Threadfin running and some other automations via PowerShell to restart services etc if they stop/crash. For the most part it all works well.

**Comment by philashworth** [comment]
Im seeing 
`<episode-num system="original-air-date">2024-07-27 18:10:00</episode-num>`
On a channel that is marked as Movies. 
In fixing this issue has this issue been introduced?
