### ISSUE TITLE
Can't access web gui anymore

### ISSUE THREAD

**Issue by mshorey** [Threadfin/Threadfin#181]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
When I try to access the webgui it just shows a dim version of the server information page and a continuously spinning blue icon in the center of the screen.  When opening developer tools there are errors for:

"base_ts.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'hide')
    at showElement (base_ts.js:69:30)
    at ws.onmessage (network_ts.js:43:13)"

And the web gui will never load.

**Server (please complete the following information):**
- OS: Docker/Docker-Compose running on Debian 11
- Arch: Intel 64 Bit
- Threadfin Version and Build: 1.0.22, 1.0.21, 1.0.20.

**To Reproduce**
1. Go to: I try to go to the web gui of Threadfin "192.168.1.35:30044/web/"
2. Click on: N/A
3. Scroll down to: N/A
4. See error: "base_ts.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'hide')
    at showElement (base_ts.js:69:30)
    at ws.onmessage (network_ts.js:43:13)"

**Expected behavior**
For the web gui to load.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 23H2
 - Browser Have tried Chrome 119.0.6045.160, Firefox 120.0, and Microsoft Edge 119.0.2151.72
![Screenshot 2023-11-26 131626](https://github.com/Threadfin/Threadfin/assets/40186061/c853ab29-d199-44fb-b15d-f66d3fa27ba6)
![Screenshot 2023-11-26 131510](https://github.com/Threadfin/Threadfin/assets/40186061/665eb997-2400-4554-9220-703d94037f8c)
![Screenshot 2023-11-26 131149](https://github.com/Threadfin/Threadfin/assets/40186061/f2d683b2-c915-4df1-a83a-0ecc7243107f)

**Additional context**

**Comment by foscoj** [comment]
Had this today, disabled pihole for first start and it worked... Did not investigate further, but apparently there is some call to a blocked URL causing this behavior

**Comment by mshorey** [comment]
> Had this today, disabled pihole for first start and it worked... Did not investigate further, but apparently there is some call to a blocked URL causing this behavior

Yep.  This did it.  Super strange that pihole would be causing this issue.

**Comment by foscoj** [comment]
Actually the call to whatever tracking / ad URL is "causing" this

**Comment by mshorey** [comment]
https://github.com/StevenBlack/hosts/issues/2515
