### ISSUE TITLE
0 added to inactive channel numbers

### ISSUE THREAD

**Issue by jimbothigpen** [Threadfin/Threadfin#182]
**Describe the bug**
When renumbering inactive channels, a 0 is appended to the end of the channel number I enter.

**Server**
- Docker container in swarm engine 24.0.5 on Debian 12
- Intel 64 Bit
- Threadfin 1.0 (23)

**To Reproduce**
1. Change the channel numbers for an inactive channel
2. Save the changes
3. Navigate to a different menu, return to the Mapping page, and check the channel number just changed 

**Expected behavior**
Use the number I enter for the inactive channel without adding a 0

**Comment by Fyb3roptik** [comment]
That's a feature not a bug. Inactive channel numbers don't matter except they need that extra 0

**Comment by jimbothigpen** [comment]
They "need" the extra 0? Why?
