### ISSUE TITLE
Assigning Xteve Dummy - PPV causes threadfin to hard crash

### ISSUE THREAD

**Issue by Wmartin417** [Threadfin/Threadfin#19]
I have a few channels I would like to assign Xteve Dummy - PPV to them, but when I assign just one and click save on the mapping editor causes Threadfin to hard crash and refuses to restart til I delete the playlist filter that contains the assigned channel from settings.json.

My setup:
Docker version 20.10.18, build b40c2f6 on Debian 11
Threadfin 0.9 (6) on docker its fyb3roptik/threadfin:0.9.4

When it crashes, it says

```
2022/10/17 02:10:00 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
panic: runtime error: index out of range [0] with length 0

goroutine 5253 [running]:
threadfin/src.getProgramData({{0xc009594768, 0x14}, {0xc003ffa410, 0x3}, {0xc019147fc0, 0x32}, {0xc003ffa413, 0x3}, {0xc003ffa420, 0x10}, ...})
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:801 +0x7cc
threadfin/src.createXMLTVFile()
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:748 +0x738
threadfin/src.buildXEPG.func1()
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:70 +0x34
created by threadfin/src.buildXEPG
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:64 +0x133

```

Also tried assigning a random channel, clicked save and causes it to crash.

**Comment by Fyb3roptik** [comment]
#20 0.9.7 should fix this
