### ISSUE TITLE
Error too many open files

### ISSUE THREAD

**Issue by loadamasta** [Threadfin/Threadfin#190]
If saving anything on the mapping website, the log shows an error "too many open files". Threadfine then hangs for a couple of minutes. 

"Accept error: accept tcp [::]:34400: accept: too many open files; retrying in 5ms"

Xteve does not show that error and runs very well on my mac.

Running on terminal on mac os 10.15.7

**Comment by Fyb3roptik** [comment]
That is a macos issue. Not a threadfin issue
