### ISSUE TITLE
Mapping menu is empty

### ISSUE THREAD

**Issue by jpcapone** [Threadfin/Threadfin#192]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
After configuring the M3U and EPG I filter based on groups.  I have been testing with two groups for filtering.  
![image](https://github.com/Threadfin/Threadfin/assets/47680328/1aeca0a3-a715-453a-ac7e-b955a8190c8c)
and I can see channels beneath the filter items.  When I go to mapping no channels appear.  

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
Docker Image
- Arch [e.g. Intel 64 Bit]
Docker Image
- Threadfin Version and Build [to be found in the Threadfin log]
1.0 (23)

**To Reproduce**
1. Go to 'Mapping'
2. Click on 'Mapping'
No channels appear
![image](https://github.com/Threadfin/Threadfin/assets/47680328/0e602445-5d40-44dd-a2b8-9f0012f63d6a)

**Expected behavior**
I expect channels to aqppear

**Comment by kirilldem** [comment]
How did you fix this?

**Comment by jpcapone** [comment]
> How did you fix this?

In my scenario I couldn't validate that the actual m3u was working.  I took the same url and put it into emby and no channels loaded.  So I wasn't 100% sure that the issue was Threadfin.  Can you confirm that your m3u works?

**Comment by jpcapone** [comment]
Tried another m3u and got the same result.  Can anyone confirm if Threadfin actually works?

**Comment by orangejulius77** [comment]
I have exactly the same issue on the same platform

**Comment by Fyb3roptik** [comment]
I use it daily so yes it works. Do you have a matching epg? It won't work without a matching epg

**Comment by Fyb3roptik** [comment]
And did you set a filter and the channels in the filter have epg?

**Comment by jpcapone** [comment]
> And did you set a filter and the channels in the filter have epg?

I added the filters in my screenshot above for future reference.  I can only assume that the epg matches as its from the same provider as the M3U link.  Is there anything you can think of that I could try to remediate the issue?

**Comment by jpcapone** [comment]
I am thinking it might have something to do with this:
![image](https://github.com/Threadfin/Threadfin/assets/47680328/2dc113f9-93d8-4cf4-926a-e767282b8926)
I have updated it soooo many times but the availability never reaches 100%.  May be too  many streams?

**Comment by kirilldem** [comment]
> > How did you fix this?
> 
> In my scenario I couldn't validate that the actual m3u was working. I took the same url and put it into emby and no channels loaded. So I wasn't 100% sure that the issue was Threadfin. Can you confirm that your m3u works outside of Threadfin?

In my case I selected tv guide data to be coming from Plex and not from an XML file. Once I changed that in the settings you can map channels.
