### ISSUE TITLE
Smaller docker image for a smart service

### ISSUE THREAD

**Issue by volschin** [Threadfin/Threadfin#193]
**Is your feature request related to a problem? Please describe.**
The size of the docker image has grown really large since v1.0.18.

**Describe the solution you'd like**
In the Ubuntu base image there is a lot of unneeded crap with some CVE. You should try a smaller base image.

**Describe alternatives you've considered**
No

**Comment by Fyb3roptik** [comment]
Sorry not doing any new changes to this repo
