### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by WKEA-301** [Threadfin/Threadfin#194]
Hello, I am trying out the docker version you recently created. I encountered a few issues.

1. When adding a playlist, it won't let you change the number of tuners. This doesn't apply to adding your playlist even when you go to settings.
2. When mapping, Bulk Edit doesn't work as intended. Let's say you want to activate multiple channels; selecting all that apply and clicking activate as before only activates the single channel.
3. When mapping a single channel, the option to update the name is no longer available. In the past, this would pull from the XMLTV file.
4. The backup channels don't show up correctly. It shows the xmltv options and not the channel list.

Any help with this would be great. The single tuner would be #1.

**Comment by Fyb3roptik** [comment]
You can update the tuner by editing the json file accordingly. Sorry but development has ceased with Threadfin as it is being pulled into my other project Kernel
