### ISSUE TITLE
Threadfin not reporting EPG data correctly to Plex so tv programmes are showing as movies

### ISSUE THREAD

**Issue by grooverider2016** [Threadfin/Threadfin#198]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin is not categorising tv programmes correctly so plex sees them as movies and so will only record to the movies libraries. Also means the guide in plex is missing the "New" tags for programmes.

**Server (please complete the following information):**
- OS Windows 2022 Server
- Arch 64bit Intel
- Threadfin Version and Build 1.0.23

**To Reproduce**
Select a programme from guide to record. Save location will show as Movie. Tv is not an issue and there is no option to select "This Episode" or "All epsiodes". No episode numbers are being displayed. the same programmes from my HDHomerun using the same epg that threadfin imports from show episode number details, "new" tags and save to the TV library offering "This Episode" and "All Episodes" options are available. 

**Expected behavior**
When selecting a programme to record I would expect it to offer up options to select this episode, all episodes, and recording to tv library by default. Also NEW programmes should show up tagged as new in the guide. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Edge
 - Version 

**Additional context**
It would seem that Threadfin is stripping out a lot of the information from the source EPG when it is rebuilding it and this is causing plex to mislabel programmes as movies. There have been suggestions in other issues that it could be due to the episode numbering being ommited from the EPG and that rolling back to 1.0.20 is the temp fix but I have tried rolling back and rebuilding the EPG and then rebuilding the plex guide but this hasnt worked. Programmes are still shoowing up as movies when trying to schedule a recording

**Comment by Fyb3roptik** [comment]
It has to be marked as Series in order to save under TV. Verify that in Threadfin, the channel in question is set as Series. This is a Plex thing not a Threadfin thing

**Comment by grooverider2016** [comment]
This is not a plex issue. It is an issue with episode numbers not being included in the Threadfin guide for certain programmes and so without this info Plex presumes it is a movie. 
![HDHR EPG](https://github.com/Threadfin/Threadfin/assets/22882057/6307b0a5-86dd-4164-851f-d6ddbd555e1a)
![IPTV EPG](https://github.com/Threadfin/Threadfin/assets/22882057/d0aeb6cd-6310-499d-ab69-6f784ae171f3)
You can see the programmes circled in red have no episode numbers (Threadfin EPG) but in the first image the same programmes have episode numbers pulled from my EPG (Which Threadfin uses as its source)

**Comment by iceman73** [comment]
I have the same issue, as soon and I downgrade to 1.0.20 it works correctly again

**Comment by mraniki** [comment]
Downgrade from 1.0.23 to 1.0.20 did fix the issue for me as well.
