### ISSUE TITLE
using vlc, picture good, audio good, but out of sync!

### ISSUE THREAD

**Issue by trexxeon** [Threadfin/Threadfin#204]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
When I choose the vlc as buffer it works, but audio is out of sync. 
I have tried streaming to vlc and emby and have the same fault.

**Server (please complete the following information):**
- OS Debian 12
- Arch Intel 64 Bit
- Threadfin Version and Build 1.0 Build: 23
**To Reproduce**
Play a channel

**Expected behavior**
play with audio and video in sync
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos, emby on nvidia shield
 - Browser safari

**Comment by Fyb3roptik** [comment]
Unable to reproduce this. Have you tried using ffmpeg instead? I would suggest using that over VLC
