### ISSUE TITLE
Channel mapping is not working

### ISSUE THREAD

**Issue by rykr** [Threadfin/Threadfin#205]
I have m3u/xml files from m34u.com, iptveditor.com, and IPTV boss.   I have verified that tvg-id and channel id in the xml match each other.   I have tried with filters setup and without.   I add the m3u and xml file in and the channels are not mapped.  I can map them manually but it supposed to do it automatically.

What am I doing wrong?

**Comment by Fyb3roptik** [comment]
You have to have a filter of some sort. Join our discord for durther assistance
