### ISSUE TITLE
[ERROR] invalid argument (File not found) - EC: 1004

### ISSUE THREAD

**Issue by Crosus97** [Threadfin/Threadfin#206]
**Describe the bug**
Found a errror with no description, i dont know where is ocurred, i think is edit channel because a finde the #55 with the same error, but i dont know which channel is 

**Server (please complete the following information):**
- OS Linux [DOCKER]
- Arch AMD64
- Threadfin Version and Build 1.0 (23)

**To Reproduce**
I DONT KNOW

**Expected behavior**
must not ocurre

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/46854222/5777da97-b2bf-4402-abba-c1c8080172ed)

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser Chrome
 - Versión 121.0.6167.140 (Build oficial) (64 bits)

**Comment by Fyb3roptik** [comment]
Top line says it could not find the XML file. Make sure it can see both m3u and xml files
