### ISSUE TITLE
Request - The ability to change the "stream limit" image.

### ISSUE THREAD

**Issue by shorty789** [Threadfin/Threadfin#208]
**Is your feature request related to a problem? Please describe.**
When I use Tivimate to connect to threadfin, it works well, but when I change channels I regularly encounter the "No more streams available" screen, and have to wait a few seconds before the channel I have switched to loads. While I get this is to prevent duplicate streams, having the option to change the image displayed would make it a load more tolerable.

**Describe the solution you'd like**
I would like the ability to change the "No more streams available" image that gets displayed via the settings page within threadfin.

**Describe alternatives you've considered**
This problem isnt encountered when using a basic iptv proxy, I have considered using them instead, but i prefer the customization offered with threadfin enough to stick with it.

**Additional context**
While its not a dealbreaker, it is definitely one of those QOL features I would love to see, Alternatively, channel hopping via Tivimate would be another ideal outcome.

**Comment by Fyb3roptik** [comment]
You can set the tuner number up a bit to help with that. The image itself is not customizable and never will be. Sorry
