### ISSUE TITLE
Threadfin ignoring channel-id number from imported playlist

### ISSUE THREAD

**Issue by sinn24** [Threadfin/Threadfin#209]
**Describe the bug**
Threadfin uses channel "1000" as a starting number despite predefined channel numbers in imported playlist

**Server (please complete the following information):**
- OS: Ubuntu 22.04.2 LTS
- Threadfin Version and Build: 1.0 (23)

**To Reproduce**
1. Add m3u playlist & xml epg
2. Check mapping and see channel numbers

**Expected behavior**
For channel numbers to be consistent with imported playlist

**Screenshots**
![webUI screenshot](https://github.com/Threadfin/Threadfin/assets/23642845/51bb7ec8-6f96-4e1d-bb26-89882cedfb12)
![m3u screenshot](https://github.com/Threadfin/Threadfin/assets/23642845/6b3294ee-b115-4a90-834f-375897f83eed)

**Comment by Fyb3roptik** [comment]
This is expected behavior. This is how xteve worked as well. You can use a custom filter to maybe bring them all in as is but not sure that will work.

**Comment by sinn24** [comment]
This worked previously. It was only after an unexpected HDD failure a few days ago that this behaviour started when I had to redeploy my media server. Unfortunately I lost the backup files in the failure.

**Comment by froman753** [comment]
I'm also interested in this. Is there a way to get this working?
