### ISSUE TITLE
Wont read m3u file correctly/m3u Format? 

### ISSUE THREAD

**Issue by Madaraxa** [Threadfin/Threadfin#210]
Hi.
I got a m3u file which looks like this:
`EXTM3U
#EXTINF:-1,DE: Channelname
http://IPOFSERVER/PATH/12345`
Sadly Threadfin wont find a channel (jellyfin / vlc works fine with it, although i had to add the EXTM3U Part or threadfin wont read file at all).
What am I doing wrong?

**Comment by Fyb3roptik** [comment]
That is not a proper m3u file. It lacks all of the needed information. Please use a valid M3U.

**Comment by Madaraxa** [comment]
Hi. The Code quote did break my m3u.
Its actually

#EXTM3U
#EXTINF:-1,DE: Channelname http://IPOFSERVER/PATH/12345

So when i look for example Wikipedia it Shows exactly this as example. Or is a fileextension needed? It says extended m3u need to Start with #EXTM3U and in the following Lines #EXTINF: followed by length (-1 if should be ignored) then the Name and in Next line for example an URL...
What am I missing?
