### ISSUE TITLE
M3U from Server Information works, but the DVR IP does not?

### ISSUE THREAD

**Issue by whothefvckk** [Threadfin/Threadfin#211]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I had to redo my entire server and unfortunately lost all my Threadfin settings. Thread was previously working very well in my IPTV Boss-Threadfin-Plex setup. I had no issues.

Tried doing the same setup with my new server. Set my EPG using IPTV Boss. Saved M3U and EPG files to IPTVBoss/output. Copied the directory and file names and pasted them into Threadfin. Mapped all the channels appropriately. 

All seemed to be working well. Plex located the DVR IP automatically. I used the Server Information XML link for the EPG, and the entire EPG was loaded.

When I went to stream a channel, I received a "5000" error. Weird, but not like I haven't seen that issue before and was able to fix it.

Copied the DVR IP from Threadfin into VLC, and it gave me the error "Your input can't be opened: VLC is unable to open the MRL 'XXX.XXX.XXX.XXX:34400'. Check the log for details."

I reviewed my ports. Port 34400 is opened in the router and in Windows Defender Inbound and Outbound. Also made sure to allow the Threadfin.exe through both inbound and outbound.

I then thought it may be my VPN, however that had not been an issue in the past. Using Mullvad, for reference. Tried to split-tunnel the threadfin.exe file, no luck. Turned off the VPN completely, no luck. All Plex apps are split-tunnelled through the Mullvad app. Plex is working fine for my movies/shows libraries.

I then tried to use the M3U from Threadfin Server information, and it worked perfectly in VLC. No buffer at all, and my mapped channels are all showing up appropriately.

I can't figure out why the DVR IP isn't loading properly. I would understand if Plex had some issues with it, I've done troubleshooting for Plex IPTV issues many times. But I've never had a problem with VLC. At first I wondered if the problem was with IPTV Boss, but I completely re-did the M3U and EPG outputs and still got the errors. Really strange how the Threadfin M3U works fine in VLC, but the DVR IP does not.

**Server (please complete the following information):**
- Threadfin_windows_amd64.exe
- 64bit
- Threadfin version 1.0 Build 23

**To Reproduce**
1. Add XML from IPTV Boss Output
2. Add M3U from IPTV Boss Output
3. Map channels
4. Copy DVR IP from Server Information section and paste into VLC. Error response "Your input can't be opened: VLC is unable to open the MRL 'XXX.XXX.XXX.XXX:34400'. Check the log for details."
5. Copy M3U link from Server Information section and paste into VLC. M3U loads fine.

**Expected behavior**
DVR IP link should load automatically in VLC and Plex. Plex loads the M3U and EPG information properly, but no streams can be played.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 11 Pro, x64
 - Ungoogled Chromium
 - 121.0.6167.160

**Additional context**

**Comment by Fyb3roptik** [comment]
I dont use IPTV Boss so I am unable to reproduce this. Can you hop in the discord and see if someone else is having this issue with their IPTV Boss?
