### ISSUE TITLE
Mapping Page Bulk Edit

### ISSUE THREAD

**Issue by KaelenB** [Threadfin/Threadfin#212]
**Describe the bug**
Web UI's Mapping page has 2 lists. Bulk edit of channel mappings only work on the active list, and does not work on the inactive list.
By selecting bulk edit, then selecting all rows in the inactive list with the header checkbox, I would expect an edit action to effect all selected mappings (similar to active list) however the edit only applies to the single mapping that was edited.

**Server**
- OS:  Linux - Ubuntu
- Arch: Intel 64 Bit
- Threadfin Version and Build: 1.0 (24); Docker image: fyb3roptik/threadfin

**To Reproduce**
1. Visit Threadfin web UI, address:port/web/
2. Setup valid playlist, and filter
3. On Mapping Tab, select "Bulk Edit"
4. Scroll to inactive mappings and bulk select using header (or with shift click)
5. Select an inactive mapping to open the edit dialog
6. Toggle "Active" to true, then "Done" to apply
7. Observe only the clicked mapping is activated

**Expected behavior**
All bulk selected mappings should be activated

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/45247209/e5c8f424-230c-440f-9fd8-abc39e97078c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 123.0 (64-bit)

**Comment by rarrais** [comment]
Facing the same issue with latest version of Threadfin (1.0.24) and on MacOS with Firefox and Safari.

**Comment by MoikvanDoik** [comment]
I also would like to have this feature corrected/added.
When I add a playlist with channels without epg-data. I have to activate the channels one by one.
Another great setting would be that channels without epg-data automatically get the "Threadfin Dummy"

**Comment by mmo-onn** [comment]
It was said in a different issue that this will not be fixed, but someone came up with a python script to work around the issue.
https://github.com/Threadfin/Threadfin/issues/85#issuecomment-1867184225

**Comment by Fyb3roptik** [comment]
I hear you on this trust me. I am currently working on my new project Kernel Media Server in which I will be pulling in Threadfin features into the media server directly. So that is why features are on hold for Threadfin. To follow Kernel Media development please see our discord

https://discord.gg/tHWWupDZKH
