### ISSUE TITLE
Channels without epg-data could automatically get the "Threadfin Dummy"

### ISSUE THREAD

**Issue by MoikvanDoik** [Threadfin/Threadfin#215]
I sometimes update the playlist of my IPTV provider and many channels have no epg data.
So I have to set the "threadfin dummy" for each channel, which takes a lot of time. I could do this in m3u4u too, but this is also inconvenient.
This feature does not need to be enabled by default of course, but maybe it is possible to create a setting to enable it.
Thank you for continuing this great project

**Comment by mmo-onn** [comment]
Someone came up with a python [script](https://github.com/Threadfin/Threadfin/issues/85#issuecomment-1867184225) to do just this.

**Comment by Fyb3roptik** [comment]
This will be included in the last major update

**Comment by Fyb3roptik** [comment]
#1.1.0 release fixes this
