### ISSUE TITLE
Option to deactivate dlna discovery

### ISSUE THREAD

**Issue by bendschs** [Threadfin/Threadfin#216]
i think it is kind of a waste to use udp port 1900 just for auto-discovery, so it would be nice to have an option to deactivate it. 
my intention is to run a dlna client on the same machine as threadfin is running on, but threadfin is simply not starting up if it does not get the 1900.

cheers
bendsch

**Comment by MuhammadBayiz** [comment]
I'm running threadfin on a shared seedbox and port 1900 isn't permitted for me to use so I can't get threadfin to run and i haven't found a way to change the port or disable DLNA also I'm not using docker and hopefully i don't want to resolve to that. Is there any way around this?

**Comment by Fyb3roptik** [comment]
I will surface this option

**Comment by Fyb3roptik** [comment]
#1.1.0 release fixes this

**Comment by MuhammadBayiz** [comment]
Just tested it out. I can disable it now! Much appreciated.
For those who wonder how to disable it: 
After initial execution, In your home directory you will find a folder called **.threadfin** in there find the **settings.json** and open it with a text editor, find this line inside `"ssdp": true,` and change it to `"ssdp": false,` save the file and run threadfin again.

**Comment by Fyb3roptik** [comment]
You can also use the UI and go into Settings. Its under the General section
