### ISSUE TITLE
Threadfin.xml Programme>Title Field added when channel is configured as PPV

### ISSUE THREAD

**Issue by apetsche25** [Threadfin/Threadfin#217]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

Channels that are assigned "Threadfin Dummy" and "PPV" do not have the tvg-name or channel name mapped to the title tag for <programme> tage in xmltv file. 

Note: I am not sure which is technically supposed to be mapped the the title tag in threadfin.xml. For my use case, I would prefer tvg-name, but either would likely be fine.

**Server (please complete the following information):**
- OS : Docker container
- Threadfin Version and Build : Latest

**To Reproduce**
1. Configure channel as "threadfin dummy" and assign "PPV"
2. Ensure "Replace PPV channels title/desc:" setting is active
3. Update Xepg and XMLTV

**Expected behavior**
For "programme" tag in threadfin.xml ; a "title" child tag is added.

![image](https://github.com/Threadfin/Threadfin/assets/49372611/5a6472fc-b042-464c-86b7-2161893d5479)

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/49372611/f763876f-aaf3-49f3-a67c-22791da236eb)
![image](https://github.com/Threadfin/Threadfin/assets/49372611/99e1ccc9-f2c5-4cd0-b1bd-48a2942dded6)
![image](https://github.com/Threadfin/Threadfin/assets/49372611/2139fb4e-cf3c-44b2-8a12-e4b4d7385138)
![image](https://github.com/Threadfin/Threadfin/assets/49372611/b4566e76-a512-4034-a62e-4ad6743cfcf8)
![image](https://github.com/Threadfin/Threadfin/assets/49372611/d1ad22cf-11e4-4fce-b28f-af976cb6c477)

**Comment by Fyb3roptik** [comment]
Im not sure what you mean here. It makes the title for me in the programme section?
