### ISSUE TITLE
tvg-logo is not overwritten when force https has been used

### ISSUE THREAD

**Issue by marcelGoerentz** [Threadfin/Threadfin#220]
**Describe the bug**
When using the force https option the tvg-logo urls are not pointing to the correct endpoint.
For example, instead of pointing to https://example.org/images/80a9151eb91032f7c9901ffad4563036.png it is pointing to http://192.168.0.1/images/80a9151eb91032f7c9901ffad4563036.png

**Server (please complete the following information):**
- OS: Linux - Ubuntu 22.04.4
- Arch: Intel 64-bit
- Threadfin Version and Build: 1.0 Build: 24

**To Reproduce**
1. Activate the force to https option and type a domain
2. Restart the server
3. Check the generated m3u file

**Expected behavior**
The m3u file should have updated tvg-logo urls pointing to the named domain

**Comment by Fyb3roptik** [comment]
Make sure Image Caching is enabled as well. See if that fixes it.

**Comment by Fyb3roptik** [comment]
1.1.0 release fixes this
