### ISSUE TITLE
Initial install of Threadfin in a Docker on Synology

### ISSUE THREAD

**Issue by Bones57a** [Threadfin/Threadfin#221]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Bones57a** [comment]
Server (please complete the following information):

- Synology NAS - 
- Synology Container manager

Threadfin Version and Build [to be found in the Threadfin log]
Version:                1.0 Build: 24

To Reproduce
Steps to reproduce the behavior: 

1. install Image, Run  - create Container assigning port 344001 to 34400, 
2. map path /volume3/docker\/teve/conf to /home/threadfin/conf
3. go to  http://192.168.1.3:34401/web/
4. New Playlist - M3U and enter
5. name as test desrciption blank  and M3U file as /home/threadfin/conf/data/xteve.M3U

get error as per log

Expected behavior - not sure - first time user



Screenshots
<img width="1331" alt="image" src="https://github.com/Threadfin/Threadfin/assets/162721072/c6afd5a4-afec-417c-8ac1-997a8f7c34a6">


Desktop (please complete the following information):

OS: [e.g. iOS] Windows 11
Browser [e.g. chrome, safari] Chrome
Version [e.g. 22] Version 122.0.6261.95 (Official Build) (64-bit)

**Comment by Venezia1337** [comment]
try change it to: /home/threadfin/data/xteve.m3u

remember you have to put that file in the data folder. if you don't have it there, that's why it can't find it

**Comment by Fyb3roptik** [comment]
Try doing `file:///home/threadfin/data/xteve.m3u` for a local file
