### ISSUE TITLE
Channel ID in the XMLTV file has changed. Channel has been deactivated

### ISSUE THREAD

**Issue by adrianguanipa** [Threadfin/Threadfin#222]
Just to confirm, channels in both m3u and xmliv need to have the same ID to be mapped, correct? but what if you have a a backup XMLTV with a different channel ID, can that be mapped? because I'm getting this warning indicating the Chanel EPG data is disabled after manually mapping a channel with a different channel data.

2024-03-15 19:57:35 [Threadfin] [ERROR] Missing EPG data: US: COMET HD () - EC: 0
2024-03-15 19:57:35 [Threadfin] [WARNING] Channel ID in the XMLTV file has changed. Channel has been deactivated

Thanks.

**Comment by Fyb3roptik** [comment]
Backup channels do not have to be active. It will simply swap out the url.

**Comment by Fyb3roptik** [comment]
Also yes if the tvg-id changes and its not in the EPG it will automatically deactivate
