### ISSUE TITLE
Threadfin streams looping in Plex randomly, sometimes irrecoverably 

### ISSUE THREAD

**Issue by david-a-kelly** [Threadfin/Threadfin#224]
**Describe the bug**
Ongoing issues where streams enter a loop. Sometimes it recovers, often need to restart the stream. Buffer settings don't seem to have a consistent positive effect/change

**Server (please complete the following information):**
- OS Alpine Linux - Docker/Portainer
- Threadfin Version and Build 1.024

**To Reproduce**
Stream IPTV via Plex/Threadfin

**Expected behavior**
Where buffering issues exist, the stream is able to continue when connections resumed or buffer cleared. No endless looping.

**Desktop (please complete the following information):**
 - OS: Alpine Docker

 - Version1.0.24

**Additional context**

**Comment by Babyyoda777** [comment]
Same here, also happens in Jellyfin for me, I’ve tried both Plex and Jellyfin. I have no streaming buffer at all and directly accessing m3u8 works fine on safari however in app it struggles, especially on Google TV.

**Comment by Fyb3roptik** [comment]
Replying tio @david-a-kelly : Are you using a buffer? I would suggest not using a buffer with Plex. If you continue to see these issues make sure you're using a VPN. You should be running this through a gluetun container.

Replying to @Babyyoda777 Plex does not support HLS. MPEGTS only!

**Comment by david-a-kelly** [comment]
@Fyb3roptik  thanks for getting back to me :-) 

I have tried without a buffer, and it works fine - except I cannot get it to run more than one stream simultaneously. 

The issue root cause seems to be a dodgy stream, but then the symptoms are seen in getting stuck in a loop. Some times and some streams it is perfect for days. 

I am not running via VPN at all, and just running in a docker container within an LXC - I'll look into gluetun, thanks a lot

**Comment by Fyb3roptik** [comment]
It looks because your ISP kills the feed and it replays the segments it has. VPN is a must.
