### ISSUE TITLE
Err:  interface conversion: interface {} is map[string]string, not map[string]interface {}

### ISSUE THREAD

**Issue by stegsolutions** [Threadfin/Threadfin#225]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin keeps crashing at boot

**Server (please complete the following information):**
- OS Linux Unraid
- Arch x64
- Threadfin Version and Build 1.0 build 24

**To Reproduce**
1. Start the container

**Expected behavior**
It boots

**Additional context**
```
* * * * * FATAL ERROR * * * * *
OS:   linux
Arch: amd64
Err:  interface conversion: interface {} is map[string]string, not map[string]interface {}

panic.go:838 runtime.gopanic
iface.go:262 runtime.panicdottypeE
xepg.go:631 threadfin/src.mapping
xepg.go:111 threadfin/src.buildXEPG
config.go:268 threadfin/src.StartSystem
threadfin.go:197 main.main
proc.go:259 runtime.main
asm_amd64.s:1572 runtime.goexit

* * * * * * * * * * * * * * * *
```

**Comment by Fyb3roptik** [comment]
Looks like you have a bad EPG. Care to post some of it?

**Comment by stegsolutions** [comment]
I have multiple. And I tried renaming them so they wouldn't load and it still crashes.
