### ISSUE TITLE
Force HTTPS also rewrites outbound channel URLs

### ISSUE THREAD

**Issue by jbruns** [Threadfin/Threadfin#227]
Possible that the issue in https://github.com/Threadfin/Threadfin/issues/132 was misunderstood: when the Force HTTPS setting is enabled, the upstream channel URLs from an HDHR or IPTV provider are also rewritten, which is undesired. I don't claim to have deep understanding of the code, but I believe the rewrite is happening here:

https://github.com/Threadfin/Threadfin/blob/77129c8db012cfd2dda21e200db5b461632239bf/src/m3u.go#L237-L247

With this in place, Threadfin then forces https connections _outbound to the stream provider_, as well as _inbound to itself_..I believe we just want inbound connections to Threadfin to be https; we can't really influence what the upstream provider supports or doesn't support.

The change I would suggest is, don't do the proto/host/port rewrite at that point to `channel.URL` in m3u.go (Let me know if you want a PR for this).

_Originally posted by @jbruns in https://github.com/Threadfin/Threadfin/issues/132#issuecomment-2008604875_

**Comment by Fyb3roptik** [comment]
That's how https works. Everything has to support it. This is not a bug

**Comment by troykelly** [comment]
@Fyb3roptik That's not how HTTPS works. This isn't a passthrough transparent proxy, you shouldn't be rewriting the sources for threadfin to provide a secure connection to it's downstream. I believe you are misunderstanding how things work.
