### ISSUE TITLE
Special characters in xml files not parsed properly

### ISSUE THREAD

**Issue by davidclaeysquinones** [Threadfin/Threadfin#228]
**Describe the bug**
I use this [epg source](https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiafanart_sincolor.xml.gz) in order to obtain program information.
Special characters like ó and ñ are not properly handled. In some cases these characters are ignored or another character comes in it's place.
I suspect it has to do something with the file encoding.

**Comment by MoikvanDoik** [comment]
Did you enable this? Works for German Umlauts
![grafik](https://github.com/Threadfin/Threadfin/assets/79359434/9a07a9ba-b5a1-4359-a8da-308d16943dab)

**Comment by davidclaeysquinones** [comment]
It surprisingly works as easy as it seems :). Out of curiosity is there a reason this setting is not enabled by default ?

**Comment by Fyb3roptik** [comment]
Because by default I didnt want non asciii characters because some providers think its cute to add non ascii LIVE to their event feeds

**Comment by davidclaeysquinones** [comment]
I even didn't knew some providers did that, makes sense.
