### ISSUE TITLE
ffmpeg / threadfin buffer issue with specific streams

### ISSUE THREAD

**Issue by miccayo** [Threadfin/Threadfin#229]
**Describe the bug**
I am using the PlutoTV EPG and XMLTV data from https://nocords.xyz/ (automatically generates an EPG and XMLTV file for PlutoTV periodically). I have reviewed the file and its XMLTV contents and they appear to be formatted correctly. I have attempted to recreate this issue with other streams from the file but only sometimes does this occur. It seems like it occasionally replaces the [URL] parameter with empty space, leading ffmpeg or Threadfin buffer to close out due to no stream URL being present. I've also tried using the VLC buffer to no success. Some channels from this list work, others do not. The main channel that will not work for me is the Judge Judy Channel, and sometimes COPS.

(ffmpeg)
2024/03/28 20:33:58 [Threadfin] FFMPEG log:             Error opening input files: Invalid argument
2024/03/28 20:33:58 [Threadfin] FFMPEG log:             [in#0 @ 0000021440520940] Error opening input: Invalid argument
2024/03/28 20:33:58 [Threadfin] FFMPEG log:             Error opening input file .

(threadfin)
2024/03/28 20:45:27 [Threadfin] Buffer:                 false [-]
2024/03/28 20:45:27 [Threadfin] Channel Name:           The Judge Judy Channel
2024/03/28 20:45:27 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
2024/03/28 20:45:27 [Threadfin] Streaming URL:
2024/03/28 20:45:27 [Threadfin] Streaming Info:         URL was passed to the client.
2024/03/28 20:45:27 [Threadfin] Streaming Info:         Threadfin is no longer involved, the client connects directly to the streaming server.
2024/03/28 20:45:27 [Threadfin] [ERROR] Streaming error (Steaming URL could not be found in any playlist) - EC: 1203

I'm not sure if it would have to do with this file.
https://github.com/Threadfin/Threadfin/blob/03aa59621dc0cea267f6b19e5105380da7e14262/src/buffer.go#L984

**Server:**
- Windows 10
- Intel 64 Bit
- 1.0 Build: 26, Database Version 0.5.0

**To Reproduce**
Go to https://nocords.xyz/, download the PlutoTV EPG and XMLTV files, activate the Judge Judy Channel and COPS, or some other channels and test them. I was unable to get Judge Judy Channel to load but others will. Add to Plex as DVR / Live TV and import channels, attempt to view different streams using any buffer you prefer.
![image](https://github.com/Threadfin/Threadfin/assets/6856974/a6bfb24e-a722-434c-ac86-3e053336d593)

**Expected behavior**
To be able to stream the channel as the others stream properly.

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/6856974/68a9a6c9-b65f-46d3-957d-0c66acc14333)

**Desktop (please complete the following information):**
 - Windows
 - Google Chrome
 - Version 123.0.6312.59

**Comment by Fyb3roptik** [comment]
I would need to see the m3u and EPG. Also I will need to see what is in ffmpeg. I should also say if using Plex, just go no buffer. Plex creates it's own buffer

**Comment by miccayo** [comment]
The m3u file and EPG are linked in my original bug report.

PlutoTV.m3u: https://gist.github.com/miccayo/afe8aec7b01aebed7f91b9fd8a595dac
PlutoTV-epg.xml: https://gist.github.com/miccayo/99dc708f7c2a063bc5eb4fa97da8920e

The error code ffmpeg is returning is for no input URL provided. In my original report, I used both threadfin buffer and ffmpeg.

**Comment by Fyb3roptik** [comment]
This is an improperly formed M3U. Please use one that has tvg-id and follows standards
