### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MCTyler** [Threadfin/Threadfin#23]
Can you also copy and fix the 150 issues that xTeVe has since it looks like Marmei has retired?

**Comment by Fyb3roptik** [comment]
A lot of them have either been fixed or will be eventually. I wont stop you from posting a bulleted list here though of the main ones people are wanting.

**Comment by MCTyler** [comment]
A lot of them are just user error. I think that's why Marmei gave up ;)

**Comment by Fyb3roptik** [comment]
lol no worries. If you have any feature requests just put them here

**Comment by MCTyler** [comment]
Nope, IPTVBoss took care of all I requested. I just help out xTeVe on Discord. GL with "your" project.
