### ISSUE TITLE
Channel Logos from playlist not used when tvg-id is blank

### ISSUE THREAD

**Issue by imran0** [Threadfin/Threadfin#233]
**Describe the bug**
I have an IPTV provider where I filter lists for only Live Events through Threadfiin, Live events however don't have any real tvg-id's so they're blank. I'm having an issue where Threadfin will populate the XML and M3U files for these Live Channels with the last tvg-logo found from any tvg-id=(blank).

The IPTV provider has some explicit content channels where the tvg-id is also blank, so the channel logos are being used by that which I don't want (presumably because they are last in the M3U/EPG list).

**Expected behavior**
Image should be pulled from tvg-logo attribute on the same playlist item line.

**Comment by Fyb3roptik** [comment]
I will fix this and it will come out in the next release

**Comment by Fyb3roptik** [comment]
1.1.0 release fixes this

**Comment by Fyb3roptik** [comment]
Can you give me an example m3u and xml please? I need some way to recreate this issue

**Comment by Fyb3roptik** [comment]
@imran0 Please post an example. Or join the Discord and ping me
