### ISSUE TITLE
No Configuration Wizard

### ISSUE THREAD

**Issue by pixel24** [Threadfin/Threadfin#234]
**Describe the bug**
After new installation -> Web login does not start a wizard.

**Server (please complete the following information):**
- OS Ubuntu 23.04
- Arch Intel 64 Bit
- Threadfin Version 1.0 Build: 26

**To Reproduce**
1. Install the Docker-Image / Container
2. Open from Client http://192.168.83.10:34400/web/
3. Only the main menu at the top is displayed.

**Expected behavior**
According to the documentation, a configuration wizard should start to make basic settings adjustments.

**Screenshots**
![threadfin-01](https://github.com/Threadfin/Threadfin/assets/16030132/da951b58-11ea-4dd8-952b-fc077a16e7f4)

**Desktop (please complete the following information):**
 - OS:Linux Mint 21.3
 - Browser firefox
 - Version 125.0.1+linuxmint1+virginia

**Additional context**
I created the container using the following composer file:

version: "2.3"
services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin  # Zeitzone für Deutschland (Berlin)
    volumes:
      - /docker/threadfin/data/conf:/home/threadfin/conf
      - /docker/threadfin/data/temp:/tmp/xteve:rw
    restart: unless-stopped

**Comment by Fyb3roptik** [comment]
That is a feature not a bug. The wizard was full of bugs
