### ISSUE TITLE
When using the buffering option, ffmpeg process is never stopped in background

### ISSUE THREAD

**Issue by w0d4** [Threadfin/Threadfin#236]
**Describe the bug**
I activated the buffering feature using ffmpeg. Playback works perfectly.
When I close my client or stop playback, the ffmpeg process stays still open in background and is never closed.
So it's still counted as open stream on the provider side.

**Server (please complete the following information):**
- official docker image
- 64bit
- 1.0 Build: 26

**To Reproduce**
1. Go to Settings
2. activate buffering
3. start stream in any client
4. stop stream after a few seconds/minutes
5. run `ps -ef | grep ffmpeg` on docker host
6. see still open ffmpeg process

**Expected behavior**
If I stop the stream in my client, the buffering ffmpeg process should also be stopped after some user specified time.

**Additional context**
If I kill the ffmpeg process by hand on the docker host, the stream is also closed on provider side and not counted anymore against my connection limit.

**Comment by cmaxwe** [comment]
If you rollback to 25 this issue is not present,

**Comment by w0d4** [comment]
OK, thanks. Will check this and disable updates if it's working.

**Comment by Fyb3roptik** [comment]
This has been fixed in the latest build
