### ISSUE TITLE
The logos seem to be zoomed too much and therefore not showing the full logo correctly.

### ISSUE THREAD

**Issue by willowtvsucks** [Threadfin/Threadfin#237]
**Describe the bug**
Unlike on xteve, for the same playlist with the same epg, the logos are blown out of proportion thereby resulting in the logo not being displayed correctly.

**Server (please complete the following information):**
- OS [MacOS]
- Arch [Intel 64 Bit]
- Threadfin Version and Build [latest]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fyb3roptik** [comment]
Please provide more details on how to reproduce. I am not seeing this issue

**Comment by Bierdusche** [comment]
![Screenshot 2024-05-02 074631](https://github.com/Threadfin/Threadfin/assets/133897568/5bb67553-682f-43db-bda9-b58299cd8b2b)
I am having the same issue. it seems like the server information window is open.

**Comment by Bierdusche** [comment]
it's back to normal for me.
