### ISSUE TITLE
Option to pull channel numbers from M3U file

### ISSUE THREAD

**Issue by sshort1955** [Threadfin/Threadfin#238]
After many hours of comparing proxies to get IPTV streams into Plex, I discovered a few differences between them. The most notable option (which is not supported by xteve/threadfin) is the ability to bring in channel numbers from the M3U file. Like most users, I subscribe to a playlist editor to manage what channels are brought into the proxy. Those editors also have the ability to assign channel numbers, making them align with EPGs from Plex, xmltv, etc. If the channel numbers were able to be brought into Threadfin, then they will automatically match inside of plex (I use the Threadfin Dummy in threadfin and the EPG in Plex).

This should be an option, not the standard....

**Comment by flippz** [comment]
Yes id like this to and for the exact same reasons :)

**Comment by Fyb3roptik** [comment]
This will be in the next release

**Comment by Fyb3roptik** [comment]
Can you please send me an example of what it looks like?

**Comment by Fyb3roptik** [comment]
1.1.0 release fixes this

**Comment by sshort1955** [comment]
Not sure what you are asking of me:
"Can you please send me an example of what it looks like?". 
Please clarify

I updated to 1.1(1) but I don't see any options/settings to use M3U channels.

**Comment by sshort1955** [comment]
Here are  the relevant log entries from last restart:
2024/05/14 07:50:47 TAG LATEST:  1.1.1
2024/05/14 07:50:47 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.1.1/Threadfin_linux_amd64
2024/05/14 07:50:47 [Threadfin] UUID:                   2024-04-IB2H-UPY073
2024/05/14 07:50:47 [Threadfin] Tuner (Plex / Emby):    1
2024/05/14 07:50:47 [Threadfin] EPG Source:             XEPG
2024/05/14 07:50:47 [Threadfin] Plex Channel Limit:     480
2024/05/14 07:50:47 [Threadfin] Unfiltered Chan. Limit: 480
2024/05/14 07:50:47 [Threadfin] Backup Path:            /root/.threadfin/backup/
2024/05/14 07:50:47 [Threadfin] Backup file:            /root/.threadfin/backup/threadfin_auto_backup_20240514_0750.zip
2024/05/14 07:50:47 [Threadfin] Download:               https://opop.pro/BajeKDoUwHvkXVu
2024/05/14 07:50:47 [Threadfin] Header filename:        4kLiveIPTV.m3u
2024/05/14 07:50:47 [Threadfin] Check File:             https://opop.pro/BajeKDoUwHvkXVu
2024/05/14 07:50:47 [Threadfin] Save File:              https://opop.pro/BajeKDoUwHvkXVu [ID: MLN6GI034UT9KYD8JLXY]
2024/05/14 07:50:47 [Threadfin] Download:               https://opop.pro/3C1oVg4pSLZG2Lq
2024/05/14 07:50:48 [Threadfin] Header filename:        IPTVEditor_epg.xml
2024/05/14 07:50:49 [Threadfin] Check File:             https://opop.pro/3C1oVg4pSLZG2Lq
2024/05/14 07:50:49 [Threadfin] Save File:              https://opop.pro/3C1oVg4pSLZG2Lq [ID: XAYM1D4JVB11RA6EHQMK]
2024/05/14 07:50:49 [Threadfin] All streams:            68
2024/05/14 07:50:49 [Threadfin] Active streams:         68
2024/05/14 07:50:49 [Threadfin] Filter:                 0
2024/05/14 07:50:49 [Threadfin] XEPG:                   Parse XMLTV file: 4kLiveIPTV
2024/05/14 07:50:49 [Threadfin] XEPG:                   Update database
2024/05/14 07:50:49 [Threadfin] XEPG:                   Save DB file
2024/05/14 07:50:49 [Threadfin] XEPG:                   Map channels
2024/05/14 07:50:49 [Threadfin] XEPG:                   Cleanup database
2024/05/14 07:50:49 [Threadfin] XEPG Channels:          33
2024/05/14 07:50:49 [Threadfin] DVR IP:                 172.21.0.2:34400
2024/05/14 07:50:49 [Threadfin] Web Interface:          http://172.21.0.2:34400/web/ | Threadfin is also available via the other 5 IP's.
2024/05/14 07:50:49 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - TBS*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Grit TV*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - FOX SPORTS 2 HD
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - ESPN HD
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Discovery West*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - FX
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Paramount TV
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Root Sports Northwest Plus
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Magnolia Network
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Starz Cinema
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "starzcinema.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Cooking Channel
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - HBO family west
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - AXS TV
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - COMEDY CENTRAL WEST
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Bravo East
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "bravo.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - ESPN 2
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Starz Encore Westerns
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "starzencorewesterns.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - HGTV East*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Sony Movie Channel
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "sony.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - HBO Comedy*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "hbocomedy.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - FOX SPORTS 1 HD
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - HBO West*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "hbowest.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Turner Classic Movies
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - HBO Family*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "hbofamily.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Root Sports Northwest
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - ESPN U HD
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Starz West
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "starzwest.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - MeTV
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - USA Network West
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - TV Land
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - Food Network*
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "-": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] Create Dummy Guide:     Time offset -0600 - AMC
2024/05/14 07:50:49 [Threadfin] [ERROR] strconv.Atoi: parsing "amc.us": invalid syntax () - EC: 0
2024/05/14 07:50:49 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/conf/data/threadfin.xml.gz)
2024/05/14 07:50:49 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/conf/data/threadfin.m3u)
2024/05/14 07:50:49 [Threadfin] XEPG:                   Ready to use

**Comment by Fyb3roptik** [comment]
You dont need to set an option. If the m3u uses the `tvg-chno` attribute then it uses that for the channel number. I would need to see an example of your m3u (edit out the URL)

**Comment by sshort1955** [comment]
Here is my M3U file link

https://opop.pro/BajeKDoUwHvkXVu

**Comment by Fyb3roptik** [comment]
Give me a bit and i will check this

**Comment by sshort1955** [comment]
#EXTM3U
#EXTINF:0 CUID="91" tvg-chno="519" tvg-name="Cinemax ActionMax" tvg-ID="actionmaxpacific.us" tvg-logo="https://logo.iptveditor.com/cinemaxactionmax.png" group-title="Movies",Cinemax ActionMax
http://ky-iptv.com:25461/xxxxx/xxxxx/176012
#EXTINF:0 CUID="95" tvg-chno="517" tvg-name="Cinemax MoreMax West" tvg-ID="moremaxpacific.us" tvg-logo="https://logo.iptveditor.com/cinemaxmoremax.png" group-title="Movies",Cinemax MoreMax West
http://ky-iptv.com:25461/xxxxx/xxxxx/176017
#EXTINF:0 CUID="100" tvg-chno="522" tvg-name="Cinemax ThrillerMax West" tvg-ID="thrillermaxpacific.us" tvg-logo="https://logo.iptveditor.com/cinemaxthrillermax.png" group-title="Movies",Cinemax ThrillerMax West
http://ky-iptv.com:25461/xxxxx/xxxxx/176023
#EXTINF:0 CUID="113" tvg-chno="506" tvg-name="HBO Comedy" tvg-ID="hbocomedy.us" tvg-logo="https://logo.iptveditor.com/hbocomedy.png" group-title="Movies",HBO Comedy
http://ky-iptv.com:25461/xxxxx/xxxxx/176042
#EXTINF:0 CUID="115" tvg-chno="507" tvg-name="HBO Family" tvg-ID="hbofamily.us" tvg-logo="https://logo.iptveditor.com/hbofamily.png" group-title="Movies",HBO Family
http://ky-iptv.com:25461/xxxxx/xxxxx/176047
#EXTINF:0 CUID="116" tvg-chno="503" tvg-name="HBO Signature" tvg-ID="hbosignature.us" tvg-logo="https://logo.iptveditor.com/hbosignature.png" group-title="Movies",HBO Signature
http://ky-iptv.com:25461/xxxxx/xxxxx/176048
#EXTINF:0 CUID="117" tvg-chno="501" tvg-name="HBO West" tvg-ID="hbowest.us" tvg-logo="https://logo.iptveditor.com/hbowest.png" group-title="Movies",HBO West
http://ky-iptv.com:25461/xxxxx/xxxxx/176050
#EXTINF:0 CUID="118" tvg-chno="509" tvg-name="HBO Zone" tvg-ID="hbozone.us" tvg-logo="https://logo.iptveditor.com/hbozone.png" group-title="Movies",HBO Zone
http://ky-iptv.com:25461/xxxxx/xxxxx/176052
#EXTINF:0 CUID="119" tvg-chno="547" tvg-name="Showtime 2" tvg-ID="showtime2.us" tvg-logo="https://logo.iptveditor.com/showtime2.png" group-title="Movies",Showtime 2
http://ky-iptv.com:25461/xxxxx/xxxxx/176054
#EXTINF:0 CUID="122" tvg-chno="552" tvg-name="Showtime Family Zone (East)" tvg-ID="showtimefamilyzone.us" tvg-logo="https://logo.iptveditor.com/showtimefamilyzone.png" group-title="Movies",Showtime Family Zone (East)
http://ky-iptv.com:25461/xxxxx/xxxxx/176060
#EXTINF:0 CUID="123" tvg-chno="551" tvg-name="Showtime Next" tvg-ID="showtimenext.us" tvg-logo="https://logo.iptveditor.com/showtimenext.png" group-title="Movies",Showtime Next
http://ky-iptv.com:25461/xxxxx/xxxxx/176061
#EXTINF:0 CUID="125" tvg-chno="545" tvg-name="Showtime West" tvg-ID="showtimewest.us" tvg-logo="https://logo.iptveditor.com/showtimewest.png" group-title="Movies",Showtime West
http://ky-iptv.com:25461/xxxxx/xxxxx/176064
#EXTINF:0 CUID="127" tvg-chno="568" tvg-name="Sony Movie Channel" tvg-ID="sony.us" tvg-logo="https://logo.iptveditor.com/sonymoviechannel.png" group-title="Movies",Sony Movie Channel
http://ky-iptv.com:25461/xxxxx/xxxxx/176066

**Comment by Fyb3roptik** [comment]
https://discord.gg/E9NzXrmW

Join the discord and DM me please

**Comment by Deihmos** [comment]
> You dont need to set an option. If the m3u uses the `tvg-chno` attribute then it uses that for the channel number. I would need to see an example of your m3u (edit out the URL)

This is not working. My m3u has tag-chno but I don't see the this in Plex.
