### ISSUE TITLE
Not honoring #EXTVLCOPT:http-referrer

### ISSUE THREAD

**Issue by purplescorpion1** [Threadfin/Threadfin#243]
**Describe the bug**
I have an m3u playlist that requires
#EXTVLCOPT:http-referrer=
#EXTVLCOPT:http-user-agent=

The m3u plays the streams perfectly fine outside of threadfin but if you try to run the streams through threadfin it doesn't work.
I have set the user agent in threadfin settings but it seems like it is not honoring the referrer which is why the stream fails

Log shows 
Error opening input: Server returned 403 Forbidden (access denied)

There is no way to set the referrer in threadfin settings and this would be different for every playlist anyway so a global setting wouldn't work. (Tried setting it also through both ffmpeg and vlc options but didn't work. Even if it did it would break other playlists)
What we need is a setting to be able to set the referrer and user agent per playlist

Does threadfin support #EXTVLCOPT lines in the m3u? I'm guessing not which is why the streams do not work

**Server (please complete the following information):**
- OS - Windows
- Arch - intel 64bit
- Threadfin Version - 1.0 (27)

**To Reproduce**
Add a playlist that requires a referrer via
#EXTVLCOPT:http-referrer=

**Expected behavior**
Stream to play like it does in the m3u outside of threadfin

**Additional context**
Downloaded the playlist direct from threadfin to play in VLC and it doesn't work
m3u not going through threadfin works
Other m3us that do not require a referrer work through threadfin

**Comment by Fyb3roptik** [comment]
This is not supported and will not be supported

**Comment by purplescorpion1** [comment]
Thats a shame as a lot of m3us now feature needing referrers and other headers

Should be a basic feature really

**Comment by purplescorpion1** [comment]
@Fyb3roptik 

I found a program that can do exactly what the issue is in threadfin
https://www.hls-proxy.com/

So if this program can do it I see no reason why it can't be done in threadfin
I prefer threadfins interface and mapping - all it is missing is setting http headers per playlist

**Comment by Fyb3roptik** [comment]
I have bigger plans for this with my new software kernel
