### ISSUE TITLE
Add multiple tags for channels using filter

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#245]
I use tags of channels to do parental filtering - it would be great if additional tags could be set using the filter (not only one of the predefined set, sports, movies, etc.)

**Comment by Fyb3roptik** [comment]
Oh I see what you're saying now

**Comment by Fyb3roptik** [comment]
Unfortunately, it would require some work to accomplish this. I will plan on this being a feature in Kernel Media Server once I get to adding m3u/epg directly. 

https://discord.gg/tHWWupDZKH to follow Kernel Media Server

**Comment by tobiasredel** [comment]
Ok - but would you still consider this being a feature for the future for threadfin?
