### ISSUE TITLE
Inaccessible path after automatic updates of "m3u" and "xmltv" files

### ISSUE THREAD

**Issue by carfanatic93** [Threadfin/Threadfin#247]
Description:
After the automatic updates of the "m3u" and "xmltv" files have run, I have noticed that the path "http://serverip:34400/m3u/threadfin.m3u" becomes inaccessible. However, once I log in to the WEBui and press "Save" under Mapping once, the path becomes accessible again.

Server:
- OS Linux Debain 12 / Docker
- Arch Intel 64 Bit
- Threadfin Version and Build:  1.1 (1) (DOCKER)

Steps to Reproduce:

1. Run the automatic updates for the "m3u" and "xmltv" files.

2. Attempt to access the path "http://serverip:34400/m3u/threadfin.m3u" after the updates.

3. Observe that the path is inaccessible.

4. Log in to the WEB UI.

5. Navigate to the Mapping section.

6. Press "Save" under Mapping.

7. Attempt to access the path "http://serverip:34400/m3u/threadfin.m3u" again.

8. Observe that the path is now accessible.

Expected Behavior:
The path "http://serverip:34400/m3u/threadfin.m3u" should remain accessible after the automatic updates of the "m3u" and "xmltv" files without requiring manual intervention.

Additional Information:

No abnormalities or error messages are observed in the logs related to this issue.

EDIT:

Right after the restart of the Container the m3u file looks like this and is not accessible (with the Docker Network IP):

![image](https://github.com/Threadfin/Threadfin/assets/128144210/29636e35-9342-422c-9802-2e0219f022b2)

After press save in the Mapping section it looks like this and is accessible (th IP is the right one now form the Docker Host system):

![image](https://github.com/Threadfin/Threadfin/assets/128144210/a23afa33-6ed7-4aa8-bc61-fd27296130fa)

**Comment by Fyb3roptik** [comment]
Yup I noticed this yesterday as well. I fully expected to do a couple patches :)

**Comment by carfanatic93** [comment]
Hi @Fyb3roptik,

I upgraded to 1.1.2 and after the restart of the container I can´t access "http://serverip:34400/m3u/threadfin.m3u" via the browser or Jellyfin.

Here a Screenshot from the threadfin.m3u right after the reboot:

![image](https://github.com/Threadfin/Threadfin/assets/128144210/9e9103f5-709f-4a1d-a463-ea8a9a83200b)

**Comment by Fyb3roptik** [comment]
Are you actually using the 172 address? Or are you using 192?

**Comment by carfanatic93** [comment]
> Are you actually using the 172 address? Or are you using 192?

I´m using the 192. address.

**Comment by Fyb3roptik** [comment]
Oh I see, my docker networks use .1 as the ending octet. Let me see if I can use a different way so it ignores docker networks

**Comment by Fyb3roptik** [comment]
if you do an `ifconfig` what is the name of the interface that uses `172.18.0.2`

**Comment by carfanatic93** [comment]
> if you do an `ifconfig` what is the name of the interface that uses `172.18.0.2`

Inside the docker container the name of the interface is "eth0".

**Comment by Fyb3roptik** [comment]
No not inside of docker. On the machine itself

**Comment by carfanatic93** [comment]
Oh okay. There it is "docker0"

**Comment by Fyb3roptik** [comment]
ok perfect ty

**Comment by carfanatic93** [comment]
Hi @Fyb3roptik,since the update to 1.1.8 setting the HTTP Domain causes this error:
`2024/05/21 07:57:51 [Threadfin] [ERROR] listen tcp 192.168.177.175:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001`
`2024/05/21 07:57:51 [Threadfin] [ERROR] listen tcp 192.168.177.175:34400: bind: cannot assign requested address () - EC: 0`
and I can´t access the web ui anymore. I had to delte the HTTP Domain in the settings.json. But then the meu got the docker ip in it as described in the beginning of this issuie.

**Comment by Fyb3roptik** [comment]
What did you put for the setting exactly? Also looks like it might be in use?

**Comment by carfanatic93** [comment]
"192.168.177.175" for HTTP Domain. This is also the IP of the Docker host. If I use the new release 1.1.18 and leave this setting blank, the url´s in the m3u got the docker network ip.
With 1.1.16 and the ip "192.168.177.175" set in the HTTP Domain everything works

**Comment by carfanatic93** [comment]
Then I got this error and the web ui is not available! 

`2024/05/21 07:57:51 [Threadfin] [ERROR] listen tcp 192.168.177.175:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001`
`2024/05/21 07:57:51 [Threadfin] [ERROR] listen tcp 192.168.177.175:34400: bind: cannot assign requested address () - EC: 0`
