### ISSUE TITLE
XMLTV Encoding issues

### ISSUE THREAD

**Issue by cvb941** [Threadfin/Threadfin#249]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin has wrong encoding on the XMLTV output.

**Server (please complete the following information):**
- OS - Docker
- Arch Intel 64 Bit
- Threadfin Version and Build 1.1

**To Reproduce**
As an example, this XMLTV programme title from the source feed:

```
<title>Hadi ve městě</title>
```

Gets borked into this in the threadfin XMLTV feed:
```
<title lang="">Hadi ve mst</title>
```

**Screenshots**
Titles are missing letters.
<img width="1116" alt="image" src="https://github.com/Threadfin/Threadfin/assets/2351527/47f9cc25-02ec-44db-9209-a6e4b7c2e00e">

**Comment by Fyb3roptik** [comment]
Check to see if you have Enable Non ASCII checked in settings. If you don't have it checked, please do so and restart threadfin

**Comment by cvb941** [comment]
Seems like enabling that option fixes the issue. I did not notice it. Why isn't it on by default?

In Jellyfin though, the letters are still missing, maybe that is a separate issue with Jellyfin..
