### ISSUE TITLE
Filter page keeps crashing

### ISSUE THREAD

**Issue by myhrmans** [Threadfin/Threadfin#25]
I have a m3u8 file with over 100,000 streams. 

Entering the filter tab keep crashing the page because each of the streams are printed out in the page making it veeeery long.

**Comment by Fyb3roptik** [comment]
Yes I have the same issue with bad m3u files. You probably have a lot of 24/7 channels that mucks it up. I will see what I can do here. Can you paste in any error messages by chance?

**Comment by Fyb3roptik** [comment]
Oh are you getting the Aw Snap page? If so there isnt much I can do here about that. I will attempt to make some changes to the code to filter out any channels without a group. Maybe that will help.

**Comment by myhrmans** [comment]
Correct. I'll look into the codebase when I have time, I think we are printing to many rows, there should be a better way to handle that.

**Comment by Fyb3roptik** [comment]
I have fixed this. It will be in the 0.9.12 release

**Comment by Fyb3roptik** [comment]
Fixed in 0.9.12

**Comment by myhrmans** [comment]
Can confirm it works, still really slow loading time but not expecting anything else when printing 100k rows.
