### ISSUE TITLE
static channel number

### ISSUE THREAD

**Issue by skinnyzaz** [Threadfin/Threadfin#250]
**Is your feature request related to a problem? Please describe.**
When channels like ppv update the channel name for example it changes the channel number to a lower available number.

**Describe the solution you'd like**
I would like an option to keep the channel number static even if the channel name is updated.

**Additional context**
I keep my main channels numbers starting from 1. Then ppv channels at 1000 next nba channels at 1100 and so on. I find this way it keeps it organized if I have to add more channels later. but currently if a ppv channel or say nba 01 updates the channel name those channels get placed at the next lowest available channel number and puts everything out of order.

**Comment by Fyb3roptik** [comment]
You can use something like m3u4u to set the channel number statically. If you provide `tvg-chno` in your m3u then it will keep it that number always

**Comment by skinnyzaz** [comment]
I looked into this, with m3u4u I would have to set every single channel number manually and would take too long. plus then you are always dealing with another step/app if you make any changes. would be a really nice feature to have an option on threadfin to check a box to keep channel number static regardless if the channel name is updated.
