### ISSUE TITLE
configure listening ip

### ISSUE THREAD

**Issue by bendschs** [Threadfin/Threadfin#253]
**Describe the bug**
Since the latest updates (1.1.4 to 1.1.6) threadfin started listening to the ip of my openvpn-server instead of the local lan ip. The webinterface is only reachable via local lan ip if i start threadfin without openvpn server running.

Is there a way to define the listening ip in the settings file?

**Server (please complete the following information):**
- debian bookworm
- arm64
- Threadfin Version 1.1.6

**Expected behavior**
Threadfin should first of all start listening to the primary ethernet device and then, maybe additionally to all other devices such as tun (if nothing is configured). On top it would be nice if one could set the listening ip in the config file (does not need to be in the webinterface).

**logs**
```
2024/05/17 09:22:49 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.1.6/Threadfin_linux_arm64
2024/05/17 09:22:49 [Threadfin] UUID:                   2019-01-DEV-Threadfin!
2024/05/17 09:22:49 [Threadfin] Tuner (Plex / Emby):    2
2024/05/17 09:22:49 [Threadfin] EPG Source:             XEPG
2024/05/17 09:22:49 [Threadfin] Plex Channel Limit:     480
2024/05/17 09:22:49 [Threadfin] Unfiltered Chan. Limit: 480
2024/05/17 09:22:49 [Threadfin] Backup Path:            /home/pi/.threadfin/backup/
2024/05/17 09:22:49 [Threadfin] Backup file:            /home/pi/.threadfin/backup/threadfin_auto_backup_20240517_0922.zip
2024/05/17 09:22:49 [Threadfin] Download:               http://192.168.3.73:7777/api/y3o/file/favorites.m3u
2024/05/17 09:22:50 [Threadfin] Check File:             http://192.168.3.73:7777/api/y3o/file/favorites.m3u
2024/05/17 09:22:50 [Threadfin] Save File:              http://192.168.3.73:7777/api/y3o/file/favorites.m3u [ID: M7D8AQLFL183EXGAFSBO]
2024/05/17 09:22:50 [Threadfin] Download:               http://192.168.3.73:7777/api/swc/file/favorites.m3u
2024/05/17 09:22:50 [Threadfin] Check File:             http://192.168.3.73:7777/api/swc/file/favorites.m3u
2024/05/17 09:22:50 [Threadfin] Save File:              http://192.168.3.73:7777/api/swc/file/favorites.m3u [ID: M8DJ2N2PTGYYU3YGTHBW]
2024/05/17 09:22:50 [Threadfin] Download:               http://192.168.3.73:4000/download/epg.xml
2024/05/17 09:22:50 [Threadfin] Header filename:        epg.xml
2024/05/17 09:22:50 [Threadfin] Check File:             http://192.168.3.73:4000/download/epg.xml
2024/05/17 09:22:52 [Threadfin] Save File:              http://192.168.3.73:4000/download/epg.xml [ID: XBMWGEFX8NB01F8Z9B7Z]
2024/05/17 09:22:52 [Threadfin] All streams:            69
2024/05/17 09:22:52 [Threadfin] Active streams:         69
2024/05/17 09:22:52 [Threadfin] Filter:                 0
**2024/05/17 09:22:52 [Threadfin] DVR IP:                 10.31.11.1:34400
2024/05/17 09:22:52 [Threadfin] Web Interface:          http://10.31.11.1:34400/web/ | Threadfin is also available via the other 1 IP.**
2024/05/17 09:22:52 [Threadfin] XEPG:                   Parse XMLTV file: easyepg
2024/05/17 09:22:54 [Threadfin] XEPG:                   Update database
2024/05/17 09:22:54 [Threadfin] XEPG:                   Save DB file
2024/05/17 09:22:54 [Threadfin] XEPG:                   Map channels
2024/05/17 09:22:54 [Threadfin] XEPG:                   Cleanup database
2024/05/17 09:22:54 [Threadfin] XEPG Channels:          69
2024/05/17 09:22:54 [Threadfin] XEPG:                   Create XMLTV file (/home/pi/.threadfin/data/threadfin.xml)
2024/05/17 09:22:55 [Threadfin] XEPG:                   Compress XMLTV file (/home/pi/.threadfin/data/threadfin.xml.gz)
2024/05/17 09:22:56 [Threadfin] XEPG:                   Create M3U file (/home/pi/.threadfin/data/threadfin.m3u)
2024/05/17 09:22:56 [Threadfin] XEPG:                   Ready to use
```

```
ifconfig
end0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.3.73  netmask 255.255.255.0  broadcast 192.168.3.255
        ether d8:3a:dd:c0:20:6f  txqueuelen 1000  (Ethernet)
        RX packets 444766  bytes 198647450 (189.4 MiB)
        RX errors 0  dropped 5451  overruns 0  frame 0
        TX packets 377042  bytes 175221173 (167.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 112  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 251749  bytes 363894412 (347.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 251749  bytes 363894412 (347.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.31.11.1  netmask 255.255.255.0  destination 10.31.11.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 430  bytes 43290 (42.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 554  bytes 157115 (153.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by marcelGoerentz** [comment]
+1
I have the same problem, since I have multiple IP Addresses for one interface. It would be fine, if there is a way to configure the ip address threadfin is listening to.
Threadfin does not listen to the loopback address, if so, in my case it would not be necessary to define a listening address.

**Comment by flyize** [comment]
Ahhh, this explains why it isn't working for me right now.

**Comment by Fyb3roptik** [comment]
You can set Threadfin Domain in Settings to fix this

**Comment by flyize** [comment]
That doesn't actually fix it.

**Comment by IradColdheart** [comment]
It looks like i face the same issue with 1.1.4-6 versions.  
Reverting to 1.0.27 fixed it.  
I'm using the docker container. Threadfin Domain in Settings did not fix it (at least with an IP address), nor specifying ip:port:port  in the docker compose file. THREADFIN_PORT=ip:port did not work either.

**Comment by brum74** [comment]
I'm having this issue with my docker container as well, setting the domain in settings doesn't help either.

**Comment by gurg1e** [comment]
I have my domain set in the settings and am experiencing this too. 

v1.1.6 broke HTTPS access via my Traefik reverse proxy (eg https://threadfin.mydomain.com) and was also inaccessible using the container hostname from other containers on the same docker network (eg. http://threadfin:34400). Rolling back to 1.0.27 solves the issue.

**Comment by bendschs** [comment]
why has this issue been closed? comments show clearly that there is high demand for resolving this.

**Comment by skinnyzaz** [comment]
broke min also so I reverted to 1.0

**Comment by marcelGoerentz** [comment]
With 1.8 it is now working when httpdomain is set to 127.0.0.1

**Comment by gurg1e** [comment]
Updated to 1.1.12 and I can access the webui and Jellyfin can load the EPG now, but playing in JF is still broken (settings unchanged from my [previous post](https://github.com/Threadfin/Threadfin/issues/253#issuecomment-2118484657)). 

`[ERR] [53] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
System.Net.Http.HttpRequestException: Connection refused (threadfin:34400)`

Would like to troubleshoot but probs wont have time until the weekend so I have again reverted to 1.0.27.

**Comment by troykelly** [comment]
@marcelGoerentz this is not resolved in 1.1.12
Can we please reopen one of the issues so it's clear this is a bug?

**Comment by marcelGoerentz** [comment]
@troykelly I'm not the owner of the repo neither I'm a maintainer, as mentioned in #257 I've created a PR to fix this Issue #260.
Unfortunately the owner is not willing to recognize that there is an issue and closed everything regarding this topic.
Nevertheless, if there are still people out there willing to use this software I've made a [fork](https://github.com/marcelGoerentz/Threadfin)  of this repo where I fixed it.
I will upload the binary files so you can use my fix.

**Comment by troykelly** [comment]
Apologies @marcelGoerentz thank you. Will switch to the fork.

**Comment by marcelGoerentz** [comment]
@troykelly I've just uploaded the binaries to my fork
@Fyb3roptik It would be nice if there would be a new setting where users can explicitly set the IPs Threadfin should listen to.
By just setting ab IP as a domain name is working for IPv4 but if a user wants to use IPv6 it does not work.
My fix will let Threadfin listen to any interface on the machine, but I assume that many users want to restrict it to specific interface or even to a specific IP address.
Therefor, a new setting has to be implemented where it will be possible to configure the mentioned things. I would even suggest to add a new settings category where the user can set all the network related settings.
I would implement the solution, but I'm not that deep into TS, JS and GO. to be honest so it would take some time to do so.

**Comment by carfanatic93** [comment]
> @troykelly I've just uploaded the binaries to my fork @Fyb3roptik It would be nice if there would be a new setting where users can explicitly set the IPs Threadfin should listen to. By just setting ab IP as a domain name is working for IPv4 but if a user wants to use IPv6 it does not work. My fix will let Threadfin listen to any interface on the machine, but I assume that many users want to restrict it to specific interface or even to a specific IP address. Therefor, a new setting has to be implemented where it will be possible to configure the mentioned things. I would even suggest to add a new settings category where the user can set all the network related settings. I would implement the solution, but I'm not that deep into TS, JS and GO. to be honest so it would take some time to do so.

Did you also push a docker image ?

**Comment by marcelGoerentz** [comment]
> > @troykelly I've just uploaded the binaries to my fork @Fyb3roptik It would be nice if there would be a new setting where users can explicitly set the IPs Threadfin should listen to. By just setting ab IP as a domain name is working for IPv4 but if a user wants to use IPv6 it does not work. My fix will let Threadfin listen to any interface on the machine, but I assume that many users want to restrict it to specific interface or even to a specific IP address. Therefor, a new setting has to be implemented where it will be possible to configure the mentioned things. I would even suggest to add a new settings category where the user can set all the network related settings. I would implement the solution, but I'm not that deep into TS, JS and GO. to be honest so it would take some time to do so.
> 
> Did you also push a docker image ?

@carfanatic93  Sorry, unfortunately I didn't push a docker image since I lack skills here too

**Comment by kmaid** [comment]
I jumped onto Discord with @Fyb3roptik and he said it would be fixed in version 1.2.0) (https://discord.com/channels/1022987280685748234/1242507112228065310)

**Comment by JustBeta** [comment]
I use a Windows command that allows port/IP redirection to another port/IP.
I use Threadfin on Windows, but it also works on Linux; of course, you need to adapt the command.
This allows me to use version 1.1.12 while waiting for version 1.2.0.

Here is the command on Windows:
netsh interface portproxy add v4tov4 listenaddress=192.168.0.39 listenport=34400 connectaddress=192.168.48.1 connectport=34400

**Comment by marcelGoerentz** [comment]
Hey guys,

I updated my fork and upload new binaries. Now you are able to restrict threadfin to accept only requests on the provided IPs.
This should work for IPv4 as well as for IPv6.
Please Note that the webserver is still listening to all interfaces and addresses.

**Comment by flyize** [comment]
@marcelGoerentz Any chance of a PR here?

**Comment by marcelGoerentz** [comment]
> @marcelGoerentz Any chance of a PR here?

@flyize Sure, I raised the PR #268

**Comment by marcelGoerentz** [comment]
Docker images are now available:

`docker pull mgoerentz/threadfin:latest`

**Comment by carfanatic93** [comment]
> Docker images are now available:
> 
> `docker pull mgoerentz/threadfin:latest`

Works !!

**Comment by Fyb3roptik** [comment]
1.1.13 will add the bind IP setting

**Comment by bendschs** [comment]
thank you guys! @marcelGoerentz @Fyb3roptik

**Comment by Fyb3roptik** [comment]
Re-open this issue if it is not fixed. Thanks

**Comment by 2fst4u** [comment]
You can't edit the settings if the web server doesn't start in the first place. How do we resolve this in the version you've applied the fix to? 

I'm lost on what to actually do.

**Comment by bendschs** [comment]
i noticed that too, could be irritating for users that are new to threadfin. for now you can set it manually in ./.threadfin/settings.json .

**Comment by GeekSpeak79** [comment]
Feedback:
I adjusted my binded Statiic IP by directly editing settings.json; everything worked out great I can not access the UI from a remote PC.

Side Note: When I launched Threadfin from command line (Not as a service), the listed web interface IP worked for me to connect to the UI on my local server so I could edit the static IP for the WebUI.

Thank you all for your work and dedication!

**Comment by rplushh** [comment]
the update resulted in the same outcome as the original post. I am running threadfin in a gluetun network. I had to manually change the bindIP in settings.json to the virtual network IP in order to access threadfin locally.

**Comment by gurg1e** [comment]
Is binding to an IP address the right idea for a service in docker? Docker network IPs are designed to be dynamic and the container should be accessed using the hostname (usually the name of the container).

**Comment by troykelly** [comment]
> Is binding to an IP address the right idea for a service in docker? Docker network IPs are designed to be dynamic and the container should be accessed using the hostname (usually the name of the container).

You typically want your application to be as flexible and network-agnostic as possible when it's designed to operate inside a docker container. This is important because containers are used in vastly different environments, and each environment might have a different network configuration.

"0.0.0.0" is used for IPv4 addresses and tells the operating system that your application should accept connections on all IPv4 addresses available to the container. "::" is the equivalent for IPv6 and tells the system to accept connections on all IPv6 addresses.

Binding to "0.0.0.0" or "::" is generally recommended as it ensures the containerised application remains flexible and fully compatible with Docker’s networking capabilities. This practice avoids the complications associated with fixed IP addresses or hostnames, maintaining the portability and scalability central to Docker's value proposition.

**Comment by 2fst4u** [comment]
So the question still remains, how do we actually resolve the problem when updating?

**Comment by marcelGoerentz** [comment]
You could set the binding ip to 0.0.0.0

**Comment by troykelly** [comment]
My suggestion is that the code should only ever bind to `0.0.0.0` (and `::` if available) and let the user decide through docker networking configuration how and where it is accessible.

It removes a layer of complexity from the code, and let's Docker do what it's meant to.

**Comment by marcelGoerentz** [comment]
This is exactly what my suggested solution does.
And self hosting users can restrict the web server access.
Unfortunately my PR didn't make it. It was closed without a comment.

**Comment by troykelly** [comment]
It's clear that a lot of hard work and dedication goes into Threadfin, and that's something I am sure we all greatly value. This is evidenced by the broad involvement in this issue alone.

I've noticed a few networking-related issues that recur across the repository, concerning network binding and how SSL works for remote servers. Understanding the full scope of Docker’s networking capabilities can be tricky, and there's always a learning curve with such complex topics.

While I understand and respect the decisiveness in managing issues and PRs, it might be beneficial to consider community feedback a bit more, especially on topics as intricate as networking. This approach can foster diverse solutions and enhance the project’s robustness.

It would be great to get this issue reopened, so a fix to what is obviously a broad problem can be devised and agreed upon.

**Comment by iceman73** [comment]
Can the Readme be updated on how to add this when upgrading from an existing installation, as well as changes needed for an initial install, this will help new comers or people not understanding why an upgrade broke their installation.

**Comment by flyize** [comment]
@Fyb3roptik I think we'd all love your input here?

**Comment by Fyb3roptik** [comment]
I'm not interested in keeping this project going TBH. It's a stepping stone. And every time I get pulled into it I get pulled away from kernel. I won't be doing anymore development on it unless I find issues that are show stoppers. Sorry but at some point I have to say enough. 

This repo is very very badly coded. xteve was complete mess of a codebase. I hate working with this code.

I will be closing any new issues that arise. Sorry but I don't have time.

**Comment by flyize** [comment]
Fair enough. I think we all thank you for all of your work.

**Comment by telnetdoogie** [comment]
> I'm not interested in keeping this project going TBH. It's a stepping stone. And every time I get pulled into it I get pulled away from kernel. I won't be doing anymore development on it unless I find issues that are show stoppers. Sorry but at some point I have to say enough.
> 
> This repo is very very badly coded. xteve was complete mess of a codebase. I hate working with this code.
> 
> I will be closing any new issues that arise. Sorry but I don't have time.

Thanks for what you've done here, @Fyb3roptik  - Is there a way you can appoint some maintainers beyond yourself so that the community can contribute autonomously and keep this alive?

**Comment by Fyb3roptik** [comment]
It's not going away as much as I'm upgrading it to a new project that will have what works good without the mess

**Comment by telnetdoogie** [comment]
Love it! Do your thing!!
