### ISSUE TITLE
Group title filter with ampersand

### ISSUE THREAD

**Issue by sthacker79** [Threadfin/Threadfin#256]
Unable to create a filter if the group title contains the "&" character.  I have a group title named "Comedy & Drama".  After creating the filter and looking at the settings.json file I see the group title contains "filter": "Comedy",.

**Comment by Fyb3roptik** [comment]
I found your issue. I will push this out with 1.1.10

**Comment by Fyb3roptik** [comment]
Nevermind I fixed this in 1.2.0 so look for it when it deploys

**Comment by Fyb3roptik** [comment]
1.1.12 should now fix this and add ampersand support
