### ISSUE TITLE
Listening only on host IP

### ISSUE THREAD

**Issue by troykelly** [Threadfin/Threadfin#257]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
With the latest container update, Threadfin is now not listening do the default "0.0.0.0" or "::" - it seems to select a single address and binds. This breaks Threadfin in a docker container with host networking.
I believe the bug was introduced by https://github.com/Threadfin/Threadfin/commit/b27dfdd3c069a5e35b83b7dd3cfeba065a3f5068

**Server (please complete the following information):**
- OS Ubuntu 23.10
- Arch x86_64
- Threadfin Version and Build 1.1.6

**To Reproduce**
1. Update the existing working threadfin container to 1.1.6
2. Fail to connect to threadfin

**Expected behavior**
Threadfin should listen on the default IPv4 and IPv6 addresses unless the user explicitly configures otherwise. Selecting Threadfin's interface using the current logic will break many configurations.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Comment by bendschs** [comment]
same here and same/similar issue as in https://github.com/Threadfin/Threadfin/issues/253

**Comment by troykelly** [comment]
I was wrong about the cause of the issue, this was introduced in `1.1.1`. That is to say `1.1.0` was the last working version.

**Comment by marcelGoerentz** [comment]
Hey guys, I can confirm it is now working with 1.8 when setting the httpdomain and restarting the service.

**Comment by troykelly** [comment]
> Hey guys, I can confirm it is now working with 1.8 when setting the httpdomain and restarting the service.

What IP address does it listen on? Is it listening on both IPv6 and IPv4?

**Comment by marcelGoerentz** [comment]
IPv4 currently, but should also work with IPv6, but no guarantee

**Comment by troykelly** [comment]
> IPv4 currently, but should also work with IPv6, but no guarantee

So it's back to listening on "::" as it should? Or it's binding to a specific IP of the hostname?

**Comment by marcelGoerentz** [comment]
sudo netstat -tulpn | grep threadfin gives me this:
tcp        0      0 127.0.0.1:8091          0.0.0.0:*               LISTEN      484563/threadfin
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           484563/threadfin

**Comment by marcelGoerentz** [comment]
I've created a PR for this to fix: https://github.com/Threadfin/Threadfin/pull/260

**Comment by Fyb3roptik** [comment]
This has already been fixed in 1.1.8
