### ISSUE TITLE
invalid character entity & (no semicolon)

### ISSUE THREAD

**Issue by remb0** [Threadfin/Threadfin#258]
when importing my xml url in the latest version, i got the message:
XML syntax error on line 490: invalid character entity & (no semicolon)

What can I do about it?

**Comment by Fyb3roptik** [comment]
Show me what line 490 looks like

**Comment by remb0** [comment]
#EXTINF:-1,NL | HORSE & COUNTRY TV
http://redacted.link:80/redacted/redacted/51
#EXTINF:-1,NL | HGTV
http://line.clear-ocean.link:80/redacted/redacted/417087
#EXTINF:-1,✦●✦●      SP⚽RT      ✦●✦●      
http://redacted.link/redacted/redacted/207312

in vscode is line 490 the horse & country tv

**Comment by remb0** [comment]
I understand,   but This is coming from a online m3u I cannot change.  Or do you have an idea hoe to do this?
