### ISSUE TITLE
M3U Parser is BROKEN

### ISSUE THREAD

**Issue by bweezy21** [Threadfin/Threadfin#262]
Since the dev doesn't review comments on closed issues, and closes issues that are not fixed:

https://github.com/Threadfin/Threadfin/issues/161
https://github.com/Threadfin/Threadfin/issues/170
https://github.com/Threadfin/Threadfin/issues/172
https://github.com/Threadfin/Threadfin/issues/259

This is a problem. It is broken. Stop closing these issues. 

xteve_m3uParser.go line 135: content = strings.Replace(content, "'", "\"", -1) 
this replaces single quotes with double quotes which then leads to bad tokenization later where double quotes all get replaced with empty strings. 

This is a bug do not close this issue without fixing it. Others should be able to see that it doesn't work as intended. There is no M3U spec and therefore no justification for removing single quotes. If you must replacing them with empty strings would be better than the current implementation.

**Comment by Fyb3roptik** [comment]
The M3U fix is coming in 1.2.0. I will close issues as I see them as resolved. Dont like it? Make your own repo then
