### ISSUE TITLE
unable to access threadfin from other computers as listening on 127.0.0.1

### ISSUE THREAD

**Issue by grooverider2016** [Threadfin/Threadfin#264]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
unable to access server web console from remote computer by browsing to hostname/ip of threadfin server. only works from the threadfin server itself using localhost/127.0.0.1 

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] Windows 2022
- Arch [e.g. Intel 64 Bit] intel 64bit
- Threadfin Version and Build [to be found in the Threadfin log] 1.1.4 to 1.1.10

**To Reproduce**
1. start threadfin_windows_amd64.exe
2. open browser on another computer and browse to threadfin web console via ip of threadfin computer or hostname
3. page cannot be displayed error - no page found

**Expected behavior**
should see web console login screen (if auth enabled) or web console page

**Additional context**
as the server is listening on 127.0.0.1 it is only responding to requests from itself despite threadfin saying it is also listening on X other ip addresses. IT isnt actually listening on those other addresses or at least if it is then it isn't responding. Resolution would be to allow specifying the ip address that the server should listen on as well as the port that it should listen on.

**Comment by Fyb3roptik** [comment]
Resolved on Discord. For context updating HTTP Threadfin Domain to the ip address it needs to be. `192.168.0.12` instead of `http://192.168.0.12`

**Comment by grooverider2016** [comment]
[like]  Gareth Winn reacted to your message:
________________________________
