### ISSUE TITLE
Using no buffer option creates error in emby client (The SSL connection could not be established, see inner except)

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#266]
**Describe the bug**
When i use 'no buffer' option i get an error using emby client "The ssl connection could not be established, see inner exception" and i get this error on each and every channel. When checking the threadfin logs i can see that the correct iptv url is forwarded and when i try to open the mentioned iptv url from the log using a direct player (e.g.) vlc it also works. When i enable a buffer (VLC /ffmpeg) in threadfin i do not have this error - channels play correctly - but i would prefer not using a buffer. This issue with the ssl error just recently started some days ago

**Server (please complete the following information):**
- Linux (docker)
- Synology 720+ (docker)
- Main 1.1 (11)

**To Reproduce**
1. Use no buffer option in threadfin
2. Play a channel in emby

**Expected behavior**
I would like to have no error when trying to play a stream in emby with no buffer option in threadfin (as it also worked before some days ago)

**Desktop (please complete the following information):**
 - Macbook Air 2
 - Chrome

**Comment by Fyb3roptik** [comment]
If it plays correctly in VLC then chances are something changed with Emby. Is this input in MPEGTS? Or HLS?

**Comment by tobiasredel** [comment]
Mpegts
________________________________
Von: Nick Wallace ***@***.***>
Gesendet: Wednesday, May 22, 2024 12:45:54 AM
An: Threadfin/Threadfin ***@***.***>
Cc: Tobias Redel ***@***.***>; Author ***@***.***>
Betreff: Re: [Threadfin/Threadfin] Using no buffer option creates error in emby client (The SSL connection could not be established, see inner except) (Issue #266)


If it plays correctly in VLC then chances are something changed with Emby. Is this input in MPEGTS? Or HLS?

**Comment by tobiasredel** [comment]
I also raised the topic with Emby - but no update yet on their end and as the streams itself have not changed I wonder why it should be an Emby topic as threadfin does not really alter the streams when buffering.

**Comment by Fyb3roptik** [comment]
This is an Emby issue 100%. If you arent using the buffer then Threadfin has no control over it.
