### ISSUE TITLE
Adding backup channel not showing in mapping but shows in filter

### ISSUE THREAD

**Issue by skinnyzaz** [Threadfin/Threadfin#270]
**Describe the bug**
Added a channel named ESPN Backup from my source, the channel is listed in my active filter but not showing in mapping.
I do already have an ESPN channel but its a different channel and named differently.
![image](https://github.com/Threadfin/Threadfin/assets/1121042/27da30ec-d040-4068-a173-ffd0a694f410)

**Server (please complete the following information):**
- Ubuntu 20
- Intel 64 Bit
- 1.1 (12)

**Comment by Fyb3roptik** [comment]
You can see it in the urls.json file. It won't be in the mapping. It simply does a url swap
