### ISSUE TITLE
Upgrading from Version 1.0(16)  ->  Version 1.1(13)  - Slugish when displaying web interface each time

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#271]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have Threadfin behind an NGINX proxy with subdomain.  I.E., https://threadfin.mydomain.com  Every time I upgrade to a new version, I simply replace the EXE with a newer version and execute the EXE.  To my surprise, this is the first time after I upgraded, I noticed that it takes nearly 2 seconds to display the web interface; even on my LAN from any other PC/mobile device.  When I revert back to the previous version the interface displays instantly every time.  If I go back to the latest version, it is back to being sluggish again when displaying the web interface.

NOTE:  I have a super fast server with 1GB/s network interface.  My client PC also has 1GB/s network interface.  I don't notice any unusual errors in the log.  If there is something I can provide you, please let me know.  I reverted back to the older version for now.

**Server (please complete the following information):**
- OS Windows 11
- Intel 64 Bit
- Threadfin Version:  1.1 (13)

**To Reproduce**
1. Go to https://threadfin.mydomain.com 

**Expected behavior**
It is lightning fast when I use any version that is <= 1.0(16 ).  I am not sure which version introduced this sluggishness.  I haven't tried any other versions in between 1.0(16 ) - 1.1(13)

**Screenshots**

**Desktop (please complete the following information):**
- OS Windows 11
 - Browser [MS Edge]
 - Version [Version 125.0.2535.67 (Official build) (64-bit)]

**Additional context**

**Comment by Fyb3roptik** [comment]
You need to set the bind ip address

**Comment by mkanet** [comment]
> You need to set the bind ip address

This PC only has a single network adapter with IPV4:  `192.168.1.2`.  I first tried using `192.168.1.2` as the bind IP address and restarted.  That didnt allow me to access it via https://threadfin.mydomain.com/ anymore.  Then, I changed the bind IP address to `0.0.0.0` and restarted.  It now seems to now have the behavior it used to have in all previous versions.

Maybe you could have threadfin bind IP address default to `0.0.0.0`; unless specified by the user.  Luckily you told me and I guessed using `0.0.0.0`.   I don't think that is very intuitive.

Did I guess correctly by using 0.0.0.0?  All I know is now it seems to be fast like it used to be.

**Comment by mkanet** [comment]
Thank for the suggestion.  Can you think of what IP address I should use for this setting so it is safe and also the same speed when accessing Threadfin/xTeVe web interface?  I am not sure what to use so it is the equivalent of how it used to be.
