### ISSUE TITLE
Upgrading from Version 1.0(16) -> Version 1.1(13) - Plex Playback Error Could not tune channel. Please check your tuner or antenna.

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#272]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
When I try to play any LiveTV shows in Plex after upgrading from Version 1.0(16) -> Version 1.1(13), none of the LiveTV channels will stream to Plex.  I get the general error:  `Playback Error
Could not tune channel. Please check your tuner or antenna.`.  If I revert back to the old version of Threadfin, all LiveTV channels start working again.  There are no warnings or errors in the Threadfin log.  In Plex's console, the only related error was:

```
[HttpClient/HCl#75dc] HTTP error requesting GET http://192.168.1.2:34400/discover.json (7, Couldn't connect to server) (Failed to connect to 192.168.1.2 port 34400 after 2021 ms: Couldn't connect to server)
```
**NOTE:** I changed the bind IP address from 0.0.0.0 to 192.168.1.2, however, that didn't make any difference to the above issue.  The only easy fix I know is to revert back to Version 1.1(13).  

**Server (please complete the following information):**
- OS Windows 11
- Intel 64 Bit
- Threadfin Version:  1.1 (13)

**To Reproduce**
1. Play any LiveTV channel in Plex

**Expected behavior**
The playback to start normally just like the older versions of Threadfin

**Screenshots**

**Desktop (please complete the following information):**
- OS Windows 11
 - Browser [MS Edge]
 - Version [Version 125.0.2535.67 (Official build) (64-bit)]

**Additional context**

**Comment by Fyb3roptik** [comment]
Did you enable ssdp?

**Comment by Fyb3roptik** [comment]
Check settings and make sure ssdp is enabled

**Comment by mkanet** [comment]
@Fyb3roptik I just checked.  SSDP is already enabled.  

Is there any information I can provide you to help you know what might be wrong?  I've been using the same settings/configuration for many years, even when I was using xTeVe.

**Comment by 2fst4u** [comment]
Same issue here. SSDP is enabled. Closing this as complete is a bit rude.

**Comment by mkanet** [comment]
@2fst4u  I agree.  I decided to continue remaining on the older version `1.0 Build: 16` indefinitely since I'm not sure how what to do to avoid this.  

Also, versions newer than `1.0 Build: 16`  [also have UI sluggishness that didnt exist before](https://github.com/Threadfin/Threadfin/issues/271).
