### ISSUE TITLE
Threadfin Will Not Update

### ISSUE THREAD

**Issue by NOsauce86** [Threadfin/Threadfin#274]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS: Windows 10 64bit
- Threadfin Version: 1.0 (23)

**To Reproduce**
1. Open Threadfin
2. Terminal gives error: 2024-05-30 12:44:46 [Threadfin] Start Update:           Branch: Main
2024-05-30 12:44:46 [Threadfin] [ERROR] bad status: 404 Not Found (Update failed) - EC: 6002

**Expected behavior**
Threadfin to update automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome or Brave

**Additional context**
I have tried downloading and running later exe files, but they fail during the terminal boot process.

**Comment by Fyb3roptik** [comment]
Join the Discord and ping me please

https://discord.gg/CNaSkER2zD
