### ISSUE TITLE
Allow for additional/custom buffering applications

### ISSUE THREAD

**Issue by syco** [Threadfin/Threadfin#278]
Hi
I want to buffer streams using streamlink instead of ffmpeg/vlc.
Would it be possible to add a custom option where the buffering application can be manually configured?
In my case it would be `/usr/bin/streamlink [url] best`

Clearly it's my responsibility to ensure the custom application I chose is installed and available.

Thanks

**Comment by Fyb3roptik** [comment]
No new features are being added
