### ISSUE TITLE
In Tivimate, channel not start on selection without error

### ISSUE THREAD

**Issue by dunlopr** [Threadfin/Threadfin#279]
**Describe the bug**
When I tune in a channel from my Threadfin on Tivimate, I get an eternal hourglass. There's nothing in the Threadfin app log, as if I wasn't using it.

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]: Ubuntu 22.04 via docker
- Arch [e.g. Intel 64 Bit] AMD64
- Threadfin Version and Build [to be found in the Threadfin log] v1.1.14

**To Reproduce**
In Threadfin:
Set the following parameters:
-EPG Source: XEPG
-Update all file at startup
-Stream buffer: ffmpeg
-Buffer size: 1 MB
-Store buffer in RAM
-Timout 700
- Enable authentication for: WEB, PMS, M3U

Create a user with rights to: PMS, M3U and XML
Add HDHomerun tuner
Add an XML guide from an online supplier.
Link channels with their guide

On a Chromecast with Google TV:
- Install Tivimate
- Add a Threadfin playlist (with authentication) to Tivimate
- Add an XML guide (without authentication) from Threadfin

Use for a few days. After a while, synthonization stops working. No error in the logs of Threadfin

**Expected behavior**
The problem is not constant. I force the guide update in Threadfin, click the “save” button in settings and go to Tivimate and force an update of the playlist and guide. At that point, it works again for a day. I have to do this every day. So I went back to version 1.0.24 and the problem stopped.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Tivimate on Chromecast with Google TV
 - Version [e.g. 22] TiviMate/5.0.4

**Additional context**
The problem occurs with version 1.1.14 but also with several previous versions. For the moment, I'm back to version 1.0.24.
I also use Threadfin in a Plex server. No problems there.

**Comment by Fyb3roptik** [comment]
Does tivimate support mpegts? Sounds like its not a threadfin issue if its working on Plex

**Comment by Fyb3roptik** [comment]
Feel free to pop into the discord. Link is in the README

**Comment by dunlopr** [comment]
> TF keeps the m3u and epg files on the server. Any issues accessing those files from only a certain app would indicate some issue with the url you used in that app or your server configuration.
> 
> Can you access those files by going directly to them using the same url that's in tivimate within a web browser?
**Yes, I use the internal IP address:
http://192.168.1.8:34400/m3u/threadfin.m3u?username=xxx&password=yyy (with the right information here)
http://192.168.1.8:34400/xmltv/threadfin.xml**
> 
> Also you mentioned auth on m3u but off on epg? Is there a reason for that? Does it work if you turn on auth for the epg also?
**I tried with authentication enabled. Same problem. I even tried without the TF guide and used a guide from another source. Still the same behavior.**
> 
> For it to pull the epg the first time but not subsequent pulls seems very odd as it is simply a file that the link is accessing, it's not like TF is creating a new epg on the fly when tivimate asks for an update.

**It's not an EPG retrieval problem, when I choose a channel, it doesn't activate in TF. I have an hourglass in tivimate that won't stop. It's as if the command to turn on the channel doesn't send itself.**

**Comment by dunlopr** [comment]
> Does tivimate support mpegts? Sounds like its not a threadfin issue if its working on Plex
Yes, I've been using your program for almost a year now, which I love by the way. In tivimate it's very smooth and usually very reliable, if I stay on version 1.0.24. I like to keep track of the versions of a tool that is so well maintained. I wouldn't want to stick with an old version.

**Comment by dunlopr** [comment]
I understand that this kind of bug is complex to fix. If only I had a message in the log. It seems to be when Tivimate calls the channel. As if TF wasn't receiving the call. However, with 1.0.24, everything is fine.
