### ISSUE TITLE
Threadfin Dummy -> PPV doesn't have "Title" populated

### ISSUE THREAD

**Issue by crobibero** [Threadfin/Threadfin#28]
Version: 0.9 Build: 18
Running with `fyb3roptik/threadfin:latest`

Sample program:
```xml
<programme channel="3297" start="20221104130000 -0400" stop="20221105235959 -0400">
<category lang="en">sports</category>
<episode-num system="original-air-date">2022-11-04 13:00:00</episode-num>
<icon height="" src="https://domain.tld/image.png" width=""/>
<credits/>
<video/>
<date/>
</programme>
```

I would expect that the program title would be the ppv title.

**Comment by Fyb3roptik** [comment]
Did you enable this in Settings?

**Comment by Fyb3roptik** [comment]
I see it working for me is why I ask

**Comment by crobibero** [comment]
Are you referring to "Replace PPV channels title/desc"? 
If so- yes that is enabled

**Comment by Fyb3roptik** [comment]
Please try using the version I just pushed out. 0.9.20

**Comment by crobibero** [comment]
@Fyb3roptik Not sure what is happening but the `latest` and `0.9.20` tags both still start `0.9 Build: 19` so I am unable to test the changes

**Comment by Fyb3roptik** [comment]
I will check on this when I deploy 0.9.21 today. Sorry for the delay!

**Comment by Fyb3roptik** [comment]
This should be fixed now. 0.9.21 is up on docker. Make sure you pull the latest image

**Comment by Fyb3roptik** [comment]
Closing for now. Please re-open if this issue persists.

**Comment by crobibero** [comment]
This seems to be working correctly now, thanks!
