### ISSUE TITLE
mapped channel problem

### ISSUE THREAD

**Issue by JustBeta** [Threadfin/Threadfin#280]
Hi,

**Describe the bug**
I have a problem with the m3u => epg mapping.
I correctly imported my XML before the m3u files.
I created a corresponding filter.

At the mapping level, the majority of the channels are not mapped correctly.
In my research, I noticed that the channels that were not mapped do exist in the XML file of the epg (value of tvg-id = channel-id).
However, the case is not respected.

**Server (please complete the following information):**
- OS Windows 11
- Arch x64
- Threadfin Version and Build 1.1.14

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/25150896/520e9b7b-bbe7-4f8c-acc1-315b0d5e5294)

![image](https://github.com/Threadfin/Threadfin/assets/25150896/fea20481-7eff-4067-b854-d57314441dbf)

![image](https://github.com/Threadfin/Threadfin/assets/25150896/2c35f7cf-6689-4271-bd43-7bdc2a1234de)

![image](https://github.com/Threadfin/Threadfin/assets/25150896/89549ae6-ad81-4b60-8cb2-15ccba3e74cc)

**Additional context**
sample m3u:
#EXTM3U
#EXTINF:-1 **tvg-id="tf1.fr"** tvg-name="FR - TF1 FHD " tvg-logo="http://go4.pw/EUROPE/FRANCE/TF1.png" group-title="EU | FRANCE GENERAL",TF1 FHD
http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

sample epg: 

  <**channel id="TF1.fr"**>
    \<display-name>TF1\</display-name>
    <icon `src="https://www.teleboy.ch/assets/stations/308/icon320_light.png?v2023_48_0"/>`
  \</channel>
  <programme start="20240604060000 +0200" stop="20240604065500 +0200" **channel="TF1.fr"**>
    \<title lang="fr">TFou\</title>
    \<desc lang="fr">Splat &amp; Harry (ST) / Pfffirates (ST) / Paw Patrol, la Pat'Patrouille (ST)\</desc>
    \<category lang="fr">Jeunesse\</category>
    \<category lang="fr">Mag. Jeunesse\</category>
    \<icon src="https://proxymedia.woopic.com/api/v1/images/1870%2Fepg%2Ffe4fec3704804a98b315276fe59e7c01.jpg"/>
    \<rating system="CSA">
      \<value>Tout public\</value>
    \</rating>
  \</programme>

excuses my english, i'm french.

**Comment by Fyb3roptik** [comment]
The channel id is lowercase and the EPG is uppercase. Not the same

**Comment by JustBeta** [comment]
Yes, of course. But isn't it possible to have the option to ignore case sensitivity?
