### ISSUE TITLE
Better filtering

### ISSUE THREAD

**Issue by albinmedoc** [Threadfin/Threadfin#282]
**Is your feature request related to a problem? Please describe.**
I find it very difficult to create detailed rules. Most of the time I let too many channels through.
My IPTV provider, provides me with 240k channels, I would really need a way to fine tune which channels show up in Plex so I'm not hitting the limit

By solving this I think Threadfin would stand out from other M3U proxies and hopefully be the way to go.

**Describe the solution you'd like**
To be able to create more detailed rules. It would be great to have nested operators. 
Like the following. 

`{ { Disney || Nickelodeon || NickToons } && { SE || EN } } !{VOD}`

This would return channels that _**includes either**_ 
* Disney
* Nickelodeon
* NickToons 

and _**includes either**_
* SE
* EN

and _**does not include**_
* VOD

**Describe alternatives you've considered**
I've tried creating several separate rules, but they seem to cancel each other out. Maybe this is a bug that should be investigated?

**Comment by Fyb3roptik** [comment]
try m3u4u to set it and then import that to threadfin
