### ISSUE TITLE
BUG - Web Auth/Caching/Saving

### ISSUE THREAD

**Issue by JReming85** [Threadfin/Threadfin#283]
1st thank you for picking up this project, its much appreciated.
2nd this will include several bugs, if needed I can create seperate issues

**Describe the bug**
1. Enabling WEB Auth + PMS/DVR Auth will break the tuner.  Plex was reporting 0 channels, and would not add.

2. Just having WEB Auth enabled + Image Caching/Force HTTPS, breaks images.  Images will just try to load forever but will not work.  It also doesnt seem to be forcing HTTPS in some instances as :80 is hardcoded is all the cached images.

3. Bulk Edits will auto save when clicking Done, instead of the Save button. Was doing a bulk edit on 50ish channels and it overwrote the EPG when I clicked Done.  Tried to reload but found it was already saved.
Not sure if that was expected, but xTeve would not make any changes until Save was pressed.

 

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
Debian GNU/Linux 12 (bookworm) - Debian 1:6.1.73-1+rpt1 
- Arch [e.g. Intel 64 Bit]
Arm64 - RPI5
- Threadfin Version and Build [to be found in the Threadfin log]
1.1 (14) - Main

**Comment by JReming85** [comment]
I have it running on an RPI5 using the Threadfin_linux_arm64 binary.

 

I also have the port set to 80, and a reverse proxy on another machine providing https via nginx.

 

The EPG would also not download using the provided example and I had to go oldschool with http:// <http://%3cuser%3e:%3cpass%3e@%3cip%3e:80> <user>:<pass>@<ip>:80 for it to accept.

 

I also noticed it gets stuck in “Maintenance” mode when doing heavy editing/importing sometimes.

**Comment by Fyb3roptik** [comment]
You should never set it to port 80. Dont do that. Use either the port it comes with or a different higher number. Youre using a reverse proxy so there is no need to use port 80.

**Comment by Fyb3roptik** [comment]
Also the images are using :80 because that is what youre using...again use a different port and is you want them over https then use the reverse proxy address with it
