### ISSUE TITLE
Not working on localhost or with VPN ?

### ISSUE THREAD

**Issue by requa3r0** [Threadfin/Threadfin#286]
Hi

I just compiled to 32-bit android 9 on the Beelink GT king inside the grat linux emulater termux. (from F-droid)
I also run KODI 21 omega and use the PVR IPTV_Simple_Client addon

I did this with xTeVe and have run the latest version for years, using 
http://localhost:34400/web/

But for some reason Threadfin does not answer on localhost?

When I run the Torguard VPN, it does not even answer on the IP

http://192.168.1.XXX:34400/web/

xTeVe never had a problem with either localhost or the VPN?

This basically makes Threadfin unusable for the purpose, because the hole point with the small TV box is take with you from home to summerhouse or a friends house etc. That means you get a new IP all the time, and besides the Torguard VPN is set to auto-load and block none VPN connections.

Is this a bug or a settings issue, or on purpose?

Requa3r0

**Comment by Fyb3roptik** [comment]
Set the bind address in settings

**Comment by requa3r0** [comment]
Thanks for your speedy reply.
I set it to localhost, and this worked.

Now KODI, IPTV_Simple_Client addon set to http://localhost:34400/...... works.
Also when the VPN is engaged.
And the local IP also answers for easy configuration from a PC.

Can you please explain why this is not set to localhost pr default.
This seems to be rather strange - Most would expect the server to answer on both local IP and localhost, and its absoutly needed in a DHPC environment.

Also the EPG Source is set to PMS where I would think XEGP is the normal standard.

So, this issue is a recommendations for the two options to be set to localhost and EXPG settings pr. default.

Thanks for a great new software, ill test it any may deploy Threadfin on all the xTeVe/KODI platforms I maintain ;O)

**Comment by Fyb3roptik** [comment]
Different people have different setups. Its easier to just specify instead of guess. Glad its working!

**Comment by requa3r0** [comment]
After a few restarts and further test I realize it does in fact not work

1: The local IP does not answer when localhost has been selected. 
Not on the device or on a PC on the local LAN network

2: KODI can not even see the Threadfin server on localhost, unless you have access the server on localhost in a browser on the device. Then Threadfin anwsers KODI on localhost.

The network code seems to be full of bugs. I will have to give up on Threadfin for now and revert back to xTeVe.

To bad.

Please reopen this issue.

**Comment by PilaScat** [comment]
maybe same problem

**Comment by requa3r0** [comment]
Please reopen this issue. Its NOT soled.

Threadfin states this when installed.

**2024/12/27 15:48:20 [Threadfin] Web Interface:          http://10.13.128.105:34400/web/ | Threadfin is also available via the **other 5 IP's.****

Its not true...Its not working!!!


I just had 2 similar cases.

1: Installed threafin on oracle cloud ampere 64bit arm with no console session.
terminal lynx browser showed Threadfin online on a ip not accessible in any way.

It was almost impossible to connect to the web interface to set the bind IP
I needed to connect with ssh, and setup a manual SOCKS v4 to tab into the local-host ip.

2: Just installed threadfin on a Raspberry pi..connected to a vpn. I did forward 34400 on the vpn NAT.
It was not possible to connect to the actual local ip - only from outside..on the global VPN IP through the NAT setup.

This was never an issue with xTeVe...but Threadfin is terrible..and is not accessible on local-host, or local IP.

The bind address is a special setting, to be used in very special cases...and not something you should set standard.
Threadfin should always answer on local-host and local ip. 

not having access to the web interface by standard..is a huge issue.

Please address this huge issue.

**Comment by Fyb3roptik** [comment]
Please use the discord for support. The software is not broken, your config is wrong. Set your bind IP in the settings.json file to the IP address of the machine
