### ISSUE TITLE
Multiple clients for the same backend connection

### ISSUE THREAD

**Issue by amddeus** [Threadfin/Threadfin#287]
Multiple clients for the same backend connection like Streammaster:
"Multiple clients for the same backend connection: StreamMaster will not start a new backend stream if it is already proxing the same one. Multiple clients can watch the same channel with just one backend active stream."
https://github.com/SenexCrenshaw/StreamMaster

**Comment by Fyb3roptik** [comment]
Use a buffer for that. This already does that
