### ISSUE TITLE
Force HTTPS causes Streams with parameters not working

### ISSUE THREAD

**Issue by Zalatis** [Threadfin/Threadfin#288]
**Describe the bug**
I have a list of streaming links (302 redirect actually) looking like:
`https://example.com/stream?id=FJ48HFH`
Everything works correctly with "forceHttps": false but when turning it on with "forceHttps": true Threadfin actually redirect to 
`https://example.com/stream` it basically remove the stream ID that is present in the source m3u

**Server (please complete the following information):**
- OS Linux - DSM 7
- Arch x86_64
- Threadfin Version and Build [to be found in the Threadfin log]

**To Reproduce**
1. Use m3u with https://example.com/stream?id=FJ48HFH looks like streams
2. Go to 'Settings'
3. Activate 'Force HTTPS'
4. Streams doesn't work (Redirecting to https://example.com/stream

**Expected behavior**
When using Force HTTPS, the stream should redirect to `https://example.com/stream?id=FJ48HFH` not `https://example.com/stream`

**Comment by Fyb3roptik** [comment]
1.1.15 should fix this now

**Comment by Zalatis** [comment]
Stream url with parameters are now working with Force HTTPS.
But it comes with a new bug, when trying to reach a stream url without parameters like so : 
`https://dvr.example.fr/stream/9a75c0154ecafe3c457358a827d1ed34`
It is replaced by : 
`https://dvr.example.fr/stream/9a75c0154ecafe3c457358a827d1ed34?`

And automatically gives us page 404

**Comment by Fyb3roptik** [comment]
Fixed in 1.1.16
