### ISSUE TITLE
 [ERROR] unexpected end of JSON input () - EC: 0

### ISSUE THREAD

**Issue by mayorgergich** [Threadfin/Threadfin#289]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin web not loading.

**Server (please complete the following information):**
- OS Linux Ubuntu
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log] latest

**To Reproduce**
Install via docker using latest tag

**Expected behavior**
Install to provide website access

**Screenshots**
Logs:

2024/06/24 16:43:28 [Threadfin] Version:                1.1 Build: 14
2024/06/24 16:43:28 [Threadfin] Database Version:       0.5.0
2024/06/24 16:43:28 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 2
2024/06/24 16:43:28 [Threadfin] Hostname:               threadfin
2024/06/24 16:43:28 [Threadfin] System Folder:          /home/threadfin/conf/
2024/06/24 16:43:28 [Threadfin] [ERROR] unexpected end of JSON input () - EC: 0
/For help run: /home/threadfin/bin/threadfin -h
2024/06/24 16:43:54 [Threadfin] Version:                1.1 Build: 14
2024/06/24 16:43:54 [Threadfin] Database Version:       0.5.0
2024/06/24 16:43:54 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 2
2024/06/24 16:43:54 [Threadfin] Hostname:               threadfin
2024/06/24 16:43:54 [Threadfin] System Folder:          /home/threadfin/conf/
2024/06/24 16:43:54 [Threadfin] [ERROR] unexpected end of JSON input () - EC: 0

**Additional context**

**Comment by Fyb3roptik** [comment]
are the json files in that location?

**Comment by M1noa** [comment]
try validating the json in an online json validator and see if it tells you the error
