### ISSUE TITLE
Better icon resolution

### ISSUE THREAD

**Issue by albinmedoc** [Threadfin/Threadfin#290]
**Is your feature request related to a problem? Please describe.**
I want to add Threadfin as an Enhanced App in [Heimdall](https://heimdall.site/), I need a icon with better resolution. 
I have made an PR to Heimdall which can be found [here (PR-746)](https://github.com/linuxserver/Heimdall-Apps/pull/746)

**Describe the solution you'd like**
To get an icon with better resolution. Icon should be min width 100px and min height 100px when PNG.
SVG-file would be even better.

**Describe alternatives you've considered**
To drop the development of the Enhanced App for Heimdall.

**Comment by Fyb3roptik** [comment]
I dont have any 100x100 images for it. Just make one its fine

**Comment by albinmedoc** [comment]
Okay, I took the opportunity to make it as SVG. I add them here if you want/need it sometime. 

![threadfin icon](https://github.com/Threadfin/Threadfin/assets/7331299/2c62fb87-4217-46ae-a624-0aaa40a311cc)
![threadfin](https://github.com/Threadfin/Threadfin/assets/7331299/d50cd8d9-64bf-4fc2-b76d-ff5427eff48a)
