### ISSUE TITLE
Export m3u with group-title not working

### ISSUE THREAD

**Issue by pstrejajo** [Threadfin/Threadfin#293]
After getting m3u without group-title (.../m3u/threadfin.m3u), later requests with group-title (.../m3u/threadfin.m3u?group-itle=some-group) provide the same playlist with all the streams.

https://github.com/Threadfin/Threadfin/commit/876ce5728bf55f04af0ca165a18c174576821607 introduced serving already created m3u file, but this prevents using group-title. Probably this should be skipped when group-title is used.

**Comment by Fyb3roptik** [comment]
Fixed in 1.1.16
