### ISSUE TITLE
[Feature Request] Threading

### ISSUE THREAD

**Issue by M1noa** [Threadfin/Threadfin#297]
**Is your feature request related to a problem? Please describe.**
I find the time it takes to "Update database" long and slow..

**Describe the solution you'd like**
If you could enable threading and give Threadfin many cpu threads for tasks it could run a lot faster.

**Additional context**
https://stackoverflow.com/questions/17868419/how-can-my-go-program-keep-all-the-cpu-cores-busy

**Comment by Fyb3roptik** [comment]
You need to shrink your m3u. Or you can try a better processor. I'm not taking any new feature requests at this time
