### ISSUE TITLE
Converting custom LIVE title in Title

### ISSUE THREAD

**Issue by hayrun-st** [Threadfin/Threadfin#30]
My XML TV guide provider adds a very unique tag to the title for live events.  This tag gets stripped out when Threadfin parses it.

The title is as follows: ᴸᶦᵛᵉ

I was told the special characters used here are: 
ᴸ = 7480, ᶦ = 7590, ᵛ = 7515, ᵉ = 7497

I'm not 100% sure what the numbers correspond to as ansi characters only go up to 255.

I'd love for there to be an option to replace specific information like ᴸᶦᵛᵉ with custom text or xml tag of our own choosing.  At worst case, I'd like to either see it left in or changed to something like ***LIVE*** so that I can take action on it to record.

**Comment by Fyb3roptik** [comment]
I strip those out on purpose since it shows as boxes on Roku and thus should not be present. I can however add some functionality to the PPV dummy data to allow for custom text.

**Comment by hayrun-st** [comment]
That would be amazing.  I use the docker version of this and will be tracking whenever it's committed.  Thank you.

**Comment by Fyb3roptik** [comment]
This will be out in 0.9.20

**Comment by hayrun-st** [comment]
I took a look at the latest version but not sure how exactly I should use this?  What am I missing?
