### ISSUE TITLE
Tuner Status / Client Status

### ISSUE THREAD

**Issue by vajonam** [Threadfin/Threadfin#303]
**Is your feature request related to a problem? Please describe.**
Status of tuners and clients server

**Describe the solution you'd like**
- It will be nice to see how many active tuners are for each playlist are active. 
- show how many clients are connected to each playlist

**Describe alternatives you've considered**
- tailing the logs is the best way for me to find this out. Assuming a connection has happened in the recent past. 

**Additional context**
Awesome work for now!

**Comment by Fyb3roptik** [comment]
It now shows you # of connected clients AND # of connections to provider
