### ISSUE TITLE
Force HTTPs isnt working as expected.

### ISSUE THREAD

**Issue by shorty789** [Threadfin/Threadfin#304]
**Describe the bug**
Force HTTPS is incorrectly applying to outbound playlist connections.

With force HTTPs on, threadfin tries to connect to playlist using the wrong port.

My playlist is usually located on x.x.x.x:8080, however when I enable HTTPs within threadfin after running it through my reverse proxy, every time i attempt to load the playlist, it tries to communicate on x.x.x.x:443.

It would appear that the forcing https applies to outbound connections as well as inbound as it currently stands.

When I check my playlist, it still shows as :8080 being configured within the threadfin settings.

I would have expected the playlist to still be read by threadfin as HTTP, but then pushed to clients as HTTPs.

**Server (please complete the following information):**
- OS - Ubuntu (Installed in docker container)
- Intel 64 Bit
- Threadfin Version and Build [1.1 (16)]

**To Reproduce**
Access threadfin itself via a reverse proxy
Add a playlist located on a web server presenting on a non standard port, but using HTTP. (for me, port 8080)
Force HTTPs within threadfin settings
Attempt to view a channel through any client once playlist has updated.

**Expected behavior**
I would have expected threadfin to access the playlist on http://:8080 rather than forced through https://:443, before buffering it and passing out out to clients that are connected to threadfin via https://:443.

**Additional context**
While this doesnt behave as I would have expected, if this does happen to be intended behaviour, please advise me accordingly and I will look to try and adjust my setup to reflect.

![image](https://github.com/user-attachments/assets/ae0e9b14-0fa5-4066-8534-8ee3931b2c5b)

![image](https://github.com/user-attachments/assets/f634ffdf-7e01-4873-af95-2712f2176c84)

**Comment by Fyb3roptik** [comment]
Https uses 443 that's how that works. This is how it should be

**Comment by shorty789** [comment]
No problem, thanks for clarifying, I didnt know if it would work in a
similar manner to a reverse proxy setup, I would have preferred it if I had
the ability to amend the urls within the M3U that threadfin creates to be
https, while still retaining the outbound connection from threadfin to the
server on :8080. While it makes sense from the client -> server perspective
everything would be https, I dont think it really needs to be for the
server->server connection which would be local only and never accessed by
any other device.

**Comment by Fyb3roptik** [comment]
ALL URLS IN HTTPS MUST BE HTTPS. This is forced by all browsers now too. You cannot and should not have a mix of HTTP and HTTP
