### ISSUE TITLE
Set Threadfin URL

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#306]
Hi, 

I do not use image caching but i would still like to set the url which is used by threadfin in the m3u - right now it seems like that threadfin is putting the url in the m3u based on the last url used to access threadfin which sometimes works, sometimes it does not. 
I would like to just set the external url of threadfin (reverse proxy) which is then populated in the m3u.

**Comment by Fyb3roptik** [comment]
You need to set the bind ip in settings. Threadfin will always use whatever domain you set in the URL for the m3u/epg
