### ISSUE TITLE
Plex Intergration Failed

### ISSUE THREAD

**Issue by Ollboll26** [Threadfin/Threadfin#309]
I have attempted everything and put countless hours into tying to get Threadfin to function with Plex.
Unfortunately with no luck. I am able to get Plex to import the channels and EPG data into the DVR, but when attempting to stream, it is unable to start a transcode session correctly. I'm unsure of where the issue is coming from.
Some assistance would be greatly appreciated.

Jul 28, 2024 20:14:14.526 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Starting a new rolling subscription for session 6950d1d65ece9482-com-plexapp-android channel 2.
Jul 28, 2024 20:14:14.535 [140732701077728] Fehlersuche — [Req#18ae1] Activity: registered new activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - "Refreshing Sub"
Jul 28, 2024 20:14:14.535 [140732701077728] Fehlersuche — [Req#18ae1] Activity: updated activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - completed 0.0% - Refreshing Sub
Jul 28, 2024 20:14:14.535 [140732701077728] Fehlersuche — [Req#18ae1] Activity: updated activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - completed 0.0% - Refreshing Sub
Jul 28, 2024 20:14:14.535 [140732701077728] Fehlersuche — [Req#18ae1] Activity: updated activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - completed 0.0% - Refreshing Sub
Jul 28, 2024 20:14:14.536 [140732701077728] Fehlersuche — [Req#18ae1] Activity: updated activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - completed 0.0% - Refreshing Sub
Jul 28, 2024 20:14:14.536 [140732701077728] Fehlersuche — [Req#18ae1] Activity: registered new activity 422939a9-2536-4b22-abb7-ba6c87875396 - "Processing subscriptions"
Jul 28, 2024 20:14:14.536 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Scheduling subscriptions.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Initialized 1 schedulers.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Starting with 0 grabs, scheduled 0 active ones preemptively.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Partitioning, step one, let's compute an absolute ordering.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1]  DVR:NewSchedule: Between 2024-07-28 20:14:14 and 2024-07-28 20:19:14 on channel 2: 'Live TV - Session'
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Initial partitioning completed with 1 partitions.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Partitioning completed with 1 partitions.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: PARTITION of size 1.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1]  DVR:NewSchedule:    Between 2024-07-28 20:14:14 and 2024-07-28 20:19:14 on channel 2: 'Live TV - Session'
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: After processing the partition, we have 1 alternate realities.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: We computed 1 alternative realities in 0 ms.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: The winning schedule had score: 10 and 0 conflicts.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1]  DVR:NewSchedule: device 0 tuner 0 airing 0 between 2024-07-28 20:14:14 and 2024-07-28 20:19:14 on channel 2: 'Live TV - Session'
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Starting grab immediately for 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2 and we're 0 seconds in already.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Scheduled all subscriptions in 1 ms.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Activity: Ended activity 422939a9-2536-4b22-abb7-ba6c87875396.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: There are 1 active grabs at the end.
Jul 28, 2024 20:14:14.538 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Waiting for media grab to start.
Jul 28, 2024 20:14:14.539 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Starting operation for 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2.
Jul 28, 2024 20:14:14.540 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Activity: registered new activity 39ef6d8b-8d06-4029-bd3f-aa0f72470e29 - "Recording"
Jul 28, 2024 20:14:14.540 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: HDHomerun starting a media grab on device device://tv.plex.grabbers.hdhomerun/2024-07-63CX-UAA8L3 (Golang Threadfin, supported) tuner 0.
Jul 28, 2024 20:14:14.540 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Creating custom segmented recorder for grab for channel 2
Jul 28, 2024 20:14:14.540 [140732709630176] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/HCl#147] HTTP requesting GET http://172.19.0.4:34400/discover.json
Jul 28, 2024 20:14:14.540 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/HCl#148] HTTP requesting GET http://172.19.0.4:34400/lineup.json
Jul 28, 2024 20:14:14.543 [140732709630176] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/HCl#149] HTTP requesting GET http://172.19.0.4:34400/lineup_status.json
Jul 28, 2024 20:14:14.593 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] DVR:Segmenter: Creating a new recorder for http://172.19.0.4:34400/stream/fd47c41ef846d43b7dd845bcb36c41b5.
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Setting timer to stop grab of 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2 in 300 seconds.
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Waiting for a tuner on device://tv.plex.grabbers.hdhomerun/2024-07-63CX-UAA8L3 (1 available) for at most 300 seconds.
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Allocated a tuner on device://tv.plex.grabbers.hdhomerun/2024-07-63CX-UAA8L3 (0 left)
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] We're going to try to auto-select an audio stream for account 1.
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Selecting best audio stream for part ID -1 (language: en)
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] We're going to try to auto-select a subtitle for account 1.
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Audio Stream: -1, Subtitle Stream: -1
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: Selected protocol hls; container: mpegts
Jul 28, 2024 20:14:14.594 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Unable to find title for item of type 5
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: analyzing media item -1
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: : no direct play video profile exists for http/mpegts/
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: : no direct play video profile exists for http/mpegts//
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: : codec is unavailable for analysis
Jul 28, 2024 20:14:14.594 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: : codec is unavailable for analysis
Jul 28, 2024 20:14:14.595 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Unable to find title for item of type 5
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] MDE: : selected media 0 / -1
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Cleaning directory for session 26e2ecc7-b769-44dc-aa41-91d31c2ebd64 ()
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Starting a transcode session 26e2ecc7-b769-44dc-aa41-91d31c2ebd64 at offset -1.0 (state=3)
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Streaming Resource: Added session 0x7ffedf8141d8:26e2ecc7-b769-44dc-aa41-91d31c2ebd64
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/JobRunner] Job running: FFMPEG_EXTERNAL_LIBS='/config/Library/Application\ Support/Plex\ Media\ Server/Codecs/63e2f72-c89f34deceb2628d2484565f-linux-aarch64/' X_PLEX_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "/usr/lib/plexmediaserver/Plex Transcoder" -noaccurate_seek -ignore_unknown -scan_all_pmts -1 -rw_timeout 30000000 -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -fflags +discardcorruptts+fillwallclockdts -probesize 20000000 -i http://172.19.0.4:34400/stream/fd47c41ef846d43b7dd845bcb36c41b5 -map "0:V?" -codec:V copy -map "0:a?" -codec:a copy -map "0:s?" -codec:s copy -break_non_keyframes 1 -segment_format mpegts -f ssegment -individual_header_trailer 0 -segment_time 1 -segment_start_number 0 -segment_time_delta 0.25 -segment_list "http://127.0.0.1:32400/video/:/transcode/session/26e2ecc7-b769-44dc-aa41-91d31c2ebd64/6b642fbd-ca06-487b-b80b-8255c9992cef/manifest?X-Plex-Http-Pipeline=infinite" -segment_list_type csv -segment_list_size 5 -segment_list_separate_stream_times 1 -segment_list_unfinished 1 -max_delay 5000000 -map_metadata -1 -map_chapters -1 "media-%05d.ts" -y -nostats -loglevel quiet -loglevel_plex error -xioerror -progressurl http://127.0.0.1:32400/video/:/transcode/session/26e2ecc7-b769-44dc-aa41-91d31c2ebd64/6b642fbd-ca06-487b-b80b-8255c9992cef/progress
Jul 28, 2024 20:14:14.595 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/JobRunner] In directory: "/tmpfs/Transcode/Sessions/plex-transcode-26e2ecc7-b769-44dc-aa41-91d31c2ebd64"
Jul 28, 2024 20:14:14.596 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android/JobRunner] Jobs: Starting child process with pid 522
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] TranscodeSession: session failed while waiting for duration
Jul 28, 2024 20:14:16.710 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Failed to start session.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Recorder: Unable to create transcode session or session failed to start.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Killing job.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Signalling job ID 522 with 9
Jul 28, 2024 20:14:16.710 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Recorder: Error 16 (Recording failed. Please check your tuner or antenna.) starting the record, shutting things down.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Cleaning up rolling grab for channel 2.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Recorder: No more consumers, stopping.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Recorder: Asked to stop recording 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2.
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Freed a tuner on device://tv.plex.grabbers.hdhomerun/2024-07-63CX-UAA8L3 (now 1 available)
Jul 28, 2024 20:14:16.710 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Operation for 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2 completed with status error (Recording failed. Please check your tuner or antenna.)
Jul 28, 2024 20:14:16.710 [140732701077728] Fehler — [Req#18ae1] Subscription: Rolling media grab failed to start.
Jul 28, 2024 20:14:16.711 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Cancelling grabs for subscription 161: 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2
Jul 28, 2024 20:14:16.711 [140732701077728] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Cancelling operation for 'Live TV - Session 6950d1d65ece9482-com-plexapp-android' on channel 2 with status cancelled.
Jul 28, 2024 20:14:16.711 [140732701077728] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Operation was active, stopping recorder.
Jul 28, 2024 20:14:16.711 [140732701077728] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] We've cancelled the grab with 298 seconds remaining.
Jul 28, 2024 20:14:16.712 [140732701077728] Fehlersuche — [Req#18ae1] Activity: registered new activity b1b72aab-02c9-4e8d-9d52-175a7275aaf5 - "Processing subscriptions"
Jul 28, 2024 20:14:16.712 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Scheduling subscriptions.
Jul 28, 2024 20:14:16.715 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Activity: Ended activity 39ef6d8b-8d06-4029-bd3f-aa0f72470e29.
Jul 28, 2024 20:14:16.715 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Grabber: Cleaning up rolling grab for channel 2.
Jul 28, 2024 20:14:16.715 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Recorder: No more consumers, stopping.
Jul 28, 2024 20:14:16.715 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Starting media grab failed.
Jul 28, 2024 20:14:16.715 [140732705370336] Fehler — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Unknown metadata type: 
Jul 28, 2024 20:14:16.715 [140732705370336] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Asked for unknown type: -1
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Initialized 1 schedulers.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Starting with 0 grabs, scheduled 0 active ones preemptively.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Partitioning, step one, let's compute an absolute ordering.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Initial partitioning completed with 0 partitions.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: Partitioning completed with 0 partitions.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: We computed 1 alternative realities in 0 ms.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] DVR:NewSchedule: The winning schedule had score: 0 and 0 conflicts.
Jul 28, 2024 20:14:16.716 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: Scheduled all subscriptions in 3 ms.
Jul 28, 2024 20:14:16.717 [140732701077728] Fehlersuche — [Req#18ae1] Activity: Ended activity b1b72aab-02c9-4e8d-9d52-175a7275aaf5.
Jul 28, 2024 20:14:16.717 [140732654039264] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Activity: updated activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f - completed 100.0% - Refreshing Sub
Jul 28, 2024 20:14:16.718 [140732701077728] Fehlersuche — [Req#18ae1] Subscription: There are 0 active grabs at the end.
Jul 28, 2024 20:14:16.718 [140732654039264] Fehlersuche — [Req#18ae1/Grabber/2-6950d1d65ece9482-com-plexapp-android] Activity: Ended activity 166f35d6-c4b6-45cf-967f-a1a9d1d3045f.

**Comment by Fyb3roptik** [comment]
I need threadfin output not Plex. Also is it mpegts? Plex doesn't support HLS

**Comment by Ollboll26** [comment]
This is my Threadfin log. The direct stream works in VLC, but it seems Threadfin is failing to pipe the file with an FFMPEG error and Plex is trying to read it as HLS like you stated and of course its failing.
Any Ideas


2024-07-29 10:36:22 [Threadfin] Buffer:                 true [ffmpeg]
2024-07-29 10:36:22 [Threadfin] Buffer Size:            1024 KB
2024-07-29 10:36:22 [Threadfin] Channel Name:            ABC TV
2024-07-29 10:36:22 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
2024-07-29 10:36:24 [Threadfin] Streaming Status:       Playlist: Melbourne - Tuner: 1 / 3
2024-07-29 10:36:24 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
2024-07-29 10:36:24 [Threadfin] Streaming URL:          https://c.mjh.nz/abc-vic.m3u8
2024-07-29 10:36:24 [Threadfin] FFMPEG:                 Processing data
2024-07-29 10:36:24 [Threadfin] Streaming Status:       Receive data from FFMPEG
2024-07-29 10:36:24 [Threadfin] FFMPEG log:             /usr/bin/ffmpeg: error while loading shared libraries: libavdevice.so.59: cannot open shared object file: No such file or directory
2024-07-29 10:36:24 [Threadfin] Streaming Status:       Client has terminated the connection
2024-07-29 10:36:24 [Threadfin] Streaming Status:       Channel:  ABC TV (Clients: 0)
2024-07-29 10:36:24 [Threadfin] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
2024-07-29 10:36:24 [Threadfin] Streaming Status:       Playlist: Melbourne - Tuner: 0 / 3
2024-07-29 10:36:25 [Threadfin] Streaming Status:       Channel:  ABC TV - No client is using this channel anymore. Streaming Server connection has ended
2024-07-29 10:36:25 [Threadfin] Streaming Status:       Playlist: Melbourne - Tuner: 0 / 3

**Comment by Fyb3roptik** [comment]
Plex doesnt support HLS. You cant say it works because it works in VLC. Everything works in VLC lol. You need to have ffmpeg convert it to mpegts. The default in Threadfin should suffice for this.

**Comment by Fyb3roptik** [comment]
Your error indicates it cant find a library.

https://stackoverflow.com/questions/12901706/ffmpeg-error-in-linux

Check this for your answer. I moved away from FFMPEG to VLC a long time ago
