### ISSUE TITLE
IP address listening specification

### ISSUE THREAD

**Issue by redairforce** [Threadfin/Threadfin#31]
If I am using a docker container with a VPN interface and an internal interface, I can hit http://internalip:34400/web no problem. I can even find it in Plex with the internal ip. As soon as Plex asks to pull a stream through ffmpeg, it is pulling it from http://vpnip/34400. That interface isn't accessible via Plex.

Plex adds tuner just fine. 
Tuner status
Channels
(292)
IP address
http://172.28.0.2:34400
Model
Threadfin

Plex Error upon trying to run stream:
SSDP: Error parsing device schema for http://192.168.1.16:34400/device.xml

This is specifically difficult because I need to run a MacVLAN interface for my VPN container. That interface isn't accessible via the host.

**Comment by Fyb3roptik** [comment]
A couple of questions:

1. Are you using a buffer?
2. If so which one?
3. Using the internal IP SHOULD make threadfin use that IP in the XML/M3U. View those and see if that is the case?

**Comment by Fyb3roptik** [comment]
Please re-open when youre ready
