### ISSUE TITLE
Feature Request: Add channel ID to Mapping window

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#310]
**Is your feature request related to a problem? Please describe.**
Yes to make it easier to not duplicate a backup channel with the primary channel

**Describe the solution you'd like**
Add the channel ID under the  channel name within the Mapping Window (see attachment)

**Describe alternatives you've considered**
Name primary channel within the m3u as something to remind user that channel is the primary

**Additional context**
See example addition of channel ID to mapping window.

**Current**:
![image](https://github.com/user-attachments/assets/2dba553f-faf3-46b0-9077-a600aaf7514a)

**Requested addition**:
![image](https://github.com/user-attachments/assets/19c457b1-e0c7-4588-90bb-cfb70cfd94d6)

**Comment by Fyb3roptik** [comment]
I changed it to show tvg-id as well as the provider id for the channel in parenthesis
