### ISSUE TITLE
Backup Channels

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#311]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have been reading about the backup channels on this discord and am still having issues getting them to work. I have the primary and backups under the same m3u and I have the settings listed below along with the log.

**Server (please complete the following information):**
- OS Windows 11
- Intel 64 Bit
- Threadfin Version 1.1 (16)

**To Reproduce**
1. Add extra streams to m3u for specific channels and save them in the same m3u
2. Add a primary channel
3. Set the extra streams of the same channel to inactive
4. Add the extra streams as a backup to the primary

**Expected behavior**
If the primary channel fails, such as 404, Threadfin moves to the first backup channel. If that one fails, it moves to the next one, etc.

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: Android TV
 - Browser: IPTV Pro
 - Version: 8.0.7

**Additional context**
Channel settings:
![image](https://github.com/user-attachments/assets/308ec1d9-afcb-4271-905a-21c78b171eab)

Threadfin settings
![image](https://github.com/user-attachments/assets/7134067c-3532-4ad7-ac24-11128a4e97df)

Logs:
![image](https://github.com/user-attachments/assets/9a717e66-f15e-4442-88d7-bf14ba544d01)

**Comment by Fyb3roptik** [comment]
I'll check this out as it should be working

**Comment by mme89** [comment]
Didn't want to open a new issue, cause I think it's related. 

If I got 2 m3u playlists, both set Tuner/Streams to 1. Both playlists have the exact same channels.
So I map all channels from playlist A and set all channels from playlist B as backup channels. 

Now I open channel A and of course the Tuner for playlist A is occupied. I thought Threadfin would now switch to playlist B for a new channel request. Or is Threadfin only switching when the source is not reachable or giving an error back?

**Comment by Fyb3roptik** [comment]
Oh I see the issue. Backup channels only supports 1 playlist unfortunately. I will be adding better functionality for this in my new plex replacement Kernel Media Server

**Comment by theqkash** [comment]
@Fyb3roptik so no way to make backup channels for multiple m3u's working here in threadin?

**Comment by Fyb3roptik** [comment]
It's out of scope at the moment. A lot of these features will be in Kernel once it's at 1.0 so I don't want to have to do it twice
