### ISSUE TITLE
Can't bulk auto add XMLTV Channels

### ISSUE THREAD

**Issue by bajire72** [Threadfin/Threadfin#313]
Hello,

I have a problem with my Threadfin, in the mapping section i can't auto add the XMLTV channels with the Bulk Edit...
When i want to change the channel it change only for the one i click...

I have like 200 channels, what can i do ?

**Comment by Fyb3roptik** [comment]
You can set the setting for default and then you'll never have to set it. It will keep your channels active

**Comment by kinduff** [comment]
@Fyb3roptik hello, where can I find the setting for this default?
