### ISSUE TITLE
Issue adding M3U Playlist from a local file

### ISSUE THREAD

**Issue by john22savage** [Threadfin/Threadfin#316]
**Describe the bug**
When I add a playlist and xmltv file from a local file and then create a filter to display the channels, when a go to Mapping, it is adding "     ,"  (quotes there to show how many spaces in front of the comma) in front of the Channel Name. I'm attaching a sample M3U and XMLTV file.

**Server (please complete the following information):**
- OS Windows
- Arch Intel 64 Bit
- Threadfin Version 1.1 (16)

**To Reproduce**
1. Add Playlist test.m3u
2. Add XMLTV file test.xmltv
3. Create M3U Group Title Filter for Group Title:  TEST-JS. Add an Include field of:  TEST
4. Go to Mapping
5. The Channel name has added 5 spaces and a comma in front of the Channel Name

**Expected behavior**
I'd expect the Channel Name to be exactly what is in the M3U file

**Screenshots**
![image](https://github.com/user-attachments/assets/0534df6f-9c17-4598-8c9d-089c61713dbd)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, but it is also happening on Windows 10 Pro
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (64-bit)

I cannot upload the m3u and xmltv files so I'm adding them here.

M3U File:
*********************************BEGIN***********************************
#EXTM3U
#EXTINF:-1, tvg-chno="9022" tvg-id="9022" tvg-name="TEST CHANNEL 01" tvg-logo="https://www.creativefabrica.com/wp-content/uploads/2021/10/22/Iptv-Badge-icon-logo-Neon-icon-Vector-Graphics-19116059-1-1-580x387.jpg" group-title="TEST-JS",TEST CHANNEL 01
http://someURL.com/channel9022.ts
#EXTINF:-1, tvg-chno="9009" tvg-id="9009" tvg-name="TEST CHANNEL 02" tvg-logo="https://www.creativefabrica.com/wp-content/uploads/2021/10/22/Iptv-Badge-icon-logo-Neon-icon-Vector-Graphics-19116059-1-1-580x387.jpg" group-title="TEST-JS",TEST CHANNEL 02
http://someURL.com/channel9009.ts
*********************************END*************************************

XMLTV File:
*********************************BEGIN***********************************
<?xml version="1.0" encoding="utf-8"?>
<tv generator-info-name="JohnsSports" source-info-name="JohnsSports">
  <channel id="9022">
    <display-name>TEST CHANNEL 01</display-name>
    <icon src="https://www.creativefabrica.com/wp-content/uploads/2021/10/22/Iptv-Badge-icon-logo-Neon-icon-Vector-Graphics-19116059-1-1-580x387.jpg" ></icon>
  </channel>
  <channel id="9009">
    <display-name>TEST CHANNEL 02</display-name>
    <icon src="https://www.creativefabrica.com/wp-content/uploads/2021/10/22/Iptv-Badge-icon-logo-Neon-icon-Vector-Graphics-19116059-1-1-580x387.jpg" ></icon>
  </channel>
  <channel id="ADumy">
    <display-name>ADummy</display-name>
    <icon src="" ></icon>
  </channel>
   <programme channel="ADummy" start="20240801000000 -0500" stop="20240801030000 -0500">
	  <title lang="en">ADummy</title>
	  <desc lang="en">ADummy</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801000000 -0500" stop="20240801030000 -0500">
	  <title lang="en">TEST CHANNEL 01</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801030000 -0500" stop="20240801060000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801060000 -0500" stop="20240801090000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801090000 -0500" stop="20240801120000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801120000 -0500" stop="20240801150000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801150000 -0500" stop="20240801180000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801180000 -0500" stop="20240801210000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240801210000 -0500" stop="20240801240000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802000000 -0500" stop="20240802030000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802030000 -0500" stop="20240802060000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802060000 -0500" stop="20240802090000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802090000 -0500" stop="20240802120000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802120000 -0500" stop="20240802150000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802150000 -0500" stop="20240802180000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802180000 -0500" stop="20240802210000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240802210000 -0500" stop="20240802240000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803000000 -0500" stop="20240803030000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803030000 -0500" stop="20240803060000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803060000 -0500" stop="20240803090000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803090000 -0500" stop="20240803120000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803120000 -0500" stop="20240803150000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803150000 -0500" stop="20240803180000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803180000 -0500" stop="20240803210000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9022" start="20240803210000 -0500" stop="20240803240000 -0500">
	  <title lang="en">TEST CHANNEL 01 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 01 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801000000 -0500" stop="20240801030000 -0500">
	  <title lang="en">TEST CHANNEL 02</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801030000 -0500" stop="20240801060000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801060000 -0500" stop="20240801090000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801090000 -0500" stop="20240801120000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801120000 -0500" stop="20240801150000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801150000 -0500" stop="20240801180000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801180000 -0500" stop="20240801210000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240801210000 -0500" stop="20240801240000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-01 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802000000 -0500" stop="20240802030000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802030000 -0500" stop="20240802060000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802060000 -0500" stop="20240802090000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802090000 -0500" stop="20240802120000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802120000 -0500" stop="20240802150000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802150000 -0500" stop="20240802180000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802180000 -0500" stop="20240802210000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240802210000 -0500" stop="20240802240000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-02 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803000000 -0500" stop="20240803030000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803030000 -0500" stop="20240803060000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803060000 -0500" stop="20240803090000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803090000 -0500" stop="20240803120000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803120000 -0500" stop="20240803150000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803150000 -0500" stop="20240803180000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803180000 -0500" stop="20240803210000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
   <programme channel="9009" start="20240803210000 -0500" stop="20240803240000 -0500">
	  <title lang="en">TEST CHANNEL 02 - NO EVENT</title>
	  <desc lang="en">TEST CHANNEL 02 - NO EVENT</desc>
	  <category lang="en">Sports</category>
	  <category lang="en">Series</category>
	  <episode-num system="original-air-date">2024-08-03 00:00:00</episode-num>
	  <icon height="" src="" width=""></icon>
	  <credits></credits>
	  <video></video>
	  <date></date>
	  <new></new>
  </programme>
</tv>
*********************************END*************************************

**Comment by Fyb3roptik** [comment]
Your m3u is not properly coded. You have a comma after #EXTINF: which should not be there. That is why it shows

**Comment by Fyb3roptik** [comment]
It should be `#EXTINF:` not `#EXTINF,`
