### ISSUE TITLE
Some channels are not playing

### ISSUE THREAD

**Issue by mrepetto-certx** [Threadfin/Threadfin#317]
I'm trying to play the channels or RAI (an Italian provider) and I'm always getting the same error:
![image](https://github.com/user-attachments/assets/dd9b9749-2ad2-4700-acf2-1af59458fdbe)

The link in the m3u is: `http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=7&forceUserAgent=raiplayappletv`

Could it be the geo-block? I do not think so as I'm able to play another provider who geo-blocks it without any problem.
https://live03-col.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/manifest.mpd

I tried to switch to vlc, but still, all RAI's channels are not playing, and I'm in Italy.

**Comment by purplescorpion1** [comment]
If they don't play in VLC they are not going to work in threadfin. Threadfin will not magically make your streams work and are not responsible for your provider issues

But here is a hint - Where did you get the stream from? You will probably need a user agent and a referer (the latter is not supported in threadfin)
If you just found the link floating around the internet and not actually working in a video player the chances are its dead

**Comment by mrepetto-certx** [comment]
Thank you, @purplescorpion1, for the quick reply! What puzzles me is that in Jellyfin, the stream works flawlessly. But you are probably right; it might be because of the user agent. I got the link from here https://github.com/Tundrak/IPTV-Italia/blob/main/iptvitaplus.m3u

So, there is no way to enforce the user agent in Threadfin?

**Comment by purplescorpion1** [comment]
Its in the settings. You can add your own user agent

**Comment by mrepetto-certx** [comment]
I tried, but nope, it does not work either. I think the problem might be that it is a relinker and not the actual stream file. If I put the link in the browser, I get the following m3u:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="ita",NAME="Italiano",DEFAULT=YES,AUTOSELECT=YES,URI="itarai1_160/chunklist_ao.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="V.O",NAME="Lingua Originale",DEFAULT=NO,AUTOSELECT=YES,URI="engrai1_160/chunklist_ao.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="des",NAME="Audiodescrizione",DEFAULT=NO,AUTOSELECT=YES,URI="desrai1_160/chunklist_ao.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5689632,CODECS="avc1.640033,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac"
rai1_5000/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5689632,CODECS="avc1.77.42",URI="rai2_5000/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3940630,CODECS="avc1.4d402a,mp4a.40.2",RESOLUTION=1600x900,AUDIO="aac"
rai1_3600/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3940630,CODECS="avc1.77.42",URI="rai2_3600/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2793078,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac"
rai1_2400/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2793078,CODECS="avc1.77.42",URI="rai1_2400/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2137033,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=1024x576,AUDIO="aac"
rai1_1800/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2137033,CODECS="avc1.77.42",URI="rai1_1800/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1365331,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=768x432,AUDIO="aac"
rai1_1200/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1365331,CODECS="avc1.77.31,mp4a.40.2",URI="rai1_1200/chunklist.m3u8?baseuri=%2Fraiuno1%2Fhls%2F&tstart=0&tend=1722881405&tk2=e98261a0020464d25780615c2dbed442a5ba48b06bb6a55b778b9dca0823eb4e"
```

**Comment by purplescorpion1** [comment]
I have tested the stream link 

You can copy and paste this into an txt file and save as m3u and it plays in VLC
```
#EXTM3U
#EXTINF:-1 tvg-id="Rai1.it" tvg-chno="1" tvg-logo="https://cdn.jsdelivr.net/gh/Tundrak/IPTV-Italia/logos/rai1.png" group-title="Rai",Rai 1
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=7&forceUserAgent=raiplayappletv
```

use referer
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

It is geoblocked to Italy else you get a screen saying its only available in Italy

**Comment by mrepetto-certx** [comment]
Indeed, it works on my local installation of VLC. But it does not if I put it on Threadfin with agent `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0` set Stream Buffer to VLC and use input as HDHomeRun server into Jellyfin. 

From Threadfin I get:
![image](https://github.com/user-attachments/assets/c910a9f3-817d-419f-92c3-bad0d0559594)

**Comment by mrepetto-certx** [comment]
I'm assuming it will only work with VLC and not FFMPEG? I'm just saying cause I'm using hardware acceleration on FFMPEG.

**Comment by purplescorpion1** [comment]
try the stream link as just

http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803

And you can use FFMPEG I assume

**Comment by Fyb3roptik** [comment]
You probably have to use mpegts. I bet jellyfin doesn't support dash or HLS. You have a dash feed.

**Comment by Fyb3roptik** [comment]
Also I've had way better luck with VLC than with ffmpeg. Just make sure it's using cvlc and not vlc

**Comment by Fyb3roptik** [comment]
You need to set the $DISPLAY to a value for your GPU. Typically just setting `export DISPLAY=:0` will do it. Or in docker set that as an environment variable

**Comment by mrepetto-certx** [comment]
I set it as an env variable but I still get:
![image](https://github.com/user-attachments/assets/5f786544-4773-4d2e-8dc3-c57afb4780db)

The display is set correctly in the container
![image](https://github.com/user-attachments/assets/51e5687b-bd84-4dc1-8355-f4003ead2222)

**Comment by Fyb3roptik** [comment]
no it needs to be `:0` not `0`

**Comment by mrepetto-certx** [comment]
Oh my bad. Set to :0 and I still get:

![image](https://github.com/user-attachments/assets/b21d5b02-3d09-4a2d-814b-d9eccfee513a)

**Comment by Fyb3roptik** [comment]
Hop onto our Discord please (link is in README). We can troublehsoot this there, this is not a threadfin issue
