### ISSUE TITLE
I think something in the new update broke my setup

### ISSUE THREAD

**Issue by jjf3** [Threadfin/Threadfin#318]
My threadfin has been working flawlessly for months until I updated it today. 

I think my problem seems to be that docker automatically is putting my threadfin ip at 172.17.0.2 where it needs to be in the 192.168.1.153 ip address. I cannot seem to get this fixed. I don't recall seeing that in the logs before this update and I have no idea how to route it back. 

I am using synology and containermanager. My ports are set as 34400 -> 34400. Everything else is standard. When I try to go to my IP I get 404 error. 

What is the right way to fix this? I tried to fix this in dockerd.json, but my lack of networking knowledge has only gotten me so far. Any help is appreciated. I can take screenshots if needed.

**Comment by purplescorpion1** [comment]
set 
"bindIpAddress": "192.168.1.153",

in settings.json

**Comment by jjf3** [comment]
Thanks for the quick reply. I cannot seem to locate the settings.json file. Maybe my setup is borked, but where should it normally be?? I only see dockerd.json.

**Comment by purplescorpion1** [comment]
I don't use docker but I presume it will be where ever your mount folders are

If you can access the web UI via 172.17.0.2 or what ever threadfin tells you its running on you can change it in the settings page under blindip

**Comment by jjf3** [comment]
Ok so I have /volume2/Data2/home/threadfin/bin
 /volume2/Data2/home/threadfin/cache
 /volume2/Data2/home/threadfin/conf

but no file in any of those folders.

**Comment by purplescorpion1** [comment]
When you start threadfin at least in non docker it tells you the location of settings.json in the console window

[Threadfin] Load Settings:  ---- location is here

Since I don't use docker I can't help any further if you can't access the web UI or find the required file

**Comment by jjf3** [comment]
Hmm. Apparently it should be in /volume2/Data2/home/threadfin/conf/settings.json, but it has not been created there.

**Comment by Fyb3roptik** [comment]
I will be adding an ENV variable option for this when i push out the next update today. `THREADFIN_BIND_IP_ADDRESS` or if doing command line `-bind 0.0.0.0`

**Comment by Fyb3roptik** [comment]
Check the Dockerfile for the change. Now you can simply set the bind ip address as an env variable

**Comment by frazzyfin** [comment]
I'm running Threadfin version 1.2 Build: 0 in docker and still encountering this problem.

I have set `THREADFIN_BIND_IP_ADDRESS` in the docker compose file which didn't work.

I have set `"bindIpAddress"` which also didn't work.

Threadfin continues to bind to random IP 172.19.0.41 in both cases.

**Comment by hobhobuk** [comment]
Same here, using windows, so no setting file.  inputted bind IP, still does not work, yet says its working on 9 IPs.. if only it worked on one that actually was correct.
