### ISSUE TITLE
Restream Online Radio Station

### ISSUE THREAD

**Issue by gltich** [Threadfin/Threadfin#320]
I created a m3u with a online radio station stream, after some tweaking, it works but freezes the screen of my prior channel when played. So I'm listening to online music with a frozen picture of my last watched channel.

Since I'm sure you can't get the metadata of the radio station passthrough the stream. I'd suggest a channel background (wallpaper) jpg or png. In addition to this feature, All my other channels work great with using ffmpeg. This Radio stream doesn't play well with ffmpeg .mp3 or other similar extension streams. Adding a setting to specify I can use this channel stream buffer for vlc would be helpfull.

I've tried with vlc and it works great probably due to it handling streams. 
I've tried changing my stream buffer setting to vlc, but my Video channels struggle or don't do as great as with ffmpeg. (Need stream buffer for more tuner streams)
My iptv app (tivimate) I'd have to resort to send that specific radio stream channel to open vlc app in android tv and playing it then.

**Comment by Fyb3roptik** [comment]
Threadfin supports only mpegts or hls. This seems way out of scope
