### ISSUE TITLE
Unable to start streams in 1.1.18 

### ISSUE THREAD

**Issue by vajonam** [Threadfin/Threadfin#322]
I unable to start a stream any more.

```
threadfin         | 2024/08/05 15:22:17 [Threadfin] Streaming Status:       Channel: UK SKY SPORTS GOLF HD (Clients: 1)
threadfin         | 2024/08/05 15:22:19 [Threadfin] FFMPEG log:             [h264 @ 0x5575afd01d40] non-existing SPS 0 referenced in buffering period
threadfin         | 2024/08/05 15:22:19 [Threadfin] FFMPEG log:             Last message repeated 1 times
threadfin         | 2024/08/05 15:22:19 [Threadfin] FFMPEG log:             [NULL @ 0x5575afd12e40] Unable to find a suitable output format for 'title=Threadfin'
threadfin         | 2024/08/05 15:22:19 [Threadfin] Streaming Status:       Client has terminated the connection
threadfin         | 2024/08/05 15:22:19 [Threadfin] Streaming Status:       Channel: UK SKY SPORTS GOLF HD (Clients: 0)
threadfin         | 2024/08/05 15:22:19 [Threadfin] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
threadfin         | 2024/08/05 15:22:19 [Threadfin] FFMPEG log:             title=Threadfin: Invalid argument
```

Rolling back to 1.1.16 works. I clicked update only playlists with both versions. Did no other changes other than pulling latest image and recreating container.

**Comment by mf1x** [comment]
Same thing here :)

`2024-08-06 10:55:57 [DEBUG] Restream Status:        Playlist: Dream.bz - Channel: Sat.1 HD - Connections: 3
2024-08-06 10:55:57 [Threadfin] Streaming Status:       Channel: Sat.1 HD (Clients: 1)
2024-08-06 10:56:00 [Threadfin] FFMPEG log:             [NULL @ 0x5f3e6a4efa80] Unable to find a suitable output format for 'title=Threadfin'
2024-08-06 10:56:00 [Threadfin] Streaming Status:       Client has terminated the connection
2024-08-06 10:56:00 [Threadfin] Streaming Status:       Channel: Sat.1 HD (Clients: 0)
2024-08-06 10:56:00 [Threadfin] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
2024-08-06 10:56:00 [Threadfin] FFMPEG log:             title=Threadfin: Invalid argument
2024-08-06 10:56:00 [DEBUG] Streaming Status:       Remove temporary files (/tmp/threadfin/2024-01-7QBD-7A0SYD/M7E94BQ6N51PUZ9HYJUP/3e696ae86041e2eeafeeea88fb2dfbc9/)
2024-08-06 10:56:00 [DEBUG] Remove tmp folder:      /tmp/threadfin/2024-01-7QBD-7A0SYD/M7E94BQ6N51PUZ9HYJUP/3e696ae86041e2eeafeeea88fb2dfbc9/`

**Comment by bendschs** [comment]
same here

**Comment by Fyb3roptik** [comment]
Fixed in 1.1.19

**Comment by mf1x** [comment]
Thanks a lot :)

**Comment by bendschs** [comment]
does not work for me yet :/

**Comment by jsbear** [comment]
Not working for me either, tried both 1.1.18 & 1.1.19.

**Comment by raclo** [comment]
I confirm it still doesn't work, I'm going back to 1.1.16

**Comment by vajonam** [comment]
in .19 I see 



```
threadfin         | 2024/08/06 03:07:13 [Threadfin] Streaming URL:          http://xxxx.net:80/xxx/xxxx/391434.ts
threadfin         | 2024/08/06 03:07:13 [Threadfin] BUFFER ARGS:             -user_agent Threadfin -hide_banner -loglevel error -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -rtbufsize 128M -i http://xxx.net:80/xxx/xxx/391434.ts -c copy -f mpegts pipe:1
````

```
2024/08/06 03:07:16 [Threadfin] FFMPEG log:             [h264 @ 0x563594c4b940] non-existing SPS 0 referenced in buffering period
```

I have some other buffer args, not sure if the is causing the issue.

**Comment by adrianguanipa** [comment]
I confirm the latest here still doesn't work, I had to switch back to 1.1.16 to get it to work.

**Comment by Fyb3roptik** [comment]
ok will fix this today

**Comment by soapdishbandit** [comment]
> ok will fix this today

Same here, unable to start streams. Thank you so much for looking into it! :)

**Comment by Fyb3roptik** [comment]
Try 1.1.20

**Comment by vajonam** [comment]
Works for me. will continue to test.

**Comment by Fyb3roptik** [comment]
Please re-open if its not working.

**Comment by soapdishbandit** [comment]
1.1.20 works now! Thank you!

**Comment by bendschs** [comment]
works! thank you so much!

**Comment by jsbear** [comment]
Back in action, much appreciated :)

**Comment by mf1x** [comment]
Thanks 💪🏻
