### ISSUE TITLE
buffering not working as well since 1.1.17

### ISSUE THREAD

**Issue by vajonam** [Threadfin/Threadfin#327]
**Describe the bug**
When the Buffer checkbox is enabled, the clients keep showing wait cursors and watching experience isn't great.

**Server (please complete the following information):**
- OS - Linux Docker
- Arch Intel AMD64
- Threadfin Version and Build: versions > 1.1.16

**To Reproduce**
1.  Buffer Size o 2MB
2.  Buffer to RAM checked
3.  FFMpeg options `-hide_banner -loglevel error -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -rtbufsize 128M -i [URL] -c copy -f mpegts pipe:1` 
4. Watch stream on client. 

**Expected behavior**
Smooth stream shows up on the clients, rather than stop / start buffered stream. 

**Screenshots**
None

**Desktop (please complete the following information):**
Not Applicable

**Additional context**
rolling back to 1.1.16 seems to work the best, with nicely buffered / smooth stream.

**Comment by Fyb3roptik** [comment]
I'm not seeing any issues on my end. Everything runs smooth for me on ffmpeg. Check your options and maybe adjust

**Comment by vajonam** [comment]
Thanks. I will try removing the ` -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -rtbufsize 128M` 

I am not convinced that `-rtbufsize 128M` does anything..

**Comment by vajonam** [comment]
Sorry I am not able to debug this further, I am rolling back to 1.1.16, will see if any other users see issues with the buffering. Thanks.
