### ISSUE TITLE
ERROR: too many colons in address

### ISSUE THREAD

**Issue by SlothCroissant** [Threadfin/Threadfin#33]
Running `threadfin` in docker, with some very basic commands: 

`-v $PATH:/home/threadfin/conf`
`-e threadfin_BRANCH=beta` (I've also tried main - same results)
`-e threadfin_DEBUG=3`
`-p 34400:34400`

I can't even get `threadfin` to start as something seems to be weird with the web server binding:

```
For help run: /home/threadfin/bin/threadfin -h
2022/12/18 17:48:26 [Threadfin] [WARNING] Don't run this as Root!
2022/12/18 17:48:26 [Threadfin] Version:                0.9 Build: 19
2022/12/18 17:48:26 [Threadfin] Database Version:       0.5.0
2022/12/18 17:48:26 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 2
2022/12/18 17:48:26 [Threadfin] Hostname:               threadfin-69766c4f84-q4fs9
2022/12/18 17:48:26 [Threadfin] System Folder:          /home/threadfin/conf/
2022/12/18 17:48:26 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2022/12/18 17:48:26 [Threadfin] Temporary Folder:       /tmp/threadfin/2022-12-0JBJ-A1YGC2/
2022/12/18 17:48:26 [Threadfin] GitHub:                 https://github.com/Threadfin
2022/12/18 17:48:26 [Threadfin] Git Branch:             Beta [Threadfin]
2022/12/18 17:48:26 [Threadfin] SSDP / DLNA:            true
2022/12/18 17:48:26 BRANCH:  Beta
2022/12/18 17:48:26 FILE:  https://github.com/Threadfin/Threadfin/releases/download/0.9.20/Threadfin_linux_amd64?raw=true
2022/12/18 17:48:26 [Threadfin] Update Available:       Version: 0.9.20
2022/12/18 17:48:26 [Threadfin] Update Server:          
2022/12/18 17:48:26 [Threadfin] Start Update:           Branch: Beta
2022/12/18 17:48:26 [BIN] New version (Threadfin): 0.9.20
2022/12/18 17:48:26 DEBUG:  https://github.com/Threadfin/Threadfin/releases/download/0.9.20/Threadfin_linux_amd64?raw=true
2022/12/18 17:48:26 [BIN] Download new version...
2022/12/18 17:48:27 [BIN] Update Successful
For help run: /home/threadfin/bin/threadfin -h
2022/12/18 17:48:27 [Threadfin] [WARNING] Don't run this as Root!
2022/12/18 17:48:27 [Threadfin] Version:                0.9 Build: 20
2022/12/18 17:48:27 [Threadfin] Database Version:       0.5.0
2022/12/18 17:48:27 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 2
2022/12/18 17:48:27 [Threadfin] Hostname:               threadfin-69766c4f84-q4fs9
2022/12/18 17:48:27 [Threadfin] System Folder:          /home/threadfin/conf/
2022/12/18 17:48:27 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2022/12/18 17:48:27 [Threadfin] Temporary Folder:       /tmp/threadfin/2022-12-0JBJ-A1YGC2/
2022/12/18 17:48:27 [Threadfin] GitHub:                 https://github.com/Threadfin
2022/12/18 17:48:27 [Threadfin] Git Branch:             Beta [Threadfin]
2022/12/18 17:48:27 [Threadfin] SSDP / DLNA:            true
2022/12/18 17:48:27 BRANCH:  Beta
2022/12/18 17:48:27 FILE:  https://github.com/Threadfin/Threadfin/releases/download/0.9.20/Threadfin_linux_amd64?raw=true
2022/12/18 17:48:27 [Threadfin] UUID:                   2022-12-0JBJ-A1YGC2
2022/12/18 17:48:27 [Threadfin] Tuner (Plex / Emby):    1
2022/12/18 17:48:27 [Threadfin] EPG Source:             PMS
2022/12/18 17:48:27 [Threadfin] Plex Channel Limit:     480
2022/12/18 17:48:27 [Threadfin] Unfiltered Chan. Limit: 480
2022/12/18 17:48:27 [Threadfin] All streams:            0
2022/12/18 17:48:27 [Threadfin] Active streams:         0
2022/12/18 17:48:27 [Threadfin] Filter:                 0
2022/12/18 17:48:27 [Threadfin] DVR IP:                 10.42.5.205:tcp://10.43.12.192:34400
2022/12/18 17:48:27 [Threadfin] Web Interface:          http://10.42.5.205:tcp://10.43.12.192:34400/web/ | Threadfin is also available via the other 3 IP's.
2022/12/18 17:48:27 [Threadfin] [ERROR] listen tcp: address :tcp://10.43.12.192:34400: too many colons in address (Web server could not be started.) - EC: 1001
2022/12/18 17:48:27 [Threadfin] [ERROR] listen tcp: address :tcp://10.43.12.192:34400: too many colons in address () - EC: 0
```

**Comment by Fyb3roptik** [comment]
Seems you're using an outdated version

**Comment by SlothCroissant** [comment]
> Seems you're using an outdated version

Can you expand on that? According to the logs, it runs an update, and 0.9 build 20. I'm using the `:latest` tag on the provided [Dockerfile](https://hub.docker.com/r/fyb3roptik/threadfin/tags), and the Dockerfile [looks like it pulls the latest from the `beta` branch](https://github.com/Threadfin/Threadfin/blob/beta/Dockerfile#L11). 

Am I missing something simple here?

**Comment by SlothCroissant** [comment]
Update - I can confirm this issue also happens with the main `xTeVe` release. So this fork likely just inherited the bug. I reported it in the xTeVe Discord, but they have historically not answered any questions on anything not specifically related to `docker run`. 

If you're able to check this out, @Fyb3roptik , that'd be great. If not, all good - I'll see if I can find alternatives to xTeVe and its forks. 

Details:

Looks as though the settings.json gets populated with a bad port number string, and all heck breaks loose from there:

```
2022/12/18 17:48:27 [xTeVe] DVR IP:                 10.42.5.205:tcp://10.43.12.192:34400
2022/12/18 17:48:27 [xTeVe] Web Interface:          http://10.42.5.205:tcp://10.43.12.192:34400/web/ | xTeVe is also available via the other 3 IP's.
2022/12/18 17:48:27 [xTeVe] [ERROR] listen tcp: address :tcp://10.43.12.192:34400: too many colons in address (Web server could not be started.) - EC: 1001
2022/12/18 17:48:27 [xTeVe] [ERROR] listen tcp: address :tcp://10.43.12.192:34400: too many colons in address () - EC: 0
```

If I change the port manually in settings.json and reload, it just resets it back to the bad value

```
  "port": "tcp://10.43.54.140:34400",
```

**Comment by Fyb3roptik** [comment]
It definitely works. Please join our discord

**Comment by Fyb3roptik** [comment]
https://discord.gg/Bh9DhRcsBM

**Comment by elraro** [comment]
> Ok, in case anyone stumbles on this in the future:
> 
> i had a service (https://kubernetes.io/docs/concepts/services-networking/service/) to expose threadfin to my network. Kube adds some env vars to your deployment when you do this: https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables
> 
> ```
> For example, the Service redis-primary which exposes TCP port 6379 and has been allocated cluster IP address 10.0.0.11, produces the following environment variables:
> 
> REDIS_PRIMARY_SERVICE_HOST=10.0.0.11
> REDIS_PRIMARY_SERVICE_PORT=6379
> REDIS_PRIMARY_PORT=tcp://10.0.0.11:6379
> REDIS_PRIMARY_PORT_6379_TCP=tcp://10.0.0.11:6379
> REDIS_PRIMARY_PORT_6379_TCP_PROTO=tcp
> REDIS_PRIMARY_PORT_6379_TCP_PORT=6379
> REDIS_PRIMARY_PORT_6379_TCP_ADDR=10.0.0.11
> ```
> 
> since my service was named `threadfin`, Kubernetes adds an env var called THREADFIN_PORT with value of protocol://ip_address:port
> 
> and guess what issues that causes, since threadfin uses `THREADFIN_PORT` as your port value (usually 34400)
> 
> Solution is to explicitly declare the env var `THREADFIN_PORT` in your kube deployment manifest.
> 
> Closing this as resolved, @Fyb3roptik can decide if he wants to support cube deployments in time, but for now hopefully if others try to bootstrap this into kube, they will have success from my learning experience.

just happened to me :) thanks for the help!
