### ISSUE TITLE
Mapping tab - arranging by Channel No Ascending not working as expected.

### ISSUE THREAD

**Issue by shorty789** [Threadfin/Threadfin#332]
![image](https://github.com/user-attachments/assets/30b3befe-737e-448f-a892-4a6d61ac16fd)
Please see the attached screenshot, when in the mapping tab, channel numbers are not currently being ordered as expected, making management a little more challenging, it is as though they are not being treated as numerical values.

Version: 1.2 (0)
Docker container
Ubuntu VM

**Comment by Fyb3roptik** [comment]
I don't see this issue myself. Can you tell me exactly your steps?

**Comment by shorty789** [comment]
For the sake of further testing, I deleted and recreated the container,
keeping only the config files in place. The same thing happens. I tried the
basics such as ctrl+f5 refresh and incognito mode and nothing has changed.

It seems to have only happened since the recent update.

There is no change in ordering on the m3u that threadfin itself creates,
just the way that it is presented within the mapping tab.

**Comment by shorty789** [comment]
I have just this moment fixed the issue.

It would seem that for some reason, some of the channels had been
automatically populated to have their channel name in the channel number
field.

After assigning the affected channels numbers, saving, and refreshing, it
now presents itself correctly again.

The affected channels were at the bottom of the playlist.

**Comment by Fyb3roptik** [comment]
oh nice! Glad you got it sorted
