### ISSUE TITLE
AAC(0xaac0) audio : Missing audio or no stream

### ISSUE THREAD

**Issue by Hula1267** [Threadfin/Threadfin#334]
This bug seems related to some streams particularity. Maybe AAC(0xaac0) audio. 

Bug is different according to selected buffer option in TF.

- No buffer : No audio
- Buffered with ffmepg : Stream doesn work at all

When I input direct stream in the m3u, not passed to TF, everything works. Exemple of 2 freetv streams with the problem:

TV5 Monde Info
https://ott.tv5monde.com/Content/HLS/Live/channel(info)/variant.m3u8

TVA
https://tvalive-dai01.akamaized.net/Content/HLS/Live/channel(575b93c5-be31-ee34-6285-14620fd14048)/index.m3u8

- Threafin version : 1.2
- Official Docker on Synology
- Player used for testing the proxied m3u: Tivitmate, Sparkle IPTV player, Potplayer

**Comment by Fyb3roptik** [comment]
What ffmpeg options are you doing? The default one simply copies the stream, so that shouldnt effect it

**Comment by Hula1267** [comment]
@Fyb3roptik Ffmeg options?  What do you mean?

I only have to choose between these options. I tried No buffer and FFmpeg, that's it. 

![image](https://github.com/user-attachments/assets/6cf30e15-75a3-48c6-836f-9311161619b5)


Both lead to differents problems, like i explained in my post. 
Again: 

No buffer : No audio
Buffered with ffmepg : Stream doesn work at all

**Comment by Hula1267** [comment]
> That's just the selection on which app handles it. The options under it are how you manually control what it outputs.
> 
> The issue is your client application does not support the stream, you need to set options to transcode either audio or video as necessary to make your client happy.

Client doesn have problem with the direct link stream. Problem only occurs when Threadfin handle it.

**Comment by Fyb3roptik** [comment]
You said you get no audio, which tells me its probably a codec issue for your client. With a buffer, you should look at your Threadfin logs to see what it says

**Comment by purplescorpion1** [comment]
Are you using a ffmpeg with AAC codec enabled?

If you use direct your client player needs to be able to support the AAC audio and have the codecs capable of playing it

If you are a windows user use this ffmpeg as it will have all codecs enabled
https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
