### ISSUE TITLE
Plex doesn't seem to be connecting

### ISSUE THREAD

**Issue by MadMacMig** [Threadfin/Threadfin#337]
Threadfin and Plex were working this morning, came back home, now it was no longer working!! I've wasted 20+ hours on this crap for more issues to arise!

Rant to the side for a second, thread fun seems to be working and shows up on plex, nothing has changed, it's just seems like the connection has been lost and when I click on a channel to play, nothing shows up in the threadfin log, and I get a connection error on plex. I've checked the ports and everything seems to be fine.

I am running threadfin in a docker container and plex in another container.

**Comment by Fyb3roptik** [comment]
This is why you dont use Plex for Live TV. They have killed it. Kernel Media Server update is coming soon!
