### ISSUE TITLE
docker: slice bounds out of range

### ISSUE THREAD

**Issue by hayrun-st** [Threadfin/Threadfin#34]
Running the latest version, I've noticed my docker shut down pretty often, checking the logs shows this:

panic: runtime error: slice bounds out of range [1687608:0]

goroutine 569 [running]:
github.com/avfs/avfs/vfs/memfs.(*MemFile).Write(0xc0009c41b0, {0xc00026f000, 0x1000, 0x1000})
        /home/runner/work/Threadfin/Threadfin/vendor/github.com/avfs/avfs/vfs/memfs/memfs_file.go:653 +0x697
threadfin/src.thirdPartyBuffer(0x0, {0xc0036e8d80, 0x14}, 0x0, 0x0)
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:1704 +0x12e2
created by threadfin/src.bufferingStream
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:225 +0x998
m

FWIW, I've never had crashes with running the old xteve.

**Comment by Fyb3roptik** [comment]
Yeah old xteve didn't have this ram buffer. Will patch! Thanks!

**Comment by Fyb3roptik** [comment]
Patched in 0.9.21 - To be released

**Comment by Fyb3roptik** [comment]
Closing for now. Please re-open if this issue persists.

**Comment by Fyb3roptik** [comment]
1.0.1 should address this. Please update

**Comment by hayrun-st** [comment]
The issue has reappeared in 1.0.13 (and possibly before).  Again, running in Docker container on Unraid server.

I've had it crash several times over the past few days all with a very similar error:

panic: runtime error: slice bounds out of range [1063824:0]

goroutine 231 [running]:
github.com/avfs/avfs/vfs/memfs.(*MemFile).Write(0xc000f89b00, {0xc00067f000, 0xa48, 0x1000})
        /src/vendor/github.com/avfs/avfs/vfs/memfs/memfs_file.go:653 +0x697
threadfin/src.thirdPartyBuffer(0x0, {0xc0052a4588, 0x14}, 0x0, 0x0)
        /src/src/buffer.go:1698 +0x12e2
created by threadfin/src.bufferingStream
        /src/src/buffer.go:224 +0xa58
