### ISSUE TITLE
panic: interface conversion: interface {} is nil, not src.Playlist

### ISSUE THREAD

**Issue by nzzane** [Threadfin/Threadfin#341]
**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]: Unraid Docker
- Arch [e.g. Intel 64 Bit], AMD 64bit
- Threadfin Version and Build [to be found in the Threadfin log]: 1.2 (2) - (fyb3roptik/threadfin:latest-nvidia)

**To Reproduce**
Stream Buffer: ffmpeg
Buffer Size: 8MB
FFMPEG Options: -hide_banner -loglevel warning -analyzeduration 3500000 -probesize 4000000 -i [URL] -c copy -f mpegts -metadata:s:a:0 language=eng -fflags +genpts -preset ultrafast -tune zerolatency -timeout 6000000 -max_interleave_delta 0 -copyts pipe:1

When using Buffer, some channels cause Threadfin to throw the below panic and crash, when using No Buffer, the streaming client just throws the 404 or 403 error and fails to load - no crashes
Playlist: https://i.mjh.nz/au/Sydney/raw-tv.m3u8
XMLTV: https://i.mjh.nz/au/Sydney/epg.xml

**Expected behavior**
Not to panic and crash? 

**Log**
```
2024/08/24 08:56:36 [Threadfin] Buffer:                 true [ffmpeg]
2024/08/24 08:56:36 [Threadfin] Buffer Size:            8192 KB
2024/08/24 08:56:36 [Threadfin] Channel Name:            South Park
2024/08/24 08:56:36 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
2024/08/24 08:56:37 [Threadfin] Streaming Status:       Playlist: Sydney Freeview - Tuner: 1 / 3
2024/08/24 08:56:37 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
2024/08/24 08:56:37 [Threadfin] Streaming URL:          https://***************
2024/08/24 08:56:37 [Threadfin] FFMPEG:                 Processing data
2024/08/24 08:56:37 [Threadfin] Streaming Status:       Receive data from FFMPEG
2024/08/24 08:56:38 [Threadfin] FFMPEG log:             [hls @ 0x55fca8d575c0] Can't support the subtitle(uri: https://***************
2024/08/24 08:56:39 [Threadfin] FFMPEG log:             [https @ 0x55fca90a5b80] HTTP error 403 Forbidden
2024/08/24 08:56:39 [Threadfin] FFMPEG log:             [hls @ 0x55fca8d575c0] Unable to open key file https://***************
2024/08/24 08:56:40 [Threadfin] FFMPEG log:             [hls @ 0x55fca8d575c0] Error when loading first segment 'https://***************
2024/08/24 08:56:40 [Threadfin] FFMPEG log:             https://***************: Invalid data found when processing input
2024/08/24 08:56:40 [Threadfin] Streaming Status:        Client has terminated the connection
2024/08/24 08:56:40 [Threadfin] Streaming Status:        Channel:  South Park (Clients: 0)
2024/08/24 08:56:40 [Threadfin] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
2024/08/24 08:56:40 [Threadfin] Streaming Status:       Channel:  South Park - No client is using this channel anymore. Streaming Server connection has ended
panic: interface conversion: interface {} is nil, not src.Playlist

goroutine 483 [running]:
threadfin/src.clientConnection({{0xc00a6f6ce0, 0xb}, {0x0, 0x0}, {0xc007922a20, 0x59}, {0xc00d3070a0, 0x20}, 0x0, {0xc00f445920, ...}, ...})
        /src/src/buffer.go:571 +0x48f
threadfin/src.thirdPartyBuffer(0x0, {0xc00f445920, 0x14}, 0x0, 0x1)
        /src/src/buffer.go:1223 +0x1998
created by threadfin/src.bufferingStream
        /src/src/buffer.go:248 +0xa6a

```

**Comment by purplescorpion1** [comment]
These are geo blocked channels. Are you in Australia?
Does the m3u work in vlc 

The 403 error suggest you are not using an Australian IP or the site has changed their security and require a referer header

**Comment by nzzane** [comment]
Yep, can watch some fine, but others not - I presume due to, as you say, requiring a different header, or my ip is blocked

The main channels I stream can be watched, so not a huge issue
The main issue is the crashing when it encounters the 403/404’s
Could entirely be something specific to the playlist I’m using, in which case that’s mostly fine, I can work around that

**Comment by Fyb3roptik** [comment]
I will patch this panic
