### ISSUE TITLE
Channel logo not showing in Plex

### ISSUE THREAD

**Issue by wanderleyteixeira** [Threadfin/Threadfin#346]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I updated the channel logos in Threadfin (Mapping section). They all look good in Threadfin. 

**Server (please complete the following information):**
- Threadfin running on Synology Docker
- Threadfin Version and Build: 1.2 (2)

**Expected behavior**
Threadfin updates the images correctly to show in Plex.

**Screenshots**
<img width="283" alt="Threadfin" src="https://github.com/user-attachments/assets/aa7447f5-c24a-489b-85aa-40fd07422191">
<img width="140" alt="Plex" src="https://github.com/user-attachments/assets/a1e73a7b-7c1c-49ab-b248-60ecc13e48ae">

**Desktop (please complete the following information):**
 - OS: web, tv
 - Browser:  chrome, safari
 - Version: latest

**Additional context**
This might not even be a Threadfin issue since Plex is only taking the ones from the guide xml.

**Comment by wanderleyteixeira** [comment]
The guide.xml does not have the channel name. Threadfin does. "Update Channel Logo" is checked so I assume that it should be rendering it.

**Comment by Fyb3roptik** [comment]
Try enabling Image Caching and see if that helps. Restart after you do

**Comment by wanderleyteixeira** [comment]
> Try enabling Image Caching and see if that helps. Restart after you do

I tried that and also restarting Plex but nothing changed.

**Comment by Fyb3roptik** [comment]
Re-Open this ticket if it still does not work
