### ISSUE TITLE
Missing EPG data error

### ISSUE THREAD

**Issue by wanderleyteixeira** [Threadfin/Threadfin#347]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Errors in console for missing EPG data even though they are available.

Guide.xml
```
  <channel id="TSN 1 HD">
    <display-name lang="en">TSN 1 HD</display-name>
```

M3U
`#EXTINF:-1 tvg-id="TSN1.ca" tvg-name="TSN 1 HD" tvg-logo="https://p13.cx:443/images/e0825695759b5b37d714c022bbcd549b.png" group-title="CA | Sports",TSN 1 HD
`

**Server (please complete the following information):**
- Synology Docker
- Threadfin Version and Build: 1.2 (2)

**Expected behavior**
No errors. Even though it says the channel was deactivated, it is not.

**Screenshots**
Log:
```
2024-08-27 10:03:10 [Threadfin] [ERROR] Missing EPG data: TSN 1 HD () - EC: 0
2024-08-27 10:03:10 [Threadfin] [WARNING] Channel ID in the XMLTV file has changed. Channel has been deactivated.
```

**Additional context**
Not sure what the issue is or how to troubleshoot it

**Comment by Fyb3roptik** [comment]
I will need more than 2 lines of you xml to see

**Comment by wanderleyteixeira** [comment]
[guide.xml.gz](https://github.com/user-attachments/files/16770266/guide.xml.gz)
The guide

**Comment by wanderleyteixeira** [comment]
Sharing the guide.xml (input in XMLTV) and the threadfin.xml (does not have mpg data?). Shared the files in Discord.

**Comment by Fyb3roptik** [comment]
I will close this. Please do troubleshooting on Discord. If there is an issue I will file it here. Thanks!
