### ISSUE TITLE
No Option to Update Channel Name for PPV Channels

### ISSUE THREAD

**Issue by ceb0610** [Threadfin/Threadfin#348]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

Whenever I try to add my NFL, MLB or PPV channels to Threadfin, they don't have the option to "Update Channel Name" so that the channel and epg update with new events.

- Docker
- Intel 64 Bit
- Threadfin 1.2 (3)

![image](https://github.com/user-attachments/assets/0373483f-7726-49f7-8c1e-496e57c08045)
![image](https://github.com/user-attachments/assets/e2126d09-07ab-4f22-998d-66bf7ab3afd1)

I noticed that in the xepg.json file, the channels that do show the Updated Channel Name option have a "_uuid.key" set.

![image](https://github.com/user-attachments/assets/85d1900f-1e86-47c0-aa1a-b8277ffcea58)

**Comment by Fyb3roptik** [comment]
You do not need to do that. The PPV Dummy data handles that for you, hence why it isnt there. It grabs the content from the channel name and populates the xml with it
