### ISSUE TITLE
Feature Request: Favorites

### ISSUE THREAD

**Issue by lasharor** [Threadfin/Threadfin#349]
**Is your feature request related to a problem? Please describe.**
I would like to define some channels in an additional "favorites" group. Now, channels are sorted default by group. However, most of the times I am not interested in all the channels in the group. But, in some cases I want to view some due to specific content available in a channel I would usually not watch. It is annoying to always have to come back to the ui and enable a specific channel.

**Describe the solution you'd like**
Being able to map channels to a second group and/or have a checkbox to enable "favorite" channels. 

**Describe alternatives you've considered**
I understand I can do this also in most clients but, I would like to have a solution that is more universal and doesn't depend on the client application in use.

**Comment by Fyb3roptik** [comment]
I'm not understanding this. You can already add custom EPG categories and assign it to a channel. What else is being asked for?

**Comment by lasharor** [comment]
You are totally right. Sorry!

Thanks anyways for all of your efforts!
