### ISSUE TITLE
Renamed Channels Reverting

### ISSUE THREAD

**Issue by propho** [Threadfin/Threadfin#353]
**Describe the bug**
Since version 1.2.4 renamed channels revert to provider naming.

**Server (please complete the following information):**
- OS Ubuntu
- Arch 64-bit
- Threadfin Version and Build 1.2.5

**To Reproduce**
1. Change "Channel Name"
2. Save mapping
3. Refresh channels from provider
4. Channel name will revert

**Expected behavior**
Renamed channel information retained.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Edge

**Additional context**
This is happening on all channels and not specific to type and/or filter.

**Comment by jaretclifton** [comment]
I'm experiencing the same issue still and I'm on 1.2.7

Edit channel, rename, done, save, refresh, channel name is reverted.
