### ISSUE TITLE
Anyone successfully running a version NEWER than 1.2.3 on UNRAID?

### ISSUE THREAD

**Issue by jsbear** [Threadfin/Threadfin#355]
Kind of weird, docker log files not showing any error messages, the webui never comes up, seems to crap out during the initialization phase.  High CPU usage, I let it sit for 10-15 minutes, nothing.  Reverting back to 1.2.3 and I'm all good.

**Comment by tobiasredel** [comment]
Same issue as https://github.com/Threadfin/Threadfin/issues/354. @Fyb3roptik said that it has to do with the probechannel feature and our M3Us having too many 24/7 channels. Problem is, that i dont have the chance currently to prefilter the m3u before it reaches threadfin as its external. Hope that there will be an option to disable the probechannel feature and / or fix it for 24/7 channels.

**Comment by Fyb3roptik** [comment]
It's not probe channel. It's the generation of tvg-id

**Comment by Fyb3roptik** [comment]
Closing since this is a duplicate of #354
