### ISSUE TITLE
#311 regression - backup channels do not work

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#357]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Backup channels do not work. I have only one playlist and the primary channel and backups under the same m3u and I have the same settings as in https://github.com/Threadfin/Threadfin/issues/311#issue-2434098185

**Server (please complete the following information):**
OS Windows 11
Intel 64 Bit
Threadfin Version 1.25

**To Reproduce**
Add extra streams to m3u for specific channels and save them in the same m3u
Add a primary channel
Set the extra streams of the same channel to inactive
Add the extra streams as a backup to the primary

**Expected behavior**
If the primary channel fails, such as 404, Threadfin moves to the first backup channel. If that one fails, it moves to the next one, etc.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/Threadfin/Threadfin/issues/311#issue-2434098185)

Desktop (please complete the following information):

OS: Android TV
Browser: IPTV Pro
Version: 8.0.7

**Additional context**
The bug is not present in 1.22 and prior. I did not test v1.23 or 1.24 but it is present in 1.25.

**Comment by PiratesIRC** [comment]
yes, they are. I have not changed anything from the upgrade from 1.22 to 1.25. I am currently on 1.21 as 1.22 crashed on me once and the backup channels are working great.

**Comment by Fyb3roptik** [comment]
Can you provide logs showing it error and not go to the backup channel?

**Comment by PiratesIRC** [comment]
I just upgraded to 1.2.7 and was unable to replicate it. If it happens again, I'll post it again. Thanks for your attention on this.
