### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by davidclaeysquinones** [Threadfin/Threadfin#359]
Since version 1.2.5 I'm experiencing some serious performance issues.
I haven't changed anything on my channel lists, hardware or any other thing.
Since this update updating the database can take up to 30 minutes or straight out makes the container freeze.
Previously this got done in about 5 minutes without any hickups.

**Comment by carfanatic93** [comment]
Same here

**Comment by Fyb3roptik** [comment]
Already known. No need for another issue
