### ISSUE TITLE
Image caching not rewriting xml

### ISSUE THREAD

**Issue by xXx-st4cktr4c3-xXx** [Threadfin/Threadfin#36]
Seems that it is downloading the images (with query params too which is great for saving space, bad for image quality lol) but it doesn't seem to be changing the image URL in the XML file to point to where the cached image is stored on the server.

**Comment by Fyb3roptik** [comment]
It is currently only updating the m3u, but will make sure the xml gets updated

**Comment by Fyb3roptik** [comment]
Patched in 0.9.21 - To Be Released

**Comment by Fyb3roptik** [comment]
Patched in 0.9.21 - Closing for now. Please re-open if this issue persists.
