### ISSUE TITLE
Active mapped channels not saving in backup

### ISSUE THREAD

**Issue by timleeds15** [Threadfin/Threadfin#364]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Had to spin up a new threadfin container. When I restored the backup to my previous container, none of my active mapped channels had transferred over. Everything else was there, filters, xmls, etc.

**Server
- OS Linux - Ubuntu
- Threadfin Version 1.2 and Build 6

**To Reproduce**
1. Go to settings tab.
2. Click on backup.
3. Spin up a new instance of threadfin.
4. Go restore recent backup.
5. See that no active mapped channels are present.

**Expected behavior**
All mapped active channels with linked XML files and logos should be restored.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge.
 - Version most recent.

**Additional context**

**Comment by Fyb3roptik** [comment]
I am not able to reproduce this. I have tried with an auto backup as well as a new backup. Both restore everything for me just fine
