### ISSUE TITLE
Cannot approach threadfin after installation

### ISSUE THREAD

**Issue by jnathalia** [Threadfin/Threadfin#365]
I have xTeVe running, but due to some EPG issues I have read I need to move forward to threadfin.

The problem is, I do not succeed in getting access to the local website http://192.168.1.100:34400/web

I have installed it on a docker on my Synology NAS. I did the same configuration as xTeVe, like the mapping to the data and conf folder in the docker. All is starting fine, looking at the log and the processor utilisation. However, if I look at for instance /docker/threadfin/conf/cache/images I don't see anything.

What am I doing wrong here?

I have the log below.
![Screenshot 2024-09-05 at 12 27 05](https://github.com/user-attachments/assets/a99ecf2a-1a7c-4834-a20d-6e477a5f4d48)

**Comment by Fyb3roptik** [comment]
Set your bind address to the IP address you want to use to access it

**Comment by jnathalia** [comment]
I have set the address equal to the address of my Synology NAS, like as xTeVe (which is set in docker by using the host IP address which is my NAS). Threadfin you can set its own binding address at the settings. I have used the default port 34400, also like xTeVe which has been stopped in Docker (of course). Should I use another IP address in my local network?
