### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#366]
Since 1.2.5 i have the weird effect, that out of a sudden filtered channels do not appear anymore in the mapping list.
The logs do not show anything but on the filter tab i can see the channels being added Channel: (+) .....
but then on the mapping table its just not appearing.

**Comment by Fyb3roptik** [comment]
Delete and re-add the filter. See if that fixes it for you

**Comment by tobiasredel** [comment]
I did - no change. I only managed to get it working by deleting all filters to get all channels back, when adding the filters, gone again.

**Comment by Fyb3roptik** [comment]
You have overlapping channel numbers then
