### ISSUE TITLE
Downloading the threadfin.m3u file via an HTTP request is only possible with authentication, not working properly

### ISSUE THREAD

**Issue by ovargasp** [Threadfin/Threadfin#369]
I'm not sure if this is a Bug or a configuration issue, for what I understand if I enable authentication, and set **Downloading the threadfin.m3u file via an HTTP request is only possible with authentication** to true (marked) then I'm not supposed to be able to download the m3u file from the server without providing a username and password. But If I try to get the threadfin.m3u from the server, I can to get it every time, I tried it with curl, web browser and televizio for android.

meaning: curl http://192.168.x.y:34400/m3u/threadfim.m3u gets the playlist, using the web browser and going to http://192.168.x.y:34400/m3u/threadfin.m3u starts the download, etc.

I configured both m3u file and epg download with authentication and this only happens with the m3u file, trying to download the epg xml without username and/or password responds with forbiden. Meaning curl 192.168.x.y:34400/xmltv/threadfim.xml fails but curl http://192.168.x.y:34400/xmltv/threadfim.xml?username=xxx&password=yyy works as expected.

Environment:
- OS: Ubuntu 22.04 with docker
- Arch: x64
- Threadfin docker 1.2(6) and 1.2(7) -> updated some minutes ago.

To reproduce, 
1. get docker image, run it
2. add a playlist and xmltv guide.
3. in settings: Enable authentication
4. create a new user with only M3U Access and XML Access enabled.
5. In settings -> Authentication select all options to require username and password for webui, access PMS, M3U, XML and API
6. open a terminal/shell and run command **curl http://192.168.x.y:34400/m3u/threadfin.m3u**
7. it will show the m3u file content

Expected behavior
The request to fail with forbiden if no authentication provided while requesting m3u/threadfin.m3u, curl and/or webbrowser not showing content but a forbiden error.

I went through all documentation and I think I configured authentication correctly, and I'm not getting any errors in the log, and it works with the xmltv file but not with the m3u. I also restarted the docker after configuring authentication when it failed the first time, so configuring and restarting doesn't fix the problem. 

Any help is appreciated.

**Comment by ovargasp** [comment]
I'm not proficient in go, so if I try to fix this I may screw it up even worst, but reading the code and with a little googling I think I got what's happening... this section of code: 

https://github.com/Threadfin/Threadfin/blob/main/src/webserver.go#L352

says that if the group-title parameter is empty (or not present), it'll look for the file in the file system and if the file exists it will serve it back to the client, and this is way before it even considers authenthication, so as long as you ask for the threadfin.m3u no arguments it will bypass the m3u authentication setting and reply with the file.

I may be mistaken because as I said before I know very little about go lang, and I'm even less familiar with your code but got caught by this particular behavior. 

I must say it's great project and I love it...

**Comment by trapy7** [comment]
same problem version 1.2 (7)

**Comment by trapy7** [comment]
any news?

**Comment by Fyb3roptik** [comment]
1.2.8 will have this fix

**Comment by ovargasp** [comment]
I just updated to 1.2(8) and is still doing presenting the same behavior, please reopen

**Comment by ovargasp** [comment]
I just updated to 1.2(8), tried and is still presenting the same behavior, please reopen
