### ISSUE TITLE
Update docker Threadfin on Synology fails to start and restart

### ISSUE THREAD

**Issue by jnathalia** [Threadfin/Threadfin#371]
The issue I had while the docker was set to use "host" IP address, wasn't solved. Therefore I re-open but with an additional issue.

I have updated my docker the 9th of September with the same settings. Now, when starting, it fails immediately. As I have "Enable auto-restart" on, the docker cannot be stopped or deleted. This must have to do something with the update, as I haven't changed anything. It's very difficult with Synology to get into the docker, except for browsing its folders.

It has something to do with the recent update?

PS I have several dockers based on "host" setting and they have no issue sharing the host IP address.

**Comment by Fyb3roptik** [comment]
Join the discord, This is not an issue with Threadfin
