### ISSUE TITLE
EPG not displaying properly

### ISSUE THREAD

**Issue by justradko** [Threadfin/Threadfin#373]
The EPG of some of the channels is not visible, it appears without characters or with random symbols eg. (), 7, 1, etc. pieces of the title I'd guess. 
Some of the channels are okay. 
The language on most is Cyrillic, it's not specific to the language as it works in some. 
This only happens when I map the channels in Threadfin and use XMLTV link provided by Threadfin, if I match them in PLEX it has no issues. 
<img width="1371" alt="Screenshot 2024-09-14 at 9 29 10" src="https://github.com/user-attachments/assets/9a3f6bda-e2b4-4aae-a3ea-498cd11c9392">
<img width="1066" alt="Screenshot 2024-09-14 at 9 29 44" src="https://github.com/user-attachments/assets/72698c08-0ca0-4929-a1d1-50fbe4ea8a62">
<img width="1194" alt="Screenshot 2024-09-14 at 9 29 57" src="https://github.com/user-attachments/assets/9bd3fc01-1565-4d7e-a8af-e8d728991e80">
The description seems to be intact in most, but I noticed that some are wrongly taken from other channels and are mix-matched. 

NON-ASCII is enabled. 
<img width="1660" alt="Screenshot 2024-09-14 at 9 31 09" src="https://github.com/user-attachments/assets/4a90475d-a0ad-49e0-9fd9-c0980d9aeed7">
The EPG file looks strange in the program. 

ORIGINAL EPG file: https://easyupload.io/h4xh7f

- Windows
- Intel 64bit
- 1.2(7)

**Comment by Fyb3roptik** [comment]
1.2.8 should fix this

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.8

**Comment by yar229** [comment]
Same thing in 1.2.9...
EPG source http://epg.one/ru2.xml.gz

**Comment by yar229** [comment]
> Same thing in 1.2.9... EPG source http://epg.one/ru2.xml.gz

Sorry...
Working if checked "Enable Non-ASCII" in settings
