### ISSUE TITLE
Mapped channels missing from M3U

### ISSUE THREAD

**Issue by grooverider2016** [Threadfin/Threadfin#375]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fyb3roptik** [comment]
Dont create empty issues
