### ISSUE TITLE
Threadfin m3u list default multiple streams into a single one

### ISSUE THREAD

**Issue by ardoviniandrea** [Threadfin/Threadfin#377]
**Describe the bug**
I have a list on m3u84u with ~180 channels, that all works when I use it directly on VLC on my pc
I pass this list on threadfin in order to add EPG (and of course use it on Plex)

My problem is that threadfin doesn't recognize some of the channels (at least that's what I think it's happening) and flatten thems giving a single streamID, so even if I switch channels it plays the same one for ~20 of them

Is there a way for me to fix it manually? Because as I mentioned they all play fine with the m3u84u file

**Server (please complete the following information):**
- Ubuntu server 24.04
- Threadfin Version and Build : 1.2 Build: 5 (same issue with build 7)

**To Reproduce**
I have added my m3u4u list to Threafin playlist
The m3u4u list have ~180 channels, unique ID% is very low, but not sure if there is something I can fix (screenshot 1)
In the mapping tab all channels are display correctly
When I then use the threadfin.m3u list I see that some channels default to a single stream id like in the screenshot 2

**Expected behavior**
All channels should have a separate streamid and play like they do in VLC from m3u4u list

**Screenshots**
<img width="884" alt="Screenshot 2024-09-16 at 14 58 43" src="https://github.com/user-attachments/assets/d9540e67-bdb1-4507-9ada-6536af07c481">
<img width="1438" alt="Screenshot 2024-09-16 at 15 01 12" src="https://github.com/user-attachments/assets/0f515b20-39cb-47f4-966c-e2ebb017706f">

**Comment by Fyb3roptik** [comment]
Check your `tvg-id` on the incoming. Make sure theyre not the same
