### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#379]
Hi Iam running threadfin on docker and i am experiencing high cpu usage - looking at docker stats when i start the application it slowly starts to grow and then stays at 200% all the time until do a manual restart. i cannot see anything special in the logs. Iam running docker on synology nas 720+ - any idea what could cause high cpu usage?

**Comment by Fyb3roptik** [comment]
Please join the discord for this type of support. We can help you better there
