### ISSUE TITLE
Ability to merge Playlist

### ISSUE THREAD

**Issue by Traace** [Threadfin/Threadfin#38]
**Is your feature request related to a problem? Please describe.**
Hi, I've multiple IPTV connections. Every connection has its own M3U link thus is a seperated playlist and every M3U only allows one concurrent connection. All playlists are mapped to the same XMLTV file.

When creating a Filter list the channels gets mapped multiple times (for each of the playlists), resulting in redundant entries & confused users...

**Describe the solution you'd like**
The Ability to merge playlists with prioritization / load balancing.

**Describe alternatives you've considered**
I tried to map the other connections as backup channels, however it doesn't seems to be possible to delete the redundant mapping entries.

**Additional context**
I'm unable to use Threadfin because of this. Its the same reason why xTeVe doesn't work for me.
Currently I'm using TVHeadend, it has its own problems, but can handle this load balancing scenario very well.

**Comment by Fyb3roptik** [comment]
Sounds like you need a new provider 😂

**Comment by Fyb3roptik** [comment]
Hop on the discord and we can discuss how to do this

**Comment by Fyb3roptik** [comment]
https://discord.gg/4qrmpMmzWU

**Comment by Fyb3roptik** [comment]
You could also use the Backup Channel functionality in Threadfin. Deactivate all channels from connection 2, make them each backup channels of their connection 1 counterparts
