### ISSUE TITLE
Channel mapping bad with similar names

### ISSUE THREAD

**Issue by dceldran** [Threadfin/Threadfin#380]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
My iptv provider has the same channel repeated with similar names, so in case one channel goes down you can easly switch to another. Example of naming:
- Example channel 1 FHD (R)
- Example channel 1 FHD B (R)
- Example channel 1 FHD (S)
- Example channel 1 FHD B (S)

The problem is that sometimes whatever channel i open, it be always be mapped to the same channel. I can see in the logs the url threadfin is opening and is always the same even if i change between the 4 channels. But sometimes this doesn't happens. If i remove the iptv playlist and i add it again, the mapping fix until threadfin updates the playlist, restarts or whatever.

**Server (please complete the following information):**
- OS Ubuntu (but threadfin is dockerized)
- Arch x64
- Threadfin Version and Build: i was in 1.1.16 and i update to 1.2.7 with same result

**To Reproduce**
I don't know, just have an iptv provider with similar channel names.

**Expected behavior**
An exact mapping of channels with name. Example:
Now:
- Example channel 1 FHD (R) -> mapped to -> Example channel 1 FHD (R)
- Example channel 1 FHD B (R) -> mapped to -> Example channel 1 FHD (R)
- Example channel 1 FHD (S) -> mapped to -> Example channel 1 FHD (R)
- Example channel 1 FHD B (S) -> mapped to -> Example channel 1 FHD (R)

Expected:
- Example channel 1 FHD (R) -> mapped to -> Example channel 1 FHD (R)
- Example channel 1 FHD B (R) -> mapped to -> Example channel 1 FHD B (R)
- Example channel 1 FHD (S) -> mapped to -> Example channel 1 FHD (S)
- Example channel 1 FHD B (S) -> mapped to -> Example channel 1 FHD B (S)

**Screenshots**

**Desktop (please complete the following information):**
Tried with plex in more than one device, ios, appletv, windows.

**Additional context**
Sorry if this is explained in some documentation/issue, i was searching about this but i don't found nothing. Thanks!

**Comment by Fyb3roptik** [comment]
This is based on your m3u tvg-id. I'll need to see an example of your m3u

**Comment by dceldran** [comment]
I can see that in my m3u the tvg-id of all channels i want to map it's the same, so impossible to do a correct mapping right?

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.8

**Comment by cachibachero** [comment]
Now, all the channels with same id but different names appear in the mapping section with individual numbers; however, they won't populate in the output server file. It populates only one channel.

**Comment by dceldran** [comment]
I've done some testing and i have the same problem, in the .m3u file it's only one channel populated and in plex i have the same problem, i can see all the channels with same id but different name and always open same channel in my iptv provider.

Thanks!

**Comment by cachibachero** [comment]
It is not plex or any client. If you download the m3u file it will show only one channel

**Comment by cachibachero** [comment]
Which is weird since TF gets to the point of mapping it perfectly, Feeling that we are just one step to success

**Comment by dceldran** [comment]
> It is not plex or any client. If you download the m3u file it will show only one channel

It's what i say, i've tried the two options and in the .m3u file it's like you said, only one channel populates and in plex (it's how i use threadfin) i can see all the channels but all of them points to the same iptv provider channel

**Comment by Pretzel1538** [comment]
Same issue here with similar names.
My server info says i have 974 mapped channels, the Threadfin .m3u output only contains 747.

In the filter view I can see all "Active Streams" correctly.
e.g.
"Channel 1 HD"
"Channel 1 HD *" 
"Channel 2 HD"
"Channel 2 HD *" 

But the created .m3u file only contains one.

**Comment by Fyb3roptik** [comment]
Again, it wont know they're different channels unless the tvg-id is different

**Comment by cachibachero** [comment]
Is it possible to tell THFN to look for the name instead of the channel ID for EPG purposes?
I don't mean reprogramming the whole framework. For example, adding a switch to allow the use of the name of the channel instead of the ID; otherwise let THFN act as it normally does.
