### ISSUE TITLE
Getting HDHomeRun lineup.json timeout

### ISSUE THREAD

**Issue by begunfx** [Threadfin/Threadfin#381]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have two HDHomeruns connected via Threadfin. They were working well for a while, but now I can't seem to update their playlists in threadfin.  When I try to update, I get a i/o timeout error with the following path: http://192.168.1.56/lineup.json.  I tried putting that in a browser and it reads the json file just fine.  

Here's the specific message in the log:
 [ERROR] Get "http://192.168.1.56/lineup.json": dial tcp 192.168.1.56:80: i/o timeout () - EC: 0

**Server (please complete the following information):**
- Running Docker container inside Synology Server (DSM 7.2.1)
- 1.2 (7)

**To Reproduce**
1. Error happens when trying to startup container or when trying to update playlist

**Comment by Fyb3roptik** [comment]
I also use hdhomeruns and am not able to reproduce this

**Comment by begunfx** [comment]
Additional note:  I am running threadfin through gluetun docker.

Here's my docker compose:
`version: "2.3"
services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    network_mode: "container:gluetun"
    #Ports managed in container: gluetun
    #ports:
    #  - 34400:34400
    environment:
      - deunhealth.restart.on.unhealthy=true
      - PUID=1034
      - PGID=100
      - TZ=America/Los_Angeles
      - THREADFIN_DEBUG=3
      - THREADFIN_BRANCH=main
    volumes:
      - /volume1/docker/threadfin/conf:/home/threadfin/conf
      - /volume1/docker/threadfin/xteve:/tmp/xteve:rw
    healthcheck:
      test: "curl -fs localhost:9999 || kill 1"
      interval: 1m
      timeout: 1m
    restart: always
`

**Comment by Fyb3roptik** [comment]
You should be using gluetun with hdhomerun. That traffic is local....

**Comment by begunfx** [comment]
I'm not using gluetun with hdhomerun.  I'm only using it with the threadfin container.
