### ISSUE TITLE
Active Channels missing from m3u

### ISSUE THREAD

**Issue by 2esq** [Threadfin/Threadfin#382]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Active channels are not being included in the generated threadfin.m3u file.

**Server (please complete the following information):**
- OS docker (ubuntu host)
- Arch: inter x64
- Threadfin Version and Build: 1.2.7 (also tested on 1.2.6)

**To Reproduce**

**Expected behavior**
The active channels should be present in the threadfin.m3u file.

**Screenshots**
![SCR-20240923-gk0](https://github.com/user-attachments/assets/f0dbf16a-6131-44f3-9666-a19cdb320171)
![SCR-20240923-g5m](https://github.com/user-attachments/assets/4cb79af0-31de-49f9-9b57-65c319f2f151)

**Comment by Fyb3roptik** [comment]
Duplicate #374
