### ISSUE TITLE
No ability to select audio stream of a multi audio stream channel

### ISSUE THREAD

**Issue by ElEmFurt** [Threadfin/Threadfin#383]
**Is your feature request related to a problem? Please describe.**
I was using xTeve and then came upon Threadfin which greatly improves the backend management and while it works as expected, my problem is that the IPTV provider I am using, has multiple languages as audio streams within a channel, for e.g. English and Tamil are options for one channel and when I play it on the IPTV site, I can select and remedy the problem whereas ThreadFin (and also xTeve) pick a default one which sadly in my case isn't English. 

**Describe the solution you'd like**
It would be nice if I could select the audio streams for each channel somehow when sending to JellyFin.
![image](https://github.com/user-attachments/assets/598d67a6-99dd-4d5e-a31f-9f2f72afb94e)

**Describe alternatives you've considered**
None other than using the IPTV provider directly.

**Additional context**
My main workflow is JellyFin -> ThreadFin -> JioTVGo (my IPTV provider, setup as a server locally). If I connect my IPTV provider directly to JellyFin, I get a lot of useless channels and ThreadFin allows me to turn on, only the ones I need.

Any help with the problem above would be appreciated.

**Comment by Fyb3roptik** [comment]
This all depends on how youre buffering and what not. Threadfin while based on xteve has gone through a ton of changes. This is not something on my radar currently sorry

**Comment by bbruenings** [comment]
@ElEmFurt  if you go to the settings, use FFMPEG as stream buffer and change the FFmpeg options to the following 
-hide_banner -loglevel error -i [URL] -map 0 -c copy -f mpegts pipe:1

The audio streams should be passed to the output stream and therefore should show up in jellyfinn.

Hope that helps let me know if you need any support.
