### ISSUE TITLE
Enable jumping to backup from another playlist when tuner limit is reached on original playlist

### ISSUE THREAD

**Issue by ivantrejo41** [Threadfin/Threadfin#385]
**Is your feature request related to a problem? Please describe.**
Currently, when using multiple M3U playlists with tuner limits (e.g., Playlist 1 -> limit 1, Playlist 2 -> limit 1), the system does not allow seamless switching to a backup channel from another playlist when the tuner limit of the original playlist is reached. For example, if I am watching Channel 1 from Playlist 1 and it fails, it should ideally jump to Channel 1 from Playlist 2 (backup). However, if I attempt to watch Channel 2 from Playlist 1 simultaneously and reach the tuner limit, the system prevents jumping to the backup channel, leading to interruptions and limiting viewing options.

**Describe the solution you'd like**
I would like to see a feature that allows the system to automatically jump to a backup channel from a different playlist when the tuner limit of the original playlist is reached. This would enable smoother viewing experiences by ensuring that even when a limit is hit, the user can continue watching through the backup channel seamlessly, enabling the posibility of viewing a number of channels above the limit.

**Describe alternatives you've considered**
Currently, the only workaround is to manage channels manually and ensure the tuner limits are not exceeded on the original playlist. An option is having duplicated channels, one from each playlist. This is not ideal, as it disrupts the user experience and complicates the management of multiple channels and playlists.

**Comment by Fyb3roptik** [comment]
This is a new feature and will not be done. I have other plans for this for other software
