### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Yumega** [Threadfin/Threadfin#390]
newest version  

stderr: 2024/10/02 14:38:01 [Threadfin] Streaming Status:       Receive data from VLC
stderr: 2024/10/02 14:38:01 [Threadfin] VLC log:                [000055b4515cf790] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
stderr: 2024/10/02 14:38:01 [Threadfin] VLC log:                [000055b4515c7230] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
stderr: 2024/10/02 14:38:01 [Threadfin] VLC log:                [000055b4515c7230] main interface error: no suitable interface module
stderr: 2024/10/02 14:38:02 [Threadfin] VLC log:                [000055b45152e430] main libvlc error: interface "dbus,none" initialization failed
stderr: 2024/10/02 14:38:02 [Threadfin] VLC log:                [000055b4515da3b0] main interface error: no suitable interface module
stderr: 2024/10/02 14:38:02 [Threadfin] VLC log:                [000055b45152e430] main libvlc error: interface "globalhotkeys,none" initialization failed
stderr: 2024/10/02 14:38:02 [Threadfin] VLC log:                [000055b4515da3b0] dummy interface: using the dummy interface module...
stderr: 2024/10/02 14:38:10 [Threadfin] VLC log:                [00007f2bc803e4a0] mpeg4audio decoder: AAC channels: 2 samplerate: 32000

**Comment by Fyb3roptik** [comment]
You need to run

`export DISPLAY=:0`
