### ISSUE TITLE
Threadfin excessive processor usage

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#392]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Threadfin is intermittently using 15 to 25% CPU even when there are no streams active.

**Server (please complete the following information):**
- OS Windows 11 x64
- Threadfin Version and Build 1.2 (8)

**To Reproduce**
1. Run Threadfin

**Expected behavior**
In the past CPU usage was much lower when idle; 1 to 2%.

**Screenshots**
![threadfin-tm](https://github.com/user-attachments/assets/ec0aabde-f005-475b-8510-c36a02114fe6)
![threadfin-resmntr](https://github.com/user-attachments/assets/be51e258-fc5a-4846-a0ff-4c4c7ec88e8f)

**Desktop (please complete the following information):**
 - OS: Android TV / Nvidia Shield
 - Browser IPTV & Tivimate

**Additional context**
I am using a FFmpeg as a buffer.

**Comment by Fyb3roptik** [comment]
Restart Threadfin. You probably have orphaned streams
