### ISSUE TITLE
Channel Probe does not work

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#393]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Channel Probe does not work.

**Server (please complete the following information):**
- OS Windows 11 x64
- Threadfin Version and Build 1.2 (8)

**To Reproduce**
1. Within Mapping tab, open a channel
2. Click Probe Channel button
3. Status status "Probing Channel Details..."
4. Nothing else happens

**Expected behavior**
Probe shows stream info

**Screenshots**
![threadfin-probe](https://github.com/user-attachments/assets/1a045ea2-a3b4-4cef-88bf-48d10ff282e2)
![threadfin-probe-path](https://github.com/user-attachments/assets/53797372-31eb-4355-81a3-2e4537c7ff6c)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser Firefox
 - Version 131.0

**Additional context**
Does not work on any stream I have.
No output details are shown in the logs.

**Comment by Fyb3roptik** [comment]
you have the word ffmpeg in your path. Try renaming the folder to something else and it will fix it. Its looking for ffmpeg in the path and changing it to ffprobe
