### ISSUE TITLE
Playlist URL Changes not updating cache

### ISSUE THREAD

**Issue by xXx-st4cktr4c3-xXx** [Threadfin/Threadfin#40]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
The `urls.json` file does not update when changing a playlist M3U url (query param changes).
This prevents the updated M3U URLs from being sent to Plex.
This is being experienced when using no buffer/transcoding.

**Server (please complete the following information):**
- OS: Gentoo 6.1.8
- Arch AMD64
- Threadfin Version: 1.0 Build: 1

**To Reproduce**
1. Edit the playlist URL and just add a query param (?blah)
2. Save the playlist
3. Go to Plex and stream a channel
4. Threadfin logs show that the old URL is still being used.
```
[Threadfin] Streaming URL:          http://192.168.0.2:8089/devices/ANY/channels/6033/stream.mpg?format=ts&codec=copy
[Threadfin] Streaming Info:         URL was passed to the client.
[Threadfin] Streaming Info:         Threadfin is no longer involved, the client connects directly to the streaming server.
```

**Comment by Fyb3roptik** [comment]
Fixed in https://github.com/Threadfin/Threadfin/releases/tag/1.0.2
