### ISSUE TITLE
Active Channel ignores Cancel button

### ISSUE THREAD

**Issue by PiratesIRC** [Threadfin/Threadfin#404]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
In channel mapping, if you deselect 'Active' from an active channel and press cancel, the channel is still shown as inactive (red) and if you open the channel again, the active is deselected. Basically, the active channel toggle is saved when you press the Cancel button.

- Threadfin Version and Build 1.29

**Desktop (please complete the following information):**
 - OS: Winblows 11
 - Browser Brave
 - Version 170.126

**Comment by Fyb3roptik** [comment]
For now just refresh the page without saving and you will be fine. This will just be a thing until I have time
