### ISSUE TITLE
Channels fail to save an updated name after a browser refresh or feed update

### ISSUE THREAD

**Issue by jaretclifton** [Threadfin/Threadfin#408]
Describe the bug
Even as of version 1.2.10 channels fail to "save" an updated name and revert to provider naming.

Server (please complete the following information):

OS Ubuntu
Arch 64-bit
Threadfin Version and Build 1.2.10
To Reproduce

Change "Channel Name"
Save mapping
Refresh the browser page (navigating between tabs will not suffice)
Channel name will revert
Expected behavior
Renamed channel information retained.

Screenshots
N/A

Desktop (please complete the following information):

OS: Windows
Browser: Chrome
Additional context
N/A

**Comment by Fyb3roptik** [comment]
This is currently working fine for me. Is this channel marked as a live event channel in the filter? Is it a linear channel or a live event channel?

**Comment by jaretclifton** [comment]
All channels that I've tried this on are regular non live event channels. Local networks as well as cable networks. They all accept the update when I click "Done", then click "Save". Browse between tabs and the names stay updated. Refresh the page at all, the names revert.

**Comment by Fyb3roptik** [comment]
Yes this happened to me just now. Will have this fixed soon

**Comment by DionVermeulen** [comment]
Same here

**Comment by bendschs** [comment]
same here

**Comment by jaretclifton** [comment]
Can confirm it still happens with 1.2.15 which makes sense by looking at the commits. Just keeping folks updated. :)

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.16
