### ISSUE TITLE
Threadfin by default is NOT available via the other IP's

### ISSUE THREAD

**Issue by colemar** [Threadfin/Threadfin#409]
**Describe the bug**
Threadfin listens to only one IP address.

**Server (please complete the following information):**
- OS Ubuntu 22.04.3
- Arch ARM64
- Threadfin Version 1.2 Build: 10

**To Reproduce**
1. Start threadfind executable without command parameters.
2. See console message: `Web Interface:          http://10.0.0.1:34400/web/ | Threadfin is also available via the other 4 IP's.`

**Expected behavior**
`netstat -tpln` listing other IP addrs besides the one mentioned in the log.

**Screenshots**
![image](https://github.com/user-attachments/assets/0bd8fdc9-7e32-4147-a9b7-63cde7b1bbf7)
![image](https://github.com/user-attachments/assets/804234b5-fa3b-4c6c-aa0e-06982a61b3ec)

**Desktop (please complete the following information):**
Irrelevant.

**Additional context**
Also `./Threadfin_linux_amd64 -bind 62.210.x.y` has the same behaviour: listening only to 10.0.0.1.
The only way to make Threadfin listen on the primary interface 62.210.x.y seems to be editing `~/.threadfin/settings.json` and setting `"bindIpAddress": "62.210.x.y"`. Still, it declares "Threadfin is also available via the other 4 IP's" in the console log, but it listens only to 62.210.x.y.

**Comment by Fyb3roptik** [comment]
By default it will listen on the machine's IP. You can edit settings.json if you cannot get to the UI. No issue here, that is intended

**Comment by colemar** [comment]
But the console log is misleading:
Web Interface:          http://10.0.0.1:34400/web/ | Threadfin is also available via the other 4 IP's.
It is NOT available on other IP's.

**Comment by IceOfWraith** [comment]
This issue should be reopened.

I just ran into this with the Docker image as well. Had to edit the settings.json file directly for it to take the IP I wanted. I'm glad there's at least a workaround for now though.
