### ISSUE TITLE
Specific Stream Buffer per Playlist

### ISSUE THREAD

**Issue by Zalatis** [Threadfin/Threadfin#412]
**Is your feature request related to a problem? Please describe.**
Kinda, some service providers such as Pluto TV, got ads on it, and using ffmpeg or vlc can cause some troubles.
In my case I will use No Buffer for Pluto and ffmpeg for any other providers

**Describe the solution you'd like**
I would like to be abled to define No Buffer for a specific Playlist. 
And for example ffmpeg for an other (Instead of defining it generally)

**Describe alternatives you've considered**
Getting multiple instances of Threadfin running but it looks like when we try to use an other Threadfin instance the stream url got a "?" append that cause a not working stream

**Comment by Fyb3roptik** [comment]
This is done in the latest build. Use 1.2.13
