### ISSUE TITLE
Converting EPG data for Plex

### ISSUE THREAD

**Issue by philipbutts** [Threadfin/Threadfin#413]
Threadfin is awesome, but it's mildly annoying that in addition to things like EPG123, I have to find a way to parse pre-made xmltv files for plex. I have a curated list of sources, with a premade guide provided in a channelsDVR XML format. It works well with threadfin, with the exception of titling everything as "new" and giving each episode a title corresponding to today's date. Initially this caused a wave of unintended DVR recordings, everything old was new again!

Looking into it, it has something to do with the difference between "tvg" and "tv-id" tags, and the way plex interprets certain symbols like quotation marks. I've hunted around for some kind of program to automatically convert them into a format Plex could appreciate, but I came up empty. 

Then I got frustrated and looked again, and found this old project: https://github.com/kevdog114/channels-dvr-plex-xmltv-proxy

It purports to do what I'm looking for, but I can't get it to run, probably owing to my poor understanding of docker. Besides, even if it did work, it would add to the endless script spaghetti my EPG data has to pass through before it hits plex. After many frustrating days fighting this problem, I wonder if this the kind of functionality that could be integrated into threadfin itself. Could it output EPG data in different formats for disagreeable platforms? Is there some alternative solution to this issue I'm not seeing?

**Comment by Fyb3roptik** [comment]
Threadfin has a setting called Enable Non ASCII. Make sure it is disabled and it should remove any of those weird characters.

As for the tag youre talking about it is actually `tvg-id` and you should really really stop using Plex for live tv. It is broken as hell and very limiting.
