### ISSUE TITLE
1.2.10 causing massive DNS floods

### ISSUE THREAD

**Issue by derekcentrico** [Threadfin/Threadfin#416]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I noticed my Piholes going offline with thousands of queries a minute coming from my home server.  After a few days of toying around, I found the flood originating from the threadfin docker.  It is the latest version, 1.2.10.  Killing the docker ends the flood.  Flood begins as soon as the docker is operational.  In fact, it flooded DNS requests totaling 2,258 in under two minutes before I killed it off this last time around.  The domain being flooded with queries is consistently "shop.eaglemoss.com". 

I have no clue what shop.eaglemoss.com is, never frequented the site, and it is not used in my datasets for Threadfin that I can tell.  Nevertheless, it shouldn't be a massive DNS flood even if it were somehow referenced.

**Server (please complete the following information):**
- OS Ubuntu 24.04.1
- Arch 64
- Threadfin Version and Build 1.2 Build: 10   --also confirmed to occur on 1.2.9.  

**To Reproduce**
1. Run docker 
2. See flood

**Expected behavior**
No DNS floods to occur. 

**Screenshots**
![image](https://github.com/user-attachments/assets/c2846ae7-3790-48b8-886b-cbd1c9eaabd1)

**Additional context**
I use the following docker compose:

>   threadfin:
>     image: fyb3roptik/threadfin:latest
>     container_name: threadfin
>     environment:
>       - PUID=1000
>       - PGID=996
>       - TZ=America/New_York
>       - THREADFIN_DEBUG=3 
>     ports:
>       - "30044:34400"
>     volumes:
>       - /home/docker/threadfin/:/home/threadfin/conf
>       - /media/storage5/threadfin:/tmp/threadfin:rw
>     restart: unless-stopped

docker log:

> 2024/10/22 10:06:08 [Threadfin] [WARNING] Don't run this as Root!
> 2024/10/22 10:06:08 [DEBUG] Debug Level:            3
> 2024/10/22 10:06:08 [Threadfin] Version:                1.2 Build: 10
> 2024/10/22 10:06:08 [Threadfin] Database Version:       0.5.0
> 2024/10/22 10:06:08 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 1
> 2024/10/22 10:06:08 [Threadfin] Hostname:               55bc0bfd1654
> 2024/10/22 10:06:08 [Threadfin] System Folder:          /home/threadfin/conf/
> 2024/10/22 10:06:08 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
> 2024/10/22 10:06:08 [Threadfin] Temporary Folder:       /tmp/xteve/2020-06-394Y-L6UCG7/
> 2024/10/22 10:06:08 [DEBUG] Create Folder:          /tmp/xteve/2020-06-394Y-L6UCG7/
> 2024/10/22 10:06:08 [Threadfin] GitHub:                 https://github.com/Threadfin
> 2024/10/22 10:06:08 [Threadfin] Git Branch:             Master [Threadfin]
> 2024/10/22 10:06:08 [Threadfin] SSDP / DLNA:            true
> 2024/10/22 10:06:08 BRANCH:  Master
> 2024/10/22 10:06:08 [Threadfin] Update URL:             No server URL specified, update will not be performed. Branch: Master
> 2024/10/22 10:06:08 [Threadfin] UUID:                   2020-06-394Y-L6UCG7
> 2024/10/22 10:06:08 [Threadfin] Tuner (Plex / Emby):    3
> 2024/10/22 10:06:08 [Threadfin] EPG Source:             XEPG
> 2024/10/22 10:06:08 [Threadfin] Plex Channel Limit:     480
> 2024/10/22 10:06:08 [Threadfin] Unfiltered Chan. Limit: 480
> 2024/10/22 10:06:08 [Threadfin] Backup Path:            /home/docker/.xteve/backup/
> 2024/10/22 10:06:08 [DEBUG] Create Folder:          /home/docker/.xteve/backup/
> 2024/10/22 10:06:08 [DEBUG] Create backup file:     /home/docker/.xteve/backup/threadfin_auto_backup_20241022_1006.zip
> 2024/10/22 10:06:08 [Threadfin] Backup file:            /home/docker/.xteve/backup/threadfin_auto_backup_20241022_1006.zip
> 2024/10/22 10:06:08 [Threadfin] Download:               http://m3u4u.com/m3u/URL
> 2024/10/22 10:06:08 PROXY URL:  
> [SSDP] 2024/10/22 10:06:16 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53424
> 2024/10/22 10:06:19 [Threadfin] Header filename:        M3UPlus-Playlist-20241022100618.m3u filename*
> 2024/10/22 10:06:20 [Threadfin] Check File:             http://m3u4u.com/m3u/URL
> 2024/10/22 10:06:23 [Threadfin] Save File:              http://m3u4u.com/m3u/URL [ID: ID]
> 2024/10/22 10:06:23 [Threadfin] Download:               https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz
> 2024/10/22 10:06:23 PROXY URL:  
> 2024/10/22 10:06:25 [Threadfin] Extract gzip:           https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz
> [SSDP] 2024/10/22 10:06:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:06:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> 2024/10/22 10:06:33 [Threadfin] Check File:             https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz
> [SSDP] 2024/10/22 10:06:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:06:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:06:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:06:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:06:56 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:06:56 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:07:06 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:06 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> 2024/10/22 10:07:12 [Threadfin] Save File:              https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz [ID: ID]
> 2024/10/22 10:07:12 [Threadfin] Download:               http://tv.url:port/LIVE/data
> 2024/10/22 10:07:12 PROXY URL:  
> 2024/10/22 10:07:12 [Threadfin] Header filename:        epg.xml
> 2024/10/22 10:07:13 [Threadfin] Check File:             http://tv.url:port/LIVE/data
> 2024/10/22 10:07:14 [Threadfin] Save File:              http://tv.url:port/LIVE/data [ID: ID]
> 2024/10/22 10:07:14 [Threadfin] Download:               http://m3u4u.com/m3u/URL
> 2024/10/22 10:07:14 PROXY URL:  
> 2024/10/22 10:07:14 [Threadfin] [ERROR] 403: http://m3u4u.com/m3u/URL Forbidden () - EC: 0
> 2024/10/22 10:07:14 [Threadfin] [WARNING] Data is corrupt or unavailable, Threadfin now uses an older version of this file
> 2024/10/22 10:07:15 [Threadfin] [WARNING] Plex can not handle more than 480 streams. If you do not use Plex, you can ignore this warning.
> 2024/10/22 10:07:15 [Threadfin] All streams:            10000
> 2024/10/22 10:07:15 [Threadfin] Active streams:         2349
> 2024/10/22 10:07:15 [Threadfin] Filter:                 23
> 2024/10/22 10:07:15 [Threadfin] Web Interface:          http://172.18.0.20:34400/web/ | Threadfin is also available via the other 2 IP's.
> 2024/10/22 10:07:15 [Threadfin] XEPG:                   Parse XMLTV file: M3U4U
> 2024/10/22 10:07:15 [Threadfin] XEPG:                   Parse XMLTV file: Provider
> 2024/10/22 10:07:16 [Threadfin] XEPG:                   Parse XMLTV file: Kevev ALL
> [SSDP] 2024/10/22 10:07:16 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:16 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:07:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:07:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:07:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:07:56 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:07:56 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> 2024/10/22 10:08:01 [Threadfin] XEPG:                   Update database
> 2024/10/22 10:08:01 [Threadfin] XEPG:                   Save DB file
> 2024/10/22 10:08:01 [Threadfin] XEPG:                   Map channels
> 2024/10/22 10:08:01 [Threadfin] XEPG:                   Cleanup database
> 2024/10/22 10:08:02 [Threadfin] XEPG Channels:          1064
> 2024/10/22 10:08:02 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
> [SSDP] 2024/10/22 10:08:06 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:08:06 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> 2024/10/22 10:08:08 [Threadfin] Create Dummy Guide:     Time offset -0400 - GEO
> 2024/10/22 10:08:08 [Threadfin] [ERROR] strconv.Atoi: parsing "(no tvg-id)": invalid syntax () - EC: 0
> 2024/10/22 10:08:12 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/conf/data/threadfin.xml.gz)
> 2024/10/22 10:08:12 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/conf/data/threadfin.m3u)
> 2024/10/22 10:08:13 [Threadfin] XEPG:                   Ready to use
> 2024/10/22 10:08:13 [Threadfin] Image Caching:          Images are cached (1006)
> [SSDP] 2024/10/22 10:08:16 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:08:16 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:08:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:08:26 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:08:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:08:36 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663
> [SSDP] 2024/10/22 10:08:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 172.18.0.1:53325
> [SSDP] 2024/10/22 10:08:46 received M-SEARCH MAN="ssdp:discover" ST=upnp:rootdevice from 169.254.108.205:43663

**Comment by derekcentrico** [comment]
I didn't think 1.2.9 was affected.  However, the flood started after ~5 minutes of threadfin running.  Going back to test 1.2.8 for longer duration to confirm.

**Comment by derekcentrico** [comment]
Okay, still flood on 1.2.8.  Started happening about 10 minutes in.  This is super strange.  Logs show nothing.

Funny enough, this started around the time m3u4u.com went into offline mode for its download functions on EPGs.  

Totally going to go on a wild theory:  Threadfin process for pulling the XML EPG flooded their site during their outage and got my IP banned.  Then, Threadfin seems to try to do something to pull the XML which is trying to hit that domain dozens of times a second.  Threadfin is hitting the DNS to get the IP lookup for that request which also floods my Pihole offline because the flood created a ban on M3U4U.

**Comment by Fyb3roptik** [comment]
This is not part of the Threadfin software. Please join the discord for support on this
