### ISSUE TITLE
Update 1.2.12, cannot tune channel

### ISSUE THREAD

**Issue by Serph91P** [Threadfin/Threadfin#420]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
After the Update to 1.2.12 I cannot watch anything anymore. The pleayer reports that the tuner is not reachable.
I attached the log where you can see everything works until you try to tune a channel. After that the webinterface is also not reachable anymore.

**Server (please complete the following information):**
- OS: Debian / Docker
- Arch Intel 64 Bit
- Threadfin Version and Build: Version: 1.2 Build: 12

**To Reproduce**
Install latest update.
try to tune a channel
get error
check log

**Expected behavior**
channel to be tuned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser Firefox
 - Version 131.0.3

**Additional context**
````
2024-10-23 06:06:28
2024/10/22 23:06:28 [Threadfin] XEPG: Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
2024-10-23 06:06:30
2024/10/22 23:06:30 [Threadfin] XEPG: Compress XMLTV file (/home/threadfin/conf/data/threadfin.xml.gz)
2024-10-23 06:06:30
2024/10/22 23:06:30 [Threadfin] XEPG: Create M3U file (/home/threadfin/conf/data/threadfin.m3u)
2024-10-23 06:07:04
2024/10/22 23:07:04 http: panic serving 172.18.0.11:58856: interface conversion: interface {} is nil, not string
2024-10-23 06:07:04
goroutine 478 [running]:
2024-10-23 06:07:04
net/http.(*conn).serve.func1()
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:1825 +0xbf
2024-10-23 06:07:04
panic({0x83e020, 0xc0045bbad0})
2024-10-23 06:07:04
/usr/local/go/src/runtime/panic.go:844 +0x258
2024-10-23 06:07:04
threadfin/src.Stream({0x9f6790, 0xc0126de2a0}, 0xc013a22800)
2024-10-23 06:07:04
/src/src/webserver.go:147 +0x973
2024-10-23 06:07:04
net/http.HandlerFunc.ServeHTTP(0x7f7643acc408?, {0x9f6790?, 0xc0126de2a0?}, 0x40efe5?)
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:2084 +0x2f
2024-10-23 06:07:04
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f6790, 0xc0126de2a0}, 0xc013a22800)
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:2462 +0x149
2024-10-23 06:07:04
net/http.serverHandler.ServeHTTP({0xc0045bb8f0?}, {0x9f6790, 0xc0126de2a0}, 0xc013a22800)
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:2916 +0x43b
2024-10-23 06:07:04
net/http.(*conn).serve(0xc0126c4140, {0x9f6b38, 0xc007fe1a10})
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:1966 +0x5d7
2024-10-23 06:07:04
created by net/http.(*Server).Serve
2024-10-23 06:07:04
/usr/local/go/src/net/http/server.go:3071 +0x4db
````

**Comment by Serph91P** [comment]
Reverting to 1.2.10 is working again.

**Comment by JustBeta** [comment]
Yes, I confirm.
Same problem, same solution

**Comment by kmaid** [comment]
I am having this problem too

**Comment by bendschs** [comment]
same here

**Comment by Fyb3roptik** [comment]
Will fix it today

**Comment by Fyb3roptik** [comment]
1.2.13 incoming with the patch. You should be able to go into your Playlists and hit Save to set it initially. This patch will safely check that now and set it to the global setting

**Comment by Serph91P** [comment]
> 1.2.13 incoming with the patch. You should be able to go into your Playlists and hit Save to set it initially. This patch will safely check that now and set it to the global setting

I dont quite understand there is already a playlist presend so why do I have to do this now?

**Comment by jeffreyswiggins** [comment]
> 1.2.13 incoming with the patch. You should be able to go into your Playlists and hit Save to set it initially. This patch will safely check that now and set it to the global setting

thank you.... i thought i had done that but I guess i was just doing an "update" to that and the EPG and not saving.  I have to do that once a week or so for my provider so i started off thinking that was my problem this morning before I went down a rabbit-hole for a few minutes and came here to see if new versions had been released and issues.  I do use Watchtower for updates and it send notifications for updates to my Slack so I could see it was updated and that led me here.

Fixed for the time being using the "Save" on the current release

**Comment by Fyb3roptik** [comment]
> > 1.2.13 incoming with the patch. You should be able to go into your Playlists and hit Save to set it initially. This patch will safely check that now and set it to the global setting
> 
> I dont quite understand there is already a playlist presend so why do I have to do this now?

Read the release notes. There is a new setting there for Buffer in the Playlist. Hitting Save will set it. The newest build though takes that into account and sets it for you if you havent

**Comment by bendschs** [comment]
still not working for me.

**Comment by Fyb3roptik** [comment]
Open all existing Playlists and hit Save

**Comment by JustBeta** [comment]
It's ok for me, after resynchronization.
