### ISSUE TITLE
Xtream support

### ISSUE THREAD

**Issue by ReeZey** [Threadfin/Threadfin#424]
**Is your feature request related to a problem? Please describe.**
Is there any plans to support the [Xtream](https://xtream-ui.org/api-xtreamui-xtreamcode/) format?

**Describe the solution you'd like**
Being able to use the Xtream credentials

**Describe alternatives you've considered**
Right now the only one supporting Xtream is [Jellyfin.Xtream](https://github.com/Kevinjil/Jellyfin.Xtream)

**Additional context**
Nothin :)

**Comment by neotwix** [comment]
> Right now the only one supporting Xtream is [Jellyfin.Xtream](https://github.com/Kevinjil/Jellyfin.Xtream)
Not agree
you could also use 

https://github.com/kornflex/iptv-strmmaker

and create strm file from your  Xstream Service.

**Comment by Fyb3roptik** [comment]
Will not be supporting this
