### ISSUE TITLE
Application crashes on latest builds when trying to watch TV from Emby

### ISSUE THREAD

**Issue by carloss66** [Threadfin/Threadfin#425]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS Linux - Unraid
- Arch x64
- Threadfin Version and Build [1.2.15]

**To Reproduce**
1. Setup live TV on Emby and use Threadfin as TV source.
2. Try to play live TV on Emby.
3. Threadfin crashes

**Expected behavior**
Expect live TV to work as it used to before.

**Log**
2024/10/24 07:10:35 [Threadfin] XEPG:                   Cleanup database
2024/10/24 07:10:35 [Threadfin] XEPG Channels:          400
2024/10/24 07:10:35 [Threadfin] [WARNING] XEPG requires an XMLTV file.
2024/10/24 07:10:35 [Threadfin] XEPG:                   Update database
2024/10/24 07:10:35 [Threadfin] XEPG:                   Save DB file
2024/10/24 07:10:35 [Threadfin] XEPG:                   Map channels
2024/10/24 07:10:35 [Threadfin] XEPG:                   Cleanup database
2024/10/24 07:10:35 [Threadfin] XEPG Channels:          400
2024/10/24 07:10:35 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
2024/10/24 07:10:35 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/conf/data/threadfin.xml.gz)
2024/10/24 07:10:35 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/conf/data/threadfin.m3u)
2024/10/24 07:10:35 [Threadfin] XEPG:                   Ready to use
2024/10/24 07:16:43 [Threadfin] Buffer:                 true [ffmpeg]
2024/10/24 07:16:43 [Threadfin] Channel Name:           NBC (KXAS) Fort Worth TX
2024/10/24 07:16:43 [Threadfin] Client User-Agent:      VLC/3.0.0-git LibVLC/3.0.0-git
2024/10/24 07:16:44 http: panic serving 172.17.0.1:36854: interface conversion: interface {} is nil, not string
goroutine 181 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x83e020, 0xc0007b2b40})
        /usr/local/go/src/runtime/panic.go:844 +0x258
threadfin/src.bufferingStream({0xc0005bb7e8, 0x14}, {0xc0003f2700, 0x67}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /src/src/buffer.go:183 +0x1e65
threadfin/src.Stream({0x9f6790, 0xc0001b41c0}, 0xc00017c000)
        /src/src/webserver.go:185 +0x938
net/http.HandlerFunc.ServeHTTP(0x149bda376138?, {0x9f6790?, 0xc0001b41c0?}, 0x40efe5?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f6790, 0xc0001b41c0}, 0xc00017c000)
        /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000910390?}, {0x9f6790, 0xc0001b41c0}, 0xc00017c000)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0005d2000, {0x9f6b38, 0xc0009cfe00})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
For help run: /home/threadfin/bin/threadfin -h

**Additional context**
Threadfin running on a Docker container in Unraid. Using Emby to watch TV. This has been working fine for over a year, but it started crashing recently after the recent updates.

**Comment by sm0kingm4n** [comment]
same for me please fix this

**Comment by doofit** [comment]
Yepp, same for me with Plex.

**Comment by jsbear** [comment]
Same issue on both Plex and Emby, reverted back 12.1.10 for now ...

**Comment by Fyb3roptik** [comment]
You need to go in and click Save on Playlists. You need to make sure a Buffer option is set for any existing Playlists
