### ISSUE TITLE
"CHECK FILE" FROZEN

### ISSUE THREAD

**Issue by bgraves49** [Threadfin/Threadfin#428]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
UI will not load on version 1.2.2 and above (including newest) with certain lists loaded.  

<img width="993" alt="nonworking" src="https://github.com/user-attachments/assets/44f288ab-c4c6-4b87-91f8-4337b36cd8f1">

**Server (please complete the following information):**
- OS [Windows 11 Pro]
- Arch [Intel 64 Bit]
- Threadfin Version and Build [1.2.2+]

**To Reproduce**
1. Start exe with config set
2. UI will never load, only a lingering "error" on CMD logs - CHECK FILE

**Expected behavior**
Service to fully start and UI to load within 2 minutes.

**Screenshots**
Non Working: 
<img width="993" alt="nonworking" src="https://github.com/user-attachments/assets/33d6e898-f53c-46ca-81b1-5b9b0e00efbb">

Working (v1.2.1): 
<img width="1174" alt="Screenshot 2024-10-26 at 12 53 56 AM" src="https://github.com/user-attachments/assets/0b69220c-a7af-48b7-a817-a9f88ad26279">

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser [Firefox]
 - Version [131.0.3]

**Additional context**
No configuration changes are made between switching the exes but only older versions work.   
Trying on a blank config does not work either. 
Smaller lists work fine.
xmltv is fine from the same source.

**Comment by Fyb3roptik** [comment]
Your m3u is too large. You need to use a service like m3u4u to cut out the 24/7 vod channels. Threadfin now assigns an id for those blank channels so that's why it takes forever

**Comment by bgraves49** [comment]
> Your m3u is too large. You need to use a service like m3u4u to cut out the 24/7 vod channels. Threadfin now assigns an id for those blank channels so that's why it takes forever

Isn't that kind of the point of the software is to take in the list and limit it itself to avoid that?  

Anyways thank I will try that

**Comment by dotbanana** [comment]
As bgraves49 mentioned i kind of don't see the point of this software anymore in this state.
