### ISSUE TITLE
Accentuated characters dissapears from xmltv

### ISSUE THREAD

**Issue by danichispa** [Threadfin/Threadfin#43]
Hello, when there is some xmltv with special characters, like accents (á é í...), Threadfin's xmltv outputs without those characters. Would it be possible that they did not disappear?

**Comment by Fyb3roptik** [comment]
This is a feature not a bug. Non ASCII are stripped out due to no support for them in some clients.

**Comment by xtinct101** [comment]
could you add a toggle to keep/remove these characters so we can have the best of both worlds??

**Comment by Fyb3roptik** [comment]
Sure thing!
