### ISSUE TITLE
http: panic serving <IP:PORT>: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by corotte** [Threadfin/Threadfin#432]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Since 1.2.11 update until current 1.2.15, Threadfin crash as soon as Plex open a live channel with the error below.
The workaround is to revert back to 1.2.10 and disable auto-update on Threadfin settings.

EDIT : reading changelog and what can cause this error, it SEEM to be related to one of the change in 1.2.11 as : 
Added the ability to force ffmpeg to use HTTP if provider has HTTPS (in Settings with FFMPEG settings)

http: panic serving <IP:PORT>: interface conversion: interface {} is nil, not string
goroutine <NUMBER MAY CHANGE> [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
panic({0x83e020, 0xc004102ae0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
threadfin/src.Stream({0x9f67b0, 0xc001186700}, 0xc00153b400)
        /home/runner/work/Threadfin/Threadfin/src/webserver.go:147 +0x973
net/http.HandlerFunc.ServeHTTP(0x765e75e45598?, {0x9f67b0?, 0xc001186700?}, 0x40efe5?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f67b0, 0xc001186700}, 0xc00153b400)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0041029f0?}, {0x9f67b0, 0xc001186700}, 0xc00153b400)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0060a60a0, {0x9f6b58, 0xc00595ede0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db

**Server (please complete the following information):**
- OS : Linux Mint 21.3                 
          Kernel: Linux 6.8.0-45-generic
    Architecture: x86-64
- Threadfin Version and Build 1.2.11-15

**To Reproduce**
1. Open a live stream from plex and get a error with the tuner
2. Check if Threadfin is crashed
3. Check for system log to find this error

**Expected behavior**
Should load just fine like it does on 1.2.10

**Comment by joshjryan** [comment]
See #430

**Comment by Fyb3roptik** [comment]
Open your playlists and hit Save
