### ISSUE TITLE
Feature - API endpoint to update / change a filter

### ISSUE THREAD

**Issue by Jacob-Lasky** [Threadfin/Threadfin#436]
**Is your feature request related to a problem? Please describe.**
My EPG gets updated pretty regularly but sports 'fixtures' change the channel that they're on. The filter doesn't read the EPG first, so I have to shuffle around my channels.

**Describe the solution you'd like**
I'd like an endpoint which lets me add, remove and update filters. This would let me do something like:
{Filter Word, Channel 1 Filter, Channel 2 Filter} --> {Filter Word, Channel 2 Filter, Channel 3 Filter}

**Describe alternatives you've considered**
The alternative is doing this manually. But I want something that would let me programatically update the filter.

**Comment by Fyb3roptik** [comment]
This is not clear on what it is youre looking for. Your channel numbers should not be changing and honestly shouldnt really matter. Just make sure they are in the same order in mapping and that is how they will show. I dont know what you mean by sports "fixtures"

**Comment by Jacob-Lasky** [comment]
It's all about automating my experience. A fixture is a sporting event.

For example, I watch college football. The games are only on Saturdays. I have local channels that I simply don't want to see except on Saturdays.

I wrote a script in Python yesterday which does this for me. It will update a filter in the `settings.json` and then restart threadfin which will recreate the mapping. I simply thought that an endpoint which would let me update a script and then regenerate the mappings based on the new filter would be nicer than restarting Threadfin.
