### ISSUE TITLE
ignore/omit XMLTV sources with channels containing invalid characters 

### ISSUE THREAD

**Issue by princinv** [Threadfin/Threadfin#437]
Problem:
I notice i am unable to even import an xmltv source which has a channel  with a semicolon

```
XML syntax error on line 275: invalid character entity &h (no semicolon)
```

Solution:
For threadfin to automatically ignore/omit these lines in xmltv files. (possibly with notification)

I know that i can remove it manually, which i will do. But it seems like it would be easy to implement.

**Comment by joshjryan** [comment]
@princinv can you add an example of the line causing the issue?   ...based on that issue, I think it might be saying that you're missing a semicolon.

**Comment by Fyb3roptik** [comment]
Please use a valid XML file. I will not be fixing it to allow for edge cases
