### ISSUE TITLE
Add header Origin and Referer, along with user agent

### ISSUE THREAD

**Issue by Hula1267** [Threadfin/Threadfin#438]
I need these to load some m3u feeds.

**Comment by purplescorpion1** [comment]
Use mitmproxyserver to inject headers.

I wrote a basic script but you can add in what ever headers are required

https://github.com/purplescorpion1/mitmproxy-for-threadfin

**Comment by Fyb3roptik** [comment]
I can add these in, would you want them in Settings near the User Agent setting?

**Comment by JHarding86** [comment]
The addition of this would be very much appreciated!

**Comment by xCrazed** [comment]
User Agent and  Referrer not saving after click save on setting page. 

Also as  @purplescorpion1 mentioned above... can they be added to the playlist settings as these would differ per playlist and can't be set as a global argument for all playlists

**Comment by lkorth** [comment]
I noticed a few things that may be bugs, it looks like updating the `Referer` on the settings page never saves the field in `settings.json`. Additionally if I manually update `settings.json` with the `Referer` and restart the service, it may not be being sent as I was still seeing 403s for a playlist. When using https://github.com/dtankdempse/m3u-playlist-proxy the playlist does work, so I believe it does have to do with Threadfin sending the `Referer` and possibly `User-Agent`.

**Comment by Fyb3roptik** [comment]
> I noticed a few things that may be bugs, it looks like updating the `Referer` on the settings page never saves the field in `settings.json`. Additionally if I manually update `settings.json` with the `Referer` and restart the service, it may not be being sent as I was still seeing 403s for a playlist. When using https://github.com/dtankdempse/m3u-playlist-proxy the playlist does work, so I believe it does have to do with Threadfin sending the `Referer` and possibly `User-Agent`.

It will send it only if the buffer is enabled, otherwise Threadfin simply does an http redirect. 

I will check on it not saving correctly though

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.17. Again you must run a buffer and VLC will not do Origin

**Comment by Permanently** [comment]
> If you are adding them in they would have to be in the playlist settings as these would differ per playlist and can't be set as a global argument for all playlists

@Fyb3roptik just echoing what @purplescorpion1 said here; in some instances people will want to add different Origins and Referrers for specific playlists - and I don't think spinning up multiple instances just to have different headers for playlists is ideal 😅
