### ISSUE TITLE
Mapped channels disappearing

### ISSUE THREAD

**Issue by wanderleyteixeira** [Threadfin/Threadfin#439]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Channels that are available in the Filter tab not shown in Mapping tab.

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log]

Docker:
2024-11-05 18:49:41 [Threadfin] [WARNING] Don't run this as Root!
2024-11-05 18:49:41 [Threadfin] Version:                1.2 Build: 15
2024-11-05 18:49:41 [Threadfin] Database Version:       0.5.0

**To Reproduce**
1. Go to 'Filter'
2. Channels are active and available
3. Go to 'Mapping'
4. Some channels are not available 

**Expected behavior**
All channels that are in the active stream in Filter tab to be shown as available to be mapped after updating image
Version: 1.2 Build: 2
Database Version: 0.5.0

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fyb3roptik** [comment]
Do the channel numbers overlap?

**Comment by wanderleyteixeira** [comment]
Yes, because I updated the input playlists coming from m3u-filter. I was able to "fix" it by removing the playlists and re-adding them. Then do all the mapping again.

**Comment by Fyb3roptik** [comment]
Yeah you cant have overlapping channel numbers, it no longer auto fixes it as that caused more issues

**Comment by Fyb3roptik** [comment]
I will have some fixes for that soon, just have to get some time to dedicate
