### ISSUE TITLE
Logos not saving in Mapping

### ISSUE THREAD

**Issue by thelazurus** [Threadfin/Threadfin#440]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Setting logos in Mapping doesn't save

**Server (please complete the following information):**
- OS Unraid
- Arch Intel x64
- Threadfin Version and Build 1.2 (15)

**To Reproduce**
1. Go to 'Mapping'
2. Click on a channel
3. Add URL to logo field
4. Logo will show after hitting done and save, but refreshing page shows that logos did not save

**Expected behavior**
Logos saved in XEPG

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 130.0.2849.68

**Comment by Fyb3roptik** [comment]
You have to hit Save on the Mapping page too...

**Comment by thelazurus** [comment]
I did, but it was my issue. I had checked Update Channel Logos thinking I had to have it checked to actually save the change, not realizing that checking that means it tries to pull a logo from the XMLTV.


Thanks.
