### ISSUE TITLE
Cant import m3u

### ISSUE THREAD

**Issue by rclarsfull** [Threadfin/Threadfin#441]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]: Debian 12

- Threadfin Version and Build [to be found in the Threadfin log]:
1.2 Build: 15

**To Reproduce**
1. Run Container
2. add Playlist
3. loads forever, logs say: 2024/11/08 08:58:44 [Threadfin] Check File:             http://cf.mar-cdn.me/get.php?username=..........

**Expected behavior**
Takes some time to check and adds playlist with channels.

**Screenshots**
After reloding the page:
![image](https://github.com/user-attachments/assets/136baafc-65ee-4406-8767-1ac5119b7194)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser chrome,

**Additional context**
**Logs**:
 2024/11/08 08:56:46 [Threadfin] Database Version:       0.5.0
threadfin  | 2024/11/08 08:56:46 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 1
threadfin  | 2024/11/08 08:56:46 [Threadfin] Hostname:               faefcde52ec4
threadfin  | 2024/11/08 08:56:46 [Threadfin] System Folder:          /home/threadfin/conf/
threadfin  | 2024/11/08 08:56:46 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
threadfin  | 2024/11/08 08:56:46 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-11-NNT1-LBTZQH/
threadfin  | 2024/11/08 08:56:46 [Threadfin] GitHub:                 https://github.com/Threadfin
threadfin  | 2024/11/08 08:56:46 [Threadfin] Git Branch:             Main [Threadfin]
threadfin  | 2024/11/08 08:56:46 SOURCE:  PMS
threadfin  | 2024/11/08 08:56:46 [Threadfin] SSDP / DLNA:            true
threadfin  | 2024/11/08 08:56:46 [Threadfin] [WARNING] Updates are disabled in the settings
threadfin  | 2024/11/08 08:56:46 [Threadfin] UUID:                   2024-11-NNT1-LBTZQH
threadfin  | 2024/11/08 08:56:46 [Threadfin] Tuner (Plex / Emby):    1
threadfin  | 2024/11/08 08:56:46 [Threadfin] EPG Source:             PMS
threadfin  | 2024/11/08 08:56:46 [Threadfin] Plex Channel Limit:     480
threadfin  | 2024/11/08 08:56:46 [Threadfin] Unfiltered Chan. Limit: 480
threadfin  | 2024/11/08 08:56:46 [Threadfin] All streams:            0
threadfin  | 2024/11/08 08:56:46 [Threadfin] Active streams:         0
threadfin  | 2024/11/08 08:56:46 [Threadfin] Filter:                 0
threadfin  | 2024/11/08 08:56:46 [Threadfin] Web Interface:          http://172.18.0.2:34400/web/ | Threadfin is also available via the other 2 IP's.
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:20 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:30 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:40 SOURCE:  PMS
threadfin  | 2024/11/08 08:57:50 SOURCE:  PMS
threadfin  | 2024/11/08 08:58:00 SOURCE:  PMS
threadfin  | 2024/11/08 08:58:10 SOURCE:  PMS
threadfin  | 2024/11/08 08:58:10 [Threadfin] Download:               http://cf.mar-cdn.me/get.php?username=xxxx&password=xxxxxxxx&type=m3u_plus&output=ts
threadfin  | 2024/11/08 08:58:10 PROXY URL:
threadfin  | 2024/11/08 08:58:35 [Threadfin] Header filename:        tv_channels_c756b61b1cf2_plus.m3u
threadfin  | 2024/11/08 08:58:44 [Threadfin] Check File:             http://cf.mar-cdn.me/get.php?username=xxxx&password=xxxxxx&type=m3u_plus&output=ts
threadfin  | 2024/11/08 09:12:42 SOURCE:  PMS
threadfin  | 2024/11/08 09:13:02 SOURCE:  PMS
**Docker comose**:
 threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=TZ=Europe/Berlin
    volumes:
      - ./threadfin/data/conf:/home/threadfin/conf
      - ./threadfin/data/temp:/tmp/threadfin:rw
    restart: unless-stopped

**Comment by technologist-osl** [comment]
+1

**Comment by sebrk** [comment]
+1

**Comment by rclarsfull** [comment]
I now went to stream master. Worked for me. https://senexcrenshaw.github.io/StreamMaster/

**Comment by bgraves49** [comment]
you'll likely be told that you need to limit your 24/7 channels.  That seems to be the new answer instead of adding something to work around it.

**Comment by Fyb3roptik** [comment]
Please use discord for things like this

**Comment by sebrk** [comment]
Uhm... is this being closed because of feisty comments or because we should only use discord?

Either way, happy to help on the issue if the base issue is handling massive m3u.
