### ISSUE TITLE
Error src/toolchain.go:64:20: undefined: avfs.NewUtils

### ISSUE THREAD

**Issue by andrewvint** [Threadfin/Threadfin#442]
I get the following error when i try to run go build Threadfin

src/toolchain.go:64:20: undefined: avfs.NewUtils

I am not sure what i am doing wrong as i have ru n the go get on all the dependencies to update them.

Any advice welcome

**Comment by Fyb3roptik** [comment]
```
go mod download

go run threadfin.go -dev -debug=3
```

If you want to just run it live in console

```
go build threadfin.go && ./threadfin -dev -debug=3
```

**Comment by andrewvint** [comment]
Still get the following error running both the commands shown above

# threadfin/src
src/toolchain.go:64:20: undefined: avfs.NewUtils
