### ISSUE TITLE
Playback error in Plex

### ISSUE THREAD

**Issue by Hzipp** [Threadfin/Threadfin#443]
First of all, a huge thumbs up for the fantastic work you're doing! 🥇

That said, whenever I try to click on any stream in Plex app or Browser, I keep getting the following error:
"Could not tune channel. Please check your tuner or antenna."

I've gone through all the bug reports/Issues and tried the "Open your playlists and hit Save" solution, but unfortunately, nothing has changed or worked.

I even tried reinstalling Threadfin completely, but the issue persists.

Is there something I'm missing or doing wrong? When I check the log, it doesn't show any errors or issues.

Thank you!

![image](https://github.com/user-attachments/assets/cf5423c6-7e7e-4b03-af2c-d16c6e7fde13)

**Comment by Fyb3roptik** [comment]
The feed you're trying to play. Is it HLS or MPEGTS?

**Comment by Hzipp** [comment]
Apologies for the unclear response. - But I believe it’s MPEG-TS, since the link ends with .ts extension.

**Comment by metrotyranno** [comment]
Not sure if related but after updating from 1.2.0 to 1.2.15 my jellyfin won't start playing either. The following is thrown to stderr

2024/11/10 19:49:15 [Threadfin] Buffer:                 true [vlc]
2024/11/10 19:49:15 [Threadfin] Channel Name:           ...:)......
2024/11/10 19:49:15 [Threadfin] Client User-Agent:      Jellyfin-Server/10.10.1
2024/11/10 19:49:15 http: panic serving 127.0.0.1:52429: interface conversion: interface {} is nil, not string
goroutine 244 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
panic({0x15537c0, 0xc0070dec30})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
threadfin/src.bufferingStream({0xc00a2c4990, 0x14}, {0xc001e93780, 0x40}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
	/home/runner/work/Threadfin/Threadfin/src/buffer.go:183 +0x1e65
threadfin/src.Stream({0x17160c0, 0xc0000fc620}, 0xc00639c200)
	/home/runner/work/Threadfin/Threadfin/src/webserver.go:185 +0x938
net/http.HandlerFunc.ServeHTTP(0x253baedd240?, {0x17160c0?, 0xc0000fc620?}, 0x111d7c5?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x17160c0, 0xc0000fc620}, 0xc00639c200)
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0070de900?}, {0x17160c0, 0xc0000fc620}, 0xc00639c200)
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0010081e0, {0x1716438, 0xc0072f8b10})
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db

**Comment by PiratesIRC** [comment]
> Not sure if related but after updating from 1.2.0 to 1.2.15 my jellyfin won't start playing either. The following is thrown 2024/11/10 19:49:15 [Threadfin] Buffer: true [vlc] 2024/11/10 19:49:15 [Threadfin] Channel Name: ...:)...... 2024/11/10 19:49:15 [Threadfin] Client User-Agent: Jellyfin-Server/10.10.1 2024/11/10 19:49:15 http: panic serving 127.0.0.1:52429: interface conversion: interface {} is nil, not string goroutine 244 [running]: net/http.(*conn).serve.func1() /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf panic({0x15537c0, 0xc0070dec30}) /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258 threadfin/src.bufferingStream({0xc00a2c4990, 0x14}, {0xc001e93780, 0x40}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...) /home/runner/work/Threadfin/Threadfin/src/buffer.go:183 +0x1e65 threadfin/src.Stream({0x17160c0, 0xc0000fc620}, 0xc00639c200) /home/runner/work/Threadfin/Threadfin/src/webserver.go:185 +0x938 net/http.HandlerFunc.ServeHTTP(0x253baedd240?, {0x17160c0?, 0xc0000fc620?}, 0x111d7c5?) /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f net/http.(*ServeMux).ServeHTTP(0x0?, {0x17160c0, 0xc0000fc620}, 0xc00639c200) /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149 net/http.serverHandler.ServeHTTP({0xc0070de900?}, {0x17160c0, 0xc0000fc620}, 0xc00639c200) /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b net/http.(*conn).serve(0xc0010081e0, {0x1716438, 0xc0072f8b10}) /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7 created by net/http.(*Server).Serve /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db

See #430
