### ISSUE TITLE
[Threadfin] [ERROR] strconv.Atoi: parsing "dummy": invalid syntax () - EC: 0

### ISSUE THREAD

**Issue by KevinLiss** [Threadfin/Threadfin#445]
**Describe the bug**
Cannot create/import playlist. After "Saving" in Mapping, error in title is shown

**Server (please complete the following information):**
- docker:latest
- Debian x64

**To Reproduce**
1. Docker-compose up threadfin
2. import playlist
3. go to mapping, select one or bulk (doesnt matter)
4. select xmltv file, enter name at "xmltv channel"
5. click ok, click save
6. error appears

**Screenshots**
![{5CEBD682-B6D6-464F-86B9-3A6E8B13D62E}](https://github.com/user-attachments/assets/27fb8986-cfaf-4bf1-b36c-ee21d481b378)
![{1E7075F5-061B-4A13-8569-DE54A92D087D}](https://github.com/user-attachments/assets/c8186368-96e7-4e78-87c6-78ad7690ac66)

**Comment by joshjryan** [comment]
@KevinLiss you need to choose a real value form the auto-complete for the EPG (e.g. for Dummy, it'd be "PPV" or "240_Minutes" or "60_Minutes" or whatever).  you can't just type a random value in "XMLTV Channel".

**Comment by KevinLiss** [comment]
Typed "240_Minutes" in and it worked, maybe there should be some auto complete, dropdown or so

**Comment by Fyb3roptik** [comment]
Yeah there is a lot of UI quirks that were inherited. Threadfin is meant to be a bridge to an eventual better successor
