### ISSUE TITLE
Playback error in Plex

### ISSUE THREAD

**Issue by Hzipp** [Threadfin/Threadfin#448]
whenever I try to click on any stream in Plex app or Browser, I keep getting the following error:
"Could not tune channel. Please check your tuner or antenna."

I've gone through all the bug reports/Issues and tried the "Open your playlists and hit Save" solution, but unfortunately, nothing has changed or worked.

![image](https://github.com/user-attachments/assets/443edcc8-c0b2-4166-8243-a0265cc93615)

I even tried reinstalling Threadfin completely, but the issue persists.
And like i said, i already did try: https://github.com/Threadfin/Threadfin/issues/430

Is there something I'm missing or doing wrong? When I check the log, it doesn't show any errors or issues.

Thank you!

image

**Comment by Fyb3roptik** [comment]
Ping in the Discord for help with this, this isnt a threadfin issue
