### ISSUE TITLE
goroutine error when starting a stream

### ISSUE THREAD

**Issue by shiznat** [Threadfin/Threadfin#453]
This configuration has been working for many months and was working until a week ago. I think updating Threadfin may have broken it but I'm not 100% positive on that as there may have been other minor updates my NAS received.

2024/11/17 01:40:02 [Threadfin] XEPG:                   Ready to use
2024/11/17 01:41:06 [Threadfin] Buffer:                 true [ffmpeg]
2024/11/17 01:41:06 [Threadfin] Channel Name:           UK: Premier Sports 1
2024/11/17 01:41:06 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
2024/11/17 01:41:07 http: panic serving 10.0.3.1:46848: interface conversion: interface {} is nil, not string
goroutine 91 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x83e020, 0xc00007d800})
        /usr/local/go/src/runtime/panic.go:844 +0x258
threadfin/src.bufferingStream({0xc001778b40, 0x14}, {0xc001449490, 0x63}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /src/src/buffer.go:183 +0x1e65
threadfin/src.Stream({0x9f6790, 0xc0025c60e0}, 0xc000c00000)
        /src/src/webserver.go:185 +0x938
net/http.HandlerFunc.ServeHTTP(0x7fa494726698?, {0x9f6790?, 0xc0025c60e0?}, 0x40efe5?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f6790, 0xc0025c60e0}, 0xc000c00000)
        /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc002d38390?}, {0x9f6790, 0xc0025c60e0}, 0xc000c00000)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0025d2000, {0x9f6b38, 0xc003d2a030})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db

QNAP Docker
[Threadfin] Version:                1.2 Build: 15
[Threadfin] Database Version:       0.5.0
[Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 1

I am attempting to stream through Plex DVR when I receive this error. It seems that the Threadfin WEB UI becomes completely unresponsive once I get this error.

Thanks!

**Comment by Fyb3roptik** [comment]
Open and save your playlists. The buffer has not been saved for your playlist

**Comment by shiznat** [comment]
Thank you, that worked. Sorry, I haven't come across this one before. Cheers
