### ISSUE TITLE
Channels fail to save an updated name after a browser refresh or feed update

### ISSUE THREAD

**Issue by jaretclifton** [Threadfin/Threadfin#456]
Describe the bug
Bug #408 was closed. Issue still exists.
Even as of version 1.2.16 channels fail to "save" an updated name and revert to provider naming.

Server (please complete the following information):

OS Ubuntu
Arch 64-bit
Threadfin Version and Build 1.2.16
To Reproduce

Change "Channel Name"
Save mapping
Refresh the browser page (navigating between tabs will not suffice)
Channel name will revert
Expected behavior
Renamed channel information retained.

Screenshots
N/A

Desktop (please complete the following information):

OS: Windows
Browser: Chrome
Additional context
N/A

**Comment by Fyb3roptik** [comment]
This is not happening for me. Are you sure you saved the mapping and not just the modal? You have to save both

**Comment by jaretclifton** [comment]
Can confirm I saved both the modal and the mappings. The exact behavior is seen as in the previous releases. Saving shows the new channel name while switching tabs within the application. For further testing, I've pressed the save button multiple times after navigating around within the app. The moment a page refresh is triggered, the previous channel name is displayed. It's like it's not persisting the update to the database.

**Comment by DionVermeulen** [comment]
I'm having the same issue with the latest version (1.2.18)

**Comment by jaretclifton** [comment]
This still happens even after toggling "Update channel name" on, Done, Save, Refresh. Then editing the channel again, the box for "update channel name" is now unchecked upon loading. Rename. Done. Save. Refresh. Reverts to previous name. Opening another bug on this since it's still an issue.
