### ISSUE TITLE
Allow optionally including the port number on images and playlists.

### ISSUE THREAD

**Issue by lephino** [Threadfin/Threadfin#459]
**Is your feature request related to a problem? Please describe.**
Running threadfin behind a reverse proxy makes it difficult when the guide adds the port number and protocol into both the m3u file and the xml file.  Plex when you have tls "required" will force upgrade any http connection to https.  So while threadfin is listening on port 34400, and is running on http://localhost:34400/, plex is forcing to "https" which is not in use.  The reverse proxy is configured for the domain on 443, and does the tls termination, and then passes the traffic to 34400.

**Describe the solution you'd like**
Allow setting the threadfin destination and a toggle on weather or not to include the port in the playlist / image links.

**Describe alternatives you've considered**
Allow a post processing script that allows running sed commands.  This would be beneficial if I wanted to change channel names to use part of the description.  For example, NFL Football is the title for any nfl game, and I may want to inject the team name into the title of the show instead.

**Additional context**
none

**Comment by Nanganator** [comment]
Have you tried setting these options in threadfin settings?
![image](https://github.com/user-attachments/assets/807852a1-be3f-40d9-9050-7fbf99a2f777)

This is working perfectly for me. My m3u and xml have no port in them.
The stream url in the m3u is then:
https://threadfin.internal.mydomain.xyz/stream/f58280c7

The reverse proxy then just directs the request to threadfins port 34400

**Comment by Nanganator** [comment]
Threadfin is essentially a proxy as well. The URL threadfin uses to connect to your provider is the one in the m3u from your provider. If its http then Threadfin will use http. Plex connecting to Threadfin via https though should satisfy its need for ssl.

**Comment by joshjryan** [comment]
FWIW: I agree that it doesn't make sense that the "ForceHTTPS" bool would cause TF to override whatever prototocl is specified in the Playlist m3u, but it does look it's intentionally coded this way.

IMO, it'd make sense to remove this section: https://github.com/Threadfin/Threadfin/blob/ecc998444875e4f36efc2e6b715a77823f30e99c/src/webserver.go#L132C1-L142C1

**Comment by Fyb3roptik** [comment]
It makes perfect sense as HTTPS has to be port 443. Apps like Plex and Jellyfin typically only work over 443 for HTTPS

**Comment by chrirauch** [comment]
> WIW: I agree that it doesn't make sense that the "ForceHTTPS" bool would cause TF to override whatever prototocl is specified in the Playlist m3u, but it does look it's intentionally coded this way.

Sure, https and port 443 make perfect sense, but not in all cases rewriting the m3u urls is wanted. Maybe an additional option "Force https for images only" would be an option?

**Comment by chrirauch** [comment]
> Yet the links in "Server Information" still contain the port
> 
> ```
> http://threadfin.domain.com:34400/m3u/threadfin.m3u
> ```



as long as you have force https not activated, the port will not be rewritten

**Comment by Fyb3roptik** [comment]
> > It makes perfect sense as HTTPS has to be port 443. Apps like Plex and Jellyfin typically only work over 443 for HTTPS
> 
> Sure, https and port 443 make perfect sense, but not in all cases rewriting the m3u urls is wanted. Maybe an additional option "Force https for images only" would be an option?

In the case of HTTPS and SSL Certificates, if 1 URL is HTTPS they ALL have to be. That is how it works. You CANNOT and SHOULD NOT mix HTTP with HTTPS
