### ISSUE TITLE
Plex streaming not working

### ISSUE THREAD

**Issue by syco** [Threadfin/Threadfin#460]
Hi,

I use threadfin official docker container and plex, both updated to the latest versions as I type.
But since a couple of days things have stopped working.

Here's the log from plex when I start a channel:
```txt
Nov 19, 2024 10:58:45.873 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Grabber: Couldn't find channel ITV2 URL for device device://tv.plex.grabbers.hdhomerun/2024-09-4US6-WXT8HB.
Nov 19, 2024 10:58:45.874 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Unable to find title for item of type 5
Nov 19, 2024 10:58:45.875 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Unable to find title for item of type 5
Nov 19, 2024 10:58:45.885 [140079270263608] ERROR - [Req#23ce2/Transcode/13adf483-569f-4760-a1cb-ff79d626a8f1/45edd28e-571b-4e09-8b25-a983bc6cc1fd] [tcp @ 0x7f12c01ffec0] Connection to tcp://172.18.0.101:5004 failed: Connection refused
Nov 19, 2024 10:58:45.885 [140079270263608] ERROR - [Req#23ce3/Transcode/13adf483-569f-4760-a1cb-ff79d626a8f1/45edd28e-571b-4e09-8b25-a983bc6cc1fd] http://172.18.0.101:5004/auto/vITV2: Connection refused
Nov 19, 2024 10:58:45.886 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Failed to start session.
Nov 19, 2024 10:58:45.886 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Recorder: Unable to create transcode session or session failed to start.
Nov 19, 2024 10:58:45.886 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Recorder: Error 16 (Recording failed. Please check your tuner or antenna.) starting the record, shutting things down.
Nov 19, 2024 10:58:45.886 [140079250651960] ERROR - [Req#23ca2] Subscription: Rolling media grab failed to start.
Nov 19, 2024 10:58:45.887 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Starting media grab failed.
Nov 19, 2024 10:58:45.887 [140079258385208] ERROR - [Req#23ca2/Grabber/5fc76db4e3cd4a002dc5fc39-5fc705fea62668002dcefe6c-sqtk9keup4g2ajhxip6fln6x] Unknown metadata type: 

```

as you can see plex is looking for `tcp://172.18.0.101:5004`, but when I attach to the docker container that port is not open.

Here's how I start the container:

```bash
docker run \
  --net docker18 --ip 172.18.0.101 \
  --expose 34400/tcp --expose 5004/tcp --expose 1900/udp \
  --dns 1.1.1.1 --dns 8.8.8.8 \
  --log-driver none \
  --name threadfin \
  --restart=no \
  --rm \
  -e THREADFIN_PORT=34400 \
  -e TZ=Europe/Dublin \
  -h threadfin \
  -v /docker/threadfin:/home/threadfin/conf:rw \
  fyb3roptik/threadfin:latest
```

Am I doing something wrong?

**Comment by syco** [comment]
Small update and then I leave it to you, I reverted docker to 1.2.15 and it's working as expected.
Although port 5004 is still not open in the container, so I don't know where plex is connecting to.

**Comment by hende101** [comment]
I'm using the Windows Binary of Threadfin and seeing the same issue. 
Plex still seems to connect and communicate with Threadfin but doesn't receive any streams. 

Rolling back to 1.2.15 works.

**Comment by joshjryan** [comment]
@syco @hende101 Can you compare the stream URLs in threadfin.m3u between 1.2.15 and the latest release?

**Comment by syco** [comment]
Is that where it should be?
![image](https://github.com/user-attachments/assets/398c77b5-4de3-4fbf-b655-87ed43f8e0e1)

**Comment by hende101** [comment]
@joshjryan 
Im keeping the same .m3u and threadfin configuration between these tests. Only thing i'm changing is the binary version.

Using 1.2.15 the console of Threadfin looks like this when starting a stream within Plex:
![image](https://github.com/user-attachments/assets/5bc980b5-73a8-4325-8a85-e17f52ade34d)

When using > 1.2.15 it looks like this:
![image](https://github.com/user-attachments/assets/64969819-2996-44f1-8370-b0a47f5da824)


Plex still says its connected to the Threadfin DVR and can see the available channels

**Comment by joshjryan** [comment]
I'm asking what the stream URLs look like _inside_ threadfin.m3.
e.g. something like 
`#EXTINF:0 channelID="x-ID.7" tvg-chno="1507" tvg-name="FOX SPORTS 2" tvg-id="1507" tvg-logo="http://192.168.100.50:2525/images/296229f25ddada30b9ddae2f30f715bd.png" group-title="SPORTS NETWORKS",FOX SPORTS 2
http://192.168.100.50:2525/stream/fc7922f4ee6f94e445994ff57f0cdf01`
...are those values the same in the functioning version vs the broken version?
(I ask because I made a change that could affect those URLs).

**Comment by syco** [comment]
Ok, but I have the EPG Source set as PMS, so as you can see in the screenshot I don't see the threadfin.m3u url.
Can I still curl it? Where is it?

**Comment by hende101** [comment]
Comparing the urls.json between the two versions shows every channelNumber being slightly different. 

For example:
1.2.15: sky1.uk
1.2.18: UK SKY One

Would that do it?

**Comment by syco** [comment]
So the solution is simply to delete the dvr and add it again?

**Comment by hende101** [comment]
> So the solution is simply to delete the dvr and add it again?

No need to delete the whole thing. Just re assign the channels inside of Plex.

**Comment by syco** [comment]
That's it, readd or remap, for me it's easier to do the first.
Anyway, thanks for looking into it.
