### ISSUE TITLE
1.2.18 Still causing PPV strconv issues.

### ISSUE THREAD

**Issue by lephino** [Threadfin/Threadfin#463]
I'm still getting this error, even on 1.2.18, linked to this issue: https://github.com/Threadfin/Threadfin/issues/451

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - ESPN Plus 017

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-61d23372fc4209fda23021e89d5a2756": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - PPV 04: UFC 309 Jones v Miocic Main Card (11.16 10:00PM ET)

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0

2024/11/18 16:10:04 [Threadfin] Create Dummy Guide:     Time offset -0700 - PPV 07: Ramirez v Smith (11.16 5:30PM ET)

2024/11/18 16:10:04 [Threadfin] [ERROR] strconv.Atoi: parsing "threadfin-bc03fb9e224b42a0b6916c1a0d5ac937": invalid syntax () - EC: 0

and here's the version header from the logs:

For help run: /home/threadfin/bin/threadfin -h

2024/11/18 16:04:28 [Threadfin] [WARNING] Don't run this as Root!

2024/11/18 16:04:28 [Threadfin] Version:                1.2 Build: 18

2024/11/18 16:04:28 [Threadfin] Database Version:       0.5.0

2024/11/18 16:04:28 [Threadfin] System IP Addresses:    IPv4: 9 | IPv6: 11

2024/11/18 16:04:28 [Threadfin] Hostname:               {masked}

2024/11/18 16:04:28 [Threadfin] System Folder:          /data/conf/

2024/11/18 16:04:28 [Threadfin] Load Settings:          /data/conf/settings.json

2024/11/18 16:04:28 [Threadfin] Temporary Folder:       /tmp/threadfin/{masked}

2024/11/18 16:04:28 [Threadfin] GitHub:                 https://github.com/Threadfin

2024/11/18 16:04:28 [Threadfin] Git Branch:             Main [Threadfin]

2024/11/18 16:04:28 [Threadfin] SSDP / DLNA:            true

2024/11/18 16:04:28 BRANCH:  Main

2024/11/18 16:04:28 TAG LATEST:  1.2.18

2024/11/18 16:04:28 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.2.18/Threadfin_linux_amd64

2024/11/18 16:04:28 [Threadfin] UUID:                  {masked}

2024/11/18 16:04:28 [Threadfin] Tuner (Plex / Emby):    2

2024/11/18 16:04:28 [Threadfin] EPG Source:             XEPG

2024/11/18 16:04:28 [Threadfin] Plex Channel Limit:     480

2024/11/18 16:04:28 [Threadfin] Unfiltered Chan. Limit: 480

2024/11/18 16:04:28 [Threadfin] Backup Path:            /data/conf/backup/

2024/11/18 16:09:45 [Threadfin] Backup file:            /data/conf/backup/threadfin_auto_backup_20241118_1604.zip

_Originally posted by @lephino in https://github.com/Threadfin/Threadfin/issues/451#issuecomment-2484338311_

**Comment by Fyb3roptik** [comment]
Is the filter marked as live event?

**Comment by Fyb3roptik** [comment]
No not ignore Filters. You're using it wrong so that's why it's broken. Use discord please
