### ISSUE TITLE
Channels still fail to save an updated name after a browser refresh or feed update

### ISSUE THREAD

**Issue by jaretclifton** [Threadfin/Threadfin#465]
Describe the bug
Bugs #408 and #456 were closed. Issue still exists.
Even as of version 1.2.18 channels fail to "save" an updated name and revert to provider naming.

Server (please complete the following information):

OS Ubuntu
Arch 64-bit
Threadfin Version and Build 1.2.18
To Reproduce

Change "Channel Name"
Click Done.
Save mapping
Refresh the browser page (navigating between tabs will not suffice)
Channel name will revert
Expected behavior
Renamed channel information retained.

Does not matter if you toggle "Update channel name" and try. No matter what steps are taken, the outcome is the same. Channels will revert to existing naming.

Screenshots
N/A

Desktop (please complete the following information):

OS: Windows
Browser: Chrome
Additional context
N/A

**Comment by Fyb3roptik** [comment]
You shouldnt be using that checkbox to Update Channel Name. That will override what YOU put in. This is working fine on the default install

**Comment by jaretclifton** [comment]
I know exactly what that does. On a whim I tried toggling it it just as someone else mentioned in in bug #456 . There is indeed a bug here that you continue to close. This is impacting other people as well, not just me. I'll just deal with it since it doesn't appear it's getting fixed any time soon.
