### ISSUE TITLE
Bug: Origin / Referer values cause one or the other to wipe on next save

### ISSUE THREAD

**Issue by Aetherinox** [Threadfin/Threadfin#466]
**Describe the bug**
Applying a header / origin is very hit and miss. Not sure if this is related to some feature I'm unaware of.
If you set both `User Header Origin:` and `User Header Referer:` and click save, it picks one of the two, and wipes the box on the other. It never allows you to use both.

At other times, when I go into the settings of Threadfin, the Origin and Header are both empty, and I have to reset them to what I had originally used.

The other issue is, I'm not even sure it's applying. I've got a link to a .m3u8 file, but the console keeps saying:
```
2024-11-28 01:08:51 [Threadfin] FFMPEG log:             [crypto @ 0x55e4950a0cc0] Unable to open resource: https://kvm1-dc3.videonode138.ru.com/ddh1/premium349/2024/11/28/13/09/19-07680.webp
```

Yet if I use the Origin and Referer header in a normal browser, I can access it fine.

I added a gif below showing the fight between the two settings.

<br />

---

<br />

**Server (please complete the following information):**
- Ubuntu 22.04 LTS
- x64
- 1.2 (18) - main branch (Docker)

<br />

---

<br />

**To Reproduce**
1. Go to Threadfin settings
2. Set a Header / Origin for each box
3. Click save
4. Edit the settings page (hard refresh works)
5. Go back to settings, and one or both boxes will be empty.

<br />

---

<br />

**Expected behavior**
I should be able to set both a header and origin

<br />

---

<br />

**Screenshots**
![czRRWm9ic0](https://github.com/user-attachments/assets/25905e76-7b6b-4967-9b23-17d87f666a90)

Here is a complete run-through of this issue. Sometimes I'll set both, and when I go back to settings, they'll both be gone. Sometimes it'll leave one or the other.

This is in regards to the settings:
- `User Header Origin:` 
- `User Header Referer:`

![JjgA7QpBZ1](https://github.com/user-attachments/assets/3a3f81b0-e233-4e80-b518-2b2115b90943)

<br />

---

<br />

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chromium + Firefox
 - Version Version Chromium 133.0.6849.0 (Developer Build) (64-bit) + Firefox 132.0.2 (64-bit)

<br />

---

<br />

**Additional context**
Restarted the Threadfin container, doing hard refreshes. Confirmed that settings are being saved to the config file.

**Comment by Aetherinox** [comment]
You may have missed, I Just updated my ticket with a gif that shows the entire issue.

And yes, I'm checking the settings file as I do this, and it's reflecting what is in the GUI. One gets wiped, and the other remains.

After I made my gif, the current settings in the file are:
```
  "user.agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1",
  "user.origin": "https://test2.domain.com",
  "user.referer": "",
```

**Comment by joshjryan** [comment]
@Aetherinox I just submitted a PR with a fix.
If you want to work around it for now: empty both fields and Save. Then set them both, and Save again.
(They'll only both "stick" if they're both changed on the same save request).

**Comment by joshjryan** [comment]
*note: I'm pretty sure that if you save any setting other than Origin/Referrer, it'll cause those values to be cleared out. So (until the fix is merged), you'll need to have these two values be the last two that you change/save.

**Comment by Aetherinox** [comment]
Awesome, appreciate it.
Glad to know I'm not going crazy.

**Comment by Fyb3roptik** [comment]
Origin and Referer have been moved to the Playlist in 1.2.19. This should fix this, please reopen if it does not
