### ISSUE TITLE
panic: time: missing Location in call to Date

### ISSUE THREAD

**Issue by NvrBst** [Threadfin/Threadfin#470]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Upgraded to 1.2.18, and I get a panic crash during bootup.  No other errors appeared in the startup, just the panic and crash.  It does download the m3u and XML just fine.

Going back to 1.2.15, there is no panic and crash.

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] Windows 11
- Arch [e.g. Intel 64 Bit] Intel 64 bit
- Threadfin Version and Build [to be found in the Threadfin log] 1.2.18

**To Reproduce**
Just booting up

**Expected behavior**
to not crash and exit out

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

2024/12/02 13:08:38 [Threadfin] XEPG:                   Parse XMLTV file: XMLTV.m3u4u
2024/12/02 13:08:38 [Threadfin] XEPG:                   Update database
panic: time: missing Location in call to Date

goroutine 99 [running]:
time.Date(0xc00a86a36e?, 0x129f4f8?, 0x11ccfc7?, 0xd8047b?, 0x7ffd5d7ce4a0?, 0xc012f45f58?, 0x3?, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/time/time.go:1404 +0x4e5
time.parse({0x11ccfba, 0xf}, {0xc00a86a360, 0x10}, 0x1?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/time/format.go:1320 +0x209c
time.ParseInLocation(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/time/format.go:957
threadfin/src.createLiveProgram({{0xc006ba9c80, 0x14}, {0xc00a86a1d0, 0x10}, {0xc0117f6840, 0x37}, {0xc00a86a208, 0x3}, {0xc0117f68c0, 0x33}, ...}, ...)
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:1100 +0x705
threadfin/src.createDummyProgram({{0xc006ba9c80, 0x14}, {0xc00a86a1d0, 0x10}, {0xc0117f6840, 0x37}, {0xc00a86a208, 0x3}, {0xc0117f68c0, 0x33}, ...})
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:1160 +0x99
threadfin/src.getProgramData({{0xc006ba9c80, 0x14}, {0xc00a86a1d0, 0x10}, {0xc0117f6840, 0x37}, {0xc00a86a208, 0x3}, {0xc0117f68c0, 0x33}, ...})
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:951 +0x158
threadfin/src.createXEPGDatabase()
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:517 +0x1078
threadfin/src.buildXEPG.func2()
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:72 +0x25
created by threadfin/src.buildXEPG
        /home/runner/work/Threadfin/Threadfin/src/xepg.go:69 +0x185

**Comment by Fyb3roptik** [comment]
Fixed in 1.2.19
