### ISSUE TITLE
Bug: Saving settings (such as Origin and Agent) are hit and miss

### ISSUE THREAD

**Issue by Aetherinox** [Threadfin/Threadfin#473]
**Describe the bug**
Originally reported here:
- https://github.com/Threadfin/Threadfin/issues/466

After the last issue was submitted, a new version of Threadfin was released (1.2.19`). Once the new version was released, you can now actually get the changes to apply, sometimes, but it is not the case with every time you refresh the settings page.

I set the Origin and Referer links, saved, and then went back to the logs to read out what was going on. I went back to the settings to make an adjustment, and the origin / referrer settings were still there. However, after I made a change to the FFMPEG options and saved, I went back to the settings page and now the Referrer and origin settings were gone. Both in the admin panel, and also in the Threadfin settings file. So it's not just a web interface glitch, it's actually resetting these settings within the admin panel for some reason.

And when it decides to do it appears to be completely random. Sometimes I can go back to the settings page twice and it's still there. Sometimes three refreshes of the settings page. I haven't figured out the exact action that is triggering it.

I have confirmed I'm on the latest version.

The odd thing to add is that this doesn't appear to be limited to _just_ the origin and referrer settings. I've also seen this happen with the `User Agent:` setting. I originally had the user agent set to a specific entry, then after a few changes, going to the logs page, and coming back, it was reset back to the original value.

I confirmed it is saving these changes in my json file, but they revert back for some reason. I have to save the changes multiple times for them to stick.

Permissions on the settings file is good.

<br />

---

<br />

**Server (please complete the following information):**
- Ubuntu Linux 22.04
- Arch amd64
- Threadfin Version and Build:  
```
[Threadfin] Version                  1.2 Build: 19
[Threadfin] Database Version    0.5.0
```

<br />

---

<br />

- 
**To Reproduce**
1. Access the threadfin settings page, set an origin and referer host.
2. Save the settings and then leave to another page in the web panel
3. Come back and check the referer and origin. If it's still there, make a change to another setting, leave the origin and referer alone.
4. Save and then go to another page such as log, and then return to the settings and check again.
5. May also need to do a hard refresh in your browser (F5)

<br />

---

<br />

**Expected behavior**
When settings are saved, they should remain in that state until otherwise changed by the user.

<br />

---

<br />

**Screenshots**

<br />

---

<br />

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox
 - Version133.0 (64-bit)

<br />

---

<br />

**Additional context**
See attached link for previous issue:
- https://github.com/Threadfin/Threadfin/issues/466

**Comment by Fyb3roptik** [comment]
These are no longer in Settings, why are you reporting something that isnt even in Settings?

**Comment by Aetherinox** [comment]
I'm not sure what you're referring to. I'm on the latest version, and these are indeed in the settings tab:

![QdFyQN9CSO](https://github.com/user-attachments/assets/2bb858bf-028d-4f50-bda5-f1aee7185786)
