### ISSUE TITLE
Buffering two streams from the same client 

### ISSUE THREAD

**Issue by golaat** [Threadfin/Threadfin#475]
If I configure threadfin to use buffering (either VLC or ffmpeg) and play a single stream from a client, it works great. If i start another stream for a different channel both channels will play for a bit, but then the 1st channel i played will stops, the second stream continues to play.

If i turn off buffering and repeat the above step, both streams play without issue on the same client.

I want to use buffering because it does seem to help with occasional stream hiccups, but I always want to be able to play more than one stream at the same time from a client.

**Comment by Fyb3roptik** [comment]
Please join the discord for support. This is an issue with your setup
