### ISSUE TITLE
Threadfin version 1.2.0

### ISSUE THREAD

**Issue by Tomiliy** [Threadfin/Threadfin#479]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have 2 Gigablue cable tuners, both can establish exactly one connection and show the TV signal. So I could watch 2 different channels, but only on 2 different devices. I would like to combine them. I have read that Threadfin can do this.
Unfortunately, I can't set Threadfin so that it works

**Server (please complete the following information):**
- Docker Container mit Threadfin 1.2.0 von: fyb3roptik/threadfin
- on a Synology 423+ mit 32GB Ram
- Threadfin Version and Build 1.2 (20) Main

**To Reproduce**
Both boxes has the same channel list
1. Playlist: Add first: http://gbquad4k.fritz.box/web/services.m3u  <Buffer: ffmpeg> ![tuner1](https://github.com/user-attachments/assets/bd909cc4-40b8-4062-ad1d-66ca2fb142a0)
2.1. Playlist: Add second: http://gbquadplus/web/services.m3u <Buffer: ffmpeg> ![tuner2](https://github.com/user-attachments/assets/304dee27-91b3-45d9-bb7f-33c1fea160c7)
3.add XMLTV EPG from one of the boxes.
4. add Filter: Filter rule: 1:0:19 ![filterRule](https://github.com/user-attachments/assets/d4f37454-7adc-4561-83b3-e621b149a324)
5. Mapping. 1 activated all channels from 1. reciver and deactivated from second. i added on all 1st channels the channels from the secons reciver as backup1 ![channellist](https://github.com/user-attachments/assets/ff8ad806-d6d1-4fa6-ad34-07ac9ac17283)
5a. Mapping second reciver in channellist ![mapping2](https://github.com/user-attachments/assets/25ab2403-3fab-4a2a-9209-0224b1ac439c)

6. Settings added:  [threadfin_backup_20241214_1414.zip](https://github.com/user-attachments/files/18135968/threadfin_backup_20241214_1414.zip)

**Expected behavior**
I understood that when the first tuner has reached its limit, it automatically switches to the second tuner that is still free.
Unfortunately, this does not happen. The first channel is running, the picture is played back and when I then want to open a second connection via Threadfin, the error message appears that no further channel is available.

**Screenshots**

**Desktop (please complete the following information):**
i Use Plex and empby

**Additional context**

Thank you for your help

**Comment by Fyb3roptik** [comment]
No that is not how Threadfin works. It does not automatically switch over to the other one. You would need to have channels from each setup.

**Comment by Tomiliy** [comment]
Is it possible to add this cool Feature?
Thanks

Nick Wallace ***@***.***> schrieb am Sa. 14. Dez. 2024 um
17:37:
