### ISSUE TITLE
Better mapping order

### ISSUE THREAD

**Issue by Zalatis** [Threadfin/Threadfin#481]
**Is your feature request related to a problem? Please describe.**
Yes, In some case when some playlists won't works but other works the mapping can be swapped unintentionally

**Describe the solution you'd like**
I would like to be able to force each playlist to start at a define number 
Example : 
 - Playlist 1 : Starts at number 0
 - Playlist 2 : Starts at number 1000
 - Playlist 3 : Starts at number 2000

**Comment by Fyb3roptik** [comment]
You do this at the filter level, not playlist. That is not changing.
