### ISSUE TITLE
Plex cannot load channel pictures

### ISSUE THREAD

**Issue by Serph91P** [Threadfin/Threadfin#485]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Since plex is rewriting all http to https but my threadfin instance is running localy no pictures get loaded.

**Server (please complete the following information):**
- OS Debain
- Arch x86
- Threadfin Version and Build 1.2 (21)

**To Reproduce**
1. Add tuner and xml via http
2. let it check the epg
3. Go to Live TV
4. No pictures are showing

**Expected behavior**
All pictures are loaded.

**Screenshots**
<img width="136" alt="{D28CA468-F4B9-493F-A730-ABBEC443E212}" src="https://github.com/user-attachments/assets/3e997697-07c2-498b-82af-3eece3e2b5ee" />

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version 133

**Additional context**
I have a domain running and could use it. But since the https option of threadfin enables https for everything even though its running localy this is not an option I dont want threadfin to be accessable from the internet.

**Comment by Fyb3roptik** [comment]
Disable https on threadfin then. If you don't want it accessible then just use http and local ip

**Comment by Serph91P** [comment]
> Disable https on threadfin then. If you don't want it accessible then just use http and local ip

You did not read what I wrote again how can I get pictures in plex then if I disable https?
