### ISSUE TITLE
can not be compiled on arm 32bit (rapsberry pi 2)

### ISSUE THREAD

**Issue by requa3r0** [Threadfin/Threadfin#486]
hi
Im not sure if the software is not compatable with arm 32bit (rapsberry pi 2)
I have been running xTeVe 2.2.0 on the pi for years.

pi@raspberrypi:~/Threadfin $ lscpu
Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           5
Model name:                      Cortex-A7

running debian bullseye
pi@raspberrypi:~/Threadfin $ uname -a
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

pi@raspberrypi:~/Threadfin $ go version
go version go1.15.15 linux/arm

after git clone of the Threafin

pi@raspberrypi:~/Threadfin $ sudo go mod tidy
go mod tidy: go.mod file indicates go 1.22, but maximum supported version is 1.15

pi@raspberrypi:~/Threadfin $ sudo go mod vendor
go: downloading github.com/avfs/avfs v0.35.0
go: downloading golang.org/x/text v0.21.0
go: downloading github.com/hashicorp/go-version v1.7.0
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading golang.org/x/net v0.32.0
go: downloading golang.org/x/sys v0.28.0

compile - with error

pi@raspberrypi:~/Threadfin $ sudo go build threadfin.go
vendor/golang.org/x/net/ipv4/control.go:12:2: found packages iana (const.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/net/internal/iana
vendor/github.com/koron/go-ssdp/internal/multicast/multicast.go:11:2: found packages ipv4 (batch.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/net/ipv4
vendor/golang.org/x/net/internal/socket/cmsghdr_unix.go:9:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /home/pi/Threadfin/vendor/golang.org/x/sys/unix
src/config.go:11:2: found packages cases (cases.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/text/cases
package command-line-arguments
        imports threadfin/src
        imports golang.org/x/text/cases
        imports golang.org/x/text/internal
        imports golang.org/x/text/language
        imports golang.org/x/text/internal/gen
        imports golang.org/x/text/unicode/cldr
        imports golang.org/x/text/internal/gen: import cycle not allowed
vendor/golang.org/x/text/language/coverage.go:11:2: found packages language (common.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/text/internal/language
vendor/golang.org/x/text/language/language.go:16:2: found packages compact (compact.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/text/internal/language/compact
vendor/golang.org/x/text/internal/internal.go:12:2: found packages language (coverage.go) and main (gen.go) in /home/pi/Threadfin/vendor/golang.org/x/text/language
vendor/golang.org/x/text/internal/gen/gen.go:38:2: found packages cldr (base.go) and main (makexml.go) in /home/pi/Threadfin/vendor/golang.org/x/text/unicode/cldr
vendor/golang.org/x/text/cases/gen.go:27:2: found packages norm (composition.go) and main (maketables.go) in /home/pi/Threadfin/vendor/golang.org/x/text/unicode/norm
vendor/github.com/avfs/avfs/errors.go:20:2: cannot find package "." in:
        /home/pi/Threadfin/vendor/io/fs
vendor/github.com/avfs/avfs/vfs_ostype_on.go:24:2: cannot find package "." in:
        /home/pi/Threadfin/vendor/slices

**Comment by Fyb3roptik** [comment]
You don't use sudo to build in go. 

You need to do this

```
go mod tidy && go mod vendor
tsc -p ./ts/tsconfig.json && go build threadfin.go
```

Do not do this as root

**Comment by Fyb3roptik** [comment]
I will add 32 bit arm in the builds for you

**Comment by requa3r0** [comment]
thanks - im just playing a bit around

I upgraded go with this guide
https://linuxcapable.com/how-to-install-golang-go-on-debian-linux/

pi@raspberrypi:~/Threadfin $ go version
go version go1.23.4 linux/arm


and installed node.js 
https://www.turbogeek.co.uk/how-to-install-typescript-on-linux/#Step_2_Install_TypeScript
but its not clear how to get tsc command working.

The pi can recognize that command, and I don't really know what it is.

pi@raspberrypi:~/Threadfin $ sudo apt install nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (12.22.12~dfsg-1~deb11u5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~/Threadfin $ tsc -p ./ts/tsconfig.json
-bash: tsc: command not found

**Comment by requa3r0** [comment]
> I will add 32 bit arm in the builds for you

What does that precisely mean?..Can just download the bin file..? Where

or do I still need to re-clone and compile my self.

**Comment by requa3r0** [comment]
stated over...it worked lol

pi@raspberrypi:~ $ git clone https://github.com/Threadfin/Threadfin.git
Cloning into 'Threadfin'...
remote: Enumerating objects: 3969, done.
remote: Counting objects: 100% (1344/1344), done.
remote: Compressing objects: 100% (332/332), done.
remote: Total 3969 (delta 1194), reused 1012 (delta 1012), pack-reused 2625 (from 2)
Receiving objects: 100% (3969/3969), 14.69 MiB | 4.27 MiB/s, done.
Resolving deltas: 100% (2626/2626), done.


pi@raspberrypi:~ $ cd Threadfin/
pi@raspberrypi:~/Threadfin $ go mod tidy
pi@raspberrypi:~/Threadfin $ go mod vendor
pi@raspberrypi:~/Threadfin $ go build threadfin.go


alll good
pi@raspberrypi:~/Threadfin $ ./threadfin
For help run: ./threadfin -h

2024/12/27 00:44:59 [Threadfin] Version:                1.2 Build: 21
2024/12/27 00:44:59 [Threadfin] Database Version:       0.5.0
2024/12/27 00:44:59 [Threadfin] System IP Addresses:    IPv4: 4 | IPv6: 2
2024/12/27 00:44:59 [Threadfin] Hostname:               raspberrypi
2024/12/27 00:44:59 [Threadfin] System Folder:          /home/pi/.threadfin/
2024/12/27 00:44:59 [Threadfin] Load Settings:          /home/pi/.threadfin/settings.json
2024/12/27 00:44:59 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-12-KCG6-DY8TXI/
2024/12/27 00:44:59 [Threadfin] GitHub:                 https://github.com/Threadfin
2024/12/27 00:44:59 [Threadfin] Git Branch:             Main [Threadfin]
2024/12/27 00:44:59 SOURCE:  PMS
2024/12/27 00:44:59 [Threadfin] SSDP / DLNA:            true
2024/12/27 00:44:59 BRANCH:  Main
2024/12/27 00:45:01 TAG LATEST:  1.2.21
2024/12/27 00:45:01 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.2.21/Threadfin_linux_arm
2024/12/27 00:45:01 [Threadfin] UUID:                   2024-12-KCG6-DY8TXI
2024/12/27 00:45:01 [Threadfin] Tuner (Plex / Emby):    1
2024/12/27 00:45:01 [Threadfin] EPG Source:             PMS
2024/12/27 00:45:01 [Threadfin] Plex Channel Limit:     480
2024/12/27 00:45:01 [Threadfin] Unfiltered Chan. Limit: 480
2024/12/27 00:45:01 [Threadfin] All streams:            0
2024/12/27 00:45:01 [Threadfin] Active streams:         0
2024/12/27 00:45:01 [Threadfin] Filter:                 0
2024/12/27 00:45:01 [Threadfin] Web Interface:          http://10.13.128.105:34400/web/ | Threadfin is also available via the other 5 IP's.
