### ISSUE TITLE
Feature request to fix an issue with PPV channels.

### ISSUE THREAD

**Issue by shorty789** [Threadfin/Threadfin#488]
Apologies in advance if I end up wording this terrible, I hope you get the point I am trying to get across.

So one of the biggest issues that I have with my provider is that the PPV channels regularly get renamed, given this happens any time an event changes, it could become a lot of maintenance, whenever this happens and threadfin updates, if any of the channels get renamed, they end up disabled, I then have to go through, enable, set up to use PPV EPG, before manually adding them into my Plex again afterwards.

Is there any way that we could get some form of channel template for these cases, some kind of channel object within threadfin itself that is independant of the playlist, but also linked based on part of the name that doesn't change would be ideal.

For example a channel object that can be persistently referred to as "PPV 01" that can be configured to be linked to a channel containing "PPV LIVE EVENT 01" or variations of it, so that if the channel happens to rename from "PPV LIVE EVENT 01 - THIS EVENT" to "PPV LIVE EVENT 01 - THAT EVENT" - it no longer causes the channels to drop off. there might still be edge cases where they are renamed to a different convention but this would eliminate a large chunk of the updates causing channels to drop off.

There are probably other more elegant solutions, including some that would catch more edge cases like the one mentioned above, but this would at least eliminate one of the biggest pet peeves I have with regularly updating playlists at the moment.

**Comment by Fyb3roptik** [comment]
You need to set Live Event checkbox on the filter. This will name things properly. You might need to delete and readd the filter

**Comment by Fyb3roptik** [comment]
Hit up the discord for more info on this
