### ISSUE TITLE
Validate Backup Stream without Buffer

### ISSUE THREAD

**Issue by xtinct101** [Threadfin/Threadfin#49]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to use the backup stream feature without using a buffer like ffmpeg. This results in passing an ffmpeg stream to a player just to make use of the backup feature.

**Describe the solution you'd like**
Allow the backup stream feature to validate the url and pass a valid url to requesting player if no errors are found.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Fyb3roptik** [comment]
The issue here is there is no way for Threadfin to know it needs to use the backup URL if no buffer is used.

**Comment by xtinct101** [comment]
Even if just looking for a 404 error for a link?

**Comment by Killianbe** [comment]
So if i use directstream the backup didn't work ?

**Comment by Fyb3roptik** [comment]
Right now the backup URL only works if you're using ffmpeg or vlc buffer. If I were to make it work without the buffer, it would only check for 404 initially and wouldn't be able to auto switch on the fly. You would have to reselect the channel for it to pick it up

**Comment by Fyb3roptik** [comment]
That said I can detect if the main is a 404 and then send the working backup, it just won't happen automatically after a working one is sent

**Comment by Killianbe** [comment]
that's be good to detect 404 error and auto send 2nde link if 1rst 404 !

**Comment by Fyb3roptik** [comment]
Yep! It's gonna be probably a week or so though.

**Comment by Fyb3roptik** [comment]
Wont do this as this feature will soon sunset into Kernel
