### ISSUE TITLE
Dummy EPG feature

### ISSUE THREAD

**Issue by HamzaM** [Threadfin/Threadfin#53]
**Is your feature request related to a problem? Please describe.**
If no XMLTV file is provided, channels don't get mapped which makes them unusable on Plex for example

**Describe the solution you'd like**
Having a Dummy EPG feature that would allow us to create an EPG and map channels automatically with their title

**Comment by Fyb3roptik** [comment]
This is already a thing :) Choose Threadfin as the XML provider and then you can create a Dummy program. If you use PPV it will map the channel name to the EPG (although there is a bug with it right now)
