### ISSUE TITLE
Possible to have channel mapping box be searchable instead of dropdown

### ISSUE THREAD

**Issue by d-diamond** [Threadfin/Threadfin#54]
Is it possible to have the XMLTV channel dropdown in channel mapping be searchable instead of a large dropdown?
This is useful for if trying to do quick mapping or testing with different guides, this is how xteve 2.5.3 functions. 

I have attached recording of the function in use. 

xteve 2.5.3 
https://github.com/SenexCrenshaw/xTeVe

https://user-images.githubusercontent.com/19967128/225454936-41abe2f7-414c-4cbd-9981-42b578ef29f9.mp4

**Comment by Fyb3roptik** [comment]
I'll add this in for sure!

**Comment by Fyb3roptik** [comment]
Done in 1.0.8
