### ISSUE TITLE
Detecting and utilizing the hostname and port Threadfin is accessed on may be problematic in reverse proxy environments

### ISSUE THREAD

**Issue by blackwind** [Threadfin/Threadfin#60]
**Describe the bug**
When Threadfin is first started, it generates files (like `threadfin.m3u`) that reference http://[docker-ip]:34400; when I visit the web interface via my reverse proxy, though, and perform certain actions, it likes to rewrite its files with the hostname and port of my reverse proxy... which none of my other Docker services can access. I suggest using the "Threadfin Domain" everywhere links are written if set, and it should accept a port as well in `hostname:port` notation. As is, I need to check the generated M3U each time I make changes to confirm it didn't point my clients to an inaccessible hostname and port, and best case scenario, if it *does* retain the Docker IP, I need to hope that Docker IP doesn't change or there could be an outage until the IPTV client's next playlist refresh. If Threadfin only wrote links using "threadfin:34400" as I've configured, neither issue would be a problem. "Server Information" should reflect this as well.

**Server (please complete the following information):**
- OS: Docker
- Arch: x86_64
- Threadfin Version and Build: 1.0 Build 7

**Comment by Fyb3roptik** [comment]
Sorry for the late reply here. Please hop on Discord to discuss docker. I am not the docker guy here :)

**Comment by blackwind** [comment]
Wish I had the time for that these days, but I just don't. The problem can easily be remediated, at any rate, with the suggested solution. Let the user specify a hostname and port, and Threadfin will work in any environment.

**Comment by DigiDr** [comment]
Agree this makes integrating into cloudbox/saltbox setups almost impossible. Please setup the container like dnsforge/xteve

**Comment by Fyb3roptik** [comment]
Fixed in 1.0.15
