### ISSUE TITLE
Add an option to use channel numbers from m3u

### ISSUE THREAD

**Issue by Deihmos** [Threadfin/Threadfin#62]
Can you please add an option to use the channel number from the m3u playlist?

**Comment by ellisd4** [comment]
Would second this.  This would fix the issue where sometimes the channels are duplicated in the lineup when the playlist is updated.

**Comment by Fyb3roptik** [comment]
Use a custom filter without checking case senstive:

`{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}`

**Comment by Deihmos** [comment]
> Use a custom filter without checking case senstive:
> 
> `{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}`

What is this supposed to do exactly? I am not following. How will this enable the channel number included in the m3u?

**Comment by Deihmos** [comment]
I did this but nothing happened. 

<img width="899" alt="image" src="https://github.com/Threadfin/Threadfin/assets/14289123/de7115d8-ce49-4654-839a-aaeee3d63b88">

**Comment by Fyb3roptik** [comment]
Yes it will pull in all channels as they are without renumbering. You can choose a starting number or keep it blank for that to be 1

**Comment by Deihmos** [comment]
> Yes it will pull in all channels as they are without renumbering. You can choose a starting number or keep it blank for that to be 1

How do you enter it? I cannot get it to work.

<img width="899" alt="Screenshot 2023-06-08 at 6 44 04 PM" src="https://github.com/Threadfin/Threadfin/assets/14289123/f7fd36ff-7a5e-41b7-b1c5-ae010c33769c">

**Comment by Deihmos** [comment]
Has anyone gotten this to work?

**Comment by Fyb3roptik** [comment]
Does it use single quotes or doubles quotes around the values? I discovered a big that didn't allow single quotes to work. I have a patch in the pipeline, I've been without a working machine for a bit. Will push it out soon

**Comment by Deihmos** [comment]
> Does it use single quotes or doubles quotes around the values? I discovered a big that didn't allow single quotes to work. I have a patch in the pipeline, I've been without a working machine for a bit. Will push it out soon

My m3u has double quotes and it didn't work. 

#EXTINF:0 CUID="1" tvg-chno="930" tvg-name="5 Star Max (East)" tvg-id="5.star.max.eastern.us" group-title="Favorites",5 Star Max (East)

**Comment by Deihmos** [comment]
I was able to get this to work. The channel number comes from the tvg-id and not the tvg-chno.
