### ISSUE TITLE
Channel Name missing if tvg-name isn't present 

### ISSUE THREAD

**Issue by warrentc3** [Threadfin/Threadfin#65]
This produces an empty channel name:
#EXTINF:-1 channel-id="frndly-32" tvg-id="frndly-32" tvc-guide-stationed="58988",FYI

This populates the channel name:
#EXTINF:-1 channel-id="frndly-32" tvg-id="frndly-32" tvg-name="FYI" tvc-guide-stationed="58988",FYI

Since there's not a proper RFC that specifies the tags in the EXTINF, often sources can be a bit all over the place.
Would it be possible to parse the line and if "tvg-name" tag isn't present in the EXTINF line, to assume the text after the last comma on the line is the channel name?

Out of curiosity, how are all the variants of the m3u EXTINF tags handled?
channel-id, channel-number, tvg-chno, epg-id, tvg-id, tvg-name, tvg-logo, groups, group-title, tvg-group, tvg-shift

**Comment by Fyb3roptik** [comment]
Should be easy enough

**Comment by Fyb3roptik** [comment]
This should be fixed in 1.0.11
