### ISSUE TITLE
/home/threadfin not properly mapped in container volume

### ISSUE THREAD

**Issue by hacktek** [Threadfin/Threadfin#70]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

Weird one. When creating a container with :

```
docker run -d  \
  --name=threadfin  \
  --restart=unless-stopped  \
  -e PGID=1000 -e PUID=1000  \
  -v /opt/threadfin:/home/threadfin  \
  -v /etc/localtime:/etc/localtime:ro  \
fyb3roptik/threadfin
```

/opt/threadfin ends up with incorrect stuff in it, which causes threadfin not to run.

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]

Ubuntu

- Arch [e.g. Intel 64 Bit]

64 bit

- Threadfin Version and Build [to be found in the Threadfin log]

1.0 Build: 10

**To Reproduce**

Run above container command

**Expected behavior**

Volume is mapped properly and threadfin runs

**Screenshots**

```
$ docker logs threadfin
/bin/sh: /home/threadfin/bin/threadfin: not found
/bin/sh: /home/threadfin/bin/threadfin: not found
/bin/sh: /home/threadfin/bin/threadfin: not found
/bin/sh: /home/threadfin/bin/threadfin: not found
/bin/sh: /home/threadfin/bin/threadfin: not found
/bin/sh: /home/threadfin/bin/threadfin: not found

$ find /opt/threadfin/
/opt/threadfin/
/opt/threadfin/conf
```

**Comment by nweishar** [comment]
I've found the same thing. I can't set the variable so that I can control where the config is stored. Causing similar log issues to you

**Comment by Fyb3roptik** [comment]
Sorry I am not one to use Docker. There are plenty of docker peeps in the discord who are better suited to help. If there is a bug I will put it here and work on it

**Comment by fredamn76** [comment]
> Sorry I am not one to use Docker. There are plenty of docker peeps in the discord who are better suited to help. If there is a bug I will put it here and work on it

Where can we find the Discord server?

**Comment by beardypig** [comment]
I dunno if this was resolved on discord, but the only volumes exposed in the Dockerfile are 

- /home/threadfin/conf
- /tmp/threadfin

so you'll want to do `-v /opt/threadfin/conf:/home/threadfin/conf` instead.

**Comment by nweishar** [comment]
This is great, thank you so much. I really appreciate it

--
Nygel Weishar
Toronto, Ontario
416-880-4733
________________________________

**Comment by fredamn76** [comment]
Hi,
So we only use  -v /opt/threadfin/conf:/home/threadfin/conf ? No temp?
Regards
Fredrik


Den tors 1 juni 2023 kl 12:46 skrev nweishar ***@***.***>:

**Comment by beardypig** [comment]
@fredamn76 I only map the `conf` directory, I do not think there is an advantage to mapping the temp directory - but I don't actually know what is stored there.

**Comment by fredamn76** [comment]
Ok. Thank you.

Regards
Fredrik

Den tis 6 juni 2023 09:42beardypig ***@***.***> skrev:

**Comment by JHeat** [comment]
> @fredamn76 I only map the `conf` directory, I do not think there is an advantage to mapping the temp directory - but I don't actually know what is stored there. 

This is so you can set the buffer to reside in memory.

**Comment by YodaDaCoda** [comment]
you should not map `/home/threadfin` as that's where the threadfin application exists within the docker container - mounting a volume there will obscure the entire threadfin application from the docker container - as indicated by `/bin/sh: /home/threadfin/bin/threadfin: not found`.

you should instead map your volume to `/home/threadfin/conf`.

FWIW, I map `threadfin:/config` and set an environment variable `-e THREADFIN_CONF=/config` for consistency with lsio containers.
