### ISSUE TITLE
[Question] How does backup channels work?

### ISSUE THREAD

**Issue by morpheus302** [Threadfin/Threadfin#71]
when i try to add a backup channel it only pulls the xml channels and not the M3U channels. can someone please explain this to me?

**Comment by Fyb3roptik** [comment]
You will not see it in the xml. Threadfin auto switches to it when using a buffer

**Comment by morpheus302** [comment]
i understand that but wheb i try to select a backup stream i do not have a list of streams but instead a list of available EPG channels

**Comment by jonnyfevernf** [comment]
I am wondering the same thing.  How does it work? Does the back up have to be active? When if I have 3 streams, how do i know which one to pick? Can I just use a channel #? Ty

**Comment by morpheus302** [comment]
> Can add 3 backup channels for an active channel (backup channels do NOT have to be active)

**Comment by Fyb3roptik** [comment]
They do not have to be active. You should just pick the backup channel from the list (you can search in the list). Once the main channel goes down, Threadfin will automatically start buffering backup channel 1, then if that goes down then backup channel 2 gets used and so on

**Comment by morpheus302** [comment]
thank you very much [d3m1s33](https://github.com/d3m1s33) for the answer. it was some kind of confusing at first. thanks [Fyb3roptik](https://github.com/Fyb3roptik) for your work :)

**Comment by Fyb3roptik** [comment]
Yes at some point I changed the dropdown to be searchable and it is listed by channel name. I will be redoing the documentation soon enough unless someone wants to volunteer lol

**Comment by Fyb3roptik** [comment]
There was an issue with backup channels that has now been fixed. Please fix your backup channels!
