### ISSUE TITLE
#KODIPROP:inputstreamaddon

### ISSUE THREAD

**Issue by 3v3rm4rt3lL** [Threadfin/Threadfin#73]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**

I would like to know if can be in a future add a function to allow Threadfin to play this kind of m3u structure : 
#EXTINF:-1 tvg-id="" tvg-logo="" group-title="", ABC7
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
#KODIPROP:inputstream.adaptive.license_key={"keys" :[{"kty":"oct","k":"","kid":""}],"type":"temporary"}
https://linear.com/manifest.mpd

I know some players actually play this stream but, Could be nice if there a chance to added to threadfin also.

**Describe alternatives you've considered**

**Additional context**

Thanks.

**Comment by Fyb3roptik** [comment]
So this would be support for KODI I presume?

**Comment by Fyb3roptik** [comment]
I will need more info on this in order to do anything.

**Comment by Fyb3roptik** [comment]
Re-open it with more info and I can look into this
