### ISSUE TITLE
Fallback when no more streams are available. 

### ISSUE THREAD

**Issue by ehschneller** [Threadfin/Threadfin#78]
Would it be possible to use backup stream if available rather than display "no more streams are available"?  This would enable to use of two m3u's to provide fallbacks and extra connections at the same time. It seems like given the current setup this could be fairly easily achieved by producing a 404 rather than the current "no more streams are available" screen.

**Comment by Fyb3roptik** [comment]
There is already a way to have backup streams without the need for additional m3us. It does require the use of a buffer though

**Comment by ehschneller** [comment]
Yes and the current backups work fine but it would be nice to also use those connections as needed. Here is my thought. I have two service providers we will call them a and b, with 2 connections each. B is setup as backup to a. 3 people want to connect to channel x,y, and z. Currently the system would put two connections on a and then say no more streams available. Falling back to B for the third and forth connection is my thought. Might as well use all available connections and drop streams only if instability occurs. I believe Tvheadend has this functionality but is far harder to manage.

**Comment by Fyb3roptik** [comment]
You want a load balancer :) now that's a good idea

**Comment by steamyRayV** [comment]
Wouldn't this be simple if instead of sending 'stream-limit.jpg' when a tuner limit is reached, it just uses the logic of receiving a 404 error? Then if no backup is available it could fall back to 'stream-limit.jpg'. 'Load balancer' makes it sound complex, when really all we need is to treat a tuner limit as an error so Threadfin will try the backup. Or am I oversimplifying?

**Comment by ctyokley** [comment]
or couldn't this be achieved with HAProxy and limiting the max streams to a specific threadfin appliance :D
