### ISSUE TITLE
Ffmpeg bug Pluto, xteve m3u cam issues 

### ISSUE THREAD

**Issue by siliconhippy** [Threadfin/Threadfin#79]
Hi !

Just came across here searching for Jellyfin m3u solutions.

1. There are numerous reports of xteve not working well with live streams eg from web cams.
2. Also ffmpeg ex discontinuity bugs with Pluto TV for Jellyfin:
https://mediahost.weebly.com/blog/live-tv-resources-for-jellyfin

Does your plugin solve such problems?

**Comment by Fyb3roptik** [comment]
If it doesn't, then let me know and I'll fix it

**Comment by siliconhippy** [comment]
Ok I will test !

Also will your plugin stream live YouTube channels with or without pre processors like Streamlink + tvheadend?

**Comment by siliconhippy** [comment]
@d3m1s33 

1. What if I already have an m3u as in OP link ?
Will Threadfin process live YouTube links fine?

2. Also how about yt_dlp+ Streamlink GUI like Tartube? I heard yt_dl is not actively developed.

https://github.com/axcore/tartube

Will either dlp or dl give me live streams?

Unluckily I have not proceeded with threadfin + Jellyfin yet given my earlier Jellyfin + xteve experiences with highly delayed stream output. I am also trying to figure out some other issues before I proceed 😊

**Comment by siliconhippy** [comment]
Ok thanks....better understanding now.

Yes one problem with non live YouTube streams is that audio and video streams are separate. So you have to use ffmpeg ( or VLC) to process which slows response. 

Hopefully live YouTube streaming could be streamed via "No Buffer" as well as other integrated A/V channels, and Jellyfin would not automatically buffer such streams and force ffmpeg processing resulting in delays...

**Comment by Fyb3roptik** [comment]
The client also has to be able to play the codec. You will find better luck with hls than you will with mpeg-ts

**Comment by Fyb3roptik** [comment]
Also you will want to use yt-dlp

**Comment by siliconhippy** [comment]
@Fyb3roptik 

Agree on both counts as above. I plan to use Kodi with ( 2 Jellyfin clients, one more for library) and Chrome browser. Think both do well with HLS.

So yt_dlp can generate live m3u streams from live channels?

**Comment by siliconhippy** [comment]
@d3m1s33 

Ok will try 😸
Think xteve didn't have any buffer adjustment.

**Comment by siliconhippy** [comment]
Ah ... interesting 🤔

This ffmpeg buffer is available in threadfin ?
Because my plan is to use either direct m3u playlist or process through tvheadend/streamlink if needed.

So threadfin output is mpegts which is quite suitable for 580/720/1080p viewing. HLS would really shine for 1080p + streams but has complexity of multi stream management.

I wish there were a threadfin arch document I could read without necessarily gory coding details.

**Comment by Fyb3roptik** [comment]
You can use hls. I use hls on mine. You can use whatever ffmpeg flags you want. It just gives you an interface for adding them.
