### ISSUE TITLE
Active Stream list

### ISSUE THREAD

**Issue by ehschneller** [Threadfin/Threadfin#82]
Would it be possible to show a list of active streams. Channel, client, perhaps IP? You currently can parse some of this info from the log but not tell who's who when user agent is the same.

**Comment by iceman73** [comment]
I handled this by setting user agent for each of my devices

**Comment by ehschneller** [comment]
yes but going through 100's of lines of log to figure out which are still active is not ideal

**Comment by ehschneller** [comment]
I run threadfin as a proxy on a vps then distribute from there via https to various players. This seems to limit buffering as the vps evens out the bursts in the stream. Also putting into https allows some privacy at the isp level. Sent from my iPhoneOn Jun 2, 2023, at 7:15 PM, Dr D3 ***@***.***> wrote:﻿
Not to minimize your ask here, but wouldn't this be better suited for the client to provide?
Or are you using multiple clients?
Could you shed some light on your use case?
