### ISSUE TITLE
How to retrieve Filtered & Mapped Channel info via API

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#84]
I would like to make a simple API call to retrieve the information in the screenshot below via REST query.  However, I can't find "Filtered Channels" "Mapped Channels" data listed in the [original Xteve API documentation](https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md). 

Could you please tell me how to do this, is possible?  Even if possible, the documentation says authentication MUST be enabled.  However, I can't enable authentication yet until [this issue](https://github.com/Threadfin/Threadfin/issues/57) is resolved.

![image](https://github.com/Threadfin/Threadfin/assets/811008/847acb2a-0222-401d-ba91-da10db4fb63b)

Anyway, I was just looking for a programmatic way to retrieve this information.  Hopefully, it's possible; and, not too complicated.

**PS:**  The whole reason why I want to do this is because once in a while, I will try to watch IPTV in Plex.. and, only to find out there are 0 channels available (when IPTV provider is down).  With this API request, I will know instantly how many channels are available before I even try to watch IPTV.. the information would display on my [Home Assistant](https://www.home-assistant.io/) information panel; which has support to retrieve json API response data.

**Comment by Fyb3roptik** [comment]
Under Client Information:

Filtered Channels = client_information.streams
Mapped Channels = client_information.xepg

**Comment by mkanet** [comment]
Thank you @Fyb3roptik.  I currently have all authentication completely disabled in Threadfin and enabled API in settings. 

**Could you please give me a working cURL example command I can test with which retrieves, for example, all active streams** (presuming all authentication is disabled)?  If I have a working example, I will be able to use it to create other successful API queries.

Below, is my best effort (which I know is completely wrong).  I am not very experienced with API queries, so please forgive my inexperience:

```
curl --header "Content-Type: application/json" --request POST --data '{"cmd":"status", "Filtered Channels":"streams.active/streams.all"}' http://192.168.1.2:34400/api
```
Returns no data.  Not even an error. :-(

**Comment by Fyb3roptik** [comment]
You're missing the trailing slash. /api/

**Comment by mkanet** [comment]
> You're missing the trailing slash. /api/

Thank you for the quick reply!  After I added a trailing slash, it now returns:  **Bad Request [400]**.  There's still something wrong with the below command:

```
curl --header "Content-Type: application/json" --request POST --data '{"cmd":"status", "Filtered Channels":"streams.active/streams.all"}' http://192.168.1.2:34400/api/
```

**RESULT:**
```
Bad Request [400]
```

**Comment by Fyb3roptik** [comment]
Here is one from my postman with your ip

```bash
curl --location 'http://192.168.1.2:34400/api/' \
--header 'Content-Type: application/json' \
--data '{
  "cmd": "status"
}'
```

**Comment by Fyb3roptik** [comment]
Here is the same call with a token:

```bash
curl --location 'http://192.168.1.99:34400/api/' \
--header 'Content-Type: application/json' \
--data '{
  "cmd": "status",
  "token": "TOKEN_GOES_HERE"
}'
```

**Comment by Fyb3roptik** [comment]
https://discord.gg/bEPPNP2VG8

**Comment by mkanet** [comment]
@Fyb3roptik thank you so much for inviting me to your Discord channel.  There were very friendly and helpful people who helped me figure this out.  It is much easier to do cURL commands in a nix environment than in Windows.
