### ISSUE TITLE
Bulk Edit does not seem to work

### ISSUE THREAD

**Issue by KZkici** [Threadfin/Threadfin#85]
In xTeVe if you select bulk edit and a bunch of channels you can then set them all as an xml file and set as active at once,
via Threadfin only the first selection gets the changes the rest do not.

**Comment by claythegamer** [comment]
Can confirm. Same issue.
Running version 1.0 (13), amd64

**Comment by andycol** [comment]
Also not working on latest release 1.0.16 @Fyb3roptik any chance you can fix 😢

**Comment by flyize** [comment]
Glad to see I'm not a complete idiot here.

**Comment by bweezy21** [comment]
> In xTeVe if you select bulk edit and a bunch of channels you can then set them all as an xml file and set as active at once, via Threadfin only the first selection gets the changes the rest do not.

i believe this bug only applies to the non active channels. as i can bulk edit the active list. just for context.

**Comment by flyize** [comment]
Oh! I use EPGBoss! So I can just set a dummy EPG in EPGBoss, then when I hand it to TF, I'll be good? That's awesome news! Activating one by one was kind of a non-starter for me.

**Comment by andycol** [comment]
How do you set them to a dummy when ingesting?
[](https://prnt.sc/BC_ozVFNC_7x)

**Comment by flyize** [comment]
EPGBoss would be one way.

**Comment by ncsufan8628** [comment]
also having this issue.  Would love to bulk assign Dummy and Activate all of my PPV channels.

**Comment by bruor** [comment]
Same issue here,  my provider changed a bunch of IDs and I'm having to go through a few hundred channels one by one to reactivate them.

**Comment by flyize** [comment]
Obviously your repo, your rules, but wouldn't you like this open since its still a bug?

**Comment by bruor** [comment]
What is Kernel?

**Comment by bruor** [comment]
If anyone is interested in a workaround I used a python script to mark inactive channels active, set them to the dummy epg, and update the mapping name. 
`import json

# Load JSON data from the file
file_path = '/home/threadfin/.threadfin/xepg.json'

with open(file_path, 'r') as file:
    channels = json.load(file)

# Iterate through channels
for channel_id, channel_data in channels.items():
    if channel_data.get('x-active', False) is False:
        # Set x-active to true
        channel_data['x-active'] = True
        
        # Set x-xmltv-file to "Threadfin Dummy"
        channel_data['x-xmltv-file'] = "Threadfin Dummy"
        
        # Set x-mapping to tvg-id value if x-mapping is '-'
        if channel_data.get('x-mapping') == "-":
            tvg_id = channel_data.get('tvg-id', None)
            if tvg_id:
                channel_data['x-mapping'] = tvg_id

# Write the updated JSON data back to the file
with open(file_path, 'w') as outfile:
    json.dump(channels, outfile, indent=2)
`

**Comment by flyize** [comment]
> All functionality of Threadfin will be integrated into Kernel. No further development will be taking place on TF unless a core feature is broken.

Isn't that the case here? @Fyb3roptik confirmed in another thread here that he broke it somehow in the changes he made to xteve.

**Comment by Fyb3roptik** [comment]
I will not be fixing this sorry. All efforts are to get this stuff in Kernel

**Comment by bruor** [comment]
Where can we get more information and follow the development of Kernel Media Server?

**Comment by flyize** [comment]
> I will not be fixing this sorry. All efforts are to get this stuff in Kernel

Good luck!

**Comment by andycol** [comment]
Can we see kernel?

**Comment by ncsufan8628** [comment]
I found this repo/fork of xteve.  Since development seemed paused here I sought out a replacement that didn't have the myriad ppv issues, editing issues, etc.  

There's still some small things that are weird (if you adjust a filter to renumber channels, you need to remove and readd your main m3u).  But once setup it works perfectly.  Good Luck.  https://github.com/SenexCrenshaw/xTeVe

Looking forward to checking out Kernel when its done and hopefully doest suffer from the same limitations within my setup.

**Comment by flyize** [comment]
> I found this repo/fork of xteve. Since development seemed paused here I sought out a replacement that didn't have the myriad ppv issues, editing issues, etc.
> 
> There's still some small things that are weird (if you adjust a filter to renumber channels, you need to remove and readd your main m3u). But once setup it works perfectly. Good Luck. https://github.com/SenexCrenshaw/xTeVe
> 
> Looking forward to checking out Kernel when its done and hopefully doest suffer from the same limitations within my setup.

What's different between that repo and the official?

**Comment by ncsufan8628** [comment]
too much to list, here are a few screens.  All i know is for 2+ weeks i have not had a single issue with PPV or any channels disappearing. 

If I were to nitpick, i think Threadfin's ffmpeg buffer works more reliably, but overall its been a small tradeoff to not have to deal with missing channels, epg data, etc. etc.

![Untitled](https://github.com/Threadfin/Threadfin/assets/16391568/385eb9f4-5fda-4172-a180-bfc53cc9c46f)
<img width="614" alt="Screen Shot 2023-12-22 at 7 41 14 PM" 

src="https://github.com/Threadfin/Threadfin/assets/16391568/239d31c2-f2ae-41a9-84a1-2574abe392c8">
<img width="1436" alt="Screen Shot 2023-12-22 at 7 41 41 PM" 

src="https://github.com/Threadfin/Threadfin/assets/16391568/b7fbfe7c-bdf0-48bc-96db-65c01584f9fe">
