### ISSUE TITLE
More Buffer Size options or custom Value

### ISSUE THREAD

**Issue by KZkici** [Threadfin/Threadfin#89]
Using ffmpeg with 8 MB is not enough for live ppv channels it seems. The connection freezes every 30-60 seconds or so for a few seconds and then continues.
Would like a bigger buffer size 

Unless there is a better solution to pre-load at least 10 seconds in advance before playing the channel?

Do you have any magical FFmpeg Options I can use to alleviate this?

**Comment by Fyb3roptik** [comment]
That is for the old threadfin/xteve buffer. Feel free to use any ffmpeg command to handle that!

http://trac.ffmpeg.org/wiki/EncodingForStreamingSites#:~:text=%2Dbufsize%20sets%20the%20buffer%20size,seconds%20for%20more%20static%20content.

**Comment by KZkici** [comment]
Side note not sure if it matters or not the initial log states: [Threadfin] Buffer Size:            8192 KB
but if i were to check the tasks i see the custom -bufsize and -maxrate
