### ISSUE TITLE
The changelog mentions docker support, is there a docker file or repo somewhere? 

### ISSUE THREAD

**Issue by northernpowerhouse** [Threadfin/Threadfin#9]
I'd love to test this out as it includes some must have features, but I like to keep everything containerised and I've not write  a docker file before.

**Comment by Fyb3roptik** [comment]
Sorry yes I will update the README later on.

https://hub.docker.com/repository/docker/fyb3roptik/threadfin

**Comment by xtinct101** [comment]
hey Fyb3roptik,

are you planning on adding any other builds besides arm64? amd64 in particular
