### ISSUE TITLE
No streams after parsing M3U playlist

### ISSUE THREAD

**Issue by olenchenko** [Threadfin/Threadfin#92]
After downloading playlist from specified URL, checking and saving logs and web interface shows 0 streams.

**Server (please complete the following information):**
- OS - FreBSD 13.2
- Arch - Intel 64 Bit
- Threadfin Version and Build - 1.0 Build: 13

**To Reproduce**
It will not be possible to download .m3u file as I have IPTV as a part of service from my ISP and playlist download URL (http://ott.astra.in.ua/smartup/tools/playlist.php) is available only from my ISP's network.

I am attaching playlist.m3u download from mentioned URL. Also I have tried downloading file manually and configure Threadfin to use local file - same result (0 streams).

**Expected behavior**
After parsing .m3u file there should be streams available.

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/176176/eac3e5e4-2eb0-49f2-bea6-dffaf827b841)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox, Edge

**Additional context**
Partial log:
`Jun 12 18:26:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:26:04 [Threadfin] XEPG:                   Ready to use
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] Open:                   /home/threadfin/playlist.m3u
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] Check File:             /home/threadfin/playlist.m3u
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] Save File:              /home/threadfin/playlist.m3u [ID: M3ERXNLYPJ2JJDFG3KZ8]
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] All streams:            0
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] Active streams:         0
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] Filter:                 0
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Parse XMLTV file: XMLTV
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Update database
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Save DB file
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Map channels
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Cleanup database
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG Channels:          0
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/.threadfin/data/threadfin.xml)
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/.threadfin/data/threadfin.xml.gz)
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/.threadfin/data/threadfin.m3u)
Jun 12 18:28:05 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:05 [Threadfin] XEPG:                   Ready to use
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Open:                   /home/threadfin/playlist.m3u
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Check File:             /home/threadfin/playlist.m3u
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Save File:              /home/threadfin/playlist.m3u [ID: M3ERXNLYPJ2JJDFG3KZ8]
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Download:               http://ott.astra.in.ua/smartup/tools/playlist.php
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Header filename:        playlist.m3u
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Check File:             http://ott.astra.in.ua/smartup/tools/playlist.php
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Save File:              http://ott.astra.in.ua/smartup/tools/playlist.php [ID: MX51WQ9CHMNECXYXBGGK]
Jun 12 18:28:06 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:06 [Threadfin] Download:               https://iptvx.one/EPG
Jun 12 18:28:08 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:08 [Threadfin] Extract gzip:           https://iptvx.one/EPG
Jun 12 18:28:10 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:10 [Threadfin] Check File:             https://iptvx.one/EPG
Jun 12 18:28:38 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:38 [Threadfin] Save File:              https://iptvx.one/EPG [ID: XK2AQGA27T3C4R815X27]
Jun 12 18:28:38 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:38 [Threadfin] All streams:            0
Jun 12 18:28:38 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:38 [Threadfin] Active streams:         0
Jun 12 18:28:38 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:38 [Threadfin] Filter:                 0
Jun 12 18:28:38 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:28:38 [Threadfin] XEPG:                   Parse XMLTV file: XMLTV
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Update database
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Save DB file
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Map channels
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Cleanup database
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG Channels:          0
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/.threadfin/data/threadfin.xml)
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/.threadfin/data/threadfin.xml.gz)
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/.threadfin/data/threadfin.m3u)
Jun 12 18:29:04 iptv threadfin[10939]: ^[[0m^[[0m2023/06/12 18:29:04 [Threadfin] XEPG:                   Ready to use
`
[playlist.zip](https://github.com/Threadfin/Threadfin/files/11725261/playlist.zip)

**Comment by Fyb3roptik** [comment]
I have a fix for this coming soon

**Comment by olenchenko** [comment]
Hi @Fyb3roptik and thanks for the info.
I will be waiting for this fix.

**Comment by chris6570** [comment]
Out of curiosity, would this be the reason that an m3u playlist based on RTP streams does not work in THREADFIN? I ask because I have no problem using the playlist in XTEVE while it fails under THREADFIN.

**Comment by olenchenko** [comment]
Hi @d3m1s33 .
I have <170 streams in my playlist.
And as @chris6570 mentioned - xteve handles it without any problem.

**Comment by Fyb3roptik** [comment]
Coming today

**Comment by Fyb3roptik** [comment]
Fixed in 1.0.14
