### ISSUE TITLE
SchedulesDirect integration using guide2go

### ISSUE THREAD

**Issue by Xaque8787** [Threadfin/Threadfin#93]
**Is your feature request related to a problem? Please describe.**
I'm using [guide2go](https://github.com/mar-mei/guide2go), to get a local xmltv file to point Threadfin to.
**Describe the solution you'd like**
Both Threadfin and guide2go are written in GO so hoping this would be possible. It would be nice if there was an option within Threadfin to enter your SD credentials, schedule days, and other info guide2go uses; then let Threadfin handle the task of downloading/updating the xmltv with the rest of the guides and such.

**Describe alternatives you've considered**
Currently I've set up a script to run every 3 days to run guide2go to download SD xmltv data.
**Additional context**
Not sure if guide2go fits within the SchedulesDirect [terms of use](https://www.schedulesdirect.org/terms), but it seems too. Im going to reach to the devs of that to see if they'll request that guide2go be put on the [approved apps list](https://www.schedulesdirect.org/approvedsoftware) at [SchedulesDirect](https://www.schedulesdirect.org)

**Comment by mkanet** [comment]
@Xaque8787 just a headup... IMO, EPG123 is a much better tool for downloading SchedulesDirect EPG data than any other tool; especially for handling SchedulesDirect EPG images.  I don't think guide2go even supports Schedulesdirect images.  If you're already paying for a schedulesdirect EPG, you might as well take full advantage of their top-notch EPG images.  EPG123 fully supports downloading and caching ALL schedulesdirect images for each EPG program airing. It has a superior image caching engine that Plex will take advantage of directly; if you disable Threadfin image caching.

That way your Plex "LiveTV - What's On" can look like below... They are all ScheduleDirect images:
![1](https://github.com/Threadfin/Threadfin/assets/811008/6e545788-8524-45ea-bac2-245064a3340d)

**Comment by chenks** [comment]
sad this is not planned.

i currently use the dnsforge xteve fork that has guide2go included, so i can pull epg data from schedules direct.
if threadfin doesn't have any plans to include pulling EPG data from sources as a built-in function then it's unlikely i can use threadfin.

**Comment by chenks** [comment]
> @Xaque8787 just a headup... IMO, EPG123 is a much better tool for downloading SchedulesDirect EPG data than any other tool; especially for handling SchedulesDirect EPG images. I don't think guide2go even supports Schedulesdirect images. If you're already paying for a schedulesdirect EPG, you might as well take full advantage of their top-notch EPG images. EPG123 fully supports downloading and caching ALL schedulesdirect images for each EPG program airing. It has a superior image caching engine that Plex will take advantage of directly; if you disable Threadfin image caching.
> 
> That way your **Plex LiveTV - What's On** can look like below... They are all ScheduleDirect images: ![1](https://private-user-images.githubusercontent.com/811008/255279276-6e545788-8524-45ea-bac2-245064a3340d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTQyNjcsIm5iZiI6MTcxODA5Mzk2NywicGF0aCI6Ii84MTEwMDgvMjU1Mjc5Mjc2LTZlNTQ1Nzg4LTg1MjQtNDVlYS1iYWMyLTI0NTA2NGEzMzQwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwODE5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDVlMTQ4YjViN2Q3NGY2Y2ZhYjM5OGE2MGQ2NDAwZDE1MzBmNWVkNDhiMTkwN2I5Y2Q0NjNhYzQyMmRjYzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bfQnEFZ4swHjxqqY292xluBKcCcO769D_AfwcgGyJzU)

i currently use the dnsforge xteve fork that has guide2go included, so i can pull epg data from schedules direct.
i haven't come across EPG123 before, but as threadfin doesn't appear to have any built-in way to pull epg data then it's unlikely i can use threadfin instead of xteve. is there a solution?
