### ISSUE TITLE
aarch64 Docker Support

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Threadfin/Threadfin#94]
**Is your feature request related to a problem? Please describe.**
Oracle free ARM Ampere A1 instance is a aarch64 cpu. Which the current docker image does not support.

**Describe the solution you'd like**
Docker image with aarch64 support.

**Describe alternatives you've considered**

**Additional context**

**Comment by Fyb3roptik** [comment]
You should be using the linux/arm64 one. There isn't a difference between aarch64 and arm64

**Comment by Cookie-Monster-Coder** [comment]
I get this error when running it on arm64

```
/bin/sh: /home/threadfin/bin/threadfin: not found
```
