### ISSUE TITLE
slice bounds out of range regression

### ISSUE THREAD

**Issue by hayrun-st** [Threadfin/Threadfin#96]
This was fixed in an older version but has reappeared in 1.0.13 (and possibly before). Again, running in Docker container on Unraid server.

I've had it crash several times over the past few days all with a very similar error:

panic: runtime error: slice bounds out of range [1063824:0]

goroutine 231 [running]:
github.com/avfs/avfs/vfs/memfs.(*MemFile).Write(0xc000f89b00, {0xc00067f000, 0xa48, 0x1000})
/src/vendor/github.com/avfs/avfs/vfs/memfs/memfs_file.go:653 +0x697
threadfin/src.thirdPartyBuffer(0x0, {0xc0052a4588, 0x14}, 0x0, 0x0)
/src/src/buffer.go:1698 +0x12e2
created by threadfin/src.bufferingStream
/src/src/buffer.go:224 +0xa58

Unraid Docker
Threadfin 1.0.13

**Comment by Fyb3roptik** [comment]
You should NOT be using the old threadfin buffer anymore. FFMPEG or VLC are the only supported options

**Comment by hayrun-st** [comment]
> You should NOT be using the old threadfin buffer anymore. FFMPEG or VLC are the only supported options

Ffmpeg WAS being used.  In the newest version, it seems to have improved but still crashes about every 3 days with the same slice bounds issue.
