### ISSUE TITLE
Virus Detected:  Threadfin_windows_amd64.exe  (Version 1.0.13)

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#97]
Today I noticed threadfin would not start.  When I checked, I noticed `Threadfin_windows_amd64.exe` was missing.  When I tried to redownload Threadfin_windows_amd64.exe Version 1.0.13, immediately, my MS Edge web browser displayed:
![image](https://github.com/Threadfin/Threadfin/assets/811008/a17fe049-6040-4ff2-b99d-d680e911d894)

I ended up reverting back to Version 1.0.12.  

See this:
![image](https://github.com/Threadfin/Threadfin/assets/811008/bfe48218-e0a2-4897-a406-347471f56550)

**Comment by Fyb3roptik** [comment]
![Screenshot_20230625-015613.png](https://github.com/Threadfin/Threadfin/assets/339131/c3aa379b-7ef7-4f52-94d6-5b583e837bc4)
