### ISSUE TITLE
Error "/bin/sh: /home/threadfin/bin/threadfin: not found" on arm64 Docker

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Threadfin/Threadfin#98]
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Host is an ubuntu arm64
Starting Threadfin with this command 
```
sudo docker run -it -d --name=xteve3 --network=host --restart=always -v /xteve3:/home/threadfin/conf --platform=linux/arm64 fyb3roptik/threadfin:latest
```

outputs the folling error in the docker logs for the container 
```
/bin/sh: /home/threadfin/bin/threadfin: not found
```

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Deanosim** [comment]
Duplicate of #70

**Comment by Gymnae** [comment]
No, that is not a duplicate of #70, it happens even when mapping only the conf env var
